### ISSUE TITLE
Adding preview images

### ISSUE THREAD

**Issue by arkypita** [arkypita/LaserGRBL#1]
![alphadrawing](https://cloud.githubusercontent.com/assets/8782035/20867452/e58f7f38-ba44-11e6-80e1-490ae3be0358.jpg)
![galeon](https://cloud.githubusercontent.com/assets/8782035/20867453/e59430e6-ba44-11e6-91ed-0d3407387adf.jpg)

**Comment by arkypita** [comment]
![preview](https://cloud.githubusercontent.com/assets/8782035/21349915/dba84a5a-c6b4-11e6-965f-a74fd283267a.jpg)

**Comment by arkypita** [comment]
![previewsmall](https://cloud.githubusercontent.com/assets/8782035/21350108/ed218200-c6b5-11e6-9712-21de7bf7a1ea.jpg)

**Comment by arkypita** [comment]
![grayscalemap](https://cloud.githubusercontent.com/assets/8782035/21351296/1df460c2-c6bc-11e6-8eee-4612bb7978fa.jpg)

**Comment by arkypita** [comment]
![raster2laser](https://cloud.githubusercontent.com/assets/8782035/21425748/34400d46-c84b-11e6-99e5-6eb529a98f8f.jpg)

**Comment by Rost3** [comment]
i have a Eleks Laser 5.5W It burns all the coals at grayscale, too powerful. can you add a power limits. min power and max power to grayscale.

**Comment by arkypita** [comment]
Yes, it's a good idea! Since the software is in early development, the program is very wired on my hardware configuration, with limited configuration options. One of my next goals is to add a configuration page that allows you to set some parameters.

However your request is very sensible, so I will provide to implement it as soon as possible in Raster Import Form.

Greetings

**Comment by arkypita** [comment]
@Rost3 Check version 1.0.2 on https://github.com/arkypita/LaserGRBL/releases/tag/v1.0.2
You can find an option to scale laser power

**Comment by Rost3** [comment]
is good!!! some program have curves for scale laser power. but is for future.
![img_20161225_231801977](https://cloud.githubusercontent.com/assets/24759536/21473066/dc11270a-cb00-11e6-887e-e7c380f3f315.jpg)
![gray](https://cloud.githubusercontent.com/assets/24759536/21473076/d68ddf20-cb01-11e6-920c-962ebaaf486d.jpg)
I used to calibrate power the gray gradient

**Comment by Rost3** [comment]
at the beginning  of a line is switched on the laser, burns through the point and then moves. it might be worth to make so that the laser worked only when moving?

**Comment by arkypita** [comment]
@Rost3 Thank for your feedback!
I suggest you to open new issues instead of posting at the bottom of this topic. To do that, simply click the green button "new issue" on top right of the page https://github.com/arkypita/LaserGRBL/issues
Use one issue for any different issue, this help me to keep track of opened request.

> is good!!! some program have curves for scale laser power. but is for future.
It's a nice suggestion, could be a future goal. (not to difficult to implement)

> at the beginning of a line is switched on the laser, burns through the point and then moves. it might be worth to make so that the laser worked only when moving?

This is because at the beginning of the movement laser is firm, then rapidly accelerate to travel speed.
During the initial acceleration speed goes from zero to travel speed in milliseconds, but defined power still remain the same so at the beginning of the acceleration, when speed is low, laser burn more.
Since acceleration are managed by onboard software (grbl on arduino) the best approach is to scale realtime laser power according to realtime speed.

The last version (1.1) https://github.com/gnea/grbl/wiki of grbl for arduino can do that: 
> Dynamic Laser Power Scaling with Speed : If your machine has low accelerations, this option will automagically scale the laser power based on how fast Grbl is traveling, so you won't have burnt corners when your CNC has to make a turn! Enabled by the M4 spindle CCW command when laser mode is enabled.

If you decide to upgrade your arduino firmware to 1.1 please be sure to backup your settings ($$) because the update will reset arduino memory. Also keep a copy of config.h to restore the same macro options.

**Comment by Rost3** [comment]
i use grbl 1.1. thanks for the explanation of the grbl settings. Your program best I've seen.

**Comment by arkypita** [comment]
![addcbutton](https://cloud.githubusercontent.com/assets/8782035/23369543/fe063790-fd11-11e6-8b11-c3891bb93811.jpg)
![addcbutton1](https://cloud.githubusercontent.com/assets/8782035/23369547/fe0eef66-fd11-11e6-9169-dc41b40917d2.jpg)

**Comment by arkypita** [comment]
![custom button](https://cloud.githubusercontent.com/assets/8782035/23375844/238e5f70-fd2a-11e6-8826-5ff7743bbea0.jpg)

**Comment by arkypita** [comment]
![videopreview](https://cloud.githubusercontent.com/assets/8782035/23578353/fba95768-00d4-11e7-9357-99c00a30631d.jpg)
