### ISSUE TITLE
Z Axis Movement.

### ISSUE THREAD

**Issue by StuartB4** [arkypita/LaserGRBL#100]
Just wondered if it would be possible to add a feature that would allow the up and down movement of the Z Axiz (Laser up and down) to allow for focusing for different thickness's of material.
Or possibly an option to switch the laser on at low power to project a laser dot to allow for manual focusing of the laser lens before burning.

**Comment by arkypita** [comment]
> Just wondered if it would be possible to add a feature that would allow the up and down movement of the Z Axiz (Laser up and down) to allow for focusing for different thickness's of material.

[custom button](http://lasergrbl.com/it/usage/custom-buttons/)

> Or possibly an option to switch the laser on at low power to project a laser dot to allow for manual focusing of the laser lens before burning.

[custom button](http://lasergrbl.com/it/usage/custom-buttons/)

**Comment by StuartB4** [comment]
Thanks very much Arkypita. I forgot all about the Custom options.

**Comment by StuartB4** [comment]
Thanks again. I had a go and did it. I've told it to only move in 0.25mm steps because it's for focusing and it seems to work ok.
I borrowed the Up and Down icons from your icons in the Grafica folder in the source code and made them slightly smaller so I could get the letterZ in there as well.
![zupzdown](https://user-images.githubusercontent.com/16980026/30463612-a0118090-99c4-11e7-8f28-9cc16e39dc58.jpg)

**Comment by arkypita** [comment]
very good!
