### ISSUE TITLE
Terrible issue in gcode render

### ISSUE THREAD

**Issue by linewallker** [arkypita/LaserGRBL#1001]
Hello, i am developing high resolution large formát grafical laser engraver and i am experiencing big error in gcode generated from pictures, There are strange lines which is definitely not part of the original pictures and every time I generated gcode they are in different position As you can see on attached pictures.
IT is a Very big problém for my projet and I need to know how to skip tru this problém. 

Thank you in advance for your quick answer. 

Petr
![15892855036729144322479543841632](https://user-images.githubusercontent.com/57257396/81689438-953d2000-945a-11ea-9c7c-a4a63be0e8c9.jpg)
![15892855588536795805883883544028](https://user-images.githubusercontent.com/57257396/81689547-ae45d100-945a-11ea-8aa9-20388788bf12.jpg)
Plot size is 118cm width 57 cm Height on 1/16 stepp Ing vith 4 500 000 rows of gcode, now I increased number of rows per mm from 5 to 10 ank code now have around 9 000 000 rows of code with plot time about 8 days... I will see if the problém will be There again with different render setings, any experience from expert is welcome 😉

**Comment by gmmanonymus111** [comment]
Could you tell more details about your machine and the settings used to generate the GCode (like lines/mm, dithering or line2line etc)?

**Comment by linewallker** [comment]
I tried this ať the First time with experience on photos:
![15892948205277833004732017823892](https://user-images.githubusercontent.com/57257396/81706293-3a162800-9470-11ea-9444-da10104336d6.jpg)
Now I change to this :
![15892948836413385704303849703477](https://user-images.githubusercontent.com/57257396/81706517-5e720480-9470-11ea-9bad-c2396fa72c53.jpg) 
IT will také maybe 2 days to plot enough to see how it is going

Machine is arduino vith cnc shield v3 and stepper driver a4988 on 1/16 stepp Ing right now and it is total reprap from old material
![15892950009969124010164184443033](https://user-images.githubusercontent.com/57257396/81707200-c294c880-9470-11ea-9658-0f3313a665b8.jpg)

**Comment by linewallker** [comment]
Also on smaller jobs
![15892952130924612504699180253788](https://user-images.githubusercontent.com/57257396/81707795-26b78c80-9471-11ea-9341-2bd40e86449f.jpg)

**Comment by gmmanonymus111** [comment]
It seems a belt-driven machine, which might have issues when it comes to precise work. Although microstepping is meant to increase precision, it's not always working good. 1/16 steps are risky, because they can't hold a precise position (only whole steps are precise). Try to run it at 1/8 (that's what I use, but my machine is leadscrew-driven).
For the software part, make sure lasermode is enabled in GRBL (`$32` is set to 1) and you should use M4 for 'laser on command' in LaserGRBL while generating gcode. You could also try `1bit BW Dithering` instead of `Line-to-line Tracing`

**Comment by linewallker** [comment]
On full step it was laso visible so I think that could be but it but on the other Hand if It is pressent on smaller jobs with full step setup it will not be the core problém, parts are havy so I think they should hold the position, also I mesuring the lenght every 1 Hour and both sides have the samé stepper lenght, also Distance between rows is looking Very good and quality of final plot is realy good, only those rasters which is occuring in grayscale is problem
![15892967040831756354907283366034](https://user-images.githubusercontent.com/57257396/81712193-a09d4500-9474-11ea-9f57-704d659502bc.jpg)
![15892967324295861883771148058619](https://user-images.githubusercontent.com/57257396/81712294-b874c900-9474-11ea-98ca-04c6dc5d11fc.jpg)

As you can see details on bw plot is ok on full strenght of laser

**Comment by linewallker** [comment]
Could it be caused with old grbl flashed in arduino? I think I am using old 0.9 flash

**Comment by linewallker** [comment]
Also I will try s4 for laser instead of s3, I have not tried this option before

**Comment by gmmanonymus111** [comment]
You need GRBL 1.1 to use [laser mode](https://github.com/gnea/grbl/wiki/Grbl-v1.1-Configuration#32---laser-mode-boolean)
If you decide to upgrade, [this](https://github.com/gnea/grbl/wiki/Flashing-Grbl-to-an-Arduino) can be useful for flashing, or if you want to edit some advanced settings, take a look [here](https://github.com/gnea/grbl/wiki/Compiling-Grbl)

**Comment by linewallker** [comment]
I have edited laser modulation speed in the files I have flashed, I increased to 10khz based on specifications from seller to get better performance, that is why I do nou upgrade, so I will upgrade but I must find how to Edit modulation speed in new version ☹️

**Comment by StuartB4** [comment]
In Ggrbl 1.1 that can be done in the map.h file of grbl then recompiled and flashed to the arduino. 
But it  only goes up to 7.8 kHz.

>       // Prescaled, 8-bit Fast PWM mode.
      #define SPINDLE_TCCRA_INIT_MASK   ((1<<WGM20) | (1<<WGM21))  // Configures fast PWM mode.
      // #define SPINDLE_TCCRB_INIT_MASK   (1<<CS20)               // Disable prescaler -> 62.5kHz
      // #define SPINDLE_TCCRB_INIT_MASK   (1<<CS21)               // 1/8 prescaler -> 7.8kHz (Used in v0.9)
      // #define SPINDLE_TCCRB_INIT_MASK   ((1<<CS21) | (1<<CS20)) // 1/32 prescaler -> 1.96kHz
      #define SPINDLE_TCCRB_INIT_MASK      (1<<CS22)               // 1/64 prescaler -> 0.98kHz (J-tech laser)

**Comment by linewallker** [comment]
That is a Very good tip which will savé a lot of gogling 😁 Thank you Very much for your time, now I have some useful tips and I am going to start some testing and let you know about final result 👍

**Comment by StuartB4** [comment]
Ok. Good luck with it. :+1:

**Comment by linewallker** [comment]
Thanks, I will get Back in few days, in this sizes it will be slow 😄😄😄

**Comment by linewallker** [comment]
I think this probléms with raster lines occuring also on analog televisions and it is looking very similar to the lines on my plots, what do you think?
![Screenshot_20200513_164716_com google android youtube](https://user-images.githubusercontent.com/57257396/81828158-c3ddf800-9539-11ea-96f6-6cc7d162f52e.jpg)
![Screenshot_20200513_164510_com google android youtube](https://user-images.githubusercontent.com/57257396/81828173-c80a1580-9539-11ea-9353-24e5d34f3b8f.jpg)
![15893814259206684588936406033233](https://user-images.githubusercontent.com/57257396/81828336-f982e100-9539-11ea-9596-26ebce6264c1.jpg)

**Comment by linewallker** [comment]
Hello again,
  I have updated to GRBL 1.1h onto device and also downloaded and instaled latest version of LASER GRBL 3.4.1 and alsu set up to M4 instead of M3 and the result is now without any raster but after 2 days of plotting I have experienced this 2 erroras at once and machine stopped and LASER GRBL froyed with 1.23 GB used RAM on about  1/3 of whole job.

ERRORS:

LaserGrbl v3.4.1.0
Grbl v1.1h
Wrapper: UsbSerial
Win 10, Professional, 10.0.19041.0 (0)

TypeOf exception  [System.OutOfMemoryException]
Exception message [Byla vyvolána výjimka typu System.OutOfMemoryException.]
Exception source  [mscorlib], thread []
Exception method  [System.Threading.ExecutionContext Capture(System.Threading.StackCrawlMark ByRef)]

   ----------- stack trace -----------
   v System.Threading.ExecutionContext.Capture(StackCrawlMark& stackMark)
   v System.Threading._ThreadPoolWaitCallback..ctor(WaitCallback waitCallback, Object state, Boolean compressStack, StackCrawlMark& stackMark)
   v System.Threading.ThreadPool.QueueUserWorkItemHelper(WaitCallback callBack, Object state, StackCrawlMark& stackMark, Boolean compressStack)
   v System.Threading.ThreadPool.QueueUserWorkItem(WaitCallback callBack, Object state)
   v System.IO.Ports.SerialStream.EventLoopRunner.CallEvents(Int32 nativeEvents)
   v System.IO.Ports.SerialStream.EventLoopRunner.WaitForCommEvent()
   v System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   v System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   v System.Threading.ThreadHelper.ThreadStart()

Number 2 

sorry it fall down complety before I was able to coppy out … ( something about drawing or what )

But the problem with rastering is gone now, thank you for your good tips for finding the way :)

**Comment by arkypita** [comment]
From your log i see that you have a 32bit system (32bit processor and/or 32bit OS)
In 32bit OS the address space available for application is limited to 2GB

LaserGRBL is very memory hungry because it has to work with bitmaps and lot of graphical objects.

I know it may not be that simple, but I suggest you use a 64bit processor PC if you need to work with such large images.

**Comment by linewallker** [comment]
I did all your recomandations and also switched to x64 ultrabook with x64 win OS so I will see in few days if the probléms are completely gone.

Thanks a lot for your help and keep it going forward, it is cool software you are developing 👍😉
