### ISSUE TITLE
VigoEngraverL7 Stop working

### ISSUE THREAD

**Issue by safdher** [arkypita/LaserGRBL#1006]
am using a VigoEngraverL7, when try engrave anything it will stop after some time. am try to change the firmware using xloader application. but I cant flash. it shows an error. then I use your grbl application but it still has the same problem. but i can engrave(it will stop 5 times in a 5cm x 5cm picture). how can i solve this problem?

**Comment by StuartB4** [comment]
You can use LaserGRBL to flash it, it's on the Tools menu, Flash Grbl Firmware.
Start LaserGRBL but don't click connect. Then look at these pics.

**Comment by safdher** [comment]
Thank you for your Reply. it works fine. Thanks a lot

**Comment by StuartB4** [comment]
:+1:
