### ISSUE TITLE
How to skip axis accelerating / decelerating area on raster engraving? 

### ISSUE THREAD

**Issue by lome64** [arkypita/LaserGRBL#1011]
Dear all, 
doing some raster engraving on my new 3018pro CNC Laser, I noticed dark areas 
on beginning and end of each scan line. Obviously there is more laser energy brought into 
the material there. 
A closer inspection revealed that Lasergrbl switches on the laser exactly the same moment a scanline 
starts and also switches the laser off, exactly where a scanline ends.
That means, the laser is switched on, even when the axis is still accelerating and has not yet 
reached the final speed and also the laser is still on, when the axis decellerates to zero at the end of the scanline.
That results in darker edges.
See attached the file I used for testing.
![Test](https://user-images.githubusercontent.com/16515695/82645186-c532b300-9c12-11ea-8935-4a76ebe99576.jpg)
The Result clearly shows the dark edges in X direction:
![Lasergrbl_1](https://user-images.githubusercontent.com/16515695/82645275-e7c4cc00-9c12-11ea-80ae-5c07b6e51c38.jpg)

To overcome the problem I added a light grey background to the image, a little bigger than the image itself:
![Test_grey](https://user-images.githubusercontent.com/16515695/82645355-075bf480-9c13-11ea-9f59-f57935b55d0d.jpg)
So the laser is switched on within the light grey border (which is light enough to leave no imprint)
and as the image begins, the axis already reached it's full speed resulting in an equal dark imprint.
![Lasergrbl_2](https://user-images.githubusercontent.com/16515695/82645607-70dc0300-9c13-11ea-988d-5e719b8ec7c7.jpg)

So it seems there is still a little room for improvement in Lasergrbl.
Or did I just miss the correct setting?
I also have a CO2 laser machine with a completely different software. 
That machine adds accelerating and decellerating space by itself.
That would also be a nice feature in Lasergrbl!
Maybe just a numeric fiels to enter the measurement of a accelerating "border" to give the axis 
a chance to reach its final speed, before the laser is switched on. (or off at the end of the scanline)
Also of course that problem appears when parts of a scanline that are white are skipped in rapid speed.

So if there is a setting for this already I would appreciate a little hint.
If not, it would be fine ifthis feature would be added to Lasergrbl.

Thank you!
  Lothar

**Comment by arkypita** [comment]
Use grbl v1.1 with Laser Mode enabled and M4

https://github.com/gnea/grbl/wiki/Grbl-v1.1-Laser-Mode

**Comment by lome64** [comment]
arkypita, thank you for your suggestion!

The machine runs grbl 1.1, but I was not aware of M4 dynamic power scaling. 
That sounds promising. I'll have a look at it.

Thank's!
  Lothar

**Comment by lome64** [comment]
Hmmm.... 
Tried it. 
And it seems it is willing to do the right thing, but with very little success:

![Lasergrbl_3](https://user-images.githubusercontent.com/16515695/82648783-7e47bc00-9c18-11ea-9aec-ba303c269a41.jpg)

In my oppinion it's even worse than constant laser power.
Same settings as in the opening message above. Just switched laser-on-command from M3 to M4
Are there more parameters to tune this?

Lothar

**Comment by lome64** [comment]
P.S.: In the log of Lasergrbl I cannot find a $32=1 command. Does Lasergrbl send it implicitely?

**Comment by lome64** [comment]
I apologize! 
The machine was a bit messed up after making he changes. 
It showed strange behaviour and finally did not respond at all.
After a power cycle and restart of the software it now works perfect with M4 and $32=1
This is the newest result:
![Lasergrbl_4](https://user-images.githubusercontent.com/16515695/82651363-5a867500-9c1c-11ea-8258-02ff479a49c1.jpg)

I'm happy with that! 
Thank you!

**Comment by arkypita** [comment]
$32 is a setting, not a gcode.
Once set, always set

http://lasergrbl.com/wp-content/uploads/2020/05/Grbl-Configuration-ENG.pdf

**Comment by lome64** [comment]
> $32 is a setting, not a gcode.

I see. Found that in the GRBL settings. 
Thank you for your fast and competent help!

Lothar
