### ISSUE TITLE
Suggest

### ISSUE THREAD

**Issue by lianzaozi** [arkypita/LaserGRBL#1013]
I have a good suggestion for lasergrbl to support two-dimensional code and one-dimensional code generation and engraving, so that lasergrbl software can be directly used to control the laser to produce barcodes. There are many open source libraries that support QR code barcodes (zint, ZXing, ZBar ...).

**Comment by arkypita** [comment]
Thanks for suggestion.
For now it's something I'm not interested in adding. Maybe in the future or if supported economically.
