### ISSUE TITLE
laser on

### ISSUE THREAD

**Issue by ronisegoly** [arkypita/LaserGRBL#1014]
I have [laser module](https://www.sainsmart.com/products/sainsmart-blue-laser-module-kit-for-genmitsu-cnc-router-3018-mx3?_pos=1&_sid=7d14826d2&_ss=r)
Connected to [CNC machine ](https://www.sainsmart.com/collections/genmitsu-cnc/products/sainsmart-genmitsu-cnc-router-3018-prover-kit)
I can connecto the module from lasergrbl SW, jog the axis and load file
But I can't turn laser on/off by SW
If i use physical button it will be on but all the time of course so can't really engrave
Any idea?
Tried m3 m4 and laser flag 0 and 1

**Comment by StuartB4** [comment]
Do you have this enabled?

![8888888888888888](https://user-images.githubusercontent.com/16980026/82730668-58deaf00-9cf9-11ea-8737-1ca525188a03.jpg)

**Comment by ronisegoly** [comment]
Yes, I tried check and uncheck
BTW not sure it's related, when I connected the laser module I was left with one cable which was not used
See attached
![00100lrPORTRAIT_00100_BURST20200521183937288_COVER](https://user-images.githubusercontent.com/5304613/82731208-d57b8880-9d0d-11ea-81d7-acfc97436183.jpg)
![IMG_20200521_160413 (1)](https://user-images.githubusercontent.com/5304613/82731209-d7dde280-9d0d-11ea-94a7-0a8b5447c557.jpg)
![IMG_20200521_160418 (1)](https://user-images.githubusercontent.com/5304613/82731212-dad8d300-9d0d-11ea-9a88-2152e342867e.jpg)

**Comment by StuartB4** [comment]
I think that lead is for if you have the 3 pin 12v, Gnd, PWM socket on your main controller board.

**Comment by ronisegoly** [comment]
the socket on my controller is two pin
what's the functionality of the PWM connection asdie from setting laser on and changing it's level? If that's the only one then I suspect the connection is faulty

**Comment by StuartB4** [comment]
The 3 pin PWM wire supplies the power and the PWM signal to a 3 pin laser, but your laser has a seperate power supply, so from what I can see on the images you have what you need with the seperate power and the 2 pin PWM lead. The black wire is just a ground on either the 2 pin or 3 pin lead.

**Comment by StuartB4** [comment]
The only other thing I can think of is to ground both power supplies together.

**Comment by ronisegoly** [comment]
thanks
waiting for supplier's support

**Comment by ronisegoly** [comment]
issue resolved.
Initial spindle speed in config file was 10000

**Comment by StuartB4** [comment]
Ok. :+1:
