### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by ghost** [arkypita/LaserGRBL#1024]
I don't know a thing about lasers. I had ordered a cheep Super Carver off the internet. It came with software that worked for 1 day then vanished from my computer. Now I have the Super Carver but no software. I have no idea what the machine is programmed to run but hoping it may be grbl? Can anyone help me with this issue?

**Comment by thecuress** [comment]
TRY to install lasergrbl

**Comment by Schwarzi07** [comment]
Could you please provide more Information absolut the engraver.

**Comment by thecuress** [comment]
i download the softaware....i try and I tell you

**Comment by thecuress** [comment]
try this link   https://smartcarve.software.informer.com/download/

**Comment by ironhorse2959** [comment]
Schwarzi07... It's a SuperCarver 100W laser. I  did install lasergrbl and on com 3 baud 9600 it homes but wont connect. I tried benbox but none of the .hex files work. Totally new to this and totally confused?

**Comment by ironhorse2959** [comment]
thecuress... I tried to download smartcarv but it wants do download an .rar

**Comment by thecuress** [comment]
you have not winrar for decompres the file?

**Comment by StuartB4** [comment]
Change the Baudrate to 57600.
