### ISSUE TITLE
Posizione immagine e punto partenza

### ISSUE THREAD

**Issue by caparrottapasqualino** [arkypita/LaserGRBL#103]
Buongiorno, complimentandomi per l'ottimo software vorrei porre due quesiti:
1. se importo un G-code con posizione iniziale centrale non riesco a visualizzare sul vs software tutta l'immagine ma soltanto la porzione in alto a dx senza possibilità di zoom/dezoom. Esiste possibilità di vedere l'immagine da incidere nel suo complesso?
2. Esiste la possibilità di effettuare una sorta di anteprima di incisione per vedere l'area di incisione impegnata o comunque capire qual è il punto di partenza dell'incisione?

Grazie in anticipo, saluti.

Pasqualino

**Comment by arkypita** [comment]
Ciao

1. No, per come è scritto il codice di LaserGRBL la visualizzazione è centrata su 0,0 e taglia le parti negative del piano. Ho già inserito nella roadmap #64 l'obiettivo di rendere più virtuale la routine di disegno per visualizzare anche il negativo.

2. Si, con un custom button è possibile. Qui trovi un esempio di come farlo.
http://lasergrbl.com/it/usage/custom-buttons/

**Comment by arkypita** [comment]
sarebbe preferibile scrivere in inglese

**Comment by caparrottapasqualino** [comment]
Perfetto. Grazie mille per la risposta.

Chiedo scusa per l'italiano, eventuale prossimo post scriverò in inglese.

Saluti
