### ISSUE TITLE
Installer flagged by Windows Defender

### ISSUE THREAD

**Issue by kodosexe** [arkypita/LaserGRBL#1030]
Hey,

the Windows installer is being flagged by Windows Defender SmartScreen as a potential problem when you try to launch it, bacause it is an "unknown app".
It says there is no signature available and therefore it doesn't trust the program.

The screenshot is attached, but it's in German.
![laserGrblWD](https://user-images.githubusercontent.com/44935679/83554397-b08bd000-a4da-11ea-98c0-feeb4997c3d7.PNG)

**Comment by arkypita** [comment]
Known issue of false positive from AV

http://lasergrbl.com/faq/
#235
#70

I'm sorry for that, but it's something I cannot deal with it.

**Comment by arkypita** [comment]
Signing software require to pay for a signing certificate. 

As free software developed in my spare time I decide, for now, to not pay for this service.
