### ISSUE TITLE
Improved cooldown timer

### ISSUE THREAD

**Issue by frankvdh** [arkypita/LaserGRBL#1039]
Currently, the cooldown timing is simple clock time from the start of the work, not taking into account the time that the laser is actually on or off. So for example, I have had the machine stop when it was just moving the axes with the laser off.

I propose that the cooldown timing be along the lines of...
Every second:
  If the laser is on, 
       Add 1 to the timer
       If the timer exceeds the maxtime
               Turn the laser off
               If speed of either stepper is above max jerk speed
                      // Need to decelerate the steppers if speed is above max jerk
                      Record X, Y position
                      Decelerate to max jerk
                      Stop movement 
                      Position at below max jerk speed to the recorded X,Y
               endif
               Stop motors
               Pause for the offtime
               Resume motion with laser on   // Accelerating to specified speed, so also ramp up laser power
      endif
  else
     Subtract offtime/maxtime from the timer // So time spent with the laser off during positioning counts towards cooldown
  endif

**Comment by arkypita** [comment]
cooldown it is not something achievable in these terms
