### ISSUE TITLE
Editing power/speed setting in Material DB

### ISSUE THREAD

**Issue by frankvdh** [arkypita/LaserGRBL#1043]
![image](https://user-images.githubusercontent.com/6589024/83956272-48f5cc00-a8b0-11ea-8c09-8847a476401b.png)

It's unclear what format the numbers for **Speed** and **Power** should be when inserting a new record into the Material database. After some trial and error (particularly since it defaults to "100%" and "1000 mm/min", **including the non-numerics**), I found that you need to enter just the numbers.

Likewise editing a record... the % and mm/min are still there when you start editing a record, and then produce an error if you change one of these values but don't delete the non-numerics.

It would also be helpful if the error message said which field was in error, and what the expected format is.

**Comment by arkypita** [comment]
Thanks for the bug report. The database functionality is experimental, I still have to do some refinements.

The datagrid control that I use to view / take data is unfortunately not very comfortable and I expect some of these behaviors. Little by little I will try to fix them all.
