### ISSUE TITLE
Centerline offsets not working

### ISSUE THREAD

**Issue by Kalamgish** [arkypita/LaserGRBL#1047]
Hi, great program but I ran across a problem.
I want to overlay a centerline image on an existing picture but whatever I change the offsets to the centerline stays at the same position.

Thanks

P.S. offsets work fine on line to line tracing, Ver 3.5.0

**Comment by arkypita** [comment]
Thank you! You are the first that report this bug, but it exists since the first version with centerline.
I'll fix in the next version
