### ISSUE TITLE
import of NC files

### ISSUE THREAD

**Issue by gerdvogel** [arkypita/LaserGRBL#108]
when importing images you can set to use M3 or M4.
Unfortunately it is not possible with importing NC files.

Is it possible to change the software so that I can choose  M3 or M4 should be used?
I can change the NC file with an editor, but sometimes I forget that.

**Comment by brakthehun** [comment]
I use notepad to open the files and use the find and replace tool in notepad.

**Comment by arkypita** [comment]
Yes, I also use notepad++ for manual edit of gcode file but @gerdvogel is looking for an automatic mode to do that.
