### ISSUE TITLE
Hotkey Shortcuts 

### ISSUE THREAD

**Issue by Focus3** [arkypita/LaserGRBL#1080]
Good day,

i'm sorry to bother everyone with this, because it's not really much of an issue. I have been assigning Hotkeys which i use through my CNC pendant, and i wanted to assign two hotkeys to the "Speed". One to increase and one to decrease.

Is there a hotkey option for this? Because i can't find it in the Hotkeys window.

I have attached a picture.

<img width="971" alt="speed hotkeys" src="https://user-images.githubusercontent.com/39139386/88481589-a4f9da00-cf5c-11ea-8dae-5b810e7640d3.png">

thank you foryour help in advance.

**Comment by gmmanonymus111** [comment]
I don't think that kind of Hotkey is implemented yet. You can only edit step size, or, G1 and G0 Multipliers

**Comment by arkypita** [comment]
added: https://github.com/arkypita/LaserGRBL/releases/tag/v3.7.1
