### ISSUE TITLE
Laser doesn't turn on

### ISSUE THREAD

**Issue by DLovejoy1947** [arkypita/LaserGRBL#1106]
I have a 7W laser and just purchased an EleksMaker SE v3.2 stepper motor controller board. With LaserGRBL I can move the laser along the x and y-axis, but the laser will not turn on.
Are there configuration settings or firmware that I need to change?

**Comment by BeatSlayer** [comment]
Your's are...?

**Comment by DLovejoy1947** [comment]
David Lovejoy
djlovejoy@woodtoysandmore.com

**Comment by StuartB4** [comment]
Start LaserGRBL and click Connect then go to Grbl menu and click Grbl configuration you will get a list of settings. 
Post a screenshot of them here. You can expand the list so you get them all in the screenshot by stretching the window down a bit on the bottom edge.
Like this.

![Untitled](https://user-images.githubusercontent.com/16980026/91181129-76e4f280-e6e0-11ea-9ffb-7c50488c0bc0.jpg)

**Comment by wilson740** [comment]
hola
tengo un láser de 2500 mw que no prende, tiene todo conectado, hace todos los movimientos de grabar pero No funciona el láser, no enciende, no entiendo la razón
Ayuda por favor que debo hacer
Gracias
