### ISSUE TITLE
Changing Zero Point

### ISSUE THREAD

**Issue by 3DStyle** [arkypita/LaserGRBL#1108]
Is it possible to change the laser zero point?
As default LaserGRBL will start at the bottom left, like this:
![Point 1](https://user-images.githubusercontent.com/37050901/91272345-48205800-e784-11ea-99af-9fa215583f9e.png)

I want to have the control to change the zero point location, lets say I have a piece of wood that I want to laser a logo on its
center, so I'll be able to change the zero point in LaserGRBL to the center of the image, something that will look like this:

![2](https://user-images.githubusercontent.com/37050901/91273816-769f3280-e786-11ea-9fee-9a8ec35fc199.png)

**Comment by 3DStyle** [comment]
Thanks for the tip Alex, it works great!
However, an implemented button in LaserGRBL that will do this job for you will be more convenient.

**Comment by arkypita** [comment]
already in #64 as "Add image centring helper #90"
however i think you can create a custom button that set zero point at center of your job after import
