### ISSUE TITLE
Test size button

### ISSUE THREAD

**Issue by Yakov76** [arkypita/LaserGRBL#111]
I have again thanks for the excellent program ! The program would be more convenient if a button appears for testing to position the engraved item.
Kind regards,
Yakov

**Comment by arkypita** [comment]
You can use custom buttons to add whatever you want:
http://lasergrbl.com/it/usage/custom-buttons/

**Comment by Yakov76** [comment]
Oh yeah ...Bellissimo ! )) Thank you!
