### ISSUE TITLE
Zapytanie 

### ISSUE THREAD

**Issue by Belfer79** [arkypita/LaserGRBL#1125]
Dzieki waszym instrukcjam udało mi sie skonfigurowac laser grbl ma jednak lekki problem po wypaleniu obrazka jego boczne krawedzie są jakby bardziej przypalone Ttak jakby laser przy zmianie kierunku  bardziej przypalal jak to moge zniwelowac

**Comment by StuartB4** [comment]
Czy używasz M4 w ustawieniach obrazu docelowego. Jeśli nie, zmień go na M4 za pomocą menu rozwijanego.

![Untitle999d](https://user-images.githubusercontent.com/16980026/93602385-73c8e380-f9ba-11ea-8397-6a0ca808c776.jpg)

**Comment by Belfer79** [comment]
Dziekuje pomogło

**Comment by Belfer79** [comment]
A z tą opcja linia środkowa to trzeba coś dodatkowego zainstalować  lub skonfigurować

**Comment by StuartB4** [comment]
Przepraszam, nie rozumiem, co masz na myśli przez środkową linię?

**Comment by Belfer79** [comment]
Chodzi o tą czwartą opcję l
![16008040432535531209779261608597](https://user-images.githubusercontent.com/71507453/93930198-47e09180-fd1d-11ea-9305-bcbb49d8ff90.jpg)
Do tej opcji linia srodkowa co jest potrzebne zeby to działało bo teraz wyskakuje błąd (0×d8)

**Comment by Belfer79** [comment]
Prosze mi wybaczyc za pisownie ale program sam mi słowa zmienia
