### ISSUE TITLE
My laser looks big and it causes my cutting and engraving to leave big mark. I tried to to turn the focus lens tight in and it's still big. My machine is an ORTUR Laser Master 20 watt.

### ISSUE THREAD

**Issue by ikuemi** [arkypita/LaserGRBL#1129]

**Comment by arkypita** [comment]
For what I know there are 2 kind of 20W ORTUR modules: one that comes with adjustable focus ring, one that comes with a fixed focus ring.

The one with focus ring has an optimal distance at about 3-5 cm

The one with fixed focus has a very short focal distance, and comes with an alluminium block that can be use to measure that distance. It also have a ring but if you move the focus does not change.

![image](https://user-images.githubusercontent.com/8782035/94114686-f6cdbc00-fe48-11ea-950c-0453339fff18.png)

Post a picture of your modules to let me understand which kind you have.

PS: you can have a better support on ortur facebook community or ortur support forum:
https://www.facebook.com/groups/orturusergroup
https://ortur.tech/support/
