### ISSUE TITLE
$C

### ISSUE THREAD

**Issue by Yakov76** [arkypita/LaserGRBL#113]
It is not possible to check the g-code with the $ C command. I enter the command, it works, but it is not possible to start the verification process-the start button is not available. What am I doing wrong ? (GRBL 1.1)
Thank you !
Best regards,
Yakov

**Comment by arkypita** [comment]
I cannot test it now, but from what I know the start button is enabled at this conditions:
1. Com opened
2. Program loaded
3. Status Idle

Suppose 1 and 2 are ok, what could you say about 3? Is status Idle or not?
Note: you can read status on the lower right corner of the window.

**Comment by Yakov76** [comment]
Look at the screen, please
![default](https://user-images.githubusercontent.com/31748748/30798382-815ff45a-a1ea-11e7-9df7-5092a867250b.jpg)

**Comment by arkypita** [comment]
Greetings, you have found a bug. I did not handle the status "Check"
I will fix it as soon as possible

**Comment by Yakov76** [comment]
Thank you ! ))

**Comment by arkypita** [comment]
fixed

**Comment by Yakov76** [comment]
Super !!! Thanks !
P.S. The program has some inaccuracies in the Russian translation. If there is a need, I will help translate Russian.
Kind regards,
Yakov

**Comment by arkypita** [comment]
I am doing a lot of code and UI rewriting in this days. Maybe when i have finish we can re-adjust russian translation. Thanks
