### ISSUE TITLE
Czwarta opcja w lasergrbl

### ISSUE THREAD

**Issue by Belfer79** [arkypita/LaserGRBL#1137]
![image](https://user-images.githubusercontent.com/71507453/95026597-bebd4900-0692-11eb-91c4-16a903067f93.png)
 Mam pytanie co trzeba zrobić żeby tą opcja czwartą była aktywna

**Comment by StuartB4** [comment]
Z Vectorize robi to.

![image](https://user-images.githubusercontent.com/16980026/95027644-1909da00-0692-11eb-8878-6ce0d9f6a24f.png)

Z linią środkową wykonuje po prostu 1 linię w oparciu o środek takiego obiektu.

![image](https://user-images.githubusercontent.com/16980026/95027714-8289e880-0692-11eb-9732-27c3608aa8aa.png)

![image](https://user-images.githubusercontent.com/16980026/95027730-acdba600-0692-11eb-9bf9-2fd07c8c88d6.png)

![image](https://user-images.githubusercontent.com/16980026/95027739-c977de00-0692-11eb-9639-3276f12ebcd7.png)

**Comment by arkypita** [comment]
Centerline need 64bit OS

**Comment by arkypita** [comment]
http://lasergrbl.com/faq/
