### ISSUE TITLE
Cycles in custom buttons?

### ISSUE THREAD

**Issue by ssombra** [arkypita/LaserGRBL#1138]
is there a way to make a push button that makes the laser go around the image for as long as the mouse button is pressed? 
Some kind of "while" cycle.

**Comment by ssombra** [comment]
I guess a 2 state button could also work for that purpose. The idea is framing the image more than one pass.

**Comment by StuartB4** [comment]
You can edit the Custom buttons.
This is the Frame button code, it's just repeated 4 times so it will frame 4 times.
You could repeat it as many times as you want, just by adding the same code over and over.
To change the speed just increase or decrease the F numbers in the code.

![2323232323](https://user-images.githubusercontent.com/16980026/95640950-4c37d900-0a97-11eb-8e47-7571c506cb34.jpg)

**Comment by arkypita** [comment]
Hi @ssombra 
It is not possible. Grbl (firmware) doesn't support gcode for cycles and implement them in LaserGRBL software it is not simple because you cannot know when one cycle execution is ended and you can send next) because Grbl give feedback only of command received, not executed.

**Comment by ssombra** [comment]
Thanks both for the explanations.
