### ISSUE TITLE
Control Speed and Power with analog input on Arduino Mega

### ISSUE THREAD

**Issue by kernge** [arkypita/LaserGRBL#1151]
Hey
Is it possible to connect Potentiometers on external Analog in Pins on Arduino Mega to control the Speed and Power of the Laser with an external Handheld-Panel

Thanks for Informations
Gerhard

**Comment by arkypita** [comment]
this is a question to post here: https://github.com/gnea/grbl-Mega

**Comment by kernge** [comment]
ok, Thanks for Information, i will post it there
