### ISSUE TITLE
TTL connection for Laser GRBL

### ISSUE THREAD

**Issue by Hari-Merla** [arkypita/LaserGRBL#1165]
hi,
i am trying to make a Laser Engraver.
i have got most things figured out.
the very last bit of the build is left.

I have been trying to turn on an off my Laser using the TTL Driver board, i have connected it to the Z+ pins on the cnc shield but my laser doesnt seem to be turning on.

Please Help me out with this.

Thank You

**Comment by gmmanonymus111** [comment]
Could you upload some pictures about your setup and wiring?
What version of GRBL do you use?

**Comment by Hari-Merla** [comment]
> Could you upload some pictures about your setup and wiring?
i will attach the photos of the wiring from CNC Shield to Laser Driver ,  i have disassembled the rest because i want to figure out this TTL connection. 

![IMG-3117](https://user-images.githubusercontent.com/67357179/98958015-d99f9a80-2527-11eb-8846-88411c2568fe.jpg)
![IMG-3118](https://user-images.githubusercontent.com/67357179/98958017-db695e00-2527-11eb-901d-bdaf9ab65b3c.jpg)
![IMG-3119](https://user-images.githubusercontent.com/67357179/98958034-defce500-2527-11eb-99d0-143c47d26875.jpg)
![IMG-3120](https://user-images.githubusercontent.com/67357179/98958037-df957b80-2527-11eb-89bb-448f980b74da.jpg)


> What version of GRBL do you use?
i use the 1.1h version , i flashed the firmware using the LaserGRBL v3.8.0

**Comment by StuartB4** [comment]
Are you sure the blue wire is ttl - and the green ttl + on the laser driver board. 
Do you have Support PWM enabled in Settings on the Grbl menu. Second Tab from the left. 
Also $32 set to 1 and $30 set to 255 in Grbl configuration on the Grbl menu.

**Comment by StuartB4** [comment]
Does the 12 +/ - on the laser driver board next to the black power supply wires go to the laser fan, and the one next to the ttl socket to the laser diode?

**Comment by Hari-Merla** [comment]
> Are you sure the blue wire is ttl - and the green ttl + on the laser driver board.
if i flip the green and the blue wires the laser stays for the whole time.

> Do you have Support PWM enabled in Settings on the Grbl menu. Second Tab from the left.
yes i have enabled the PWM in the setting.

> Also $32 set to 1 and $30 set to 255 in Grbl configuration on the Grbl menu.
Done that.

> Does the 12 +/ - on the laser driver board next to the black power supply wires go to the laser fan, and the one next to the ttl socket to the laser diode?

YES it does

**Comment by StuartB4** [comment]
Ok.

**Comment by gmmanonymus111** [comment]
Are the laser driver and the shield on common ground or do you use the same PSU for arduino/shiled and the laser driver?

**Comment by Hari-Merla** [comment]
i have connected a volt meter to the Z+ pins and see that when the laser is off it is around 3v and when it is engraving it goes upto 7v,
Did the above without the Laser connected, just wanted to check whether the TTL Signal works

i wanted to ask do we need to use a resistor of any kind for the ttl connection.

**Comment by Hari-Merla** [comment]
> Are the laser driver and the shield on common ground or do you use the same PSU for arduino/shiled and the laser driver?

There is no Ground option on my Shield and havent given Arduino any Ground.

PS: I am really thankful for your help and support.

**Comment by gmmanonymus111** [comment]
> There is no Ground option on my Shield and havent given Arduino any Ground.

I meant the `-` pin as ground (and `+` is either 5V or 12V)

**Comment by arkypita** [comment]
> i have connected a volt meter to the Z+ pins and see that when the laser is off it is around 3v and when it is engraving it goes upto 7v,
> Did the above without the Laser connected, just wanted to check whether the TTL Signal works
> 
> i wanted to ask do we need to use a resistor of any kind for the ttl connection.

Because Arduino is a 5v device you should read 0v with laser off and about  5v with laser at full power. Any different values mean something wrong in your circuit or in the mode you use the multimeter

**Comment by Hari-Merla** [comment]
> I meant the `-` pin as ground (and `+` is either 5V or 12V)

they are on the same power supply but different connections

![IMG-3123](https://user-images.githubusercontent.com/67357179/98973038-3e172580-2539-11eb-814a-96b222385f39.jpg)

**Comment by arkypita** [comment]
When you measure z+ the red multimeter cable should be connected to z+, the black one should be connected to any of the black stripline pins (they are all connected to ground) the multimeter shoul be settled to voltage measurements DC

**Comment by Hari-Merla** [comment]
> When you measure z+ the red multimeter cable should be connected to z+, the black one should be connected to any of the black stripline pins (they are all connected to ground) the multimeter shoul be settled to voltage measurements DC

i have connected the Voltmeter to the Z+ and Z- pins 
the arduino is in idle state 
i am getting a reading of 2.31v

please find the Picture attached
![IMG-3131](https://user-images.githubusercontent.com/67357179/99045236-09e24a00-25b7-11eb-9575-2e55d0a65c4f.jpg)

**Comment by arkypita** [comment]
Can you try with the CNC motor shield removed, only on the arduino UNO pins connected via its own USB?

Here is the pinout: https://github.com/gnea/grbl/wiki/Connecting-Grbl

**Comment by arkypita** [comment]
Pin labeled GND for black probe, Pin labeled "11" (variable spindle pwm) for red probe.

**Comment by Hari-Merla** [comment]
> Pin labeled GND for black probe, Pin labeled "11" (variable spindle pwm) for red probe.
yea i figured out it was the problem in the Arduino itself.
i am using a new one now and am getting the voltages correct,
hopefully my laser will work now.

Thank you sooo muchh for your time and help.

**Comment by Hari-Merla** [comment]
Thank you so much everyone for the Time and help , i got my engraver to work.
if you are interested in knowing any details or the approach write to me on - harijagan9866@gmail.com.

Cheers!!!

**Comment by FiusRa** [comment]
Hello. my language is not english. it is a translation . may be bad. In general, I have a driver on the xl4015 microcircuit. in the datasheet, it can be controlled by ttl. here is the datasheet. https://datasheetspdf.com/pdf-file/786208/Xlsemi/XL4015/1. 8 page. the problem is that the management is reversed. that is, when the high level is turned off when the low is turned on. how to invert the output to the firmware. so that pin z is always high.

**Comment by FiusRa** [comment]
Typical System Application (TTL shutdown function)
Logic level signals shutdown function can be used in typical system application with external
components. When the TTL high voltage above 3.3V(referenced to ground, lower than VIN), the
converter will shutdown, input current less than 5mA; when the TTL Low voltage below
0.8V(referenced to ground), the converter will turn on.
