### ISSUE TITLE
Header and footer GCode do not get added when saving a file

### ISSUE THREAD

**Issue by ryanaukes** [arkypita/LaserGRBL#1172]
I run al my gcodes from a sdcard. 
In settings -> gcode the header and footer are set to 'G90' and 'G0 X0 Y0 Z0' respectively.
However, when I create a gcode and save it to a file, these codes are not added to the saved file.
Am I doing something wrong? Or can this be added to the software?

Thanks in advance,
Ryan

**Comment by arkypita** [comment]
![image](https://user-images.githubusercontent.com/8782035/99730443-bd1dd800-2abc-11eb-902e-0188175dee6e.png)

**Comment by ryanaukes** [comment]
I feel so stupid now, sorry!
