### ISSUE TITLE
laser stays on during cooling

### ISSUE THREAD

**Issue by Bazza1959** [arkypita/LaserGRBL#1195]
I have an issue where my laser stays on during cooling, it all depends on when the cooling starts. If the laser is on when cooling starts it stays on, but if it was off, in say travel, then it stays off during cooling. What can I do to fix this as I had a print get spoiled yesterday because the laser stayed on during a supposed 5 minute cooling period which left the laser on in one spot for 5 minutes and burnt a horrible big hole in my project

**Comment by arkypita** [comment]
Auto cooling only will work with certain condition. Are you sure you respect them?
There is a visible warning message in the box where the feature is activated.

![image](https://user-images.githubusercontent.com/8782035/101543099-0ff3fc80-39a4-11eb-9d25-b2c06ae596e3.png)

**Comment by Bazza1959** [comment]
I must apologize for opening this issue, as after I did, I then found the answer you have shown above
