### ISSUE TITLE
help

### ISSUE THREAD

**Issue by MareSmaX** [arkypita/LaserGRBL#1197]
Hi everyone, I'm Giuseppe, I'm writing to everyone for a solution that for now I can't solve, I have a CNC 1310, and lately I decided to try to engrave with laser module 5500w, I made an update of the controller to the GRBL 1.1 version , I have inserted the laser in the appropriate jumber I connect it to the GRBLaser software, I enter all the parameters with the gcode that interests me, but when I click on start, the machine follows all the movements perfectly, but the laser does not emit any signal from the controller, someone can you help me on this problem? I have already enabled co $$ the command $ 31 = 1 but nothing starts nothing, for any info I am waiting, thanks in advance.

Salve a tutti, sono Giuseppe, scrivo a tutti per una soluzione che per adesso non riesco a risolvere, ho una CNC 1310, e ultimamente ho deciso di provare ad incidere con laser modulo da 5500w, ho fatto un aggiornamento del controller alla versione GRBL 1.1, ho inserito nell apposito jumber il laser lo collego al software GRBLaser, inserisco tutti i parametri con il gcode che mi interessa, ma quando clicco su avvia, la macchina segue tutti i movimenti perfettamente, ma il laser non emette nessun segnale dal controller, qualcuno puo' aiutarmi su questo problema? ho gia abilitato co $$ il comando $31=1 ma niente non si avvia nulla, per qualsiasi info sono in attesa, grazie in anticipo.

**Comment by belialboy** [comment]
Novice advice here, but I think $31 sets the Minimum Spindle Speed. $32 enables Laser-mode.  M3 and M5 commands turn the laser on and off, and the S value (0-255) sets the intensity of the laser from 0-100%.
