### ISSUE TITLE
Visual studio Community 2015

### ISSUE THREAD

**Issue by wfluna** [arkypita/LaserGRBL#12]
Hi.
I try to open this project in Visual Studio Community 2015 but 
many errors appear.
What is the best integrated development environment (IDE) for this project?

**Comment by arkypita** [comment]
LaserGRBL is developed with SharpDevelop and is written in C# language targeting 2.0 framework, so it is fully compatible with older versions of Windows XP (which can also be compiled). I also tryed to open it with VS2012 and it work.

Anyway the code is all inside the solution (no external dll, no NuGet component, nothing) and must be possible to convert and open in any newer versions of the IDE, or target it to newer framework version like 3.5 and 4.0.

**Comment by arkypita** [comment]
Try to checkout now, i have just committed a version with double .sln file: one for SharpDevelop and one for VS2012. Try open VS2012 version with VS 2015, it should convert and work.

If not, please tell me more about errors

**Comment by wfluna** [comment]
hi @arkypita 
![vs20015 error](https://cloud.githubusercontent.com/assets/10509581/23150617/b1465984-f7c2-11e6-871d-13b3275f08fa.png)

click in ignore and continue 
![vs20015](https://cloud.githubusercontent.com/assets/10509581/23150511/f436ee3a-f7c1-11e6-9ed5-422107f3f72c.png)
and in the preview form label
![vs20015 preview](https://cloud.githubusercontent.com/assets/10509581/23150658/0354cc24-f7c3-11e6-98d4-cca036cf7833.png)
Best regards

**Comment by arkypita** [comment]
Are you sure that you have compiled in the solution at least once time?
Please use "Build solution" from "Build" menu. It must compile, errors will disappear.
If you have compile errors, please send (copy-paste) the full build output ("View" - "Output")

**Comment by wfluna** [comment]
no problem anymore, "Build solution" from "Build" menu is ok
and with this the app work

**Comment by wfluna** [comment]
and with sharp development this work well too.
Thanks a lot.
