### ISSUE TITLE
Laser on when "HOLD" has been pressed

### ISSUE THREAD

**Issue by JBSchueler** [arkypita/LaserGRBL#120]
When I press hold, the laser stays on (last PWM setting).
It would be nice if the laser goes off (or weak power mode like mentioned in ticket #119) when this button has been pressed.

**Comment by arkypita** [comment]
This is not in issue/request for LaserGRBL but a request for Grbl developers.
However if you upgrade to Grbl v1.1 and activate $32 laser mode you will obtain laser off each time laser stops. https://github.com/gnea/grbl/wiki/Grbl-v1.1-Laser-Mode
