### ISSUE TITLE
Feature Request:

### ISSUE THREAD

**Issue by belialboy** [arkypita/LaserGRBL#1202]
I run some long jobs on my setup. It'd be awesome if instead of a sound LaserGrbl could call an API like Pushbullet or a simple WebHook to tell me when it's complete of if an error occurred during a job. Saves me guessing on the time, and constantly running back to the machine because I think it made an unusual noise.

**Comment by StuartB4** [comment]
>  Saves me guessing on the time, and constantly running back to the machine because I think it made an unusual noise.

You should never ever leave a laser engraver unattended. Just google "Laser engraver fire"
