### ISSUE TITLE
CustomButton.gz file missing

### ISSUE THREAD

**Issue by Bunny120818** [arkypita/LaserGRBL#1207]
Hi, I have downloaded the LaserGRBL software but it doesn't come with the CustomButton.gz file, it's nowhere to be seen on my PC. 

Step 1:
I Launch LaserGrbl

Step 2:
I Right-click the button area in LaserGrbl -> click “Import Custom Buttons”
I first open the software then I go below to right-click, then I select import

CustomButton.gz file cannot be found

 I tried to remove the program and redownload a few times but it still doesn't help. what should I do? Thank you

**Comment by arkypita** [comment]
https://lasergrbl.com/usage/custom-buttons/

**Comment by Bunny120818** [comment]
Hi, Thank you for your reply. I did click on the download button but nothing happened, "there's no download" 
![111](https://user-images.githubusercontent.com/75994743/102163097-6b9f1800-3ec5-11eb-8b5f-5416a5d1681d.jpg)

**Comment by StuartB4** [comment]
It should be in the default download folder on your computer, unless you download to a different folder. 
It is there somewhere if you clicked the download link.

**Comment by Bunny120818** [comment]
Hi, Thank you for your reply. I did click on the download button but nothing happened, "there's no download"
![111](https://user-images.githubusercontent.com/75994743/102163891-16173b00-3ec6-11eb-80a9-ad843983c6b4.jpg)

**Comment by StuartB4** [comment]
I just got it and uploaded it to my pcloud account. You dont need to register or open an account, just download it. 

https://u.pcloud.link/publink/show?code=XZPA64XZb0YdRsvhbE8PzBIYLT63JpqgVTtk

**Comment by StuartB4** [comment]
![image](https://user-images.githubusercontent.com/16980026/102166764-c6fce600-3e84-11eb-8f2b-3cee3d6f2025.png)

**Comment by StuartB4** [comment]
I use Firefox browser. If I hovver the mouse over the Download button it shows the file at the bottom of the screen. When I click it it downloads, you don't get any options to save or cancel, it just downloads. 

![image](https://user-images.githubusercontent.com/16980026/102167295-0d067980-3e86-11eb-9c3c-7b668192a509.png)

**Comment by Bunny120818** [comment]
Hi, I've tried opening all files on my computer and the download is nowhere to be seen, but the link you just sent works! OMG Thank You. Next is to figure out how to use it haha thank you for the follow-up, you're awesome 

![333](https://user-images.githubusercontent.com/75994743/102169280-d142d280-3ecc-11eb-9434-2c1ed825557f.jpg)

**Comment by StuartB4** [comment]
Good to know you got it working.  
Thanks for letting us know. :+1:

**Comment by lcv-vr** [comment]
Hello
I just downloaded the custom buttons from the lasergrbl website and the same thing happens to me that was mentioned in this thread. It doesn't let me open the file either with WinRaR or WinZip... it tells me that the file is damaged. Could someone please correct the error or upload the file in another format? I use Windows 10

**Comment by arkypita** [comment]
You don't need to unzip it, just load in LaserGRBL as it is described in download page.
