### ISSUE TITLE
Newest software update has put my laser out of commission

### ISSUE THREAD

**Issue by ShelliTr** [arkypita/LaserGRBL#1210]
So up until the recent update my laser has worked fine on lasergrbl. Now that I have updated it will not work at all.

The motor is running, it is very random when it will actually connect.
When it will connect and I send the file it endlessly file transfers and never actually starts the burn.

I am at a complete loss for what to do, and I just had an order last night come in for some ornaments I make with my laser and I am starting to panic. Please help.

**Comment by hixnhx** [comment]
I have great success with lasergrbl untill the last update and every thing i try to do just burns and doesn't cut.  how do I revert to previous  version

**Comment by arkypita** [comment]
Are you talking about v3.8.5?

**Comment by arkypita** [comment]
All LaserGRBL version are available here: https://github.com/arkypita/LaserGRBL/releases
