### ISSUE TITLE
1-bit code optimalisation

### ISSUE THREAD

**Issue by JBSchueler** [arkypita/LaserGRBL#122]
I was observing the commands which where send to the cnc laser and noticed a lot of probably unneeded large commands are send over.

Each command has a feed rate and power level.
![image](https://user-images.githubusercontent.com/7997096/30984556-f0bc71a2-a48d-11e7-9567-825e7bd3e2ca.png)

In my opinion this can be set once at the beginning, before enabling the laser with M3/M4.
For 1-bit code it should not be needed to set the feed rate and power level every single line.

At the top
```
G0 F3000 S0
G1 F2000 S255
```
and the code further on will look like
```
G0 X-1.667 Y1.667
G1 X-.667 Y.667
G0 X-0.167 Y0.167 F3000 S0
G1 F2000 X-.167 Y.167 S255
```

This would save in communication and PC memory wright?
Or is there a reason to do it the way it is implemented right now?

**Comment by arkypita** [comment]
LaserGRBL is a early product. Some functions was developed on the top of the others without many attention to code aesthetics and maintainability.

The optimization was written with the approach of producing already optimized gcode (from the first step) but I saw that this is not the best solution.

Now I am going to develop a new version, my goal are:
1. separate configuration files and classes
2. rewrite image import UI
3. rewite gcode generation and optimization

The new approach for 3 will be that the generator will generate full gcode, with redundant infos. A second pass strip out all the redundant codes based on state information.

Are you sure that Grbl has 2 different F and S memories for G0 and G1? Have you a link where to read about that?
