### ISSUE TITLE
Sleep Command.

### ISSUE THREAD

**Issue by StuartB4** [arkypita/LaserGRBL#124]
Been trying to get the Sleep command to work ($SLP). GRBL 1.1
When I type the command in LaserGRBL it responds with: 
[MSG:Sleeping] but does not actually do anything, everything is still powered including the motors.
![sleep](https://user-images.githubusercontent.com/16980026/31017393-32ba6d24-a520-11e7-9f57-6540d7356149.png)

Then I have to click Disconnect and Connect again to do anything.
GRBL comes back with:
![sleep2](https://user-images.githubusercontent.com/16980026/31017403-39637db4-a520-11e7-8a20-1d5266de0f6f.png)

I click the Padlock icon to unlock it and then the Reset icon to reset GRBL.
That works fine and it comes back to normal. Just can't get it to power down the motors.
Am I missing something?

 I read this about the command:
"Sleep Mode : Grbl may now be put to "sleep" via a $SLP command. This will disable everything, including the stepper drivers. Nice to have when you are leaving your machine unattended and want to power down everything automatically. Only a reset exits the sleep state."

Thanks.

**Comment by arkypita** [comment]
LaserGRBL is only a frontend for grbl. 
What grbl does (or does not do) when a command was sent must be asked to grbl issue tracker.

**Comment by StuartB4** [comment]
Ok thanks.
