### ISSUE TITLE
Ooops! Something went wrong. (Computer without COM port)

### ISSUE THREAD

**Issue by tomturican** [arkypita/LaserGRBL#1245]
Thank you again for your great work. Today I installed your program on my second computer. There is currently no machine connected and therefore there is no active COM port.
Since version 3.8.10 I can no longer call up the settings. It is possible that the existence of a COM port is not checked correctly and an error is caught.
![2021-01-04](https://user-images.githubusercontent.com/50337031/103569918-73e8e280-4ec8-11eb-9221-652d3ca1dc58.png)

**Comment by arkypita** [comment]
Thanks for bug report. I'll check the code and release a fix

**Comment by arkypita** [comment]
Was not for the com port, it was because you never connect it to a grbl board.
I will soon release the fix.

**Comment by arkypita** [comment]
Fixed in v4.0.2 https://github.com/arkypita/LaserGRBL/releases/tag/v4.0.2
