### ISSUE TITLE
Some requests

### ISSUE THREAD

**Issue by helmuteke** [arkypita/LaserGRBL#125]
Add some basic functions standard like

Set new Home point
Laser control ( On/Off) but low , perfect for positioning the laser
Countdown timer when running G-code

**Comment by StuartB4** [comment]
To Set New Home Position.

![newhome 1](https://user-images.githubusercontent.com/16980026/31047554-e6cba4ec-a604-11e7-935b-ee860f5c853d.png)

![newhome 2](https://user-images.githubusercontent.com/16980026/31047555-eca16eb0-a604-11e7-8251-9754ccb8e2c4.png)


When you've finished click Save. 
Connect Lasergrbl, move the laser to where you want it with the 8 arrow buttons and then click on your new button to set the new Home. Move the laser again and press the little house icon and the laser should goto the new home position.

**Comment by helmuteke** [comment]
Hello , 

I know you can do this with custom buttons . But it will nicer if integrated.

What do you use for laser on / off ?

**Comment by StuartB4** [comment]
Ok.
I just use M3 for on and M5 for off. No power settings because I dont use PWM for the laser power.
It's either on full power or off.

**Comment by dgarrigop** [comment]
I use the custom button to home, but it should be home on the screen too, and only makes home for the arduino.

**Comment by arkypita** [comment]
@dgarrigop 
See #36
