### ISSUE TITLE
CH340 driver?

### ISSUE THREAD

**Issue by itow82** [arkypita/LaserGRBL#1253]
USB-SERIAL CH340 
Windows cannot verify the digital signature for the drivers required for this device (Code 52)
i have atmostack A5 and win 7
Thank you in advance
![3](https://user-images.githubusercontent.com/77118746/103925583-0fbc5d80-5118-11eb-8d37-ac9a13778c95.png)
![2](https://user-images.githubusercontent.com/77118746/103925612-1b0f8900-5118-11eb-8155-56bb35c81b2e.png)

**Comment by arkypita** [comment]
![image](https://user-images.githubusercontent.com/8782035/103939141-9c244b80-512b-11eb-85aa-29ce0b65a87d.png)

Where does your driver comes from?

**Comment by itow82** [comment]
hi
Thanks for the quick reply
driver come with the software


![6](https://user-images.githubusercontent.com/77118746/103940056-130e1400-512d-11eb-956b-de96c102d323.png)

**Comment by arkypita** [comment]
> driver come with the software

I think you mean the one you can install from LaserGRBL's "Tools" menu. Correct?

It is exactly the same I have on my PC and I have no issue.

**Comment by itow82** [comment]
yes  from LaserGRBL's "Tools" menu

**Comment by arkypita** [comment]
Seem to be a your pc issue.

Did you try google for it?

**Comment by itow82** [comment]
![8](https://user-images.githubusercontent.com/77118746/103944749-6df73980-5134-11eb-9ae6-e3d052ee729a.png)

**Comment by StuartB4** [comment]
I use this one in Windows 7 if I need to install one. 
https://learn.sparkfun.com/tutorials/how-to-install-ch340-drivers/all

Right click it and click Run as Administrator. 

![image](https://user-images.githubusercontent.com/16980026/103945076-8e22fa80-512c-11eb-8b0e-887c15fcb76c.png)

![image](https://user-images.githubusercontent.com/16980026/103945303-ec4fdd80-512c-11eb-9e03-6fb2770d9ebe.png)

**Comment by itow82** [comment]
@StuartB4  thank you very mach  
@arkypita thank you very mach

**Comment by arkypita** [comment]
Does stuart driver work for you?

**Comment by itow82** [comment]
yes

**Comment by arkypita** [comment]
@StuartB4 if you think this version is better i'll update the package inside LaserGRBL

@itow82 can you put a screenshoot of the driver property dialog, with the new driver? just to understand the difference in version, provider etc

**Comment by itow82** [comment]
![44](https://user-images.githubusercontent.com/77118746/103994896-f22ed880-5197-11eb-8e61-cd0d3ad4c333.png)
![66](https://user-images.githubusercontent.com/77118746/103994899-f3600580-5197-11eb-9efd-6a9a2e863841.png)

**Comment by StuartB4** [comment]
@arkypita 

The driver it'self It seems to work fine and without any problems.

The only problem I've had with it is when closing it after installing the driver. 
It pops this error box up. Maybe because it's an old version, may be my computer.  
It does'nt affect how it works, I just don't know why it does it.
It does'nt do it everytime either. 

I just click "This program installed correctly" and it's fine.

![image](https://user-images.githubusercontent.com/16980026/104020034-71caa080-51b4-11eb-8a44-790efc96699f.png)

**Comment by itow82** [comment]
I had the same

**Comment by StuartB4** [comment]
@itow82.

Is it still working ok?
I thought it might just be me.

**Comment by arkypita** [comment]
As my version is newer, I will continue to keep this one.

**Comment by StuartB4** [comment]
Ok @arkypita.
:+1:

**Comment by itow82** [comment]
@arkypita @StuartB4 
Sorry for the delay in reply
I built a box with a smoke pumping system and an air nozzle
And now I have tried the machine and it works
I still need to work on the settings of power and speed for better results
Thank you very much

**Comment by StuartB4** [comment]
No problem. Glad you got it working. 
Thanks for letting us know. 
:+1:
