### ISSUE TITLE
laser no quema

### ISSUE THREAD

**Issue by marposan** [arkypita/LaserGRBL#1262]
*I have a CNC 3018 Pro machine, I have incorporated an EIDevo 10 W laser and fixed focus, I use Windows 10 64 Bit and Laser GRBL v3.8.7 the controller board is V3.4
I run into the following problem when executing the Laser GRBL program, it connects to the machine, loads the selected file and when executing it, it moves correctly, the laser light changes from green to blue when the switch is pressed, it is on, but the laser does not work (does not burn).
Is there any help for this?

**Comment by arkypita** [comment]
moved to discussion
