### ISSUE TITLE
I guess there is a typo

### ISSUE THREAD

**Issue by Mrjavaci** [arkypita/LaserGRBL#1267]
Now Line 43: 
            TlpZControl.Visible = Settings.GetObject("Enale Z Jog Control", false);
I think it should be:
            TlpZControl.Visible = Settings.GetObject("Enable Z Jog Control", false);

https://github.com/arkypita/LaserGRBL/blob/a423e38101c2b843695fe41e166e235277e639e9/LaserGRBL/JogForm.cs#L43

**Comment by arkypita** [comment]
Yes, but it is only a key for settings dictionary search.
The same typo is in the SetObject so it does work.

Cannot change because it is stored in setting file, so if I change the set value is not recognized.
