### ISSUE TITLE
problem with cnc shield v3

### ISSUE THREAD

**Issue by 4noxx** [arkypita/LaserGRBL#1290]
hello

i ve a problem to start my laser with lasergrbl. 

my connection:
![2021-01-19 18_46_05-Fotos](https://user-images.githubusercontent.com/12627059/105073004-be508e80-5a86-11eb-86bc-229b106ce584.jpg)

![2021-01-19 18_51_15-Foto - Google Fotos](https://user-images.githubusercontent.com/12627059/105073434-5d758600-5a87-11eb-9b0d-e29ddfe153ad.jpg)

1) is this right?

i started laserGRBL, install GRBL 1.1f with Tools / Install GRBL Firmware
connected to the Arduino / press focus button..... but nothing happens

over the push button on the laser, i can activated the laser. but not with the software.....

my laser:
https://www.amazon.de/gp/product/B08ML7G1RT

**Comment by arkypita** [comment]
This is not a LaserGRBL issue, and should be posted under [discussion](https://github.com/arkypita/LaserGRBL/discussions) session.
(moved)
