### ISSUE TITLE
The same parameters doesn't give me the same results

### ISSUE THREAD

**Issue by Beewap** [arkypita/LaserGRBL#1298]
So, I'm still new with the laser thing but I don't understand what append.

Few days ago I make some grayscale test and I had a really good result on mdf with this settings :

![grayscale01](https://user-images.githubusercontent.com/77555477/105472088-c9c8d300-5c9b-11eb-92aa-d3abaa59506c.JPG)

And I had this result:
![IMG_20210117_19515222](https://user-images.githubusercontent.com/77555477/105473281-3bede780-5c9d-11eb-8d8c-f0875b49200f.jpg)

Which is pretty good I think.

Now, few days after, I don't know why but I have to modify the setting to get the same result.
From 3000 mm/min (the left one) to 1300mm/min (the right one).

![IMG_20210121_084045 - Copie](https://user-images.githubusercontent.com/77555477/105473627-9c7d2480-5c9d-11eb-914c-ef37819383d1.jpg)

So here is some other information:
I know that I put the laser at 5.5cm. I can move it lower (a bit) or higher and still get the focus point.

Speak of focus point, I don't have a dot, but more a line that I can have really sharp and not blurry. But not a dot. (I can't take a picture of it, the phone only see a dot, but with my eyes I see a really small sharp line).
![IMG_20210122_1040442](https://user-images.githubusercontent.com/77555477/105475862-2c23d280-5ca0-11eb-89b3-0c0281cef538.jpg)

I'm on a win10 computer, Lasergrbl 4.05, firmware 1.1f
I also try with the 4.03 and it is the same issue.
It is a 5.5w laser from Mostics cnc 2 in 1.  (450nm wavelength, 5500mW output I think)

Other information,  I try to engrave another wood type (plywood birch, pin) and there the grayscale value are shorter. 
![IMG_20210121_08522200](https://user-images.githubusercontent.com/77555477/105476934-82454580-5ca1-11eb-927d-b7a66d8d5b92.jpg)

![IMG_20210121_08411221](https://user-images.githubusercontent.com/77555477/105476819-5de96900-5ca1-11eb-9ee3-147237c73da5.jpg)

I don't know what I've done and now that I wanna try some other wood or material, I think that maybe there is something wrong and that's why I got a not so much nice result on birch plywood.

**Comment by arkypita** [comment]
LaserGRBL give the same command to the machine, provided the same configuration.

This is not a LaserGRBL bug or issue, so this should be posted under "[discussion](https://github.com/arkypita/LaserGRBL/discussions)"

Please read https://lasergrbl.com/faq/ where you can find answer to most of this common asked question.
