### ISSUE TITLE
Websocket Problem

### ISSUE THREAD

**Issue by Mrjavaci** [arkypita/LaserGRBL#1306]
**Describe the bug**
When I connect with Websocket it says "Connected" but nothing is active.

**Screenshots**
https://imgur.com/a/fZn3TNi

**Hardware and software configuration (please complete the following information):**
 - Windows version
 - LaserGRBL 4.0.6
 - Nodemcu

**Comment by Mrjavaci** [comment]
my arduino is broken :(

The data when I change arduino it "???" comes as.

It seems to be a problem with the bound rate.

https://imgur.com/a/F6PEKj8

**Comment by Mrjavaci** [comment]
There is a problem because I feed Nodemcu from usb

Solved.

**Comment by arkypita** [comment]
I am happy, because I would not have known how to help you!
