### ISSUE TITLE
Switch to .Net 5.0 to have Multiplatform

### ISSUE THREAD

**Issue by smoki3** [arkypita/LaserGRBL#1309]
Are there any plans to switch to .net 5.0 to have MacOS support?

**Comment by arkypita** [comment]
I don't believe with .Net 5.0 it can run on MacOs because the UI is based on winform

**Comment by smoki3** [comment]
Damn, you are right. This was a point that I don't observed. 

There is a project called mono which should be able to handle this. But I don't know how good this is running
