### ISSUE TITLE
Problem running on an XP laptop 

### ISSUE THREAD

**Issue by barrule** [arkypita/LaserGRBL#131]
Windows XP SP3

When starting the program I get the following error 
![image](https://user-images.githubusercontent.com/891955/31298972-5106cd12-aae4-11e7-9f1d-57d3ad692f15.png)

Does anyone know what could be the cause.

**Comment by arkypita** [comment]
I am currently using LaserGRBL on a windows XP laptop, so I am sure that it could work.
The only requirement for LaserGRBL is to have [Microsoft .NET framework v3.5](https://www.microsoft.com/it-it/download/details.aspx?id=21) installed, please check the framework installation.

**Comment by barrule** [comment]
Thanks arkypita It is working now, that was the problem.
