### ISSUE TITLE
Connect/Disconnect tooltip text - English only

### ISSUE THREAD

**Issue by pebcz** [arkypita/LaserGRBL#1313]
Connect/Disconnect tooltip text is in English only - translated strings in settings.*.resx are without effect.

ConnectLogForm.cs
TT.SetToolTip(BtnConnectDisconnect, Core.IsConnected ? Strings.BtnDisconnectTT : Strings.BtnConnectTT);
![connect](https://user-images.githubusercontent.com/77896318/106161357-2b4edd00-6187-11eb-8edc-ade80060e8bc.png)

**Comment by arkypita** [comment]
![image](https://user-images.githubusercontent.com/8782035/106163432-723dd200-6189-11eb-868d-2d5c894244b5.png)

They work in Italian.
Translation could be found in Strings.*.resx
