### ISSUE TITLE
it goes beyond the supposed coordinates

### ISSUE THREAD

**Issue by alestanga** [arkypita/LaserGRBL#1322]
when I press the start button it goes beyond the supposed coordinates

let's put it should to go to X100-Y100 and then turn on the laser and move:
when I press start, it goes to X100-Y100, turns on the laser, and then it continues to move on the X and Y axis to the infinite and beyond with the laser turned on.
then I press stop, it asks me to restart, if I say yes it goes to X100-Y100 and goes on with the program as it should.
I can provide you with a video of the behavior.

the controller is a SainSmart Genmitsu 3018

**Comment by alestanga** [comment]
I've found the issue.
it was a configuration problem.

**Comment by arkypita** [comment]
if you wish you could explain what the cause was and how you solved it, so that it helps others who may have the same situation

**Comment by alestanga** [comment]
I had a G91 right after G90.
removing G91 fixed the issue:
![laser grbl](https://user-images.githubusercontent.com/3521757/108678075-e77f9700-74ea-11eb-900a-77b73f5f3636.png)
