### ISSUE TITLE
Displays a large number of program source errors when running by Visual Studio

### ISSUE THREAD

**Issue by ashkan4818** [arkypita/LaserGRBL#1340]
Hi, I get a lot of errors when I run the source file software in Visual Studio. How can I solve this problem?
![h2](https://user-images.githubusercontent.com/20372650/107950323-ccbd9780-6fab-11eb-9651-9267986101f4.jpg)

![h1](https://user-images.githubusercontent.com/20372650/107949899-30939080-6fab-11eb-933f-86d835e0439b.jpg)

**Comment by arkypita** [comment]
Look like your VS installation doesn't have C# 7.0 support

![image](https://user-images.githubusercontent.com/8782035/107951328-7561fc00-6f98-11eb-8ed7-b74a08a1ab28.png)

**Comment by ashkan4818** [comment]
The problem was solved. Thanks for your tips

**Comment by PeterBrewmaster** [comment]
I have the same problem. Tried it on several different computers using VS 2015 and VS 2019. In VS 2019 the C# language version is 9.

**Comment by arkypita** [comment]
I don't know how to help you!

I use VS2017 Community Edition, default installation.
All the source file of LaserGRBL is included in the github repository, no dependency of third part library.

**Comment by PeterBrewmaster** [comment]
I installed VS 2017 - same problem. Even when setting the language version to 7.0 (from preset 7.3). It would be great to hear what ashkan4818 did to solve it.

**Comment by ashkan4818** [comment]
hi @PeterBrewmaster  i installed VS2017 Enterprise and required components . You must be sure to unblock the LaserGrbl zip file before extract the zip file. to do this : right click on LaserGrbl zip file and go to properties and click on "unblock". 

That's all I did and my problem was solved.
I hope you find it useful

**Comment by PeterBrewmaster** [comment]
> hi @PeterBrewmaster i installed VS2017 Enterprise and required components . You must be sure to unblock the LaserGrbl zip file before extract the zip file. to do this : right click on LaserGrbl zip file and go to properties and click on "unblock".
> 
> That's all I did and my problem was solved.
> I hope you find it useful

Thanks. I tried that but all the errors were still there. BUT what I did, I run/started the program and it worked! When stopping it there were no errors left. Must be some issue with Visual Studio 2015, 2017 and 2019.

**Comment by arkypita** [comment]
So you compile the code.

**Comment by PeterBrewmaster** [comment]
Yes.

**Comment by ashkan4818** [comment]
@PeterBrewmaster  was your problem solved?

**Comment by PeterBrewmaster** [comment]
> @PeterBrewmaster was your problem solved?

I think so. I have not tried it with the engraving machine yet though. I am building a machine to label cartons with engraving. So I need to be able to start engraving and be noticed when engraving is completed for each carton, so that this machine can bring next carton to be engraved. The LaserGRBL software is really amazing.
