### ISSUE TITLE
Help to solve the problem in developing LaserGRBL software

### ISSUE THREAD

**Issue by ashkan4818** [arkypita/LaserGRBL#1349]
Hi, I'm trying to add some features to your LaserGRBL software . I created a user control and did my coding in it. Now I have to send a series of G-codes to the CNC machine using a button, but when I press the button, I get the following error. Can you help me solve this problem? I appreciate and thank you for any of your guidance. 
![error](https://user-images.githubusercontent.com/20372650/108621127-fbbd8880-7445-11eb-9322-5ac91cc06ca0.jpg)

**Comment by arkypita** [comment]
This photograph is not enough to allow me to help you. It's like you send a picture of your engine to the mechanic asking him why the car won't start.

**Comment by ashkan4818** [comment]
:-D , OK Please tell me what information you need, so that I can send it to you
. I believe in your programming skills

**Comment by arkypita** [comment]
Share the code of the project or at least the class you are using.
Null reference means that you have not initialized / assigned "Core" variable value.

**Comment by ashkan4818** [comment]
dear @arkypita i was able to solve this problem, too. Thank you
