### ISSUE TITLE
Update 2.8.8 Custom Button behaviour.

### ISSUE THREAD

**Issue by StuartB4** [arkypita/LaserGRBL#135]
Updated to 2.8.8 ok, but now when clicking on my Custom Z axis Up and Down buttons the other icons flash when releasing the mouse button.

https://www.youtube.com/watch?v=Phj7zwknP58&feature=youtu.be

**Comment by arkypita** [comment]
Hi @StuartB4 
It look as by design. Jogging is enabled only in "Idle" state, Halt (red hand) is available only in "Run" state. This seem to be the same in older versions.
