### ISSUE TITLE
Save picures as "Projects"

### ISSUE THREAD

**Issue by LaserEngraver** [arkypita/LaserGRBL#136]
Hello,
I want to engrave Pictures. So, a Picture will be opened and Parameters will be adjusted.
Now I can save the CNC-file or send the codes direct to the engraver.
But if I want to re-adjust e.g. the brightness, I Need to reload the Picture and start from the beginning.

Is there any Option to save a Picture as a Project which makes it possible to Change the Parameters later, again and again?
Thx

**Comment by arkypita** [comment]
It is a good idea, but not so easy to implement, maybe in a future version I can think about that.
