### ISSUE TITLE
vectorize problem

### ISSUE THREAD

**Issue by gabrielsarabando** [arkypita/LaserGRBL#137]
when i try to engrave with vectorize hapen what you can see in this picture.

anyone know how to solve ?
![22447630_10159485981285788_1396396942_n](https://user-images.githubusercontent.com/32177897/31513614-c71a870e-af86-11e7-9fd2-5e728263c8ab.jpg)

thankyou

**Comment by brakthehun** [comment]
I think you'll have to explain this picture better. Which line is the vectored line?? It looks like there's some line to line tracing on here also.
