### ISSUE TITLE
Laser Configurations are not shown.

### ISSUE THREAD

**Issue by hasanyucel** [arkypita/LaserGRBL#1393]
![image](https://user-images.githubusercontent.com/26742619/112754499-0b9c2f80-8fe5-11eb-8c4c-af70dc5639f1.png)

My laser power is weak. Laser configurations are not shown. How can I fix it? I tried many versions of the software. It was working before. I updated the software. After that, it did not work.

**Comment by gmmanonymus111** [comment]
What is your GRBL version? (LaserGRBL should tell you, once you've connectred to your machine)

**Comment by hasanyucel** [comment]
Machine: Eleksmaker A3 Pro, LaserGRBL version v4.3.0

**Comment by gmmanonymus111** [comment]
I meant this:
![image](https://user-images.githubusercontent.com/9658243/112754876-7b5aec00-8fde-11eb-95de-08736ffb850a.png)

**Comment by hasanyucel** [comment]
Ah, sorry. It is 0.9i

![image](https://user-images.githubusercontent.com/26742619/112754980-5cad2300-8fe7-11eb-8eb7-65a33ee07920.png)

**Comment by gmmanonymus111** [comment]
As far as I know, laser mode is not yet implemented in GRBL v0.9, but there should be spindle configuration (aka laser power setting, `30` & `$31`). Maybe your machine needs an updated firmware?

**Comment by hasanyucel** [comment]
Thank you. I will search for it.

**Comment by moonshine76w** [comment]
I'm not sure if you tried this, but try raising and lowering the actual laser with that little screw on the side, It will raise and lower it. You want it to be at the finest point. Hope this helps.
