### ISSUE TITLE
Can't open an image file.

### ISSUE THREAD

**Issue by waterbom625** [arkypita/LaserGRBL#1401]
When I tried to open an image file, I got this. 
![1](https://user-images.githubusercontent.com/25590226/113658984-aecf0200-96d3-11eb-888a-f1bc5f82c50d.jpg)

**Comment by waterbom625** [comment]
I didn't setup the GRBL configurations correctly. Stupid me.

**Comment by StuartB4** [comment]
Been there, done that. :)
