### ISSUE TITLE
installation question

### ISSUE THREAD

**Issue by paolofabbro** [arkypita/LaserGRBL#141]
hello, i want to know what i need to install along with the program ... libraries etc. thank you!

**Comment by arkypita** [comment]
Ciao Paolo, only .NET framework 3.5 (or later) is required to run LaserGRBL.
.NET Framework >=3.5 is installed by default on Win7 and later, only on XP the installation is required #131

**Comment by paolofabbro** [comment]
thank you! I would like to pilot the EleksMaker 3 pro ...
