### ISSUE TITLE
How to zero the X/Y coordinates in software?

### ISSUE THREAD

**Issue by seemikeplay** [arkypita/LaserGRBL#142]
How can I tell LaserGRBL that the machine is already at X:0, Y:0? I already do G92 X0 Y0 to tell the firmware that it's zeroed, but LaserGRBL still shows "X: 165 Y:-135.955" (for example)

This doesn't mess up the actual code, but it doesn't display the cursor position correctly on the image while it's etching.

Is there a simple way to tell LaserGRBL that the machine is at 0,0?

Thanks!

**Comment by arkypita** [comment]
#36

**Comment by arkypita** [comment]
[Version v2.8.12](https://github.com/arkypita/LaserGRBL/releases/tag/v2.8.12) can now show working position if different from machine position.
