### ISSUE TITLE
when i upgrade it crashes my computer and i have to do a restore to restart computer from ver 4.1 to 4.3

### ISSUE THREAD

**Issue by frisbeegolfer69** [arkypita/LaserGRBL#1438]

**Comment by frisbeegolfer69** [comment]
window 10 
CNC3-3018PRO
laserGRBL VER 4.1.0

**Comment by arkypita** [comment]
There is nothing particular between version 4.1 and version 4.3 to justify such behavior.
I think the problem is external.
