### ISSUE TITLE
Not Bug - Just spelling correction on one screen

### ISSUE THREAD

**Issue by RaisingAwesome** [arkypita/LaserGRBL#1439]
**Describe the bug**
Spelling correction for Automatic Cooling tab

**To Reproduce**
Go to GRBL-->Settings-->Automatic Cooling

This statement:
Some laser diode can heat-up to much

Should read:
Some laser diodes can heat-up too much

**Additional context**
![image](https://user-images.githubusercontent.com/38836869/116493191-cf6a2200-a863-11eb-8d21-b55e1c4d4a6d.png)

**Comment by arkypita** [comment]
fixed in v4.4.0
