### ISSUE TITLE
Resize doesn t work

### ISSUE THREAD

**Issue by BeikircherDaniel** [arkypita/LaserGRBL#1445]
The resizing rectangle starts outside the picture.

If I klick on the icon to resize an image , then I klick where I want to start to resize it but the rectangle is not opening there.

**Comment by StuartB4** [comment]
![image](https://user-images.githubusercontent.com/16980026/116811690-6247dc80-ab42-11eb-9156-921f9bf772a2.png)

**Comment by BeikircherDaniel** [comment]
Thanks i know this but the box does not open where i want. It opens outsithe picture. On my pc with windows 7 was no problem now on my new one with windows 10 it does not work how it should.

**Comment by StuartB4** [comment]
The only other way to resize an image is in Target image settings where you change the W and H settings to set the engraving / cutting size. If you change one of them the other will change so the image stays in the correct size ratio.

**Comment by StuartB4** [comment]
I have windows 10 and it works ok.

**Comment by BeikircherDaniel** [comment]
Yes this is clear but if i want to cut out the image in Lasergrbl this is not the solution. I try to make a screenshot to show what the problem is.

**Comment by BeikircherDaniel** [comment]
![IMG_20210502_135155__01__01](https://user-images.githubusercontent.com/83529773/116812217-d6d44880-ab4d-11eb-83d5-00aaf5bf82d3.jpg)

**Comment by BeikircherDaniel** [comment]
This is how it looks with the left mouse key holded down.

**Comment by ibisdave** [comment]
I am having the same issue how was this fixed?

**Comment by BeikircherDaniel** [comment]
It wasnt fixed but it cuts where you want. Just the line previev is not where it should be.

**Comment by ibisdave** [comment]
I have the software on my office computer and it works fine it is my shop computer that does exactly what you had said. It does work it just puts the box in the wrong spot
