### ISSUE TITLE
SVG Import does not correctly position elements not contained with a separate layer

### ISSUE THREAD

**Issue by alastaira** [arkypita/LaserGRBL#1455]
In LaserGRBL v4.3.0, when importing an SVG file containing elements that have been placed in the main body of the SVG document rather than into a separate layer, it seems to not correctly position those elements.

Simple reproduction attached in zip file (archive only contains a single SVG file, but Github won't let you upload a file with SVG extension - doh!), in which the grid lines are placed in a separate layer ("Layer 1"), with translate(0.25,60.25) attribute. Text and outline are not contained within that layer. The SVG renders correctly in Inkscape and when loaded in a browser such as Microsoft Edge, but incorrectly in LaserGRBL as shown in screenshots.

[LaserGRBL-LayerBug.zip](https://github.com/arkypita/LaserGRBL/files/6451815/LaserGRBL-LayerBug.zip)

![Bug_LaserGRBL](https://user-images.githubusercontent.com/901056/117656448-440c5d00-b190-11eb-99c7-c24c32fe8b7d.png)
![Bug_Edge](https://user-images.githubusercontent.com/901056/117656452-44a4f380-b190-11eb-8308-4649fd7d70b2.png)
![Bug_Inkscape](https://user-images.githubusercontent.com/901056/117656454-453d8a00-b190-11eb-8804-8f17e0e35631.png)

**Comment by alastaira** [comment]
Possibly relevant - this SVG file was originally exported from OpenSCAD before being brought into Inkscape. And, even though it renders correctly within Inkscape, it therefore seems that some of its structure might differ from the way Inkscape would have defined the same file internally.

I notice that, when creating SVG files from scratch within Inkscape, all elements are placed within a layer (although I couldn't see this being a requirement according to the SVG standard).
However, in this file, I'm beginning to thing that the problem is actually with elements *not* inside a layer, but as direct child elements of the root <svg> tag.

**Comment by StuartB4** [comment]
It loads properly if you group it all together in inkscape first. 

![image](https://user-images.githubusercontent.com/16980026/117668707-1b8b5f80-b19e-11eb-88dd-f9dba8ea4925.png)

**Comment by alastaira** [comment]
The more I look at this, the more I'm convinced that the problem arises as a result of the fact that the file originated from OpenSCAD, and its definition of the SVG "non-standard standard" differs from that which Inkscape uses (which I agree, should be the SVG version on which LaserGRBL is based).

Having identified the problem, there's a relatively simple workaround which is just to edit->cut all the objects and paste them into a layer in Inkscape (eitherthe default "Layer 1", or a new one). Then save the SVG again.

**Comment by arkypita** [comment]
Hi. Currently the code that transforms the SVG into GCode is a code that I did not write myself, but that I copied "as is" from another project. My bugs are his bugs, and even if I try to fix some of them, since it is third-party code it is always very difficult to be able to intervene without risking to break something.

If we also assume that this code is not written very well, and the difficulty of interpreting the SVG specification, it turns out that I prefer to intervene as little as possible on this part.

I think the "final" step would be to throw this code away and replace it with SVG reading done with a better and more supported library [like this one](https://github.com/svg-net/SVG) and implement my own "from svg to gcode" routines.

**Comment by svenhb** [comment]
>My bugs are his bugs

This code (GCodeFromSVG.cs) was taken in 2018 and has improved since them. Actual result of this excample looks like this:
![image](https://user-images.githubusercontent.com/19973251/142765568-987e006a-41fb-48f3-b3e8-3de31006e980.png)

**Comment by falias4** [comment]
### Regarding this specific issue
The `transform="translate(x,y)"` property isn't interpreted in this version (from 2018) of the `GCodeFromSVG.cs`.
So a quick fix would be to add specific code to handle this.

### General update of the 'external library'
Out of curiosity I tried to integrate the latest code from [GRBL-Plotter](https://github.com/svenhb/GRBL-Plotter) but it was already pretty exhausting to get a simple result. 🙈
The whole thing got greatly reworked and there are many new files and references to classes, settings, etc. which are very "deep" inside GRBL-Plotter.

**Don't want to give false hope: I probably won't work on this any further.**
I don't have enough knowledge about GRBL-Plotter and all the settings to do that in a reasonable amount of time.... although the result would be very cool.
PS: The hatch fill is activated by accident. No idea how to turn it off. 😅
![image](https://user-images.githubusercontent.com/22332087/142774930-63a1e772-7ea3-402a-bd3a-9f5e11a1ff69.png)

**Comment by svenhb** [comment]
>PS: The hatch fill is activated by accident. No idea how to turn it off.

Can be deactivated here, for more options check https://grbl-plotter.de/index.php?id=form-setup&setlang=en
![image](https://user-images.githubusercontent.com/19973251/142778468-b91ad92c-f721-4019-befa-94783853846f.png)

https://grbl-plotter.de/index.php?id=form-setup&setlang=en

**Comment by arkypita** [comment]
Thank you for this report and thanks to @svenhb for the code, and thanks @falias4 for the fix.
I am currently very busy but as soon as I can I do a test and compile a new version.
