### ISSUE TITLE
progam jogging to the left half way through 

### ISSUE THREAD

**Issue by ljpsr** [arkypita/LaserGRBL#146]
I have had several projects jog to the left and have an offset half way through the project. more often than not on larger sessions

**Comment by brakthehun** [comment]
I had this issue when I exceeded the 30khz max pulse frequency.

**Comment by ljpsr** [comment]
is that the laser itself, is there a way to change so it does not happen

**Comment by brakthehun** [comment]
Let's look at your $$ settings.
How many steps per mm is yours set to?? ($100 and $101)
What is your Max speed??($110 and $111)

I had 640 steps per mm and a max speed of 10,000 mm/minute
10,000/60 = 166.6667mm/second
640 steps per mm * 166.6667 = 106666.688 pulses per second (106.7 kHz).
That was far above the 30 kHz limit.

I changed my microstepping from 1/128 to 1/32 and it worked just fine after that.

**Comment by fasteddyD** [comment]
Hi brakthehun.. I am new at this so not sure how to make the change you suggest for micro stepping, from 1/28 to 1/32.  This software works better than anything I have tried for photos but this stepping right and left spoils the fun.

**Comment by StuartB4** [comment]
Depends which stepper motor drivers you have, microstepping is usually done through them with dip switches or jumpers of some sort.

**Comment by brakthehun** [comment]
Let's start in your command line right above the data feed. Type in $$,, press enter and screenshot the data then post it in here.

**Comment by fasteddyD** [comment]
Hi brakthehun.. thanks for quick reply...this is what I get..

**Comment by fasteddyD** [comment]
[screen.docx](https://github.com/arkypita/LaserGRBL/files/1442881/screen.docx)

Sorry.. cannot seem to get a screen shot to copy  above is a word file.. I will keep trying in the meantime

**Comment by brakthehun** [comment]
So,, you are running an old firmware version of GRBL.
When you initially connect,, what does it say right above the "Type $ for help"

**Comment by fasteddyD** [comment]
As I cannot seem to copy the print screen here, I found what you were talking about in your previous post as follows:
S100=80，000
S101=80，000
S110=3000，000
S111=3000，000

**Comment by brakthehun** [comment]
That looks great. That should not be causing problems. Mine was:
$100=640.000
$101=640.000
$110=10000.000
$111=10000.000
So,, this is not your problem,, but I think your firmware might be the problem.

**Comment by fasteddyD** [comment]
Hmmm... frustrating.  This software is hands down better than what came with the machine for photos but it keeps moving left and right, especially for big files, which distorts the photo.

**Comment by brakthehun** [comment]
So,, when you connect,, what version of GRBL does it say you are running??

**Comment by fasteddyD** [comment]
That is another problem, I cannot see where the version is located.  It does,nt show up when I load the software but I also do not have the feature where I can change speed and power settings on the fly, so I think I may have an older version

**Comment by fasteddyD** [comment]
when I connect it says grbl 0.9j

**Comment by brakthehun** [comment]
So,, it should be compatible with 0.9. It is better to run 1.1 though. What is your baud rate when you connect??

**Comment by fasteddyD** [comment]
baud rate is 115200

**Comment by fasteddyD** [comment]
I only downloaded this software about 2 weeks ago but maybe vs 1.1 came later.  Probably should see if I can download the new version.

**Comment by brakthehun** [comment]
I believe 0.9 wants a baud rate of 9600
Can you try that??

**Comment by fasteddyD** [comment]
ahh... yes I can....

**Comment by fasteddyD** [comment]
would 1.1 use the higher baud rate?

**Comment by brakthehun** [comment]
Yes.
Be careful though. The pins are for laser on and Z limit are switched in 1.1

**Comment by fasteddyD** [comment]
first I will try lower baud rate with this version and hope  it does the trick.  If not, I will try downloading vs 1.1.  If I download 1.1, will I need to change anything base on your note of caution?  I am new at this and not sure what pins are or how this might create a problem.  I really appreciate you help.. I have been struggling for weeks.. trying all kinds of software, but this one is really good if only it would stop moving left and right during the burn..

**Comment by brakthehun** [comment]
If you take a pic of your controller and post it,, I can help guide you.

**Comment by fasteddyD** [comment]
hmm  seems it will only allow me to connect at 115200.

**Comment by brakthehun** [comment]
Interesting. Dd you flash the firmware yourself??

**Comment by fasteddyD** [comment]
The control board is sandwhiched between two pcs of plastic so we cannot really see it.

**Comment by brakthehun** [comment]
That's alright. If you send a pic,, I could probably figure out how to use it with 1.1

**Comment by brakthehun** [comment]
Where did you get the controller??

**Comment by fasteddyD** [comment]
No.  I bought and assembled a kit. The board was already sandwhiched between two pcs of plastic so I just mounted it and when done, it took off without me needing to do anything else.

**Comment by fasteddyD** [comment]
I will shut down and disassemble the board to take a quick photo.

**Comment by brakthehun** [comment]
It might be complicated to upgrade it then. One big setback of 0.9 on Arduino is you can't dim the laser.

**Comment by brakthehun** [comment]
Do you have a link to the kit??

**Comment by fasteddyD** [comment]
![img_7026](https://user-images.githubusercontent.com/33363572/32402549-7edab1c0-c161-11e7-9df1-a1810e2564d0.JPG)

Let me know if you can open this photo..

**Comment by fasteddyD** [comment]
OH... it opened itself... hope this helps..

**Comment by brakthehun** [comment]
Alright!! When you power the machine on,, does the laser cooling fan come on also??

**Comment by StuartB4** [comment]
Looks like there is no option to change the microstepping on that board either.
http://www.lubandiy.com/article-3-1.html

**Comment by fasteddyD** [comment]
Yes, the cooling fan comes on with power.

**Comment by fasteddyD** [comment]
Is there a better controller board that I should consider?  I work in China and the supplier is located nearby.  He basically sold me the bits and I assembled them.  Mine is 6.5 watts but he did suggest a 10 watt at the time.  I think he has optional boards etc.  Any suggestion on a board that will run with this software more smoothly?

**Comment by fasteddyD** [comment]
The software that came with the machine was a Chinese copy of the software supplied by Elks Maker.  It had so many problems with the English language that I finally downloaded EM's English version, which works exactly the same.. with less errors but same limitations with how it handles photos.

**Comment by fasteddyD** [comment]
I tried several software package trial versions and was amazed that several would drive the laser.  This software is hands down the best for photos that I have tried, if only I could keep the laser from wandering back and forth.

**Comment by fasteddyD** [comment]
I do not understand why I downloaded vs 0.9.  When I look at the available downloads I do not see an option for one or the other.  I wonder now how to determine the version of the download so that I can try 1.1??

**Comment by StuartB4** [comment]
1.1 is here:
https://github.com/gnea/grbl

**Comment by brakthehun** [comment]
You can use your current board to run 1.1. You just have to swap the laser ttl trigger with the z endstop.
