### ISSUE TITLE
Feature: horizontal overrun

### ISSUE THREAD

**Issue by SchmidtDawid** [arkypita/LaserGRBL#1472]
We (me and friends) are engraving in plexi with paint on top. The best results we have got in Line to Line tracing mode. The only problem are vertical lines (and letters) on the sides, because laser will slow down then, and it is impossible to calibrate power correctly. I have got almost 50 samples today with different power settings, and there is no correct setting to eliminate this issue. 

**Solution is behaviour when laser do not slowdown, on the end of picture but keep moving for about 10mm, and then change direction.** 

It is possible to achieve that now by draw 2 vertical lanes outside engraving area but then engraving time is very long and unnecessary. 

![slice1](https://user-images.githubusercontent.com/26749479/121028328-06f3b480-c7a8-11eb-857f-908af14f49fc.jpg)

Desired behaviour on vertical line. Then the line is perfect.
https://user-images.githubusercontent.com/26749479/121039780-ac5f5600-c7b1-11eb-8d36-3809b6ecbf54.mp4

**Comment by gmmanonymus111** [comment]
If I get your request right, it is already in development roadmap (see #64)
>  - [ ] Acceleration offset/border #102

**Comment by SchmidtDawid** [comment]
It looks it is exactly this issue. Thanks :).
