### ISSUE TITLE
Stop send G code commands after a few minitues

### ISSUE THREAD

**Issue by vilianch123** [arkypita/LaserGRBL#1488]
Hello,I use larserGRBL V4.3.0 to control my 2-axes controller. The connection is 232 serial and baudrate is 115200bps.
I use image2gcode tool to generate a g code file and I want to sent it to my controller.
But always everytime,I found larserGRBL would stop send G code again,so my axes would just stop moving.The only things
larserGRBL do is send a '?' to get controller's current status.
What's the main problem of this question？buffer size or mode to send characters?
Thank you in advance!

**Comment by arkypita** [comment]
Can you put pictures of controller, and screenshot of lasergrbl when hang?
PS. next time open thread under "discussion" instead of "issues" unless you're sure it's a lasergrbl bug.
