### ISSUE TITLE
engraving ratio issue

### ISSUE THREAD

**Issue by kre2** [arkypita/LaserGRBL#1499]
**Describe the bug**
Y axis seems to step to short compared with jogging steppen (jogging 100mm y axis moves 100mm

**To Reproduce**
setup and any engraving test of any size you what and y axis comes short .5mm pr 10mm x aixs is spot on
Can see on about 10 engravinges that y axis comes out short engraving is at little squeezed

**Expected behavior**
to engarve the size that was setup for

**Screenshots**
not at hand

**Hardware and software configuration (please complete the following information):**
 - Windows version=10
 - Engraver brand and model=home made
 - Grbl version (i.e. 0.9j, 1.1f)=1.1f
 - LaserGRBL version= 4.3

**Additional context**
ps use a lead screw on y axis when using jogging arrows in lasergrbl to move 10 or 100mm y axis moves 10 or 100mm so step/mm is spot on

sorry pretty sure I filled out the template.....but forgot to save :-)

**Comment by gmmanonymus111** [comment]
This issue template is there for a reaon, please fill it according to your issue if it happened in LaserGRBL. If it's a general issue, and not connected to LaserGRBL, please open a discussion for it. No-one will be able to help you if you won't take the time explaining your issue.

**Comment by gmmanonymus111** [comment]
Okay, I didn't get notification about your edit, only when the issue got closed.
Since your steps/mm settings correct (and LaserGRBL uses those settings to generate the gcode), I think there's a hardware issue somewhere. Is your psu strong enough to drive all the steppers along with three laser?
A picture about the issue could help here a lot.

**Comment by kre2** [comment]
hi Alex
sorry for the late response....
laser use about 1.3A powered by 2.5A supply for laser only
printer have a 5A power supply for printer only (all steppers draw abot max
1.5A)
stepper drivers is tmc2100
i have very slightly pinched y axis while printing to see if that will
corse step skipping but no skipped steps
the steam logo was set to print at 70x70 mm (steam.png) but the outcome is
x=70mmy=64mm
itś not the only print with the same outcome
kind regards kresten


Den søn. 27. jun. 2021 kl. 22.51 skrev Alex ***@***.***>:

**Comment by gmmanonymus111** [comment]
Could you attach the generated GCode here on Github? I'd like to do a test engraving to check what might go wrong. (If you can attach it, please do so on Github, as email attachments usually do not work :/)

Is the error margin the same ~6mm for all engrave jobs, is it almost 10% of the size or is it random?
When the job is finished, can your machine go to the exact `(0,0)` position where it started, or is that shifted as well?

**Comment by kre2** [comment]
turns out no problem only my setup
