### ISSUE TITLE
Version ?

### ISSUE THREAD

**Issue by jm4r7in** [arkypita/LaserGRBL#150]
How is it possible to know the version of the software installed ?
Thank !

**Comment by arkypita** [comment]
When program start

![image](https://user-images.githubusercontent.com/8782035/32176417-e0821856-bd87-11e7-9d59-bb6245e10886.png)

**Comment by fasteddyD** [comment]
On the blue bar at top in left hand corner where it says Laser GRBL it will show which version you are using. The example above does not show the version for some reason but yours will.

**Comment by arkypita** [comment]
This is a new feature of newest version
