### ISSUE TITLE
The source code of version V4.4.1 is opened and an error is reported

### ISSUE THREAD

**Issue by lianzaozi** [arkypita/LaserGRBL#1504]
The source code of the error is shown in the figure below

![image](https://user-images.githubusercontent.com/53146195/124132223-2c2bc800-dab3-11eb-966c-7b7c4f4e66b6.png)

**Comment by arkypita** [comment]
Have you at least tried to compile/build in 1 time?

**Comment by lianzaozi** [comment]
Thank you for your reply.

Yes, I tried multiple times and the result is the same every time.

**Comment by arkypita** [comment]
download/check it out now, i have fixed it
btw was only a design time issue, the solution build and run also with the error

**Comment by lianzaozi** [comment]
Thank you very much.

The problem has been resolved.
