### ISSUE TITLE
software version

### ISSUE THREAD

**Issue by fasteddyD** [arkypita/LaserGRBL#152]
I seem not to have the ability to adjust speed or power on the fly as I cannot find the sliders shown in your website.  It also says only available on vs 1.1 or higher.  I only downloaded this software about a month ago but do not know how to see what version I have.  Anyone know how to find this?

**Comment by arkypita** [comment]
Each time you connect LaserGRBL to your arduino you can read a message like "Grbl vX.xl" with grbl version.

http://lasergrbl.com/it/usage/arduino-connection/
