### ISSUE TITLE
Unstable work with diagonal engraving

### ISSUE THREAD

**Issue by Mikalay31** [arkypita/LaserGRBL#154]
1. Horizontal engraving. The engraving speed (1500) is equal to the idle speed (1500). Engraving is stable.
Here are the links to the video:
https://drive.google.com/open?id=1T8qcvb1o3Aj9f_7xp6GtnCEkLvOcNZsN

2. Diagonal engraving. The engraving speed (1500) is equal to the idle speed (1500). There are jerks (apparently there is a slowdown at the time of engraving) although this should not be.
Here are the links to the video:
https://drive.google.com/open?id=1-1i1WEHaZ3sQTVK09qi8yxg--pRBOyxz

**Comment by Mikalay31** [comment]
To understand the difference - you need to listen carefully to the sound.

**Comment by arkypita** [comment]
Hi @Mikalay31 
I develop LaserGRBL thinking that G0 (fast movement) and G1 (linear movement) could use two different speeds, so I decide to use G0 for white spaces and G1 for engraving.

Later I discover that [G0 has no feed rate](https://github.com/gnea/grbl/issues/279), so any F value used in G0 command is useless. This made the input of idle speed not meaning to the result.

So... at what speed should be executed a G0 command??? The answer is in your Grbl settings that you could show sending $$ command.

Parameters [$110, $111, $110](https://github.com/gnea/grbl/wiki/Grbl-v1.1-Configuration#110-111-and-112--xyz-max-rate-mmmin) control the speed used in G0 and parameters [$120, $121, $122](https://github.com/gnea/grbl/wiki/Grbl-v1.1-Configuration#120-121-122--xyz-acceleration-mmsec2) controls the acceleration.

In my opinion you may have an incoerent seteup of this values between X and Y axis

**Comment by Mikalay31** [comment]
Thank you! I understood your answer. I know about the $$ command. But there in the first video you can see that all the parameters are the same. $ 110 = $ 111 = 1500. Therefore I asked you. Can eat still nuances? Simply for engraving the machine with screws it is desirable to work with a constant speed of engraving and idling. And I oche need diagonal engraving. I can reset the pattern of my drawings. You can try on your engraver putting all the parameters the same. I would not be surprised that you will have the same thing. Also did not understand as acceleration on it influences? By the way $ 120 = $ 121 = 300 is also seen in the video. Do you understand me ?

**Comment by Mikalay31** [comment]
Here are the settings for $$   https://prnt.sc/h6tobi

**Comment by Mikalay31** [comment]
By the way, work at the same speed of engraving and idle speed gives less vibrations for the machine, which increases the quality of engraving. This can be seen on the video with a horizontal engraving. But it increases the processing time. With diagonal engraving, clearly there is a problem. But I'm more interested in quality) Do you understand me?

**Comment by Mikalay31** [comment]
And there is one more question. What is the principle of laser power adjustment? What is the frequency of the signal? I need this in order to find the driver specifically for your program. Because not every driver is ready to work at a frequency above 1000 Hertz. In advance I thank for answers. Nicholas.

**Comment by arkypita** [comment]
Never eard about google?

> What is the principle of laser power adjustment?
http://www.google.it/search?q=pulse+width+modulation
https://blog.protoneer.co.nz/grbls-pwm-functionality-how-to-control-a-laser-or-variable-speed-spindle/

> What is the frequency of the signal?
https://github.com/gnea/grbl/wiki/Grbl-v1.1-Laser-Mode#laser-mode-operation
https://github.com/gnea/grbl/issues/55

Please note that this functions regards Grbl and they are not dependent on LaserGRBL.

**Comment by Mikalay31** [comment]
OK.Thank you.
I understood - I study links ... But on the Internet there is no answer to my main question on diagonal engraving. Help me please )

**Comment by arkypita** [comment]
When i have time

**Comment by Mikalay31** [comment]
Yesterday once again put the experiments, but already on the latest version v2.8.15. The problem with diagonal engraving remains. Then I changed the background of the circles: Screenshot_6

**Comment by arkypita** [comment]
You are asking me to solve a problem that is in your hardware or in your configuration, not a problem that is in LaserGRBL. Do you want to tell me how can I help you?

I have repeat your test with my engraver. As you can see in the linked videos results are pefect both in [horizzontal](https://youtu.be/HKn7CwQx7ok) and [diagonal](https://youtu.be/V2TqOetk0sk) mode.

LaserGRBL optimize the speed of the engraving sending G0 (fast movement) to skip all the whitespaces.
G0 is implemented by Grbl moving the laser at the faster speed possible, as settled in parameters [$110, $111, $112](https://github.com/gnea/grbl/wiki/Grbl-v1.1-Configuration#110-111-and-112--xyz-max-rate-mmmin) and parameters [$120, $121, $122](https://github.com/gnea/grbl/wiki/Grbl-v1.1-Configuration#120-121-122--xyz-acceleration-mmsec2).

**Comment by Mikalay31** [comment]
OK. I understood. I will test or just use horizontal engraving. Tell me another question. There are buttons in the program, but I do not really understand what to use them for. Where can I read about this? I will attach a photo with questions:   
![screenshot_7](https://user-images.githubusercontent.com/33402856/32728955-4954b580-c893-11e7-819c-4bde3e039f2d.jpg)        
![screenshot_8](https://user-images.githubusercontent.com/33402856/32728961-4ce93d24-c893-11e7-9097-6fa962be78a3.jpg)    
![screenshot_10](https://user-images.githubusercontent.com/33402856/32728966-4fa2cfb2-c893-11e7-8715-facba7c781ed.jpg) 

Thank you in advance !

**Comment by Mikalay31** [comment]
What other buttons can I still insert into the program?

**Comment by arkypita** [comment]
http://lasergrbl.com/it/usage/overrides/
http://lasergrbl.com/it/usage/user-interface/
http://lasergrbl.com/it/configuration/#streaming-mode
http://lasergrbl.com/it/usage/custom-buttons/

**Comment by arkypita** [comment]
issue detector and unidirectional engraving are very new feature and I have not already documented but you can read about that in github releases storyboard

https://github.com/arkypita/LaserGRBL/releases

**Comment by Mikalay31** [comment]
Hey. I solved my problem) The reason is not in your program and not even in my hardware. The problem is probably in the GRBL itself. It is necessary to set the speed according to my copies from the screen. All that I can assume lies in the formula of the hypotenuse of the triangle. Moving along the X, Y axis at a speed of 1200 mm / min - will cause diagonal movement at a speed of 1697 mm / min. But this is only an assumption. Probably that that is not finished in calculation G0.

**Comment by Mikalay31** [comment]
![default](https://user-images.githubusercontent.com/33402856/32824157-f14239b2-c9f0-11e7-99c2-61fd0d33d806.jpg)
![0](https://user-images.githubusercontent.com/33402856/32824163-f52ab2fc-c9f0-11e7-81c1-4416bb38926d.jpg)

**Comment by Mikalay31** [comment]
![555555555](https://user-images.githubusercontent.com/33402856/32824222-2a959330-c9f1-11e7-94eb-6f1b7e722a68.jpg)
![9999999](https://user-images.githubusercontent.com/33402856/32824224-2d96eeee-c9f1-11e7-87be-b022a567939f.jpg)

**Comment by arkypita** [comment]
Please note again:
> I discover that G0 has no feed rate, so any F value used in G0 command is useless. This made the input of idle speed not meaning to the result.

So: **the second speed parameter (the one you set at value of 1200) has no effect at all.**

The speed of G0 used in whitespaces is implemented by Grbl moving the laser at the faster speed possible, as settled in parameters $110, $111, $112 and parameters $120, $121, $122.

**Comment by Mikalay31** [comment]
I understood. Thanks for the help ! Great program! I will be watching your project. He is very interesting !
