### ISSUE TITLE
v2.8.11 need testing

### ISSUE THREAD

**Issue by arkypita** [arkypita/LaserGRBL#155]
Hi all, I have released a new [version v2.8.11](https://github.com/arkypita/LaserGRBL/releases/tag/v2.8.11) that need testing.
A feature has been added that intercepts possible grbl hang/issue during job streaming and show a dialog for to warn user about this issue.

This intercept could detect:
- grbl stop responding to ? (No Real-time Status Reports) for more then 10s
- no movement when a movement is requested for more then 10s
- unexpected grbl reset during a job

I need some testing to be sure that this intercept does not trigger by mistake.
If you decide to test this version please reply to this message.

**Comment by Mikalay31** [comment]
Hey. I'm ready )
By the way, I can help. I had such a problem.
I decided it) At me during work at me the machine stopped.
Yesterday I tested everything was normal.

**Comment by Mikalay31** [comment]
Today the update window has been opened: http://prntscr.com/h7xac0     Is this the latest version?

**Comment by arkypita** [comment]
Yes! I decide i am sure about new features so i made them available for update

Il giorno 8 Nov 2017, 20:09, alle ore 20:09, Mikalay31 <notifications@github.com> ha scritto:

**Comment by arkypita** [comment]
p.s: alt+stamp and ctrl+v allow to paste image directly in github message
