### ISSUE TITLE
I currently have vs .09 installed but would like to try 1.1.  I am having difficulty finding the newer version as everything I download turns out to be 0.9.  How do I distinguse the version ahead of downloading this software?

### ISSUE THREAD

**Issue by fasteddyD** [arkypita/LaserGRBL#156]

**Comment by arkypita** [comment]
User StuartB4 already reply with all the info about how to do in this thread: https://github.com/arkypita/LaserGRBL/issues/146

Please learn how to post your issue/request. There is a field called "title" and a field called "leave a comment". Put a brief title in "title" and put the request in comment (like an email).
Further requests presented this way will be ignored and trashed.
