### ISSUE TITLE
origine lavoro

### ISSUE THREAD

**Issue by distebia** [arkypita/LaserGRBL#1606]
Salve, ho impostato grbl invertendo l'asse x (quindi a sx) e la Y positiva, in questo modo mi ritrovo in modo corretto la home in alto a sx. quando carico un file la mia origine è in basso a sx, ma la home la fa correttamente in alto a sx. Dove sbaglio? devo settare altro?

**Comment by distebia** [comment]
Riformulo il problema...magari non mi sono spiegato bene. ho sempre usato lasergrbl su 2 macchine, una diodo 445nm e una co2 50w, e non ho mai avuto la necessità di cambiare l'origine. su entrambe le macchine ho settato $ 23=7 per avere la home in basso a sinistra. essendo in basso, una volta aperto lasergrbl, e caricata una foto, mi ritrovo l'origina in basso a sinistra e tutta la foto in spazio positivo, quindi x crescente a destra e y crescente verso l'alto. Tutto perfetto. Ora sto testando una terza macchina ma vorrei la mia home in alto a sinistra, setto quindi $23=1 dove inverto solo l'asse x. In questo modo mi ritrovo correttamente la home in alto a sinistra. La home la esegue perfettamente ma, aprendo lasergrbl, vedo con la croce, che la mia origine è in basso a sinistra, ma la testa laser si trova in alto a sinistra. lancio una lavorazione ma intervengono subito i limiti rigidi in quanto la macchina da alto a sinistra va verso alto destra per iniziare la lavorazione. dove sbaglio? GRBL funziona, in altri programmi posso settare l'origine ma in Lasergrbl non lo posso fare, pressuppongo che li ricavi da GRBL. Che cosa devo settare per avere la home vista da lasergrbl in alto a sinistra? Grazie

**Comment by distebia** [comment]
non mi serve cambiare $3 in quanto gli assi si muovono correttamente, se dico destra la x parte da sx e cresce verso dx. se dico basso la y parte da alto e cresce verso di me in basso. Appena carico la foto la visualizza correttamente ma l'origine è in basso a sx. appena lancio parte da alto sx verso su, attivando l'hard limit.

**Comment by arkypita** [comment]
Certe cose dipendono da come è configurato il firmware della macchina, per esempio dove ti trovi dopo aver fatto l'homing.

https://github.com/gnea/grbl/wiki/Frequently-Asked-Questions#why-is-grbl-in-all-negative-coordinates-after-homing-or-it-so-annoying-and-not-what-im-used-to

Probabilmente il tuo problema lo risolvi solo flashando il firmware compilato con questa opzione.

![image](https://user-images.githubusercontent.com/8782035/137881160-a8205614-0fb7-4a8e-9b4e-ea3ed42a9c65.png)

**Comment by distebia** [comment]
Dopo aver fatto l'homing mi trovo in alto a sinistra, ho settato $23=1 che prevede l'inversione del solo asse X
