### ISSUE TITLE
GCODE extension support in inkscape

### ISSUE THREAD

**Issue by edsonee** [arkypita/LaserGRBL#1612]
Hello Friends, I inform you that INKSCAPE works with the extension GCODE "NGC", I suggest adding it to LASERGRBL. The idea is that it works with .NC and .NGC

![gcode](https://user-images.githubusercontent.com/83145998/137036776-c03d4767-04a0-4bb3-a2fd-4c6ce1a8d090.png)

INKSCAPE = . NGC / LASERGRBL = .NC
Others = .GC .G .GCODE .TXT .LNC .NCC .TAP

![2](https://user-images.githubusercontent.com/83145998/137038177-f28f2cca-b68b-4cd2-82d1-22a235506738.png)

**Comment by arkypita** [comment]
.ngc is not a standard extension for gcode file while .nc it is

It would be more correct to ask those who develop this plugin (which is just one of many plugins that generate gcode) to conform to a standard extension instead of inventing a new one.
