### ISSUE TITLE
Clarification of LASERGRBL manual with respect to GRBL manual ( $ 10 =?)

### ISSUE THREAD

**Issue by edsonee** [arkypita/LaserGRBL#1613]
In the manual found on the official page of LASERGRBL https://lasergrbl.com/configuration/ (image and PDF). recommended "$ 10 = 3
![Captura de pantalla 2021-10-12 192724](https://user-images.githubusercontent.com/83145998/137037578-6d87f16c-103e-4532-ab1e-b396f33f9dd3.png)
"
But the official page of GRBL, it is reported that:

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/usuario/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/usuario/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/usuario/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US style='tab-interval:36.0pt'>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto;
line-height:normal'><span style='font-size:12.0pt;font-family:"Times New Roman",serif;
mso-fareast-font-family:"Times New Roman"'>Use the table below enables and
disable reporting options. Simply add the values listed of what you'd like to
enable, then save it by sending Grbl your setting value. For example, the
default report with machine position and no buffer data reports setting is </span><span
style='font-size:10.0pt;font-family:"Courier New";mso-fareast-font-family:"Times New Roman"'>$10=1</span><span
style='font-size:12.0pt;font-family:"Times New Roman",serif;mso-fareast-font-family:
"Times New Roman"'>. If work position and buffer data are desired, the setting
will be </span><span style='font-size:10.0pt;font-family:"Courier New";
mso-fareast-font-family:"Times New Roman"'>$10=2</span><span style='font-size:
12.0pt;font-family:"Times New Roman",serif;mso-fareast-font-family:"Times New Roman"'>.<o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto;
line-height:normal'><span style='font-size:12.0pt;font-family:"Times New Roman",serif;
mso-fareast-font-family:"Times New Roman"'>[</span><span lang=ZH-CN
style='font-size:12.0pt;font-family:SimSun;mso-bidi-font-family:SimSun'>使用下表启用和禁用报告选项。只需添加列出的您想要启用的值，然后通过发送</span><span
style='font-size:12.0pt;font-family:"Times New Roman",serif;mso-fareast-font-family:
"Times New Roman"'>Grbl</span><span lang=ZH-CN style='font-size:12.0pt;
font-family:SimSun;mso-bidi-font-family:SimSun'>您的设置值来保存它。例如，具有机器位置和无缓冲区数据报告设置的默认报告为</span><span
style='font-size:10.0pt;font-family:"Courier New";mso-fareast-font-family:"Times New Roman"'>$10=1</span><span
lang=ZH-CN style='font-size:12.0pt;font-family:SimSun;mso-bidi-font-family:
SimSun'>。如果需要工作位置和缓冲区数据，则设置为</span><span style='font-size:10.0pt;font-family:
"Courier New";mso-fareast-font-family:"Times New Roman"'>$10=2</span><span
lang=ZH-CN style='font-size:12.0pt;font-family:SimSun;mso-bidi-font-family:
SimSun'>。</span><span style='font-size:12.0pt;font-family:"Times New Roman",serif;
mso-fareast-font-family:"Times New Roman"'>]<o:p></o:p></span></p>

Report    Type[报告类型] | Value[] | Description[描述]
-- | -- | --
Position   Type[职位类型] | 0 | Enable   WPos: Disable MPos:.[启用WPos:禁用MPos:]
Position   Type[职位类型] | 1 | Enable   MPos:. Disable WPos:.[启用'MPos:。禁用WPO：]
Buffer   Data[缓冲区数据] | 2 | Enabled   Buf: field appears with planner and   serial RX available buffer.[已启用Buf:字段与planner和串行接收可用缓冲区一起出现]

<p class=MsoNormal>https://github.com/gnea/grbl/wiki/Grbl-v1.1-Configuration#10---status-report-mask<o:p></o:p></p>

</body>

</html>

**Comment by arkypita** [comment]
$10 is a mask, this means that you can enable more than one feature by adding the value
3 mean 2+1 = report MPos + report buffer data
