### ISSUE TITLE
Vectorize! in small Size 

### ISSUE THREAD

**Issue by aMirMOsavi** [arkypita/LaserGRBL#163]
hi :)

![2017-11-14 11-28-35 pm by amir](https://user-images.githubusercontent.com/17276809/32801867-9778257a-c993-11e7-8d06-f551ea5d71f8.jpg)
![2017-11-14 11-28-48 pm by amir](https://user-images.githubusercontent.com/17276809/32801868-97acd428-c993-11e7-8f44-f9fad6ea8df8.jpg)
![2017-11-14 11-28-51 pm by amir](https://user-images.githubusercontent.com/17276809/32801870-97e08854-c993-11e7-8fd0-a215fccfd47c.jpg)

**Comment by arkypita** [comment]
Hi Amir
Thank for your report. I have tested and I have already found a solution.

Unluckily at this time the raster import procedure is under redesign in a separate development branch that is requesting some time to complete. I have suspended all the request regarding raster import and vectorization to prevent merging conflicts. You have to wait.

If you like to use this small sizes engraving (I am curious: what kind of job? what kind of engraver do you have with this resolution?!) you can also operate like this:

- set $100 $101 $102 to 1/10 of the current value, so you have a scale factor if 1:10 (1mm became 0.1mm)
- set $110/1/2, $120/1/2, $130,1,2 to 10x the current value
- use LaserGRBL with 10 time of the values (i.e. 60mm x 20mm to obtain 6x2mm)
