### ISSUE TITLE
MSG:Check Limits

### ISSUE THREAD

**Issue by Talae** [arkypita/LaserGRBL#1636]
since I installed the V4.6.0 , i can not use the ortur laser master 2 (firmware140).
The homing is impossible to do, msg "Check limits."
I tryed to reset the ortur, I reinstalled the drivers but i m still block.
If I unlock ans press home, the mvt go to the end course and back with a vibration noise. It comme to the 0,0 but it still in ALERT 
Help needed i have a project to do for the end of the week
thanks

**Comment by arkypita** [comment]
It is not a LaserGRBL update issue.

Your engraver has some wrong grbl configuration or mechanic issues or electric issue with limit switch.

Try disabling homing and limit switch in grbl configuration.

https://lasergrbl.com/wp-content/uploads/2020/05/Grbl-Configuration-ENG.pdf
