### ISSUE TITLE
Decimal in photo size and auto-size adjustment of the file

### ISSUE THREAD

**Issue by aMirMOsavi** [arkypita/LaserGRBL#164]
Hi mr.

It will be very good if you set the photo size automatically
And
The size of the photo is as decimal.

I'm sorry to bad speak English because I use Google Translate
![2017-11-14 11-40-03 pm by amir](https://user-images.githubusercontent.com/17276809/32802384-21649c4a-c995-11e7-8d4d-f8d3cf23af6f.jpg)

**Comment by arkypita** [comment]
Unluckily at this time the raster import procedure is under redesign in a separate development branch that is requesting some time to complete. I have suspended all the request regarding raster import and vectorization to prevent merging conflicts.
