### ISSUE TITLE
Variables for Buttons and GCode Head

### ISSUE THREAD

**Issue by wiring80** [arkypita/LaserGRBL#1647]
Hey, please excuse me if i'm wrong.

For custom buttons we can set variables like "[bottom]" of the loaded image, and so on.

In LaserGRBL Settings there is the ability to create HEAD GCodes also with that variables, if i understand right - descripts that we can use the same syntax like in custom buttons.

So my thought was, if i use the variables bottom und top for the image margins, so i can use this values to set my X & Y offset with G10 for offline engraving, cause i use negative coordinates.

Am i right with my thoughts or im confused ?

Because, and thats the problem - this variables doesnt get any values. If i export the GCode, the variables still exists in the HEAD of the GCode. I didnt try it yet with the buttons, only with the HEAD Gcode.

Many Greets, Sven

**Comment by arkypita** [comment]
Yes, you are right.
There is an issue in LaserGRBL export where variables are not converted to values

![image](https://user-images.githubusercontent.com/8782035/144059362-b90aac29-ae96-437d-844e-650131041bb5.png)

**Comment by arkypita** [comment]
Let me know if v4.6.3 (pre-release) fix this issue: https://github.com/arkypita/LaserGRBL/releases/download/v4.6.3/install.exe
