### ISSUE TITLE
Crop image button

### ISSUE THREAD

**Issue by Stewestrong** [arkypita/LaserGRBL#1659]
**Describe the bug**
Crop image button turns yellow but does not work. It does not crop the finished engraved image. It constantly goes through the entire engraving instead of the outer outline

**To Reproduce**

**Expected behavior**
Kép vágása gomb bekapcsolásával megcsinálja a gravírozást majd a külső körvonal mentén kivágja. Erre számítottam.
**Screenshots**

**Hardware and software configuration (please complete the following information):**
 - Windows version  Windows 10
 - Engraver brand and model ATOMSTACK New A5 30W Laser Engraving
 - Grbl version (i.e. 0.9j, 1.1f) v1.1f original
 - LaserGRBL version  v 4.6.2

**Additional context**

**Comment by Stewestrong** [comment]
v1.1f original

**Comment by arkypita** [comment]
One you select the crop tool you should click and drag on the preview to select the area to be crop.

![image](https://user-images.githubusercontent.com/8782035/143834663-be4803ac-cc99-40b5-86c5-54de4628109e.png)
