### ISSUE TITLE
Version 2.8.16 Error when writing changes to GRBL settings

### ISSUE THREAD

**Issue by StuartB4** [arkypita/LaserGRBL#166]
Hi. Just updated to 2.8.16 and tried to change the settings for $110 and $111.
When writing the changes to GRBL I get the error in this image, even though I never changed $32.

![untitled](https://user-images.githubusercontent.com/16980026/32895289-7175466a-cad7-11e7-87e7-7cc1872d479c.jpg)

Changing $32 and writing to GRBL also produces the same error.

**Comment by arkypita** [comment]
LaserGRBL send the whole config set, not only changed values.
If you try to change $32 manually by typing $32=0 inside "type gcode here" box, do you have the same error?

**Comment by StuartB4** [comment]
I think it has something to do with PWM. My laser is not using PWM at the minute, just on and off.
So I had a look at GRBL error 17 and it says:
"17 | Laser mode requires PWM output."

**Comment by arkypita** [comment]
Yes. i think that PWM is disabled in hardware ([VARIABLE_SPINDLE in config.h](https://github.com/gnea/grbl/blob/5967839ab38f8e984a384db1f64e781cffb9e739/grbl/config.h#L339) of grbl) and grbl reply with this error at each try to set $32

**Comment by arkypita** [comment]
It would probably be better if I limit writing only to the edited values

**Comment by StuartB4** [comment]
Yes, my config.h file has the 2 // in front of the setting on line 339.
When I get a new laser driver board that supports PWM I will remove the 2 //'s
to enable it properly.
Thanks very much for the help.

**Comment by arkypita** [comment]
fixed in [v2.8.17](https://github.com/arkypita/LaserGRBL/releases/tag/v2.8.17)

**Comment by StuartB4** [comment]
Thats great, thanks very much.
