### ISSUE TITLE
Jagged lines while creating g-code

### ISSUE THREAD

**Issue by hk89** [arkypita/LaserGRBL#170]
Hi,

I figured out that LaserGRBL does not create arcs and curves for most of the vectorized picture. Sometimes it appears that most curves are somehow turned into stair-stepped lines which wastes time, increases g-code length and distance traveled. It appears on the g-code preview screen. However they do not appear on the screen where I adjust the settings for it. I tried smoothing and downsampling without a good result. I even changed the junction deviation from 0.01 to 0.001

Please see pictures and gcode. I am using GRBL v1.1f with the settings as in the pictures.

![3](https://user-images.githubusercontent.com/24245215/32971787-8bc7b5fe-cbf7-11e7-8b62-eaaed988a8b8.png)

![2](https://user-images.githubusercontent.com/24245215/32971783-872a8cba-cbf7-11e7-8926-482f1035c888.png)

[gcode.zip](https://github.com/arkypita/LaserGRBL/files/1484040/gcode.zip)

**Comment by arkypita** [comment]
Use Smooth instead of Sharp as resize option.

**Comment by arkypita** [comment]
and read usage guide: http://lasergrbl.com/it/usage/raster-image-import/import-parameters/

**Comment by hk89** [comment]
Thanks for the kind reply. I changed it now and it is working like a charm. Sorry for wasting your time. I guess I did not see that one in the usage guide.
