### ISSUE TITLE
v2.8.17 need testing

### ISSUE THREAD

**Issue by arkypita** [arkypita/LaserGRBL#171]
I have added keyboard shortcut managment. Please someone test it before I release as official.
https://github.com/arkypita/LaserGRBL/releases/tag/v2.8.17

![image](https://user-images.githubusercontent.com/8782035/32982738-6be3572e-cc89-11e7-8f14-7868a8b0fbd8.png)

**Comment by arkypita** [comment]
I also add a "Set zero point" button, because a lot of user is asking for it.
I also made the "Homing" button appare/disappear if configured in Grbl

**Comment by TehseenHasan** [comment]
That's very nice....

**Comment by arkypita** [comment]
released, hope it work without sideeffects

**Comment by StuartB4** [comment]
Hi Arkypita.
I cant get the "Set zero point" button to work in the latest version.
I move the X or Y axis a few millimeters and the press the "Set zero point" button and the blue + jumps straight back to the bottom left home position.
It also affected my custom button which did work to set a new X0 Y0 position, that now does the same and jumps straight back to the bottom left home position when clicked.

**Comment by StuartB4** [comment]
Just realised, it does store the new 0,0 position but only shows after closing the program, restarting and clicking on Connect. Then the blue +jumps to where I moved the X,Y axiz to.

**Comment by aMirMOsavi** [comment]
Hi
get error While Use Keyboard shortcut !
![2017-11-19 02-08-19 pm by amir](https://user-images.githubusercontent.com/17276809/32989834-431354a2-cd33-11e7-971b-21c6219854b4.jpg)
[error Keyboard shortcut.txt](https://github.com/arkypita/LaserGRBL/files/1485462/error.Keyboard.shortcut.txt)

**Comment by arkypita** [comment]
> I cant get the "Set zero point" button to work in the latest version.
I move the X or Y axis a few millimeters and the press the "Set zero point" button and the blue + jumps straight back to the bottom left home position.
It also affected my custom button which did work to set a new X0 Y0 position, that now does the same and jumps straight back to the bottom left home position when clicked.

@StuartB4 
It is correct, it is the desired behavior by design.
If you set a new zero, the blue cross is now at zero. Does this make sense?

The error was in previous version of LaserGRBL that still showing the cross in absolute position. 
In my opinion now is better.

**Comment by arkypita** [comment]
@aMirMOsavi 
What are the conditions for reproducing the problem?

**Comment by StuartB4** [comment]
> It is correct, it is the desired behavior by design.
If you set a new zero, the blue cross should go at zero. Does this make sense?

> The error was in previous version of LaserGRBL that still showing the cross in absolute position.
In my opinion now is better.

Yes I understand now, thanks very much.

**Comment by arkypita** [comment]
@aMirMOsavi 
I have googled about that, seems to be a bug of Microsoft DataGridView control. References:
https://stackoverflow.com/questions/34344499/invalidoperationexception-this-operation-cannot-be-performed-while-an-auto-fill
https://connect.microsoft.com/VisualStudio/feedback/details/481029/this-operation-cannot-be-performed-while-an-auto-filled-column-is-being-resized

I have implemented a workaround for future versions.

**Comment by StuartB4** [comment]
Hi Arkypita.
I just had a look at the error text file aMirMOsavi supplied and noticed this:

> ************** Loaded Assemblies **************
mscorlib
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8825 (WinRelRS3.050727-8800)
    CodeBase: file:///C:/Windows/**Microsoft.NET/Framework64/v2.0.5072**7/mscorlib.dll

Just wondered if that could be a problem as it's a lower version than you recommend for running LaserGRBL.

**Comment by arkypita** [comment]
Good observation!

**Comment by arkypita** [comment]
In v2.8.19 I add a fix for @aMirMOsavi issue
I also have changed the update procedure that allow me to use a different installer/packager (instead of packing with winrar self extractor) that should be more antivirus friendly.
