### ISSUE TITLE
Timespan overflow because duration is too long

### ISSUE THREAD

**Issue by brucek5** [arkypita/LaserGRBL#172]
I get the subject error after clicking Create! Button.  Tried different images, sizes, speeds, and conversation tool types.

**Comment by arkypita** [comment]
Thanks for your report

LaserGRBL now compute the speed using max speed from Grbl configuration. I think I have a bug addressing the correct $ param in grbl 0.9

**Comment by arkypita** [comment]
released an update, let me know if it fix

**Comment by brucek5** [comment]
You fixed the bug, thank you.
