### ISSUE TITLE
Telegram Bot not working

### ISSUE THREAD

**Issue by HomineLudens** [arkypita/LaserGRBL#1724]
Hi, anyone facing issues registering to laser grbl bot?
I've try for a long time to register but every time I've this error

Cannot retrieve your code now, please retry later. [2]

![Screenshot_2022-01-16-20-18-24-431_org telegram messenger](https://user-images.githubusercontent.com/1007007/149674597-72654ac7-b79f-4273-b44c-2782a9720fe5.jpg)

**Comment by arkypita** [comment]
Ciao

Don't know if someone can answer to you, except me. This feature is used only by 26 people, don't know if other people try using but have issues, or what.

I have added some logging to the code, if you try to re-do the register procedure I can tell you more.

**Comment by HomineLudens** [comment]
Ciao!

The feature is really interesting, maybe still not know by many people.

I've try again a couple of minutes ago.
Let me know if I can make any other test.

**Comment by arkypita** [comment]
Found some issue in handling null values, i think it's fixed now.

**Comment by HomineLudens** [comment]
Awesome! Thanks for the super quick fix.
