### ISSUE TITLE
problema velocità V 2.8.16

### ISSUE THREAD

**Issue by cecconilorenzo** [arkypita/LaserGRBL#174]
ciao, non riesco a regolare la velocità dei motori qualsiasi valore metta nel "Gcode options" i otri vanno alla stessa velocità. come devo fare?
grazie.

**Comment by arkypita** [comment]
si vede che la velocità è limitata dalle configurazioni di grbl $110 $111 $112
ps. scrivi in inglese, grazie

**Comment by cecconilorenzo** [comment]
is there a way to solve the problem?

**Comment by arkypita** [comment]
Change the max values using "grbl configuration" form.
