### ISSUE TITLE
FileRepMalware?

### ISSUE THREAD

**Issue by rjcuomo1** [arkypita/LaserGRBL#176]
Hello,

Every time I try to download v2.8.19, AVG Internet Security blocks it from finishing saying it contains "FileRepMalware". Why does it do that? 

Thank you

**Comment by arkypita** [comment]
http://lasergrbl.com/en/faq/
https://github.com/arkypita/LaserGRBL/issues/70

Whould you like to test last version? I have changed my installer and now should be more antivirus friendly. https://github.com/arkypita/LaserGRBL/releases/tag/v2.8.20

**Comment by rjcuomo1** [comment]
That worked, thank you!
