### ISSUE TITLE
Uneven burning

### ISSUE THREAD

**Issue by Mikalay31** [arkypita/LaserGRBL#177]
Hello ! I have such a problem. The edges near the picture are burned deeper. I understand this is due to the fact that in these places the direction of motion changes. Acceleration costs a little (300). And so the laser burns more. Whether there is such function that around of a picture there was a virtual field of white color. To change the direction does not coincide with the moment of burning. Thank you ! Nicholas.

**Comment by Mikalay31** [comment]
http://prntscr.com/heesdn            http://prntscr.com/heesov

**Comment by arkypita** [comment]
Use Grbl v1.1 with laser mode enabled and M4 Dynamic Laser Power Mode to get the best result.
https://github.com/gnea/grbl/wiki/Grbl-v1.1-Laser-Mode#laser-mode-operation

**Comment by arkypita** [comment]
![image](https://user-images.githubusercontent.com/8782035/33202376-96c451ec-d0fc-11e7-868a-27f73eb43e35.png)

![image](https://user-images.githubusercontent.com/8782035/33202395-aa686684-d0fc-11e7-94dd-893d6a48b5b4.png)

**Comment by arkypita** [comment]
Also the suggested/required feature is already in roadmap #64 (acceleration offset)

**Comment by Mikalay31** [comment]
Thank you ! That helped ! Thank you for the excellent program. As always, I follow your updates.
