### ISSUE TITLE
Laser GRBL not opening in my computer

### ISSUE THREAD

**Issue by tonyjavi** [arkypita/LaserGRBL#1783]
Hey,

I have been using laser grbl with my small laser engraver for 2 years now and suddenly the application stopped opening in from my desktop so I can no longer use it.

I tried updating and re-installing but nothing seems to work. Neither there are any information banners popping up.

Any ideas?

Hardware and software config.
 - Windows version 10
 - Engraver brand and model. TOPQSC CNC 2 axis, 65x50 cm
 - LaserGRBL version 4.7.0

Thank you all!

**Comment by tonyjavi** [comment]
Hi, 

I looked thoroughly for this folder in my user but did not find it. Do you think of any other possible solution?

Thanks again,

**Comment by StuartB4** [comment]
Is the AppData folder showing, it can be a hidden folder.
If you click C, then Users, then "your name" folder, then the View menu and Options on the right you get the option to show or hide certain files and folders. Click Options and then the View tab. 

![tytytyty](https://user-images.githubusercontent.com/16980026/157055724-d577647d-5222-4552-a06c-d03700307c51.png)


![yuyuyu2](https://user-images.githubusercontent.com/16980026/157055763-0b81acd9-021e-49e8-ad8a-170d8fd1bdf2.png)

**Comment by tonyjavi** [comment]
Thanks for the tip! Now I can visualize the file but can not open it as it's a .bin folder.

I tried to open with PoweISO app but can't. Do you recommend me other app or way to open and clean this folder? Or should I just delete it?

Thanks,

![github image 2](https://user-images.githubusercontent.com/101113807/157090153-2350f392-f81c-46cf-a388-1165591f89b7.JPG)
![github image 1](https://user-images.githubusercontent.com/101113807/157090156-6b02ff19-1135-4980-93b4-64a61dbe3bb3.JPG)

**Comment by StuartB4** [comment]
If you are going to reinstall LaserGRBL you can delete any other LaserGRBL folders first.

**Comment by tonyjavi** [comment]
I deleted all of them and any other file from my laptop and reinstalled but same thing happens. I download it and create a desktop shortcut but the program does not open. 

Now when I search in User>AppDate some folders are missing.

![image](https://user-images.githubusercontent.com/101113807/157209179-4b4372dc-69e1-482c-b016-b0e7d499bf1e.png)

**Comment by StuartB4** [comment]
I don't have any other folders in there, just the files that Lasergrbl creates. May be they are not created because it does'nt start properly. 

![hhhhhhhhhhhhhhhhhhh](https://user-images.githubusercontent.com/16980026/157257673-877d436e-ae0a-491a-8152-936587c1e8a2.png)

**Comment by StuartB4** [comment]
You say you install it and create a shortcut to the desktop, but lasergrbl should do that. 
Are you using the correct shortcut.

**Comment by arkypita** [comment]
@tonyjavi can you also look inside windows event viewer (Application and System log) if you have any record about LaserGRBL or .NET framework near the clock time when you open LaserGRBL?

https://www.howtogeek.com/123646/htg-explains-what-the-windows-event-viewer-is-and-how-you-can-use-it/

**Comment by tonyjavi** [comment]
Hi all, 

Luckly I upgraded my windows to version 11 and all of sudden the program started working again.

Thank you for the tips,
