### ISSUE TITLE
Multipale pass problem

### ISSUE THREAD

**Issue by Umnik-va** [arkypita/LaserGRBL#180]
Hi!

Very nice programm, thank you very match!!

Since version 2.8.18 the function of multiple passes does not work. On version 2.8.16, everything works fine if you specify several passes and click on the "Start" icon - the program executes the selected number of passes, after each pass the counter is reduced by one. Starting with version 2.8.18 when I click on the "Start" icon the program does only one pass, the pass count is reduced by one and the code is not re-executed. To start the pass one more time, you have to blink again by the start icon.

Начиная с версии 2.8.18 не работает функция множественных проходов. На версии 2.8.16 все работает нормально, если указать несколько проходов и кликнуть по значку "Старт" - программа выполняет выбранное количество проходов, после каждого прохода счетчик уменьшается на единицу. Начиная с версии 2.8.18 когда я нажимаю на значок "Старт" программа делает только один проход, счетчик проходов уменьшается на единицу и повторно код не выполняется. Для запуска прохода еще один раз надо снова клинкуть по значку старт.

Vladimir

**Comment by StuartB4** [comment]
Same here in V 2.8.20

**Comment by arkypita** [comment]
Thanks for report. I check as soon as possible

**Comment by arkypita** [comment]
fixed in v2.8.22
was a side effect of some change I made for "job resume feature" in v2.8.16

thanks for feedback
