### ISSUE TITLE
preview window not centered on work image

### ISSUE THREAD

**Issue by Ams-Laser** [arkypita/LaserGRBL#1806]
**Describe the bug**
opening a gcode file that has x0y0 on center of work, gets cropped in preview window

**To Reproduce**
open attached file
[test.txt](https://github.com/arkypita/LaserGRBL/files/8406295/test.txt)

**Expected behavior**
work preview is centered on preview window

**Screenshots**
![image](https://user-images.githubusercontent.com/87819514/161464313-07c6469d-8c67-4b9f-816b-5df92d181a63.png)

**Hardware and software configuration (please complete the following information):**
 - Windows version
 -  10
 - Engraver brand and model
 - self build
 - Grbl version (i.e. 0.9j, 1.1f)
 - 1.1l
 - LaserGRBL version
 - 4.8.0

**Additional context**

**Comment by arkypita** [comment]
According to GRBL definition (LaserON = M3/M4 and LaserOFF = M5) the gcode you attach never turn the laser on, so lasergrbl compute a job size of 0.0 x 0.0 mm that's why it is not centered in workspace

**Comment by Ams-Laser** [comment]
isee, this is an embroidery G-code no need for laser or splindle since z is doing the stitches, and x y the movement, is it posible to center the design ?
or any code i might need to inject so the preview becomes right ?
i would love to use laser grbl to stream this type of code to my machine, i already use it for laser, plasma, oxifuel machines
thanks
Edward

**Comment by arkypita** [comment]
> or any code i might need to inject so the preview becomes right ?

M3 is the code you can use to tell LaserGRBL the laser is on.
