### ISSUE TITLE
 How to turn off spindle in pause mode?

### ISSUE THREAD

**Issue by Evil-Nemesis** [arkypita/LaserGRBL#181]
hello there
I need to turn off the spindle when I pressed feed hold button!
how can I do it!?

**Comment by arkypita** [comment]
This behaviour is managed by grbl, not by LaserGRBL

**Comment by arkypita** [comment]
use v1.1 with laser mode to obtain required behaviour
https://github.com/gnea/grbl/wiki/Grbl-v1.1-Laser-Mode

**Comment by Evil-Nemesis** [comment]
hi arkyoita.
**first of all I really thank you for your efforts!**
and thanks a lot for your answer!
I actually do that!!
for hardware button I do this:
uncomment this line in config.h:
#define ENABLE_SAFETY_DOOR_INPUT_PIN

and for the software button I changed this:
`void BtnStopClick(object sender, EventArgs e) { Core.FeedHold(); }`
to this
`void BtnStopClick(object sender, EventArgs e) { Core.FeedHold(); Core.SafetyDoor(); }`
and it's OK!
