### ISSUE TITLE
Custom buttons

### ISSUE THREAD

**Issue by vaicekas** [arkypita/LaserGRBL#183]
Hello
Thank you very much for the great program!
But I would really like a feature that would allow to enlarge the Trace frame at the custom distance. It would be used for cutting according to the contour of the picture.
I imagine this as using GCode shortcuts and mathematical steps. For example: G1 X [left] -5 Y [botom] -5
G1 X [right] +5 Y [botom] +5 and so on.
If this were not tough, we would be very happy with this feature in future versions of the program.
Thank you.

**Comment by arkypita** [comment]
It's something I always thought someone would one day ask for.

It is not too difficult, but it requires to implement of a kind of interpretation of the text a little more complicated than "search for [left] and replace with a number"

**Comment by vaicekas** [comment]
it means You are missing it to :) 
So it can be expected that this will happen sometime ;)

**Comment by arkypita** [comment]
try [v2.8.31](https://github.com/arkypita/LaserGRBL/releases/tag/v2.8.31)
