### ISSUE TITLE
New function

### ISSUE THREAD

**Issue by schwendi1** [arkypita/LaserGRBL#185]
Hello, 

first of all, I love your Programm, its very intuitive and works very good!

Although there is one thing I am missing:
on the Sliders, the Value should be visible somewhere permanently.

Thats it, thanks!

**Comment by arkypita** [comment]
i dont' know if it was what you are asking for, but I have added labels for jogging slider
https://github.com/arkypita/LaserGRBL/releases/tag/v2.8.24

![image](https://user-images.githubusercontent.com/8782035/33445921-b7a3f104-d5fe-11e7-8750-fe5f2e5715e5.png)
