### ISSUE TITLE
[svg/experimental] Optimisation of path 

### ISSUE THREAD

**Issue by arthurlutz** [arkypita/LaserGRBL#1859]
**Is your feature request related to a problem? Please describe.**
When using the svg/experiment open of an svg file with the following file : https://cdn.thingiverse.com/assets/e4/09/03/be/4c/sides.svg

I get a pretty long / jumpy path generated : 

![Screenshot from 2022-07-04 14-34-13](https://user-images.githubusercontent.com/108437/177156232-d5eae693-74c0-476d-a842-cc445a9d0a4c.png)

This works but maybe it would be feasible to have a simpler path (that at least follows the connected edges ? ) 

**Describe the solution you'd like**

A generated path that jumps between rectangles, not between lines of each rectangle. 

**Describe alternatives you've considered**
I could imagine that the svg could be modified before being send to LaserGRBL but I have no idea of how this could be done.

**Comment by arkypita** [comment]
LaserGRBL follow the instruction it found inside the SVG file, in the order they are inside the file.
Draw rectangle instead of lines (or poliline instead of single segments) and you have the expected behaviour.
