### ISSUE TITLE
SVG Viewbox directive doesn't work properly when ymin <> 0

### ISSUE THREAD

**Issue by jjcarron** [arkypita/LaserGRBL#1868]
**Describe the bug**
The Viewbox y-min value is not interpreted correctly

**To Reproduce**
1. I generate a simple square view using OpenScad (The bug is not dependent on the programm but only on non zero Viewbox y-min value)

The code is :  projection () cube (10);

The generated file looks like :
![image](https://user-images.githubusercontent.com/28822636/179425709-2526f652-d275-4286-ad7f-c2bb020b064e.svg)

or
![image](https://user-images.githubusercontent.com/28822636/179426966-f794ce4e-fdaa-4c90-809b-cf32d98c7f71.png)

4.  Open it in LaserGRBL
![image](https://user-images.githubusercontent.com/28822636/179426997-3c6b4797-65f3-4873-a873-2d67100abe9d.png)

Instead to be at **-10** the image is at **-27.8** 

There are two problems :

-  Openscad generates Y-Axis in the wrong way. (positive values are interpreted as negative values (Not your problem, but can be solved with the mirror function on openScad The code looks like : projection () mirror([0,1,0]) cube (10); ) and the generated file looks like : 
![image](https://user-images.githubusercontent.com/28822636/179426331-fa53ade3-915a-4358-b939-245909f438d6.svg)
or 
![image](https://user-images.githubusercontent.com/28822636/179427038-1933f338-f68f-4e87-b621-713b8955178e.png)

The image is uploaded correctly in LaserGRBL
![image](https://user-images.githubusercontent.com/28822636/179427075-eb2ba12e-4e1f-406d-b5b7-e11474eac214.png)

- The second problem stays. I move the object 10 in the y axis withe the code :  projection () mirror([0,1,0]) translate([0,**10**,0 ]) cube (10);
The image looks like 
![cube 10 error 3](https://user-images.githubusercontent.com/28822636/179426678-ea8fa5af-3d7c-4bdf-be6a-942d71cd253e.svg)
or
<?xml version="1.0" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg width="10mm" height="10mm" viewBox="0 **10** 10 10" xmlns="http://www.w3.org/2000/svg" version="1.1">
<title>OpenSCAD Model</title>
<path d="
M 10,10 L 0,10 L 0,20 L 10,20 z
" stroke="black" fill="lightgray" stroke-width="0.5"/>
</svg>

in the LaserGRBL it looks like  
![image](https://user-images.githubusercontent.com/28822636/179426707-f7afc3c6-1f22-4e51-ad69-df141373ec05.png)

As you see translated on 27.8 instead of 10

**Expected behavior**
The translation should be done according the value in the Viewbox Statement (with the correct units? I work in mm)

**Hardware and software configuration (please complete the following information):**
 - Windows version 10
 - Engraver brand and model Atomstack P7
 - LaserGRBL version v4.8.4

**Comment by jjcarron** [comment]
I found the problem in the code at line 205 of "GCodeFromSVG.cs" 
The line

205: tmp.OffsetY = -vbOffY * svgHeightPx / vbHeight + (svgHeightPx* scale);

should be 

205: tmp.OffsetY = -vbOffY * svgHeightPx / vbHeight + svgHeightPx; 

as the svgHeightPx was already in pixels  at this point

**Comment by arkypita** [comment]
Merged your fix in master branch, available with latest LaserGRBL version.
Hope it does not add more issues :-)
