### ISSUE TITLE
Laser engraving with arduino mega 2560 and cnc shield ramps v1.4 and 3 stepper motors

### ISSUE THREAD

**Issue by LifeIsMySchool** [arkypita/LaserGRBL#187]
Hi friend! Can you help me, please? Can I use your grlb software and laser grlb editor at arduino mega 2560 and cnc shield ramps v1.4 and 3 stepper motor? Is it possible? Are they appropriate for my component?﻿ My design will be like at the photo.
![ekran alintisi1](https://user-images.githubusercontent.com/30956341/33349522-8a9d49e8-d4ab-11e7-9898-cbb5b22bf1a0.JPG)

**Comment by arkypita** [comment]
Grbl is not my product. The github page for GRBL for mega is https://github.com/gnea/grbl-Mega/
If you use GRBL - LaserGRBL can work with your board.

**Comment by LifeIsMySchool** [comment]
Thank you. Is this grbl for laser engraving? How can I upload at the mega? Because Arduino software editor warned me that it accepts .ino or .pde extension. How can I also use CNCShield Ramps V1.4? Do you know what these files are?
[grbl-master.zip](https://github.com/arkypita/LaserGRBL/files/1513697/grbl-master.zip)
[ArduinoMegaPololuShield.zip](https://github.com/arkypita/LaserGRBL/files/1513698/ArduinoMegaPololuShield.zip)
[UltiMachineRAMPS1-4Sprinter.zip](https://github.com/arkypita/LaserGRBL/files/1513699/UltiMachineRAMPS1-4Sprinter.zip)

**Comment by LifeIsMySchool** [comment]
I installed Grbl Desktop before two days.

**Comment by LifeIsMySchool** [comment]
I cloned mega in the githup desktop. But I don't now what it means. Because I can't add any grbl file from my computer?

**Comment by arkypita** [comment]
https://github.com/gnea/grbl/wiki/Compiling-Grbl
https://github.com/gnea/grbl/wiki/Flashing-Grbl-to-an-Arduino

**Comment by LifeIsMySchool** [comment]
Do you have Arduino cod for two stepper motor, one laser head and one fan? I really need it.
