### ISSUE TITLE
The laser doesn't work 

### ISSUE THREAD

**Issue by FeetSolutions2022** [arkypita/LaserGRBL#1873]
LaserGrbl v4.8.0.0
Grbl v1.1h
Wrapper: UsbSerial
Win 10, Home, 10.0.19044.0 (7)
CLR: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll 4.8.4515.0 built by: NET48REL1LAST_C

TypeOf exception  [System.OverflowException]
Exception message [Valor demasiado grande o demasiado pequeño para Int32.]
Exception source  [mscorlib], thread [Main Thread]
Exception method  [Int32 ToInt32(System.Decimal)]

   ----------- stack trace -----------
   en System.Decimal.ToInt32(Decimal d)
   en LaserGRBL.RasterConverter.ConvertSizeAndOptionForm.AssignMinMaxLimit() en E:\LaserGRBL\LaserGRBL\RasterConverter\ConvertSizeAndOptionForm.cs:línea 78
   en LaserGRBL.RasterConverter.ConvertSizeAndOptionForm..ctor(GrblCore core) en E:\LaserGRBL\LaserGRBL\RasterConverter\ConvertSizeAndOptionForm.cs:línea 49
   en LaserGRBL.RasterConverter.RasterToLaserForm.BtnCreateClick(Object sender, EventArgs e) en E:\LaserGRBL\LaserGRBL\RasterConverter\RasterToLaserForm.cs:línea 179
   en System.Windows.Forms.Control.OnClick(EventArgs e)
   en System.Windows.Forms.Button.OnClick(EventArgs e)
   en System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   en System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   en System.Windows.Forms.Control.WndProc(Message& m)
   en System.Windows.Forms.ButtonBase.WndProc(Message& m)
   en System.Windows.Forms.Button.WndProc(Message& m)
   en System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by arkypita** [comment]
Check your grbl configuration (menu grbl, grbl configuration). Probably you have some parameters with out of range or zero value (like machine size) parameters 130 and 131
