### ISSUE TITLE
Broadcast to WLED

### ISSUE THREAD

**Issue by brakthehun** [arkypita/LaserGRBL#1884]
I hate the sounds but I'm a fan of light indicators.
WLED accepts many forms of communications - https://kno.wled.ge/interfaces/json-api/
I use LEDFX to control them with music and you just give it he IP of the WLED and the pixel count - https://github.com/LedFx/LedFx

I would like to see a color / animation for idle / alarm / running / complete

**Comment by arkypita** [comment]
for feature request please use "discussion" since this is not a bug or an issue
