### ISSUE TITLE
help , the program dont open

### ISSUE THREAD

**Issue by naomiaaa** [arkypita/LaserGRBL#1891]
LaserGrbl v4.9.3.0
Grbl v1.1 
Wrapper: UsbSerial
Win 10, Home, 10.0.22000.0 (7)
CLR: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll 4.8.4515.0 built by: NET48REL1LAST_C

TypeOf exception  [System.FormatException]
Exception message [La cadena de entrada no tiene el formato correcto.]
Exception source  [mscorlib], thread [Main Thread]
Exception method  [Void StringToNumber(System.String, System.Globalization.NumberStyles, NumberBuffer ByRef, System.Globalization.NumberFormatInfo, Boolean)]

   ----------- stack trace -----------
   en System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   en System.Number.ParseDecimal(String value, NumberStyles options, NumberFormatInfo numfmt)
   en LaserGRBL.GrblConfST.ReadDecimal(Int32 number, Decimal defval) en E:\LaserGRBL\LaserGRBL\Core\GrblCore.cs:línea 3364
   en LaserGRBL.GrblConfST.get_MaxRateX() en E:\LaserGRBL\LaserGRBL\Core\GrblCore.cs:línea 3328
   en LaserGRBL.JogForm.UpdateFMax_Tick(Object sender, EventArgs e) en E:\LaserGRBL\LaserGRBL\JogForm.cs:línea 95
   en System.Windows.Forms.Timer.OnTick(EventArgs e)
   en System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   en System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by arkypita** [comment]
what kind of machine?

**Comment by naomiaaa** [comment]
I have the atomstack A5 RPO

**Comment by arkypita** [comment]
Please try deleting (or rename) this file: C:\Users<your user name>\AppData\Roaming\LaserGRBL\LaserGRBL.Settings.bin as suggested [here](https://github.com/arkypita/LaserGRBL/issues/1890)

**Comment by naomiaaa** [comment]
![Captura de pantalla 2022-08-09 170731](https://user-images.githubusercontent.com/110940365/183770354-92a556ed-dc30-4e29-b541-ea310792f3d0.png)

Can you please tell me which file?

**Comment by arkypita** [comment]
No the path is not this one.

 C:\Users\your user name\AppData\Roaming\LaserGRBL\LaserGRBL.Settings.bin

**Comment by naomiaaa** [comment]
is there another route? because I can't find it on my PC, PLEASE

**Comment by naomiaaa** [comment]
is there another route? because I can't find it on my PC, PLEASE

**Comment by arkypita** [comment]
If you can't find the path, just check "show hidden elements" in your folder browser.

![image](https://user-images.githubusercontent.com/8782035/183840162-dd4130df-739b-436b-a739-6db3cb413735.png)

**Comment by naomiaaa** [comment]
Thanks, I already opened the program, but the FRAME, FOCUS AND BLINK light does not turn on, the machine works and records normally, I don't know what could have happened, I hope you can help me

**Comment by arkypita** [comment]
LaserGRBL need to read at least one time the configuration from the machine. please open "grbl -> grbl configuration" when the machine is connected and idle, and verify to see all the configuration values read from machine

**Comment by MARTIN83-DOT** [comment]
The program does not allow me to continue, it immediately launches me a page where it gives me the option to approach and continue what do I do? HELP!
![ERROR](https://user-images.githubusercontent.com/121684865/210102011-7031f171-4339-43d2-b984-3ced2caad039.png)
