### ISSUE TITLE
No text on create button with SVG with dutch language.

### ISSUE THREAD

**Issue by Defaezer** [arkypita/LaserGRBL#1892]
![02278F30-8C26-42B7-81E1-A5BC531BD73B](https://user-images.githubusercontent.com/34836256/184080478-0d064d78-b2e2-4d4f-8b83-ef06ca9d7096.jpeg)
![699328DF-7D85-497D-9EE4-DA1AE9B3F98E](https://user-images.githubusercontent.com/34836256/184080531-c89d5766-7043-4a98-bd2c-43800170aa2a.jpeg)

**Comment by arkypita** [comment]
thank you, i'll fix in the next release

**Comment by StuartB4** [comment]
No problem here. Is it because it's a different language?

![7777d](https://user-images.githubusercontent.com/16980026/184132431-a8cb6628-8e5f-4864-8f06-5e895eb0924c.png)

**Comment by Defaezer** [comment]
Yes, try dutch
