### ISSUE TITLE
Is there a setup tutorial for the Linksprite Laser head?

### ISSUE THREAD

**Issue by rseijo** [arkypita/LaserGRBL#19]
Hi, I have the Linksprite CNC with the optional Laser (pls see below).  
Does anyone know how to properly setup, adjust and or focus the Laser for Etching vs Cutting?   
I have tried to locate instructions for this laser with no success. 

I will be grateful for any guidance on this...

Thanks!
Ralph

http://linksprite.com/wiki/index.php5?title=DIY_CNC_3_Axis_Engraver_Machine_PCB_Milling_Wood_Carving_Router_Kit_Arduino_Grbl
 
Laser Head for DIY CNC 3 Axis Engraver Machine:  **KIT_CNC_LASHA**
Laser Wavelength 405nm
12V DC  
Output Power  500mw.

http://linksprite.com/wiki/index.php5?title=Laser_Head_for_DIY_CNC_3_Axis_Engraver_Machine

![image](https://cloud.githubusercontent.com/assets/25676792/23828634/5064525e-06a6-11e7-943f-668ef6eb8607.png)

**Comment by arkypita** [comment]
A perfect laser focusing is necessary for cut and engrave too, specially 
with low power laser.

This is what I do when I nedd to focus my laser:
- Put a piece of black cardboard on the engraving surface.
- Turn on laser at the lower available power M3 S30
- Do a small move G1 X1 F100
- Now focus by hand, rotating collimation gear to obtain the smallest dot.

Try this sequence
Diego

Inviato con AquaMail per Android
http://www.aqua-mail.com


Il 12 Marzo 2017 04:20:54 Ralph <notifications@github.com> ha scritto:

**Comment by arkypita** [comment]
Ps: always wear safety glasses when near look to focus point!

Inviato con AquaMail per Android
http://www.aqua-mail.com


Il 12 Marzo 2017 04:20:54 Ralph <notifications@github.com> ha scritto:

**Comment by rseijo** [comment]
Arkypita, thank you so much!   I will focus the laser as you recommend.  And yes, laser safety glasses!

Thanks again
Ralph

**Comment by rseijo** [comment]
Diego,  Being that the Linksprite CNC has a movable Z axis, is there a specific height the that laser should be at for focusing? 

Thanks

**Comment by arkypita** [comment]
I dont' know, I have a different laser and my CNC is 2 axis only, no Z.

**Comment by rseijo** [comment]
Thanks!
