### ISSUE TITLE
Change M3 / M4 to M106 gcode

### ISSUE THREAD

**Issue by agasevangelos** [arkypita/LaserGRBL#191]
Hi is there a way to generate gcode with custom ON/OFF M-code for the laser?
I would like to use the M106 m-codes to run the g-code on a 3dprinter running Marlin.

Thanks

**Comment by arkypita** [comment]
I plan to review much of the GCode generation-optimization algorithm to make it more flexible and configurable (i.e. change the kind of command for laser on/off). In a not too far future I will also add this feature.

As workaround you can save the file and edit it as a text file (find-replace).

**Comment by bywebberen** [comment]
I tried that, renaming it to *.gcode from *.nc with all M3 inside replaced with M106 And M5 replaced with M107 still no luck...

**Comment by arkypita** [comment]
What do you mean with no luck? What is the problem?

**Comment by bywebberen** [comment]
The the program runs(the steppers) , but it doesn't fire the laser on and
off.

Venlig hilsen / best regards
Niels Østbjerg
Syrenvænget 8
5792 Årslev

+45 40630201


Den 6. dec. 2017 7.26 PM skrev "arkypita" <notifications@github.com>:

**Comment by bywebberen** [comment]
Did the issue get resolved by anyone out there?
