### ISSUE TITLE
Enable "remove button" option in autohome

### ISSUE THREAD

**Issue by edsonee** [arkypita/LaserGRBL#1911]
Not all machines have "limit switches", and if you press that button without having the limit switches, the machine starts hitting corners causing problems.
new users always get confused
![Captura](https://user-images.githubusercontent.com/83145998/187434893-3ea193e3-e6d5-47fd-9ad0-3630904d790a.PNG)

I suggest that you allow "remove" said button, it is already blocked.

and I have come to see users confused with the "HOME" button
![Captura1](https://user-images.githubusercontent.com/83145998/187435140-7d0c1fbf-36f7-493d-8b82-0df578fab7b3.PNG)

Thanks

**Comment by arkypita** [comment]
If your machine does not have limit switches you should disable homing in GRBL configuration.
LaserGRBL react and automatically removes homing button.
