### ISSUE TITLE
incomplete cut

### ISSUE THREAD

**Issue by beytullahgol** [arkypita/LaserGRBL#192]
as seen in the picture, the cut does not end

![3](https://user-images.githubusercontent.com/17261033/33494360-0fb6d0b6-d6d4-11e7-8793-f6db3cea4fa5.jpg)
![2](https://user-images.githubusercontent.com/17261033/33494361-0fd89192-d6d4-11e7-9ac1-81f58b513b25.jpg)
![1](https://user-images.githubusercontent.com/17261033/33494362-0ffc6f40-d6d4-11e7-9b2c-1ea20cb6f10e.jpg)

**Comment by arkypita** [comment]
Is this an issue of LaserGRBL?

**Comment by beytullahgol** [comment]
i don't know.. maybe you can help or fix this with software editing

**Comment by arkypita** [comment]
Maybe laser turn on but material start melting/cutting only a little bit later OR Laser is commanded to turn on by Grbl but electronic circuits add some delay in switch on.

I think this problem/solution is similar to https://github.com/arkypita/LaserGRBL/issues/189

**Comment by beytullahgol** [comment]
machine I used CTK-1350C Cutting Plotter 
electronic circuits can create delays
the delay will work
