### ISSUE TITLE
EMULATED GRBL V1.1# message ?

### ISSUE THREAD

**Issue by Gerd12** [arkypita/LaserGRBL#1925]
EMULATED----Does anyone know how to remove or take action to stop this? After downloading latest 4.9.4, when I start the program, the first time, beside the connect button, is a heading indicates this message instead of the normal line for COM & BAUD rate.
I can load images, but the program seems to be frozen. Nothing is selectable. GRBL code config will not accept any changes, nor any other button will accept a click.
Any help would be appreciated

![Screenshot (1)](https://user-images.githubusercontent.com/92945367/190629204-ff127bbe-4ace-4a9a-a97a-cde6632714f4.png)

**Comment by StuartB4** [comment]
Settings on the Grbl menu, if you've not already found it.
![Untit45454led](https://user-images.githubusercontent.com/16980026/190833122-e547d6b0-14e4-40ab-a879-90d672f6b9b2.png)

**Comment by Gerd12** [comment]
Thank you for the quick reply. Everything works well now. Great PR.

**Comment by StuartB4** [comment]
Thats good, happy to help. 👍
