### ISSUE TITLE
new issue: Show the Filenmae of the loaded File 

### ISSUE THREAD

**Issue by midibase** [arkypita/LaserGRBL#193]
Hello,
as the title said: 
It would be nice if I could see the filename from the loaded file e.g. in the title

best regards

sigi

**Comment by arkypita** [comment]
![image](https://user-images.githubusercontent.com/8782035/33527454-af1126d8-d851-11e7-844e-f1f3b8383fb3.png)

**Comment by midibase** [comment]
Hello, thank you for your replay.

I know that, but the problem is, if you have your files saved on a network (as I 😊 ), the Fullfilename can be too long

for the textbox. So you can’t see at a glance the filename.

This is for me importand because I my files named

Wald1.jpg, Wald2.jpg etc.

 

Best regards

 

Sigi

 

 

 

Von: arkypita [mailto:notifications@github.com] 
Gesendet: Sonntag, 3. Dezember 2017 17:45
An: arkypita/LaserGRBL <LaserGRBL@noreply.github.com>
Cc: midibase <midibase@gmx.at>; Author <author@noreply.github.com>
Betreff: Re: [arkypita/LaserGRBL] new issue: Show the Filenmae of the loaded File (#193)

 

 <https://user-images.githubusercontent.com/8782035/33527454-af1126d8-d851-11e7-844e-f1f3b8383fb3.png>

**Comment by arkypita** [comment]
I don't like to have the filename in form title.
I think i will put the filename only in the texbox and the full path as tooltip on it

**Comment by arkypita** [comment]
done in v2.8.26
https://github.com/arkypita/LaserGRBL/releases/tag/v2.8.26

**Comment by midibase** [comment]
Thanks,

that‘s a good solution

 

best regards sigi

 

 

Von: arkypita [mailto:notifications@github.com] 
Gesendet: Sonntag, 3. Dezember 2017 18:32
An: arkypita/LaserGRBL <LaserGRBL@noreply.github.com>
Cc: midibase <midibase@gmx.at>; Author <author@noreply.github.com>
Betreff: Re: [arkypita/LaserGRBL] new issue: Show the Filenmae of the loaded File (#193)

 

I don't like to have the filename in form title.
I think i will put the filename only in the texbox and the full path as tooltip on it
