### ISSUE TITLE
Enhancement: Add sound to LaserGrbl

### ISSUE THREAD

**Issue by hk89** [arkypita/LaserGRBL#194]
Hi,

Nicest program for my machine. I do have an addition that will help me and others that a sound profile can be set for several conditions/states like gcode start, gcode end, gcode unsupported command, end of each pass, ... etc. That can be very handy and useful.

Thanks

**Comment by arkypita** [comment]
Could be useful and easy to implement.
I'll add to dev roadmap without promise of when i can do it :-)
