### ISSUE TITLE
Delay to reach full power

### ISSUE THREAD

**Issue by egaralmeida** [arkypita/LaserGRBL#197]
I noticed some issues while attempting to cut with a 2w diode laser small figures. The issue seems to be that the laser can't reach full power. An inkscape plugin had an option to setup a delay, and that corrected the problem (although in some cases it created spots where the laser burns while waiting). In my case, a 400ms delay was near perfect. 
Could the option to setup a delay be added to the cut settings windows?

**Comment by arkypita** [comment]
duplicated of #189 #192 
already in roadmap #64
