### ISSUE TITLE
Question on the interface of the program

### ISSUE THREAD

**Issue by Mikalay31** [arkypita/LaserGRBL#198]
Hey. Yesterday I engraved on the machine. I did not understand how to reset the coordinates of the machine. The zero coordinates button only clears the current coordinates. How do I reset all coordinates? Thank you !

**Comment by hk89** [comment]
If you mean to reset the machine coordinates, there is no way but to have limit switches and homing enabled in your grbl and then do a homing process. Machine positions can not be altered by the user.

The coordinates that you are resetting are the work coordinates where they can be set at the beginning of an image somewhere on the workpiece. Work positions can be set by the user using the G92 command. Keep in mind that they are volatile meaning that at power down grbl will lose them.
