### ISSUE TITLE
New program's functions that may be useful

### ISSUE THREAD

**Issue by Rost3** [arkypita/LaserGRBL#2]
1) need to add "frame" around the pictures to accurately position the workpiece. laser not work, only go around the pictures. My laser (not only my) has a "small power" button, do not burn, only shines.
2)  switch invert x, y axis. and start point of engraving (left up, left down, right down...... ).
3) switch vertical/horizontal/diagonal engraving.

**Comment by Rost3** [comment]
4. creation G code from the vector dxf maybe from cdr.

**Comment by arkypita** [comment]
Number 2 and 3 are easy to implement (diagonal is less quick to implement, but could be done too) but not really necessary. Number 1 is interesting and useful for anyone.

I will probabily implement them in the near future.

Number 4 is a professional feature that I don't need, and i will never need, so it's implementation is not a target for me. Development of LaserGRBL is driven by my needs, and claim to be simple and lightweight.
However is free and open software, so anyone with programming skill can fork and implement more function.

**Comment by mayhem2408** [comment]
I run a CoreXY geometry rig and diagonal engraving produces the best results and allows the stepper motors to work in a similar way to a traditional XY Rig. Not a deal breaker, but diagonal work be great for some people.

**Comment by mayhem2408** [comment]
I have forked the code and have implemented vertical engraving and working on 45 degree diagonal engraving.

**Comment by mayhem2408** [comment]
My older rig has a single stepper on the X axis and 2 steppers for the Y axis. For some reason vertical scans seem a little smoother than horizontal. Never been able to figure out why, so always used vertical engraving. 
My newer rig uses CoreXY, so it does not have a stepper for X and a stepper for Y. 45 Degree engraving allows one stepper to be in hold position, while the other stepper is in motion. It produces great results with my python scripted code.

**Comment by arkypita** [comment]
> I have forked the code and have implemented vertical engraving and working on 45 degree diagonal engraving.

Well done @mayhem2408!
I will insert your code into the main version, and i will release a new version.

**Comment by arkypita** [comment]
@mayhem2408 You can now find H/V engraving in [lastest release] (https://github.com/arkypita/LaserGRBL/releases)

Diagonal is not implemented yet, but I have rewrited all code generation to be more virtual about X and Y, so i think make it working in diagonal way could be easy to do.

**Comment by arkypita** [comment]
@mayhem2408 @Rost3 

Diagonal engraving now supported
https://github.com/arkypita/LaserGRBL/releases/tag/v1.3

**Comment by arkypita** [comment]
Image vectorization now supported
https://github.com/arkypita/LaserGRBL/releases/tag/v2.0

**Comment by mayhem2408** [comment]
@arkypita Diagonal is working great and vector is nice to. I'll post some photos of a test engrave very soon.
