### ISSUE TITLE
move faster when the laser is off

### ISSUE THREAD

**Issue by alfredanil** [arkypita/LaserGRBL#20]
If there are white spaces within the image move the laser faster.

**Comment by arkypita** [comment]
Are you sure you're using the latest version? The thing you ask for is already implemented in recent versions. Simply sets a higher Jogging speed in target image dialog (jog speed will be used on white areas).

![image](https://cloud.githubusercontent.com/assets/8782035/24047055/e32edd7a-0b24-11e7-886e-8a5bbb89901b.png)
