### ISSUE TITLE
Image Locating 

### ISSUE THREAD

**Issue by bandguy335** [arkypita/LaserGRBL#203]
I like using this to run my laser engraver, but the only problem is being able to tell where the laser is actually going to start. Do you think there is a way to add like an image locating feature, or is there a way to add that to the custom buttons?

**Comment by StuartB4** [comment]
It shows you where it's going to start with the blue broken line.

![untitled](https://user-images.githubusercontent.com/16980026/33695510-a4c56814-daf5-11e7-9d65-8ab69ac5adde.jpg)

**Comment by bandguy335** [comment]
I knew that but how do I where the laser is going to start on my machine bed.

**Comment by bandguy335** [comment]
I guess I could have been a bit better at explaining my question. I know in the NEJE laser engravers they have a "Box Locating" button that shows you how big the engraving is going to be, and where exactly on the machine bed the engraving will happen, and that's what I was hoping to get a solution to,

**Comment by hk89** [comment]
I got what you need. You need of locating the boundaries of a to-be engraved image. Solution is here in the wiki. Just add the 'M03' and 'M05' commands with your desired 'S' parameter. 
http://lasergrbl.com/en/usage/custom-buttons/

**Comment by arkypita** [comment]
added some math ability in custom buttons
try [v2.8.31](https://github.com/arkypita/LaserGRBL/releases/tag/v2.8.31)
