### ISSUE TITLE
Custom Buttons accidentally deleted...!!!  

### ISSUE THREAD

**Issue by TehseenHasan** [arkypita/LaserGRBL#208]
Now If I remove a custom button **accidentally**, it is deleted at once without **prompting user** if he is sure... Some times while clicking edit on custom buttons I pressed remove mistakenly so it delete button and I have to write button gcode again.  
There should be **confirmation message** before permanently deleting a custom button... 
Thanks.!

**Comment by arkypita** [comment]
I agree
