### ISSUE TITLE
Problem with engraving LaserGRBL preview

### ISSUE THREAD

**Issue by mibiosa** [arkypita/LaserGRBL#210]
Hi everyone,
I have a big problem with 2.8.30 version of LaserGRBL.
When I load any .nc code, in the preview image, all is red!! 
This is the issue:
![wrong preview](https://user-images.githubusercontent.com/34491407/33909193-161a6ebc-df8b-11e7-9e2f-090498c91e85.PNG)
And this is how it should be
![right image](https://user-images.githubusercontent.com/34491407/33909214-2be21dbc-df8b-11e7-8f43-3ce93bcd7cc8.PNG)
LaserGRBL engrave correctly but I need the correct preview :-(
It gives me the same problem with all the images :-(
Does anyone have the same problem?
How I can fix that problem?
Please help meeeeee.
Thank you so much in advance.
Michelangelo

**Comment by arkypita** [comment]
What software generate the .nc file?
Can you upload/post here any sample file?

**Comment by mibiosa** [comment]
Thank you for your answer arkypita :-)
The software I'm using for generate the code is T2Laser.
But the problem is that with the previous version of LaserGRBL I never had that problem.
How I can upload the .nc file in this post?

**Comment by mibiosa** [comment]
here it is:
[frontale scatola frandesco.zip](https://github.com/arkypita/LaserGRBL/files/1553453/frontale.scatola.frandesco.zip)

**Comment by arkypita** [comment]
Is "Support PWM" enabled in your conf?

![enabledpwm](https://user-images.githubusercontent.com/8782035/33912726-573ad704-df97-11e7-8aee-a51e1bf351fb.jpg)

**Comment by mibiosa** [comment]
Ok... fix!
It was not selected the option for PWM Support.... I enabled the option and now it works! :-)
![preview](https://user-images.githubusercontent.com/34491407/33912949-1fd23680-df98-11e7-94c5-111adfdddd93.PNG)
Thank you so much Arkypita :-) Thank you very much for your hard and useful job :-)
Michelangelo

**Comment by arkypita** [comment]
You are welcome, ciao!

**Comment by mibiosa** [comment]
Ma scusa, sei italiano?

**Comment by arkypita** [comment]
certo

**Comment by mibiosa** [comment]
E non potevi dirlo subito ahahah io strippandomi a scrivere in inglese ahahahha
Comunque.... ti ho fatto una piccola donazione (non è tanto) per sostenere il tuo lavoro ;-)
Alla prossima.
Michelangelo

**Comment by arkypita** [comment]
Grazie, molto gentile.

Anche se costa più fatica meglio mantenere l'inglese su queste pagine affinché possano essere d'aiuto un po' a tutti, inclusi i non italiani (che sono la maggior parte).

**Comment by mibiosa** [comment]
Certo, assolutamente d'accordo... tanto la parte riguardante il problema l'abbiamo risolta in inglese ;-)
Grazie ancora e buona serata
Michelangelo
