### ISSUE TITLE
Problem: unexecteted reser of board

### ISSUE THREAD

**Issue by mdarpamex** [arkypita/LaserGRBL#2119]
Hi everyone,
i try to build a co2 laser machine. "Work correctly" but when send first S command over 25 ($31=0 $30=1000) the job frezee and appears a UnexepetedReset error.
If laser stay in 0-15 range i have no problem, axes move correctly and job terminate successfully

Hardware:
board is ELEGOO UNO R3, with 16u2 chip. Its supply is from usb cable, not from dc cable
laser is 50W co2 laser with 80w power supply. Max 26kV, 28mA

grbl version is the last avaiable
i tryied with laser grbl 5 and the previous one
use windows10 from two different laptop

I tryied shield board from noise with metal grid and aluminium foil around board, general power supply, stepper drivers and usb serial cable. I tested continuity and it works

I have a digital thermometer for water circuit, when laser shot over S30 has some problem like from elettrical noise.

![image](https://github.com/arkypita/LaserGRBL/assets/127768744/d51bab85-9bd2-4518-801e-2fe5b57f53d6)
i draw only X axis but of corse there is Y too.
driver are settet with 6400step/rev with means config $100=80, $101=53.333 step/mm

![4c95255b-44d6-444e-a4f4-6a258d70bad7](https://github.com/arkypita/LaserGRBL/assets/127768744/6a27bd64-d7b4-48d1-a1ff-94ec27609c90)
![8fc6ec27-a005-4d07-adf4-e42e204c6dbc](https://github.com/arkypita/LaserGRBL/assets/127768744/7357f4cc-ad17-4e14-95f1-2aae190992e3)

I finish ideas to fix them, can anyone help me?

**Comment by arkypita** [comment]
Detach CO2 tube and its driver board from elegoo controller and test it without laser.
Does it does the same issue?

**Comment by mdarpamex** [comment]
no, if i disconnect pin11 from board all movement is correct and job finish without problem

**Comment by arkypita** [comment]
To me this says two things.

First hypothesis: your laser consumes too much current and the power supply can't handle it (it has a drop in voltage that resets the board) but I would exclude it because if I understand correctly you have separate power supplies.

Second hypothesis: the laser causes electrical disturbances that make you reset the board. I see you use an Arduino UNO clone, some of them are not so good in handling electromagnetic disturbs. Many people have solved all their problems by simply buying an original arduino board.

**Comment by arkypita** [comment]
I suggest also an opto-insulator on pin 11

**Comment by arkypita** [comment]
Let me know further updates to your issue.

**Comment by mdarpamex** [comment]
i bought an optoinsulator and seems to be working properly, but its output courrent is too low and when is connectet to controller laser pin voltate drop from 5v to 1.2v. 
I waiting a new component (a simply level shifter) to have a correct input voltage on laser. 
As soon as it arrives and I test it, I'll write you if it worked. Meanwhile I thank you for the suggestions, it seems to be going in the right direction

**Comment by mdarpamex** [comment]
With level shifter not working, but i build this circuit and works:

![image](https://github.com/arkypita/LaserGRBL/assets/127768744/60e6500c-afd7-4037-8526-3dd11e664d8e)

I need duplicate schema because this circuit invert signal

**Comment by arkypita** [comment]
That's great!
