### ISSUE TITLE
Window Setting Request.

### ISSUE THREAD

**Issue by StuartB4** [arkypita/LaserGRBL#212]
Hi Arkypita.
Just wondered if it would be possible to add an On / Off option in the Settings to keep LaserGRBL's Window always on top. So it stays on top of any other windows.

**Comment by arkypita** [comment]
I don't like always on top but ok... i can add it as a flag

**Comment by StuartB4** [comment]
Ok, thanks very much.

**Comment by arkypita** [comment]
I have tried to implement it quickly on mainform but it also require to change all the form to be "always on top" otherwise LaserGRBL dialog go under mainform and became not usable.
Since it require some wide changes in many form file I will delay this feature when I finish other works.

**Comment by StuartB4** [comment]
Ok thats fine.
If it ends up being a problem for the rest of the program then it does not matter if you don't implement it.
It was just something I thought about, but may be I would be the only one to use it. I know a lot of people that don't like windows that you have to minimise to see other windows underneath.
