### ISSUE TITLE
Show midle before Laser 

### ISSUE THREAD

**Issue by JPVN** [arkypita/LaserGRBL#213]
Hi at all

Thanks for the programm!

I would like to set a custom botton how shows me the middle of the image to laser. If i can show the middle of the opened project it will be easier to pose the wood. Can you help me?

Thank you.

Best Regard JPVN

**Comment by arkypita** [comment]
It is possible to move along the engraving border, not the middle.
http://lasergrbl.com/it/usage/custom-buttons/

In future i think to add some math interpretation ( + x - / ) to allow to compute different position other than left, right, top, bottom, width, height

**Comment by StuartB4** [comment]
If you know the size of the image you are burning you can just use the lef/right/up/down and diagonal arrows to position the laser in the middle of the image on screen.
The laser will then move to the middle, then you can place your work piece under the laser and it will be over the middle.

**Comment by arkypita** [comment]
try [v2.8.31](https://github.com/arkypita/LaserGRBL/releases/tag/v2.8.31)

**Comment by JPVN** [comment]
It works! Very good. Thank you!

**Comment by arkypita** [comment]
Good!
