### ISSUE TITLE
ENGRAVING POWER AND SPEED

### ISSUE THREAD

**Issue by 10Brutus10** [arkypita/LaserGRBL#2151]
**Describe the bug**
After loading a image (in mode Vectorize), in the target image pop-up menu it is possible to configure speed and power but after creating the job and saving it, if I check manually the .nc file I see that the power are the maximum of the machine ($30). 

**Expected behavior**
The power should be the one in the database or at least configurable by hand like the speed.

**To Reproduce**
Load image in vectorize mode: 
![image](https://github.com/arkypita/LaserGRBL/assets/93826205/af6e0f03-07f3-4a71-bf56-fbca7d19ecdc)

Then I select the defined values in database: 
![image](https://github.com/arkypita/LaserGRBL/assets/93826205/1f63dbfb-8c3e-4d00-93cc-e94fcbdb2a3c)

And save the job (advanced) 
![image](https://github.com/arkypita/LaserGRBL/assets/93826205/9e9516a0-53e8-474d-bfd4-cbbc1a29f82c)

If the job is opened with an test editor, it will display:
  (In this case, the maximum power is $30 = 1000)
![image](https://github.com/arkypita/LaserGRBL/assets/93826205/f43dfec5-1851-414b-a32b-d0bae970430d)

**Hardware and software configuration:**
 - Windows 11
 - Engraver CNC3018 pro
 - LaserGRBL v5.4.0

**Additional context**
Also if two differents images are loaded and for example for one of then the option of filling is selected with folling settings: 
![image](https://github.com/arkypita/LaserGRBL/assets/93826205/7f3d9414-7bdf-4575-b69a-791f5b1f7f76)

In the .nc file will only have power at S1000 and speed at F500:
![image](https://github.com/arkypita/LaserGRBL/assets/93826205/dfb2ca6d-3a48-4d24-9c0f-d5e4fd8edb67)
![image](https://github.com/arkypita/LaserGRBL/assets/93826205/239bac12-0eac-42ca-a32f-0f3f551600ca)

**Comment by arkypita** [comment]
The behavior you show is symptoms of "Support hardware PWM" flag disabled in your LaserGRBL configuration, please check for it.
