### ISSUE TITLE
Survey?

### ISSUE THREAD

**Issue by e6910** [arkypita/LaserGRBL#222]
I think it would be a nice idea to share what hardware we are using LaserGrbl to control. We can share, not only issues and solutions on the software side, but also on the hardware side, being that we are mostly using DIY hardware.

What do you think? Does it take it too far from your excellent tool?

Marino

**Comment by arkypita** [comment]
I agree and I like the idea. I also am curious about different kinds of machine using LaserGRBL (photo and description of how they are built if DIY).

**Comment by e6910** [comment]
I'' try to post about my setup tomorrow at the latest.

Marino

**Comment by Effer** [comment]
What about a page in the wiki?
A table should fit well.

**Comment by arkypita** [comment]
no one?
