### ISSUE TITLE
translation error

### ISSUE THREAD

**Issue by Defaezer** [arkypita/LaserGRBL#2248]
Not really a bug, but a translation error, in Dutch "safe" is translated as "redden" but the correct translation is "opslaan".
"redden"  means "rescuing"

**Comment by StuartB4** [comment]
I think you mean save, not safe.

**Comment by Defaezer** [comment]
I made the same translation error ;-).

Yes i mean save. 
Save = Opslaan (in Dutch)

**Comment by arkypita** [comment]
fixed in v7.5.2
