### ISSUE TITLE
Shape Outline

### ISSUE THREAD

**Issue by DomStrict** [arkypita/LaserGRBL#229]
I'm sure it's possible but I can't find the functionality withing LaserGRBL, could someone let me know if burning the outline of a solid shape is available and if so how to set the software to do it.

Many Thanks

**Comment by hk89** [comment]
+1

**Comment by DomStrict** [comment]
I think it may be the vectorize setting, I hope to test this today and will post again.

**Comment by StuartB4** [comment]
Yes, thats right.

Select your image.
![untitled1](https://user-images.githubusercontent.com/16980026/34339240-77955098-e969-11e7-8ff2-04c50c513c3d.jpg)

In the Filling drop down menu select None. Then click Next.
![untitled2](https://user-images.githubusercontent.com/16980026/34339244-7c50781a-e969-11e7-9373-0bda184dc559.jpg)

Change any settings you need to here and click Create.
![untitled3](https://user-images.githubusercontent.com/16980026/34339245-804e9a1e-e969-11e7-985f-196fd72254d3.jpg)

Run the program.
![untitled4](https://user-images.githubusercontent.com/16980026/34339247-84d9c798-e969-11e7-932e-60663a235818.jpg)

**Comment by hk89** [comment]
I thought you meant a border of an engraved raster!

**Comment by DomStrict** [comment]
Thanks Stuart
