### ISSUE TITLE
Laser ON/OFF (M3/M5) dont work?

### ISSUE THREAD

**Issue by Ch3fk0ch88** [arkypita/LaserGRBL#23]
Hi, i trie to engrave something like this:
![unbenannt](https://cloud.githubusercontent.com/assets/24894320/24326210/d3207d0e-11a9-11e7-88f7-e6ca5c635885.png)
But the result looks like this:
![file_000](https://cloud.githubusercontent.com/assets/24894320/24326216/edb18d7a-11a9-11e7-8f66-e709e643875a.jpeg)
I testet the command m3 and m5 and the laser goes on and off.

**Comment by arkypita** [comment]
LaserGRBL use "S command" to reproduce pure black or white image as well as greyscale image.
"S command" control power modulation: the ability of arduino to generate a PWM signal that control the instant power of laser by switching it very fast through its driver "TTL" pin (M3/M5 could not switch laser so fast).

Indeed, to engrave an image composed only by the colors black and white would suffice the M3 and M5 commands, but to take full advantage of laser potential, the PWM modulation is really important.

**Comment by arkypita** [comment]
Please look at those link to read about power modulation and how to activate in your board.
http://blog.protoneer.co.nz/grbls-pwm-functionality-how-to-control-a-laser-or-variable-speed-spindle/
https://github.com/gnea/grbl/wiki/Connecting-Grbl#grbls-pins (PWM use pin 11)

How to modify driver to support laser power modulation:
https://forum.arduino.cc/index.php?topic=192733.0
https://forum.allaboutcircuits.com/threads/ttl-modulated-driver-for-laser.31275/
http://forums.reprap.org/read.php?133,703931

In addition version 1.1 grbl has added an important new feature for those who use the laser, which is precisely the "laser mode". To read anything more informed about it here:
https://github.com/gnea/grbl/wiki/Grbl-v1.1-Laser-Mode#laser-mode-overview

If you follow my instructions and you will activate the laser power modulation you will find a tool much more useful than what you have now.

Best regards

**Comment by Ch3fk0ch88** [comment]
Hi,
thanks. 
at the moment i only can turn the laser on and off (have to reasearch on which way i can add a pwm inkl so DDL)

**Comment by arkypita** [comment]
Maybe I could add a config switch for who does not have PWM ability that replace all S command with M3/M5 command based on threshold. I added it on dev roadmap.

**Comment by Ch3fk0ch88** [comment]
Ok, thanks.

**Comment by Ch3fk0ch88** [comment]
So,
i tried to use an PWM like this:
![laser_driver](https://cloud.githubusercontent.com/assets/24894320/24336236/a3f36cc0-128b-11e7-803e-a484075a0df2.png)
When i laser something it looks like it works (a bit).
But:
1. I dont get the full power
2. I cant enable the laser, only when it "draw something" it goes on. I cant turn it on manually to focus the laser for example.

(Just for Info)

**Comment by arkypita** [comment]
N° 1
You can not get full power even if you connect the control pin to fixed +5V?
S255 must produce a PWM modulation of 100% time +5V out of pin 11, so it is equivalent to a +5V when you issue a S255 command.

I suppose you don't have an oscilloscope to test signal on D11 but you could try to do some diagnoses with a led+resistor on D11, and with a multimeter on transistor Vce to see if you loose some power on transistor.

Also remove 10uF capacitor near Laser Diode. PWM control need to be fast in on/off operation, and capacitor add charging/discharging times when transistor open/close to ground.

P.s. i usually prefer MOSFET as switch when i design PWM circuit, but transistor could be ok too.

N° 2
https://github.com/gnea/grbl/issues/72
https://github.com/arkypita/LaserGRBL/issues/19

**Comment by Ch3fk0ch88** [comment]
Hi, no i dont have a oscilloscope.
When i connect the E3055 to D12 and disable #define VARIABLE_SPINDLE than i get full power.

I anyway want to test a MOSFET or a 555 timer as next step, greetings.

**Comment by arkypita** [comment]
Hi! Any news? Did you get it working with full power?

**Comment by Ch3fk0ch88** [comment]
Hi, 
I have not ordered the things yet.
I wait to make a bigger order cause of the shipping costs (shipping is more expensive than the part itself^^)

**Comment by arkypita** [comment]
I know, it's a common problem. 

By the way I don't know if LM317 could be easly used in a TTL circuit.
http://laserpointerforums.com/f67/pwm-ttl-controlled-driver-56027.html

Maybe it's easier to buy a ready laser driver with ttl like this one: http://www.ebay.co.uk/itm/12V-TTL-200mW-To-2W-445nm-450nm-Laser-Diode-LD-Power-Supply-Driver-Board-/322453276000?hash=item4b13b68560:g:a2UAAOSwhQhYyCzg

**Comment by arkypita** [comment]
In these days I made a version that allows to use LaserGRBL on machines that do not have the PWM control. I have not had a chance to test it properly, but if you want to try it and tell me if it works you can download it from here: https://github.com/arkypita/LaserGRBL/releases/tag/v2.5.1-pre

**Comment by Ch3fk0ch88** [comment]
I will test it net weekend.

Greetings.

**Comment by Ch3fk0ch88** [comment]
Hi,
i testet the Version.
But why i can only use Vectoring and this 1bit thing when i disable the PWM Support?
With this i 1 Bit it all time looks a but broken.
![logo](https://cloud.githubusercontent.com/assets/24894320/24808361/aced9a9c-1bbb-11e7-9711-e6dcec24ccc1.jpg)
![unbenannt](https://cloud.githubusercontent.com/assets/24894320/24808363/ae04eac0-1bbb-11e7-9cce-ccdac5ccfb04.png)
![file_000](https://cloud.githubusercontent.com/assets/24894320/24808383/be781bac-1bbb-11e7-8162-10da2a970bc7.jpeg)

Greetings.

**Comment by arkypita** [comment]
The function called "Line To Line line tracing" is used to produce grayscale images modulating power, so it cannot be used for hardware setup without power modulation. So I have removed the option for PWM-less hardware.

1 bit dithering try to reproduce eye grayscales effect by creating a black points map. The dithering alghoritm could add some artifacts when white pixels are not "pure white".

http://lasergrbl.com/usage/raster-image-import/dithering-tool/
http://codegolf.stackexchange.com/questions/26554/dither-a-grayscale-image

But... your image is not a grayscale! Is a pure black logo. The best result for pure black logos is obtained with vectorization + filling. Try this combination, result will be OK!

**Comment by joncarns** [comment]
I have a similar issue, I have been able to connect. I can move the steppers however laser stays on from start to finish. if its plugged in the computer it is on regardless of having lasergrbl started or not. ive adjusted $32=1. unchecked the pwm box. didnt have this issue until i uploaded grbl v1.1.hex but i had no connectivity before that. ive ran the laser with t2laser however subscription issues rendered my computer without a hardware number. ive tried S0 m5

**Comment by StuartB4** [comment]
Hi joncarns. 
What setup do you have?
Which laser, laser driver, Arduino Type etc, 
Do you have any pics of the wiring / connections of the machine.

**Comment by facumaster** [comment]
hello, im using versión 3.0.10 and i cant make laser work with M3
ive already checked pin D11 and it gives 5v with M3 command, but when i plug PWM laser's pin, it does nothing. 
movements work alright, very smootly
any ideas?

![123](https://user-images.githubusercontent.com/50121402/56932594-c69ab600-6aba-11e9-938b-97b827aafd83.jpg)

![345](https://user-images.githubusercontent.com/50121402/56932607-cdc1c400-6aba-11e9-8a9e-422e42e16297.jpg)

**Comment by StuartB4** [comment]
@facumaster

![Untitle7](https://user-images.githubusercontent.com/16980026/56934499-088c2200-6ae4-11e9-8fc2-4a131ce04bf7.jpg)

**Comment by facumaster** [comment]
yes i do, ive tried the pulldown resistor solution aswell (1k ohm), but no luck.

**Comment by Emoslapper** [comment]
G'day All,

@StuartB4 I have read in other responses that you have a dvd\cd setup as do and I.
And I am running a Arduino Uno + CNC Shield V3 on the Z+ Stop for laser on, just using a 200-250mW 650nm Laser. So my question is:
Is it possible to run a PWM setup on my system?
I have the PWM ticketed on but when I use m4 the laser just does not turn on and on m3 it works.

Cheers

**Comment by StuartB4** [comment]
It should work as it is providing you laser driver is PWM/TTL compatible. 
Which laser driver do you have?
Which version of GRBL do you have?

**Comment by joncarns** [comment]
On mine the difference makes was on the actual board of the laser. I
believe there's a video on YouTube but you need to pull off the wires going
to the last from the board and under that will be 3 outputs. OOO. If yours
is in the position like this OO- then switch it to -OO
sorry for the poor description. If that didn't help I can find the links
that describe it much better

**Comment by Emoslapper** [comment]
Ummm so i am sort of not using one..... could this be the root cause??

I have the Arduino Uno + CNC Shield V3 to a relay to the laser......

**Comment by StuartB4** [comment]
Yes. You can make it work though by using a laser driver like this. 
![Untitled](https://user-images.githubusercontent.com/16980026/67812466-2b00f700-fa97-11e9-9c59-084a5172a7b8.jpg)
Available on eBay at various prices. 

The top red circle is the Laser Voltage Adjuster, the bottom one is the Laser Current Adjuster.

The Laser Tube connections top left are for a normal 2 wire laser.

The bottom right connector is where you connect 1 wire from Z+ or Z- on the CNC Shield,
and 1 wire from a Ground pin on the shield. The Z+ and Z- are both connected together on the shield so it does'nt matter which one you use, the ground pin can be any of the row of pins in the row next to it.

**Comment by Emoslapper** [comment]
Thanks for the quick reply! Ill keep you posted once the driver arrives in the mail ;)
Also wow what a great setup, nice work @StuartB4 

Thanks again

**Comment by WelshHighlander** [comment]
> Maybe I could add a config switch for who does not have PWM ability that replace all S command with M3/M5 command based on threshold. I added it on dev roadmap.

I spent some years engineering industrial CNC controls but never used a consumer CNC machine.  I bought a Creality Falcon 10w and expected laser controls to work in a standard way.  Well, no.

Sxxx/M3/M4/M5 should work like this on any CNC with a non-rotating cutting tool (e.g. cutting jet, arc cutter, etc):

M3 = spindle on (laser on)
M5 = spindle off (laser off)
M4 = M3, or M4 disabled (common for non-rotating cutting tools)
Sxxx = speed (in our case laser power)

In a real CNC machine, S commands and the M3/M4/M5 commands are independent.    You should be able to set the power (Sxxx) one time and then turn the laser on and off with G3/G5 without ever having to issue another S command.  In response to G3, the laser operates at the power specified in the last S command.  This way, the gcode in lasergrbl would operate in a standard way, it would greatly simplify (and shrink) the generated gcode, it would simplify gcode editing.  Might you fix this any time soon?

Is the lasergrbl application in the Creality Falcon 10w open source?  I can fix this myself if I have sufficient access.  All the electronic hardware is in place in the Creality Falcon, so fixing it in the electronics is not the way, for a number of reasons.
