### ISSUE TITLE
Custom button - Low light intensity

### ISSUE THREAD

**Issue by DomStrict** [arkypita/LaserGRBL#230]
Does anyone have the code for a custom button to turn the laser on low light intensity so I can identify where the laser is positioned?

Or if the functionality already exists in the software please let me know.

Thanks in advance.

**Comment by StuartB4** [comment]
Just type M3 in your custom button to switch laser on and another button with M5 to switch it off.
I think M3 S50 for example should switch the laser on with a power of 50.
I dont have a laser at the minute so I can't test it, need a new laser diode.

**Comment by DomStrict** [comment]
Thanks for the info, I will test tomorrow and let you know how it goes.

**Comment by abatinxs** [comment]
Take a new button and paste :
G01 F1000
M03 S1

**Comment by DomStrict** [comment]
Fantastic:

The code that works for low laser intensity on for me is:

G01 F1000
M3 S10

To turn it off:

M5

Thanks everyone for your help.

**Comment by DomStrict** [comment]
![lasergrbl screenshot](https://user-images.githubusercontent.com/34807231/34357033-550f8c14-ea3b-11e7-86bc-896885f467c1.jpg)

My New-look desktop
