### ISSUE TITLE
latest download has malware

### ISSUE THREAD

**Issue by andyp60** [arkypita/LaserGRBL#235]
Trojan:Win32/Fuerboos.C!cl as identified by windows defender

**Comment by arkypita** [comment]
1) LaserGRBL [is clean](https://www.virustotal.com/#/file/85744da1cff4570e1fba26fe5589f15ee52f0cdea8e3bf9daf8323b63aad84e2/detection)
2) Windows defender is worst antivirus ever
3) [False positive](https://www.google.it/search?client=opera&q=Fuerboos.C+windows+defender+false+positive&sourceid=opera&ie=UTF-8&oe=UTF-8) exist (always)

**Comment by arkypita** [comment]
I have submitted latest install.exe to windows defender false positive service and they say "No malware detected" so please try to update your AV definition.

![image](https://user-images.githubusercontent.com/8782035/34381625-050cb578-eb0a-11e7-98ad-be899c2b1c6a.png)

**Comment by ermtl** [comment]
A good way to test each new release for false positives is to send it to https://virustotal.com as this will check against 68 antivirus engines

**Comment by hayttle** [comment]
the same with me.

**Comment by StuartB4** [comment]
No problems here with latest version, or any earlier version.
I've used the free version of Comodo Internet Security for years now and would highly recommend it.
It just works.
