### ISSUE TITLE
Allow GRBL config import when not connected for offline GCODE generation

### ISSUE THREAD

**Issue by laufersteppenwolf** [arkypita/LaserGRBL#2355]
Would it be possible to allow the import of GRBL configurations when not connected to an actual machine?

Because then you could use one PC on the machine for doing the work, and on a separate PC you could prepare the GCODE files/Projects with the actual configurations of the machine (for input sanity checks, duration calculation,...)

**Comment by arkypita** [comment]
Menu grbl, settings, emulator (first tab page)
LaserGRBL contains a grbl emulator you can connect to, and able to store configuration

**Comment by laufersteppenwolf** [comment]
Thank you, I did not know that nor find that while searching for a way...
