### ISSUE TITLE
Help! New user. Laser engraving blank spaces!

### ISSUE THREAD

**Issue by ian1313** [arkypita/LaserGRBL#237]
![unnamed](https://user-images.githubusercontent.com/34924087/34423071-c4c2a3ec-ebbd-11e7-841b-60683f1f12b3.jpg)

This should say "BB - 63" but the laser is engraving the blank spaces!

**Comment by hk89** [comment]
If you were using LaserGRBL before and it was producing good results then it could be a problem with your new laser driver. Try removing the signal wire coming out from the arduino and see of the laser is still on.
