### ISSUE TITLE
5 Seconds Countdown with anoying beep sound

### ISSUE THREAD

**Issue by HeldHannes** [arkypita/LaserGRBL#2373]
Hi,

Intro:
My computer crashed (not because of LASERGRBL) and I had to get a new one,
so I thought - why not update LASERGRBL to a newer version (~6.2.???).

Plot:
I understand the idea of trying to be as safe as one can get, but I do not want to be treated like a child.
I know that a laser is a dangerous weapon of mass destruction, but I don't like to reminded about it before every operation.
I tried to shut of every alarm and sound of LASERGRBL, but it still beeps when I press START.

Solution-request:
I'd very like to be able to disable the 5-sec-warning and especially the annoying sound that it is producing.

Thank you very much.

**Comment by Hostaler** [comment]
In options 

![20240928_140151](https://github.com/user-attachments/assets/1c4dba45-6b6f-4b3b-bc8a-68ee806077c3)

**Comment by HeldHannes** [comment]
Thanks,

my options-tab looks like:
![Option-Bug](https://github.com/user-attachments/assets/f6bc1f52-561c-4faf-8b86-ed6c902838df)

**Comment by HeldHannes** [comment]
Is this a language-setting-issue? 
or is my version already outdated?

**Comment by HeldHannes** [comment]
Sound-tab looks OK:

![SoundTab](https://github.com/user-attachments/assets/a078132d-5d25-4513-ab20-68b300c8561d)

**Comment by HeldHannes** [comment]
Dark-Design-Problem

I can check and see the text only on light design.

![lightDesigntab](https://github.com/user-attachments/assets/a648ac2a-de67-4759-8307-009931074f30)

**Comment by HeldHannes** [comment]
Thanks.
