### ISSUE TITLE
limit switch button

### ISSUE THREAD

**Issue by cecconilorenzo** [arkypita/LaserGRBL#238]
Hi, I have a problem with the limit switches, nothing happens if the button is pressed and the motor keeps going. should you put some settings to make them work?
thank you.

**Comment by e6910** [comment]
Where did you connect the limit switches to? Did you make any changes the grbl configuration?

**Comment by cecconilorenzo** [comment]
hello, I am limit switch I have connected to the cnc shield, I did not give any changes to the configuration grbl.

**Comment by cecconilorenzo** [comment]
ok thanks, solved.

**Comment by e6910** [comment]
Just as I was going to write a long post on th subject. Glad you solved it.

Make sure you go over setting $21 up to $27 as they control homing and hard limits.
