### ISSUE TITLE
custom buttons with 2.5w laser

### ISSUE THREAD

**Issue by bandguy335** [arkypita/LaserGRBL#240]
I recently upgraded to a 2.5w laser diode, and the custom buttons I made to turn the laser on (M3) and turn the laser off (M5) don't actually turn the laser on or turn it off, how do I fix this problem?

**Comment by StuartB4** [comment]
Have you tried the command with the "S" command.
Like this:
M3 S255
to switch Laser on at full power, or a lower number for lower laser power.

**Comment by bandguy335** [comment]
Thank you that worked, by chance do you know how I can set the laser power in the newest update of this program, still using my 2.5w laser diode.
