### ISSUE TITLE
New please help. Image shifting

### ISSUE THREAD

**Issue by dtyers** [arkypita/LaserGRBL#241]
1Z0
![20180103_082731_hdr](https://user-images.githubusercontent.com/35068310/34523232-8e2c7fe6-f064-11e7-93dc-fbe367882873.jpg)
  Hi my names Dan. I am new to laser engraving and am trying to get started engraving photos. I have run a couple of tests an got settings close to where I think the will work, but I have a problem with the image becoming shifted part way through running. I have included some pictures. One is of the test pattern and one is of two errors in gcode. I have had the happen in more than one occasion and with different images. Not sure what is going on or how to prevent the problem from reoccurring during a project in the future. Any help or advice would be greatly appreciated. Thanks
![20180103_082731_hdr](https://user-images.githubusercontent.com/35068310/34522927-25e39650-f063-11e7-923c-13cb57fb08a1.)
![20180103_082227_hdr](https://user-images.githubusercontent.com/35068310/34522928-260cff9a-f063-11e7-989b-c3109762b764.jpg)

**Comment by arkypita** [comment]
Look like https://github.com/arkypita/LaserGRBL/issues/24

**Comment by arkypita** [comment]
Causes and solutions: http://lasergrbl.com/faq/

**Comment by dtyers** [comment]
Thanks for the help
