### ISSUE TITLE
Laser Power When Code is Running 

### ISSUE THREAD

**Issue by bandguy335** [arkypita/LaserGRBL#242]
I had recently purchased a 2.5w laser diode, but for some projects I don't need the laser power to be full blast, how am I able to turn the laser power up or down when needed?

**Comment by arkypita** [comment]
![image](https://user-images.githubusercontent.com/8782035/34556825-4dc731a6-f138-11e7-88bb-2ac148e90bc1.png)

S-MAX control the max power

**Comment by arkypita** [comment]
also

![image](https://user-images.githubusercontent.com/8782035/34600814-ab9f5ecc-f1f9-11e7-8a74-4c4b82c00ee4.png)
