### ISSUE TITLE
Costum start/stop command

### ISSUE THREAD

**Issue by basti30** [arkypita/LaserGRBL#243]
Love your software and use it quite much. One improvments came to my mind while using it extensively.

Costum laser start/stop commands: So you can eg. add a little delay after switching the laser on or when you use a servo to lower a pencil.
Example: 
M3 S1000 
G4 P0.3

Could be used to lower a Z-Axis too:
M3 S1000
G1 Z-0.5

Currently I'm using search and replace in Notepad++ for this. Would be great if this can be integrated into your amazing software.

Thanks for your great work.

**Comment by arkypita** [comment]
Some other user ask me some changes to make it compatible with pen plotter. Maybe in a future version I will add something like this.
