### ISSUE TITLE
New features

### ISSUE THREAD

**Issue by e6910** [arkypita/LaserGRBL#245]
I might be missing something here, but if not, I think these should make nice new features:

a) Possibility of using decimal numbers for both size and offsets

b) Option to keep original dimension of imported image (if and only if, resolution is stored inside image's EXIF information).

I felt the need for these, in order to be able to engrave and cut in different sessions and materials pieces for something I'm working on.

Marino

**Comment by arkypita** [comment]
I agree with point A, and this goes together with improvement in small image engraving.

With B it conflict with something LaserGRBL is now doing, that is to remember one of the two dimension of the previous engraved pictures and scale the new engraving to that size. It's ok to add this feature, but recallable from a button.
