### ISSUE TITLE
Your latest update created problems

### ISSUE THREAD

**Issue by BoxJoint24** [arkypita/LaserGRBL#2470]
**Describe the bug**
I have been using Laser GRBL for several years and have had great results mainly marking on wood surfaces. After installing the latest firmware update, things went crazy. A project will start correctly, but at some point it starts producing gibberish like images and will shift parts of a line of text to the right. 
Any suggestions?
![Example1](https://github.com/user-attachments/assets/18349fa6-0142-445a-bd8f-d2cfcf46ddae)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Hardware and software configuration (please complete the following information):**
 - Windows version     11
 - Engraver brand and model    Not sure of brand or model  3.5w
 - Grbl version (i.e. 0.9j, 1.1f)
 - LaserGRBL version                      V7.14.0

**Additional context**

**Comment by BoxJoint24** [comment]
Here is another example of the shift. I would like to know how to fix this problem.
![IMG_5833](https://github.com/user-attachments/assets/c6b0f2a0-ee30-4e21-808a-c6cb112932b0)

**Comment by arkypita** [comment]
You can easly rollback to a previous version: https://github.com/arkypita/LaserGRBL/releases

**Comment by BoxJoint24** [comment]
Thank you for the reply and the suggestion. I suppose I'll have to remove the latest version first. Before I do that , I need to determine that the laser itself is not failing.

**Comment by arkypita** [comment]
Remove the opd one is not really necessary, but if you want you can do it. Im ny opinion it is not a LaserGRBL issue, but it is your hardware fault. I say that, because none of the changes I did to LaserGRBL can cause your issue. However, feel free to test with other versions and let me know.

**Comment by BoxJoint24** [comment]
Thanks for your help. I am having trouble finding the download for v13. Can you send me the link please?Mike
    On Monday, December 23, 2024 at 10:08:41 AM EST, arkypita ***@***.***> wrote:  
 
 


Remove the opd one is not really necessary, but if you want you can do it. Im ny opinion it is not a LaserGRBL issue, but it is your hardware fault. I say that, because none of the changes I did to LaserGRBL can cause your issue. However, feel free to test with other versions and let me know.

**Comment by arkypita** [comment]
https://github.com/arkypita/LaserGRBL/releases/download/v7.13.0/install.exe

**Comment by BoxJoint24** [comment]
Your help is appreciated.I think I may have changed some settings in the GRBL config. Now I am getting mirror images.Can you send me an image of the default config settings so I can get back to a known starting point?I am sorry to be of so much trouble.Thank You so much,Mike
    On Monday, December 23, 2024 at 11:06:22 AM EST, arkypita ***@***.***> wrote:  
 
 


https://github.com/arkypita/LaserGRBL/releases/download/v7.13.0/install.exe

**Comment by BoxJoint24** [comment]
I installed v7.13.0 and it appears to have cleared up the problem. I will let you know if anything changes.Thanks so much for your help.Mike Sweeney,A loyal subscriber
    On Monday, December 23, 2024 at 11:06:22 AM EST, arkypita ***@***.***> wrote:  
 
 


https://github.com/arkypita/LaserGRBL/releases/download/v7.13.0/install.exe
