### ISSUE TITLE
LaserRGBL id disconected to Arduino UNO or Arduino Mega

### ISSUE THREAD

**Issue by Yanabalts** [arkypita/LaserGRBL#248]
[1sessionlog.txt](https://github.com/arkypita/LaserGRBL/files/1629821/1sessionlog.txt)
Hello Dear @arkypita!

I try do connect LaserRGBD to Arduino Mega2560 (also ussed Arduino UNO - same problem)

What I see:
Disconnected>Connecting>Diconnected

It looks like that https://pastenow.ru/2HUJB

I Also add session log file in attachment.

Could you kindly tell me what I do wrong. I would really love to use you program.

**Comment by StuartB4** [comment]
Change the BAUD Rate to 115200 in the drop down menu. Then click Connect.
![untitled](https://user-images.githubusercontent.com/16980026/34923216-d2efd3cc-f991-11e7-976c-4fdf16a2748b.jpg)

**Comment by arkypita** [comment]
@Yanabalts What version of grbl have you flashed on your arduino?

**Comment by Yanabalts** [comment]
Thank you very much! Right after I added RGBL to my Arduino It was connected.
Thank you!
Could you tell me also where can I find PINS for LaserGRBL working with Arduino Uno. What pins are for laser?

**Comment by arkypita** [comment]
Why not [google ](http://lmgtfy.com/?q=grbl+pinout) for that?

**Comment by lucasssimao** [comment]
Hello i having the same problem but i dontknow how to flash the arduino, i've tried to change the BAUD rate but doesn't work, could you helpme pls ? tks

**Comment by arkypita** [comment]
@lucasssimao 

If you search on google you can find what you want.
https://github.com/gnea/grbl/wiki/Flashing-Grbl-to-an-Arduino

Please note:
- grbl is not provided my me
- grbl official site: https://github.com/gnea/grbl/
- flashing a different firmware to your eleksmaker can break your engraver, if you don't know how to do that safely ask for support to http://eleksforum.eleksmaker.com
