### ISSUE TITLE
New parameters for better quality engravings

### ISSUE THREAD

**Issue by ermtl** [arkypita/LaserGRBL#250]
When using LaserGRBL with a cheap (wobbly) laser engraver, the border must be done at low speed to prevent it from being awfully distorted while the filling can be done much faster (even more so when the laser is more powerful). This is addressed with the different "filling speed" and "Border Speed" parameters.
However, when the speed difference is too big, the borders are over-burnt as the S MAX setting applies to both filling & border. Adding a different set of settings for these 2 operations would make sense.

Also, as a high acceleration (GRBL parameters $120 and $121) makes things much worse, being able to scale the value for both X & Y when drawing the borders would result in a much more precise border without slowing down the filling operation.

Another little change would be to reorder "Border Speed" and "Filling speed" parameters, as the filling is done before the border

here is an example of what the modified parameter screen could look like:
![image](https://user-images.githubusercontent.com/10635964/34943013-ce8937f2-f9c7-11e7-877a-4ac8dbcfe172.png)

**Comment by arkypita** [comment]
Is a good suggestion but make the interface more complicated. My goal is to keep the sw as simple as possible, for a newbie all this option can confuse.

**Comment by 3ditguy** [comment]
I too would like this feature, could you have an "advanced" toggle button
to show/hide some additional fields?
