### ISSUE TITLE
Arduino Mega

### ISSUE THREAD

**Issue by robin180** [arkypita/LaserGRBL#251]
Hello, can I also run Laser Grbl with an Arduino Mega?

When connecting with only the Arduino board, I'm immediately in the status alarm.

**Comment by SerialJ** [comment]
I built a diode laser machine. laser grbl + arduino uno .Fast machine 3000 MM / min, speed 3000. Begin burn raster motion jo flawless super. Contour movement freezes, stops diode goes.Gcode generation aspire.
I think there is a lot of counting, arduino does not bust.
thank you in advance for your help
