### ISSUE TITLE
losing 0

### ISSUE THREAD

**Issue by rkontz** [arkypita/LaserGRBL#252]
I put a new board on my laser and now its start cutting fine but have way through the program it changes it 0 point 
![20180120_070549](https://user-images.githubusercontent.com/35647128/35190647-e9b9ef86-fe2b-11e7-8906-8356a1476c80.jpg)
![20180120_215750](https://user-images.githubusercontent.com/35647128/35190691-e5ae5bd8-fe2c-11e7-9e7d-6221560e8d76.jpg)

![20180120_070600](https://user-images.githubusercontent.com/35647128/35190652-f1562160-fe2b-11e7-9545-327eca24cd71.jpg)

**Comment by arkypita** [comment]
You have poor quality arduino clone or electrical noise on serial line.

http://lasergrbl.com/faq/
#24
#55
#81
#118
#241

**Comment by rkontz** [comment]
Thank you . I had mounted the board on the laser . So i took it off an now seens to be running  go . It been running for 6 hour with no trouble



Happy Connecting. Sent from my Sprint Samsung Galaxy S® 5 Sport


-------- Original message --------
