### ISSUE TITLE
Enhancement, can we have the "S" current value on screen where the x-y values are

### ISSUE THREAD

**Issue by sinfocomp** [arkypita/LaserGRBL#253]
it would be nice to see the current laser powe on screen

**Comment by arkypita** [comment]
added to roadmap
must check if it is possible (aka reported by grbl realtime status message)

**Comment by nico48** [comment]
How do you install this program?  I have linux suze, and i cannot see installation program...where did you put that? ( i have googled all morning to figure it out myself....)

**Comment by arkypita** [comment]
First @nico48 please do not post haphazard (at random). This thread is talking about enhancement of showing S value on screen. Your question is not related to this, so open a different issue.

Second LaserGRBL is Windows only.

**Comment by nico48** [comment]
ok my bad, and the last remark explains a lot thanks !!

**Comment by arkypita** [comment]
@nico you are welcome
For run LaserGRBL on linux read this post: https://github.com/arkypita/LaserGRBL/issues/5
