### ISSUE TITLE
Laser to weak?

### ISSUE THREAD

**Issue by beckfly** [arkypita/LaserGRBL#254]
Hello,I'm new here and I have a question about my new Laser engraving mashine.
I have bought an EleksLaser Pro with the size of A3.The Laserpower is 0.5W.
I have assembled everything yesterday and it runs perfect with the software lasergbrl.
Today I have make the first tests.  I have tryed to focused the lence of the laser.Nothings happen.
When the Laser is quite a wihle on a Point,the Laser starts slowly to make a point of the cardboard.
So maybe the laser is to weak or what can I do or change?
Maybe sombody can help?
Michael

**Comment by abatinxs** [comment]
Replace the power in LaserGRBL with S255 to S1000. I had the same witch 3,5W laser.Do this in window with speed (F), commands on  off laser M3/M5 size object and offset.

**Comment by beckfly** [comment]
Hello,
thank you for your help.I have Chance this Settings And now everything Works.
Now i can Start to learn the possibilitis of my machine.
Kind Regards!
Michael

Von meinem iPad gesendet
