### ISSUE TITLE
Idea for quick boundary engraved picture/photo/sign

### ISSUE THREAD

**Issue by abatinxs** [arkypita/LaserGRBL#256]
Arkypita, You think about making a button to determine the boundary work of the laser engrave image?
e.g You have a photo - dimensions: 100x50mm, push a button and laser set small power (S1)  go to corners (100mm forward, 50mm right, 100mm backwards, 50mm left) of photo for better setting material like wood, paper or other.

I have a custom button with my maximum travel work area of the laser

M03 S1
G91X270Y0F4000
G91X0Y450F4000
G1X-270Y0F4000
G1X0Y-450F4000
G1X270Y450F4000
G1X-270Y-450F4000
M05 S1

My custom button is stable, it must change (and laserGRBL must generate) with the dimensions of the load file. I think is a good feature and very useful. You see if you burn a material or an expensive wood table :)

**Comment by vaicekas** [comment]
it's so easy ;)

F7000
M3 S1
G0 X[left] Y[bottom]
G1 X[right]
G1 Y[top]
G1 X[left]
G1 Y[bottom]
G0 X0 Y0
M5
