### ISSUE TITLE
Impossible to eye trace the pointer 

### ISSUE THREAD

**Issue by hk89** [arkypita/LaserGRBL#260]
Hi,

I really find it very hard to see the pointer during a job because it appears to be violet in color with blue lines in the image. A possible solution is to have its color is the color invert of the underlying lines; something similar to the old windows inverted mouse pointer as in the next picture.

**Comment by hk89** [comment]
![mouse-5](https://user-images.githubusercontent.com/24245215/35590555-e8a9a2e4-060f-11e8-8a1e-250c19e14239.jpg)

**Comment by arkypita** [comment]
Thanks @hk89 
I know this technique, i will implement in the next version. Thanks for hint

**Comment by arkypita** [comment]
It is not so easy to XOR drawing in gdi+ context, so i opted to draw cursor a little bigger to improve visibility.
