### ISSUE TITLE
LaserGRBL custom buttons backup...!

### ISSUE THREAD

**Issue by TehseenHasan** [arkypita/LaserGRBL#262]
Please add option to export and import custom buttons with its icons to a file... It will be very helpful when I install LaserGRBL software to another PC...while now I have to re-write custom buttons again with its custom icons every time I re-install software... Actually I'm using LaserGRBL on many computers... Please add this feature... Thanks..!!!

**Comment by arkypita** [comment]
C:\Users\YOUR ACCOUNT\AppData\Roaming\LaserGRBL\CustomButtons.bin contains the data of custom buttons. It is not so easy like an import export but if you copy this file from one pc to another... it work.

**Comment by arkypita** [comment]
[CustomButtons - Copia.bin.gz](https://github.com/arkypita/LaserGRBL/files/1828889/CustomButtons.-.Copia.bin.gz)
