### ISSUE TITLE
have donated the money for the download but no download

### ISSUE THREAD

**Issue by sign-n-gifts** [arkypita/LaserGRBL#265]
we followed the instructions and donated moeny for the opensource download and have not received any download at all.  please let me know how you do it asap

**Comment by StuartB4** [comment]
Go here and download it.
https://github.com/arkypita/LaserGRBL

**Comment by arkypita** [comment]
download from https://github.com/arkypita/LaserGRBL/releases
or http://lasergrbl.com/download/
