### ISSUE TITLE
Show-size command?

### ISSUE THREAD

**Issue by withoutmessage** [arkypita/LaserGRBL#269]
Would it be a way to make a custom button with a command to show the size of the image (the outer frame, so to say).

Many thanks in advance, the software is simple but so robust!

**Comment by arkypita** [comment]
it's so easy ;)

F7000
M3 S1
G0 X[left] Y[bottom]
G1 X[right]
G1 Y[top]
G1 X[left]
G1 Y[bottom]
G0 X0 Y0
M5

**Comment by arkypita** [comment]
Yes, they are variables and custom buttons support math expression with them like [left - 5] or [left + width/2]

The add custom button window show the list of available  variable

**Comment by withoutmessage** [comment]
Fantastic @arkypita
it worked like a charm
