### ISSUE TITLE
out of sync print

### ISSUE THREAD

**Issue by david259** [arkypita/LaserGRBL#270]
I am new to Laser printing and have been using GRBL to print text onto a plaque i have done a number of test runs on plywood and on 1 side of the plaque which ran over the edge  so i readjusted the text and everything was going great till the last line of text . due to it printing line by line from the top all the burns sync up except the last line of the the middle of the word is lowered and looks like a large so should be O
![20180208_135456](https://user-images.githubusercontent.com/36268380/35976654-b3718c52-0cd8-11e8-9bfa-97fae8468c69.jpg)
as you can see there is a line everything on right side is lower then the left how can i fix this  after the thing is done it does a outline of text which is also out of sync 
need this for tomorrow 

Thanks

**Comment by arkypita** [comment]
Look like common problem already documented a lot of time.
#252 #24 #55 #81 #118 #241

Read http://lasergrbl.com/faq/ and look at the end of the page for a sw solution.
