### ISSUE TITLE
minimum laser requirements ?

### ISSUE THREAD

**Issue by papa0urs** [arkypita/LaserGRBL#273]
Hello everyone,
A mega newbie here is starting the laser engraver project... I'm planning to use the laser diode extracted from one of the DVD players. I'm just wondering if this kind of Class 1 laser is enough, or should I get a Class 2 ?

Thank you for your answers !

**Comment by arkypita** [comment]
For engraving leather you need at least 250mW of power, 1W for wood. [Here](http://elabz.com/laser-diode-power-output-based-on-dvd-rrw-specs/) you can find a list of speed vs laser power for DVD burner (not player).

Of course you should build a proper current controlled/limited driver, or your diode will burn immediately if you power it at constant voltage. And of course you should provide a proper heat-sinking and lens focusing system. Focusing is very important for engraving.

Much more simple is to buy a ready to use laser engraving module from ebay/aliexpress.

Be care of your eyes. Direct or reflected rays can blind you instantly.

**Comment by papa0urs** [comment]
Thank you very much for all these precious infos. As it turned out that my 2nd dvd player has a plastic tray, I might try to find a dvd burner. But the entire engraving module seems a good idea too.
