### ISSUE TITLE
Power setting question

### ISSUE THREAD

**Issue by edcasati** [arkypita/LaserGRBL#275]
I'm confused as to the power settings for laser.
Does it go from 0-256, or 0-1024 or what is the range?
What number would be full power?

**Comment by arkypita** [comment]
Hi, the arduino pin 11 used for PWM modulation is 8 bit 0/255 different value.
However grbl is able to use a different virtual range that can be [configured with $30](https://github.com/gnea/grbl/wiki/Grbl-v1.1-Configuration#30---max-spindle-speed-rpm) and will be mapped to 0-255

**Comment by edcasati** [comment]
So the range is set by $30 by the GRBL config.h file, and it seems to be set to 255 by default.
Is there a way to run a startup script in lasergrbl, maybe upon reset, to run some commands, like setting $30, $32 (Laser mode), or other settings that we may want defaulted differently?

**Comment by hk89** [comment]
Please read grbl official documentation https://github.com/gnea/grbl/wiki/Grbl-v1.1-Configuration

It says very clearly:
> $x=val - Save Grbl setting

The $x=val command saves or alters a Grbl setting, which can be done manually by sending this command when connected to Grbl through a serial terminal program, but most Grbl GUIs will do this for you as a user-friendly feature.
