### ISSUE TITLE
cutting a silhouette

### ISSUE THREAD

**Issue by mibiosa** [arkypita/LaserGRBL#278]
Good morning folks :-)
I have a little problem... how can I do with LASER GRBL to draw a silhouette to cut it?
If I have to engrave any image on cardboard (for example) I have no problems, but if I just want to draw the outline of a square to cut it, how should I do?
Thanks in advance for answers :-)
Michelangelo

**Comment by arkypita** [comment]
https://www.youtube.com/watch?v=3aLjCtB2iMo

**Comment by mibiosa** [comment]
Thank you Arkypita! very kind as always :-)

**Comment by arkypita** [comment]
you're welcome, ciao!
