### ISSUE TITLE
Max jog speed related of grbl conf v2.8.36

### ISSUE THREAD

**Issue by aMirMOsavi** [arkypita/LaserGRBL#279]
Hi
Max jog speed set of grbl config but it set the smallest  !
It should be adjusted from the largest 
![2018-02-14 02-03-28 pm by amir](https://user-images.githubusercontent.com/17276809/36199846-09d49e84-1190-11e8-89d5-edfce0cea6c1.jpg)

**Comment by arkypita** [comment]
It use the smallest beetween X and Y because it moves both X and Y, so if i had to choose one of them I thought that is safer to choose the smallest, but it's wrong.

Since the speed is finally limited by grbl it is correct to use the maximum. Thanks for the hint.
