### ISSUE TITLE
I want to translate into another language

### ISSUE THREAD

**Issue by Rost3** [arkypita/LaserGRBL#28]
i translate many things (game/mod) to russian and ukrainian. and want to translate yours programm. but dont know how.

**Comment by arkypita** [comment]
Translation into other languages is widely appreciated.
It is easy and does not require particular skills

Strings are embedded in resource files, with .resx estensions. Here there are a .zip file with latest resx files.
[Resources.zip](https://github.com/arkypita/LaserGRBL/files/909725/Resources.zip)

A good tool for editing resx is called ResEx, and could be downloaded here:
http://resex.codeplex.com/

1) install ResEx
2) unzip resources zip file
3) Launch ResEx and open a base .resx file (not the one .it or .es that are localized)
4) From menu "Tools" select "add culture"
5) Edit strings and save the file

Finally make a new .zip file and send it to me, I will compile a new version adding your languages.

Have a nice day

**Comment by Rost3** [comment]
ok

**Comment by Focus3** [comment]
[Added Slovenian files.zip](https://github.com/arkypita/LaserGRBL/files/2002987/Added.Slovenian.files.zip)

I did my best with the Slovenian translation. Please let me know if there is issues.

Focus3.

**Comment by Mrjavaci** [comment]
> Translation into other languages is widely appreciated.
> It is easy and does not require particular skills
> 
> Strings are embedded in resource files, with .resx estensions. You can find this files inside source code, source can be downloaded by clone/download button in main github page: https://github.com/arkypita/LaserGRBL
> 
> A good tool for editing resx is called ResEx, and could be downloaded here:
> [ResExSetup1.2.zip](https://github.com/arkypita/LaserGRBL/files/909750/ResExSetup1.2.zip)
> 
> 1. install ResEx
> 2. download source
> 3. Launch ResEx and open mains .resx file (not the one .it or .es that are localized) some are in the main folder, some in subfolders, so search for *.resx
> 4. From menu "Tools" select "add culture"
> 5. Edit strings and save the file
> 6. Repeat for each .resx main file
> 
> Finally make a .zip file (of all the new added .resx files) and send it to me, I will compile a new version adding your languages.
> 
> Files involved in translation are:
> 
> * LaserGRBL\ConnectLogForm.resx
> * LaserGRBL\CustomButtonForm.resx
> * LaserGRBL\GrblConfig.resx
> * LaserGRBL\HotkeyManagerForm.resx
> * LaserGRBL\IssueDetectorForm.resx
> * LaserGRBL\JogForm.resx
> * LaserGRBL\MainForm.resx
> * LaserGRBL\PreviewForm.resx
> * LaserGRBL\ResumeJobForm.resx
> * LaserGRBL\RunFromPositionForm.resx
> * LaserGRBL\SettingsForm.resx
> * LaserGRBL\Strings.resx
> * LaserGRBL\AutoUpdate\NewVersionForm.resx
> * LaserGRBL\RasterConverter\ConvertSizeAndOptionForm.resx
> * LaserGRBL\RasterConverter\RasterToLaserForm.resx
> * LaserGRBL\RasterConverter\ResolutionHelperForm.resx
> * LaserGRBL\SvgConverter\ConvertSizeAndOptionForm.resx
> 
> Have a nice day

Are the files related to Translate still the same?

If not, what are the new files?

I am asking to add Turkish support.

**Comment by arkypita** [comment]
I suggest you to use the guide you can find here: https://github.com/arkypita/LaserGRBL/blob/master/TRANSLATING.md

This requires you to use git/github to exchange translated files, it is a bit more complex at first but allows for better and more controlled source management.

**Comment by arkypita** [comment]
Here is an up-to-date list of .resx file to translate

- LaserGRBL\ConnectLogForm.resx
- LaserGRBL\CustomButtonForm.resx
- LaserGRBL\ExceptionManager.resx
- LaserGRBL\GrblConfig.resx
- LaserGRBL\HotkeyManagerForm.resx
- LaserGRBL\IssueDetectorForm.resx
- LaserGRBL\JogForm.resx
- LaserGRBL\LicenseForm.resx
- LaserGRBL\MainForm.resx
- LaserGRBL\PreviewForm.resx
- LaserGRBL\ResumeJobForm.resx
- LaserGRBL\RunFromPositionForm.resx
- LaserGRBL\SaveOptionForm.resx
- LaserGRBL\SettingsForm.resx
- LaserGRBL\Strings.resx
- LaserGRBL\AutoUpdate\NewVersionForm.resx
- LaserGRBL\PSHelper\PSEditorForm.resx
- LaserGRBL\PSHelper\PSHelperForm.resx
- LaserGRBL\RasterConverter\ConvertSizeAndOptionForm.resx
- LaserGRBL\RasterConverter\RasterToLaserForm.resx
- LaserGRBL\RasterConverter\ResolutionHelperForm.resx
- LaserGRBL\SvgConverter\ConvertSizeAndOptionForm.resx

**Comment by arkypita** [comment]
thank you!
