### ISSUE TITLE
reverse ttl

### ISSUE THREAD

**Issue by cecconilorenzo** [arkypita/LaserGRBL#280]
hi, I have a TTL laser with inverted logic, that is with 5V is off and 0V is on.
What should I change to make it work?
thank you.

**Comment by arkypita** [comment]
Google for "grbl invert ttl"

**Comment by muxa** [comment]
@cecconilorenzo did you manage to find a solution for this? i also have TTL logic inverted on the laser

**Comment by hk89** [comment]
You did not use Google! 

Try https://github.com/gnea/grbl/issues/22
