### ISSUE TITLE
Translate software to DOBOT Mooz 2.

### ISSUE THREAD

**Issue by spairo1741** [arkypita/LaserGRBL#281]
Would it be possible to convert this software for DOBOT Mooz 2 laser (DOBOT 3D printer, laser, CNC)
The Mooz 2 software is quite modest.
What size of subsidy could encourage you to sign the program for Mooz 2
sorry for my English, written from Polish through Google translator.

**Comment by arkypita** [comment]
Its not a question of subsidy but a question of time and interest by my side.
As I don't own a DOBOT i am not interested to develop for it. In addition it is very difficult to write code that can interface to a controller, without the ability to test it on a true system.

As LaserGRBL is open source code, anyone can do this job. I encourage anyone having a DOBOT to fork and modify the code.
