### ISSUE TITLE
LaserGRBL no longer works on the Eleks Maker A3 Pro  (LaserGRBL non mi funziona più sulla Eleks Maker A3 Pro)

### ISSUE THREAD

**Issue by brillo9772** [arkypita/LaserGRBL#284]
Salve, come avevo scritto nel titolo, da qualche giorno, dopo aver fatto l'aggiornamento alla V. 2.8.36 ha iniziato a perdere la connessione tra il software e l'hardware, provo spiegarmi meglio come mi è successo. Inizialmente mi è capitato alcune volte che durante l'incisione si fermi e non si riesca più a dare comandi da software, come se mi avesse crasciato il programma. Rispegnendo e ricollegando il tutto, varie volte, si riesce a ripartire per un po', ma con il medesimo epilogo, di bloccarsi tutto, questo sempre più frequentemente, fino ad arrivare al punto che quando vado a collegare l'incisore al software, tramite pulsante dedicato, mi dice che "Un dispositivo collegato al sistema non è funzionante".
Visto che la scheda dell'Arduino nano e una compatibile, ho provato da Arduino IDE a ricaricare gli sketch ma mi da errorore, è possibile che si sia danneggiata la scheda? Grazie per l'attenzione.

Hi, as I had written in the title, a few days ago, after updating to V. 2.8.36 has begun to lose the connection between the software and the hardware, I try to explain better how it happened to me. Initially it happened to me several times that during the incision it stops and you can no longer give commands from software, as if I had crammed the program. Respecting and reconnecting the whole, several times, you are able to start again for a while, but with the same epilogue, to stop everything, this more and more frequently, up to the point that when I go to connect the engraver to the software, through dedicated button, tells me that "A device connected to the system is not working".
Since the card dell'Arduino nano and a compatible, I tried from Arduino IDE to reload the sketches but gives me error, it is possible that the card has been damaged? Thanks for the attention.

**Comment by arkypita** [comment]
Ciao, tra la versione 2.8.36 e la precedente 2.8.35 non ci sono modifiche che riguardano la comunicazione. Ad ogni modo carica il file di log (menu ? - open session log) così ci do un occhiata.

Il fatto che non riesci a caricare gli sketch potrebbe essere dovuto al fatto che le EleksMaker non hanno il bootoader? Hai mai caricato gli sketch su quel nano oppure no?

Dai sintomi che descrivi sembrerebbe che hai problemi seri di comunicazione, cosa che capita di frequente con i cloni di arduino che usano il chip CH340. leggi le [faq](http://lasergrbl.com/faq/) e prova le soluzioni consigliate.

**Comment by arkypita** [comment]
ps. la prossima volta meglio se scrivi inglese, le tue domande e le mie risposte possono essere utili anche per altre persone.

**Comment by brillo9772** [comment]
Grazie per la rapida risposta, per quanto riguarda l'inglese, mi dovrò appoggiare a un traduttore..
Thanks for the quick reply, as regards English, I will have to support a translator ..

**Comment by arkypita** [comment]
hai risolto?
