### ISSUE TITLE
Anet a8 and LaserGBRL

### ISSUE THREAD

**Issue by CapZicco** [arkypita/LaserGRBL#287]
Hi sorry for my bad english. 
Using my anet a8 with laser modification
[anet-laser-mod](http://lokspace.eu/anet-a8-3d-printer-laser-engraver-mod/)  and Inkscape  I have bad results
So i'm trying to use LaserGbrls with my anet a8 with marlin firmware, but it does'nt connect. Any hint ?
Thanks
Luca

**Comment by arkypita** [comment]
LaserGRBL is not compatible with marlin
