### ISSUE TITLE
Shifting the border line

### ISSUE THREAD

**Issue by MarcinKnD** [arkypita/LaserGRBL#289]
When I choose the "Vectorize" option and add a fill, I can see the vector line shift by a few mm on the burnout
![img_20180303_140703](https://user-images.githubusercontent.com/37018109/36934585-3d06a31a-1eec-11e8-9147-497a7c1edc1a.jpg)

**Comment by arkypita** [comment]
this could indicate cable noise, bad usb cable, bad quality arduino clone
http://lasergrbl.com/it/faq/
