### ISSUE TITLE
Override interface

### ISSUE THREAD

**Issue by OscarBrescia** [arkypita/LaserGRBL#290]
Hi, first of all thank you for your work: excellent!
Today I installed laser gbrl for the new Elekscam A3 Pro.
Everything is ok, but I don't see the bar where I can handle the ovverride, really useful function. How can I do?

Thanks

**Comment by OscarBrescia** [comment]
Solution found: it's necessary to upload the board to GRBL 1.1 and override appears. Thank you

**Comment by arkypita** [comment]
A lot of user ask me how to use grbl with Elekscam, but i cannot answer because i am not an owner of elkscam engrave. What did you do for use elek with grbl? Is there any tutorial on the web?
