### ISSUE TITLE
A lot of disconnections

### ISSUE THREAD

**Issue by powercreations** [arkypita/LaserGRBL#291]
Hello everybody, i try to use laserGRBL in my clone K40 laser with smoothieboard  and grbl LPC firmware as i really like it but i have many disconnections.

I change cable (short one), i try usb3/usb2, i test with speed slow/fast, i try with pixel per mm (10-6) but nothing fix it. 

I use other program and works ok.

What you think i do wrong? Thanks in advance

**Comment by arkypita** [comment]
can you provide the program log?
menu ? - open session log

**Comment by powercreations** [comment]
I find session log, where is the rest? :) 

I make a restart of pc and look like that was working ok but i will make some more tests today to see.

[sessionlog.txt](https://github.com/arkypita/LaserGRBL/files/1784103/sessionlog.txt)

**Comment by arkypita** [comment]
Session log is automatically trimmed to 1000 lines
The exception listed in log show that the COM port disappear/disconnect in windows, I cannot guess what could be the cause, maybe conflicting with other software/driver or cable problem.

You can see the com port if exist/disappear looking into device managment
https://support.microsoft.com/en-us/help/4026149/windows-open-device-manager

**Comment by powercreations** [comment]
Thanks for your help, i would check how is going in a while,

Is any way to connect it with smoothie ethernet?

**Comment by arkypita** [comment]
> Is any way to connect it with smoothie ethernet?

I have developed a telent connection that allow to send/receive gcode using simple TCP/IP telnet protocol but i don't know if it work with smoothie. Try yourself

![image](https://user-images.githubusercontent.com/8782035/37029997-9256c8c8-2139-11e8-872f-66fcf0a8c1e6.png)

![image](https://user-images.githubusercontent.com/8782035/37030080-e20a975a-2139-11e8-90c1-e0661f7d7e0b.png)

**Comment by powercreations** [comment]
It looks that it work ok, after laserGRBL setup i had a lot of disconnections but after of pc restart works great.

I will try and inform you if i manage to make it with ethernet, thanks again.
