### ISSUE TITLE
laser GRBL config file

### ISSUE THREAD

**Issue by mkeyno** [arkypita/LaserGRBL#3]
sorry to open the ticket for my question , I was wondering if you have successfully implemented GRBL for actual  cnc laser machine, I really interested to know more about your experience

**Comment by arkypita** [comment]
> sorry to open the ticket for my question

It's ok

>  I was wondering if you have successfully implemented GRBL for actual cnc laser machine, I really interested to know more about your experience

I'm not sure I understand the question.
However I have developed LaserGRBL for a personal use. After self-built a laser engraver, I tried to use different software without finding one that is suitable to my needs. Either they are too complex, or too simple.

And 'so the need arose and the pleasure of writing a simple, lightweight software, but it does everything I need. For now features include a very reliable GCode streamer on com port, and the loading a raster image and convert to GCode scan lines with PWM modulation.

I would soon add a conversion from raster to vector (image vectorialization) that allows to do the tracking edges.

My engraver is very homemade, made with a wooden frame and slides for drawers, bought for cheap at the hardware store. Now I'm currently updating it, with better mechanical created by the machine itself.

Unfortunately I do not have the opportunity to work with professional CNC machines, so I can not test my software environment different from that hobby (to which it is intended)

![2016-12-17 21 21 52](https://cloud.githubusercontent.com/assets/8782035/21552245/a2129716-ce00-11e6-9870-a35d36763668.jpg)
![2016-12-18 10 26 02-1](https://cloud.githubusercontent.com/assets/8782035/21552246/a2154baa-ce00-11e6-9b71-9df9469688ed.jpg)
![2016-12-21 21 29 54](https://cloud.githubusercontent.com/assets/8782035/21552247/a2180214-ce00-11e6-8c13-cbdd895971b2.jpg)

**Comment by mkeyno** [comment]
thanks for reply , I mean if you've built  successfully  cnc laser base on GRBL firmware ,I really interested to know how to configure the lib and setup your hardware . if you know any links for that I really appreciated to share  it

**Comment by arkypita** [comment]
Yes, and it is not particularly difficult. You need an Arduino one, a [arduino CNC shield](http://blog.protoneer.co.nz/arduino-cnc-shield/), and two/three driver chip for stepper motors.

Starting point could be: https://github.com/gnea/grbl/wiki/Connecting-Grbl

Google is your friend, and if you search www.google.it/search?q=grbl+cnc+arduino you can find a lot of DIY project with instructions.
