### ISSUE TITLE
Keep filename when saving a gcode file

### ISSUE THREAD

**Issue by therealjedidad** [arkypita/LaserGRBL#300]
When saving an open file, the existing filename is not persisted to the save dialog. I have a changeset ready for review with this change if I can be granted access for a pull request.

**Comment by arkypita** [comment]
feel free to submit pull request, the access is available

**Comment by therealjedidad** [comment]
Still new to using git, I've always used tfs/vsts instead. When I try to push my changes I get an error "remote: Permission to arkypita/LaserGRBL.git denied to therealjedidad."

**Comment by arkypita** [comment]
I am not an expert of github but in the past some user submit pull request, so it should be possible:
https://github.com/arkypita/LaserGRBL/pulls?q=is%3Apr+is%3Aclosed

ask @Ranthalion or @Effer how do they get it

**Comment by Effer** [comment]
@therealjedidad you should push to your repository and then open a Pull Request to @arkypita repo. You can make a pull request directly from github pages. That's the way I did.
