### ISSUE TITLE
Incisione sovradimensionata e scomposta di un logo

### ISSUE THREAD

**Issue by Mizzone** [arkypita/LaserGRBL#301]
Buonasera arkypita, ti scrivo per alcune delucidazioni come da titolo (essendo nuovo nel campo è molto probabile che io sbagli qualcosa) quindi ti chiedo:

1. quando vado ad impostare le dimensioni dell'immagine (in mm) che voglio marchiare, il laser mi incide un'immagine più grande, perché? (avevo impostato L 30 A 15, è risultata 91 mm di lunghezza e 41 mm di altezza)

2. ad un certo punto, l'immagine che il laser stava marcando si è spostata, come mai?
Allego foto dell'immagine scomposta 
![inkedphoto_2018-03-13_20-52-15_li](https://user-images.githubusercontent.com/37348212/37366850-e97b36ca-2701-11e8-9572-36a9d6ed5283.jpg)
e screenshot degli unici 2 errori riscontrati durante la marcatura
![photo_2018-03-13_20-52-20](https://user-images.githubusercontent.com/37348212/37366415-ad05328c-2700-11e8-9cdd-11366e81fc6a.jpg).
Queste le impostazioni che ho dato al software 
![image](https://user-images.githubusercontent.com/37348212/37367018-7d251c56-2702-11e8-8d47-c0e62dfba84e.png)

Grazie in anticipo per la risposta e tanti tanti complimenti per il software, che te lo dico a fare! 👍

**Comment by arkypita** [comment]
LaserGRBL produce il GCode e lo invia a grbl su arduino, ne deriva che questi problemi non dipendono da LaserGRBL ma da arduino.

Per il primo (dimensioni) devi configurare il numero di step/mm in base al tuo hardware (motore, rapporti etc). https://github.com/gnea/grbl/wiki/Grbl-v1.1-Configuration#100-101-and-102--xyz-stepsmm

Per il secondo è già tutto scritto nelle faq: http://lasergrbl.com/it/faq/

Graditi i complimenti, ps anche se è difficile è gradito scrivere in inglese.
