### ISSUE TITLE
Saving Job Profile

### ISSUE THREAD

**Issue by foxrus87** [arkypita/LaserGRBL#304]
Good afternoon.
When working with different materials, each time you enter the values of speed, power and size.
Is it possible to create profiles in some way so that when selecting any of them all these values were entered automatically, so that they are not always remembered in your head.
Example:

file profile.ini

nameprofile="photo on the board"
s_min=20
s_max=200
speed=2000
h_size=150
w_size=100

then you can have several different profiles for different tasks

**Comment by arkypita** [comment]
I am already doing this in a development branch, but i suspend development cause i have no spare time.
However I agree with your request

**Comment by foxrus87** [comment]
I'm sorry, I hope that soon you will find free time, because your program is very good!
