### ISSUE TITLE
Setting the maximum travel

### ISSUE THREAD

**Issue by AverageManVsPi** [arkypita/LaserGRBL#307]
I just installed grbl on my NEJE DK5 (https://www.gearbest.com/3d-printers-3d-printer-kits/pp_242557.html) by installing a replacement Arduino nano based board (the original board seemed to die).

I'm now using LaserGRBL, and so far have managed manual control/movement. I just tried uploading an image to engrave, however I'm guessing LaserGRBL has no idea what machine it's controlling, and how far the motors can travel, as it sent one axis over to one side and didn't want to stop.

Is there a way I can set the engrave area/max axis travel in the program? Is it normal for this to be trial and error? If I do set a limit, will the software adjust the size accordingly, or do I simply need to uplload the right file size?

Lots of questions there - very new to this!

Thanks

**Comment by StuartB4** [comment]
You need to set up GRBL to suit your machine.
Have a look here.
https://github.com/gnea/grbl/wiki/Grbl-v1.1-Configuration
