### ISSUE TITLE
unexpected reset

### ISSUE THREAD

**Issue by sinfocomp** [arkypita/LaserGRBL#313]
![image](https://user-images.githubusercontent.com/29585130/37927699-08ce3efa-30f8-11e8-8e1b-c4f1d0c38467.png)
[fajo nudo celta t38a2p21v8.txt](https://github.com/arkypita/LaserGRBL/files/1849218/fajo.nudo.celta.t38a2p21v8.txt)

**Comment by arkypita** [comment]
Hi @sinfocomp, I want to be sure that you know how the system works.
LaserGRBL has the task of sending the gcode lines through the USB-Serial line; nothing more, nothing less.

If there was a problem while streaming the line to the machine usually this is not a problem of LaserGRBL itself, but it is a problem of you hardware.

In this case it seems that the controller board has done an unexpected reset, also highlighted by the Grbl 1.1f [$ for help] line that LaserGRBL has received from your board.

I cannot guess what could be the cause of this unexpected reset, could be multiple, but you have to search the cause on your hardware. LaserGRBL has only does its job detecting that something strange is happens so it cannot finish its task to stream the file.
