### ISSUE TITLE
Picture burns out line by line

### ISSUE THREAD

**Issue by Grizz5280** [arkypita/LaserGRBL#314]
I'm not sure what I can do, but my pictures seem to show every individual line and don't look like one solid picture.  Any suggestions on how to adjust this?

![20180326_204042](https://user-images.githubusercontent.com/37823925/37946804-a0d3ea64-3144-11e8-934c-21777762e245.jpg)

**Comment by arkypita** [comment]
You can:
- increase line2line resolution (line/mm)
- unfocus your laser 
- use slower speed (darken and wider burn)

Usefull tips for engraving:
http://www.instructables.com/id/10-Tips-and-Tricks-for-Laser-Engraving-and-Cutting/

**Comment by mayhem2408** [comment]
@Grizz5280 and if the above fails to resolve the issue, check your stepper resolution. Make sure you are running a high microstep to allow the line to get a close as possible.

**Comment by Grizz5280** [comment]
Thanks so much for the help.  I got this to work out perfectly.  I just increased the # of lines per mm.

**Comment by Grizz5280** [comment]
Thanks for the help. I was able to get this to work out great by just increased the lines per mm.
