### ISSUE TITLE
Movement by jerks

### ISSUE THREAD

**Issue by vadimkkkk** [arkypita/LaserGRBL#318]
Tried to burn this progoy but the x axis for some reason moves in short discrete steps, added speed moves faster but still feels discrepancy. Tell me how to achieve a smooth motion so that only the laser flickers ???

**Comment by Icemanhpg** [comment]
Have you changed to laser mode in GRBL ? $32=1 is the activation of laser mode.

**Comment by vadimkkkk** [comment]
Thank you ...
