### ISSUE TITLE
Multiple file to job, but no subsequent processing

### ISSUE THREAD

**Issue by Alibaba0815** [arkypita/LaserGRBL#326]
Hello,
i would like to make multiple passes.
With two passes ("multiple layer") i could engrave a picture and finally cut them out. 
This is now possible, but I have a problem.
If I make a mistake with the settings of one picture, i have to reset the complete project and start again.
Is there a possibility to make a selection of each file to recalibrate the settings?
Also I want to move or calibrate the sitze each Picture. Could such a function added?
This could be very helpful.

Thanks
Alibaba0815

**Comment by arkypita** [comment]
Hi. I understand your request but for how it is written the code it is simple to append file to a job but it is not so simple to manage as different items after inserted.
