### ISSUE TITLE
engraving speed

### ISSUE THREAD

**Issue by renadan** [arkypita/LaserGRBL#327]
Hi I have a problem - I can not adjust engraving speed. Very slow and burns wood. my product GRBL 0.9J, USB port cnc engraving machine control board, 3 axis control - 2.5W 450nm Blue Laser Module TTL 12V - Nema 17 engine.
Thanks for help

**Comment by arkypita** [comment]
Maximum speeds are configured in grbl
https://github.com/gnea/grbl/wiki/Grbl-v1.1-Configuration

**Comment by renadan** [comment]
you still do not know which point to change. help thank you

**Comment by arkypita** [comment]
The setting is stored in your engraver board.
You can access it using LaserGRBL, Menu "Grbl", "Grbl Configuration"

![image](https://user-images.githubusercontent.com/8782035/38800428-89617bc0-4167-11e8-9f07-802b1e752b87.png)
