### ISSUE TITLE
translation of the program into another language (Russian localization)

### ISSUE THREAD

**Issue by Arhimed-Ru** [arkypita/LaserGRBL#333]
I tried to translate the program into Russian using my experience
here is the result:
LaserGRBL2842_ru.zip [removed]
I hope this experience will help correctly translate the next version.

I'll add the localization file. So that you can just replace it in the folder.
Ru_LaserGRBL.resources.zip [removed]
But he does not translate completely.
That there was a complete translation - it is necessary to use the above file (LaserGRBL2842_ru)

**Comment by Arhimed-Ru** [comment]
BtnZeroing...
What is it?

**Comment by arkypita** [comment]
![image](https://user-images.githubusercontent.com/8782035/38917957-8b28390e-42ec-11e8-80bb-f1f1380c2a01.png)

**Comment by Arhimed-Ru** [comment]
Transition to the zero point of coordinates - :)

**Comment by Arhimed-Ru** [comment]
I corrected the full translation:
[LaserGRBL_ru_18.04.2018.zip](https://github.com/arkypita/LaserGRBL/files/1922938/LaserGRBL_ru_18.04.2018.zip)

**Comment by arkypita** [comment]
Posting compiled exe or dll is completely useless as because on the first LaserGRBL update they will be not updated and become incompatible. If you want to do a useful work for the community you have to submit a pull request for your modified .ru.resx files so they can be included in the source.

Please note that I have suspended task of translation because i want to made some code/ui refactoring that will change the code so merging users contribution make my work more complex.

**Comment by arkypita** [comment]
https://github.com/arkypita/LaserGRBL/issues/28

**Comment by Arhimed-Ru** [comment]
please!!!!!   update the resource files (add phrases):
HotkeyManagerForm.resx
IssueDetectorForm.resx
NewVersionForm.resx
ResumeJobForm.resx
RunFromPositionForm.resx

**Comment by Arhimed-Ru** [comment]
Files with available phrases prepared, corrected and packed into the archive:
https://drive.google.com/open?id=19nOu4224ywK9vjLX9URY119YOpLDD7Ql

Why do not you allow all phrases to be translated?
For example, here is this file:
setting_codes.v1.1.hcv
error_codes.csv
alarm_codes.csv
.....
And I can not find another ten phrases that are not in the resources...

**Comment by Arhimed-Ru** [comment]
I wrote down the phrases in a table so you can see:
https://drive.google.com/open?id=1JipHKSAd2H-RaOrEkqueYhs-jRkGuqJk

**Comment by arkypita** [comment]
Visual studio 2017 community, its free and can be downloaded from official site

**Comment by arkypita** [comment]
> please!!!!! update the resource files (add phrases):
> HotkeyManagerForm.resx
> IssueDetectorForm.resx
> NewVersionForm.resx
> ResumeJobForm.resx
> RunFromPositionForm.resx

Yes, you are right. All those form ar recently added and I have not provided the localized resource file.
It's something I shoud do BUT as I have already say "I have suspended task of translation because i want to made some code/ui refactoring that will change the code so merging users contribution make my work more complex"

**Comment by Arhimed-Ru** [comment]
Visual studio 2017 community full - too big
....
please excuse me
what is the minimum package for your program?

**Comment by arkypita** [comment]
".NET  Desktop Development" is the only package needed
in alternative you can use [sharpdevelop](http://www.icsharpcode.net/OpenSource/SD/Download/Default.aspx)

**Comment by Arhimed-Ru** [comment]
I installed Visual studio and a set of NET
opened the project...compiled the program...launched
the program is only English - when switching the language the program (2.8.43) is still English
if you replace the file  LaserGRBL.resources.dll  from the older version - working
the file LaserGRBL.resources.dll 2.8.43 - no  working
I can not check files *.ru.resx 
:(

**Comment by Arhimed-Ru** [comment]
I checked the operation of the regulators 
Power (0.1...2.0), Linear (0.1...2.0), Rapid (0.25;0.5;1.0).
Linear and Rapid - work correctly speed changes
Power only diappazone 0.1 ... 1.0 - correctly
diappazone 1.1 ... 2.0 - It does not regulate

in my translation it is necessary to swap phrases:
"Холостая скорость"     ↔    "Мощность  лазера"

**Comment by Arhimed-Ru** [comment]
I translated version 2.8.44 using "Radialix"
![image 3](https://user-images.githubusercontent.com/38332702/39304363-1ac68e46-4962-11e8-9ee2-6e8870f9d35f.jpg)
![image 4](https://user-images.githubusercontent.com/38332702/39304364-1ae6e038-4962-11e8-847c-d51febcc5931.jpg)
![image 5](https://user-images.githubusercontent.com/38332702/39304366-1b4fa17c-4962-11e8-9f81-3ecbc9d942c5.jpg)
![image 6](https://user-images.githubusercontent.com/38332702/39304367-1b716974-4962-11e8-816f-993f41a0dec6.jpg)
![image 7](https://user-images.githubusercontent.com/38332702/39304368-1c35adf2-4962-11e8-99c5-9b4240e6b1ca.jpg)
![image 8](https://user-images.githubusercontent.com/38332702/39304370-1cd62dea-4962-11e8-9e1c-bccf4be3b7d2.jpg)
![image 9](https://user-images.githubusercontent.com/38332702/39304371-1d0acf32-4962-11e8-870e-e6b5fe801362.jpg)
![image 10](https://user-images.githubusercontent.com/38332702/39304373-1d5f7d2a-4962-11e8-9048-0d1b2d3d062d.jpg)
![image 11](https://user-images.githubusercontent.com/38332702/39304374-1df48348-4962-11e8-998b-97246b843000.jpg)
![image 12](https://user-images.githubusercontent.com/38332702/39304375-1ea73d8a-4962-11e8-830a-0becc3c6cff2.jpg)
![image 13](https://user-images.githubusercontent.com/38332702/39304376-1ef8ba48-4962-11e8-8a00-72d4d2d153f6.jpg)
![image 14](https://user-images.githubusercontent.com/38332702/39304377-1f697af8-4962-11e8-878f-bfc883fb83f4.jpg)
![image 15](https://user-images.githubusercontent.com/38332702/39304417-429b9fd8-4962-11e8-9da7-77c8cf1721f6.jpg)

**Comment by 4arus** [comment]
Добрый день. Вы можете скинуть ссылку на переведенную программу.

**Comment by 4arus** [comment]
Ваша работа очень хорошая.

**Comment by Arhimed-Ru** [comment]
4arus
даю ссылку на русский экзешник (он в архиве):
https://drive.google.com/open?id=1qU8pnHOpFZcoynAZUEqti5O344Dap515
файл извлеките из архива (можете проверить на вирусы - я сам ничего там не добавлял),
скопируйте в папку с программой (можете убрать приставку "ру")
переключать на другие языки нет смысла (этот файл с русскими фразами).

**Comment by 4arus** [comment]
Спасибо. Я тоже когда то пытался перевести первые выпуски. Но Visual studio выдавало ошибку, пробовал "радиаликсом" но так и не освоил эту программу. Сейчас занимаюсь автономным контроллером для лазерного станка с grbl. Как закончу поделюсь.

**Comment by 4arus** [comment]
Доброго времени суток. Понравился ваш перевод. А вы случаем не переводили последний релиз программы?

**Comment by Arhimed-Ru** [comment]
![image 1](https://user-images.githubusercontent.com/38332702/42324981-881bf4d0-806d-11e8-940f-fc9aa1f28733.jpg)
https://drive.google.com/open?id=1IvdAXS6rn9QBXKK8iVx1-kfm_DzMC766

**Comment by Mikalay31** [comment]
Не удалось скачать текстовую инструкцию.
