### ISSUE TITLE
Question: Does LaserGRBL use the Coolant Enable?

### ISSUE THREAD

**Issue by DirkDeCraemere** [arkypita/LaserGRBL#335]
I tried hooking up  a small fan, driven by the GRBL Coolant Enable pin (A3).
This should blow away the smoke during the burning process.
However, the Coolant Enable does not appear to be used by LaserGRBL.

Thanks for the great project!
-Dirk

**Comment by arkypita** [comment]
LaserGRBL does not produce coolant command in its raster import.
Imho coolant could be turned on via custom buttons or kept always on, but as a lot of user ask for it I will add  asap.

Also please note that this request is already in [development roadmap](https://github.com/arkypita/LaserGRBL/issues/64) so please check it before posting
