### ISSUE TITLE
limit switches XY... Z?

### ISSUE THREAD

**Issue by Arhimed-Ru** [arkypita/LaserGRBL#337]
I have so far only two engines...
I want to install limit switches
for parking mode "Homing"
Is the limit switch is needed on all axes (XYZ)?
or two (XY) will be enough?
how will parking happen without the switch on the axis Z?
...
Thank you

**Comment by arkypita** [comment]
Hi. Limit switches and homing procedure are controlled totally by grbl.
LaserGRBL only push the homing command to the controller, so the right place to ask is the grbl github page, not here. Please learn to recognize the right area of ​​competence.

However: 
https://github.com/gnea/grbl/wiki/Set-up-the-Homing-Cycle
https://github.com/gnea/grbl/wiki/Wiring-Limit-Switches

Note that 2axis homing can only be activated by recompiling grbl code, no grbl configuration for disabling Z axis homing.

https://github.com/gnea/grbl/issues/278
