### ISSUE TITLE
cant open raster image import

### ISSUE THREAD

**Issue by austriandummy** [arkypita/LaserGRBL#34]
sorry, im a absolute newbie and my englisch is very bad.
mayby anyone could help me........i dont no how to integrate or install all those cool featers in lasergrbl...???

**Comment by arkypita** [comment]
- File -> Open File
- Select an image file (.jpg .png .bmp...)

**Comment by austriandummy** [comment]
this ones i know....but lasergrbl dosn´t open a window or import picture to work with it.

**Comment by arkypita** [comment]
Did you see the open file dialog, but when you select the graphic file the raster image dialog did not show?

1) If you don't have latest version (2.6.2) please update to the new version.
2) Open the file dialog and select image file.
3) Open session log and copy and paste your session log here, let me see if there is some error in file reading.

![sessionlog](https://cloud.githubusercontent.com/assets/8782035/25585011/c844393c-2e98-11e7-81e0-07247a57e4f8.jpg)

**Comment by austriandummy** [comment]
07.05.2017 17:16:00	Program     	------------ PROGRAM START ------------
07.05.2017 17:16:02	SetStatus   	Machine status [Disconnected]
07.05.2017 17:16:12	OpenFile    	Open C:\Users\Public\Pictures\Sample Pictures\Koala.jpg
07.05.2017 17:16:12	RasterImport	System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
07.05.2017 17:16:12	RasterImport	   bei LaserGRBL.RasterConverter.RasterToLaserForm.PbConverted_Resize(Object sender, EventArgs e)
07.05.2017 17:16:12	RasterImport	   bei System.Windows.Forms.Control.OnResize(EventArgs e)
07.05.2017 17:16:12	RasterImport	   bei System.Windows.Forms.PictureBox.OnResize(EventArgs e)
07.05.2017 17:16:12	RasterImport	   bei System.Windows.Forms.Control.OnSizeChanged(EventArgs e)
07.05.2017 17:16:12	RasterImport	   bei System.Windows.Forms.Control.UpdateBounds(Int32 x, Int32 y, Int32 width, Int32 height, Int32 clientWidth, Int32 clientHeight)
07.05.2017 17:16:12	RasterImport	   bei System.Windows.Forms.Control.UpdateBounds(Int32 x, Int32 y, Int32 width, Int32 height)
07.05.2017 17:16:12	RasterImport	   bei System.Windows.Forms.Control.SetBoundsCore(Int32 x, Int32 y, Int32 width, Int32 height, BoundsSpecified specified)
07.05.2017 17:16:12	RasterImport	   bei System.Windows.Forms.Control.ScaleControl(SizeF factor, BoundsSpecified specified)
07.05.2017 17:16:12	RasterImport	   bei System.Windows.Forms.Control.ScaleControl(SizeF includedFactor, SizeF excludedFactor, Control requestingControl)
07.05.2017 17:16:12	RasterImport	   bei System.Windows.Forms.Control.Scale(SizeF includedFactor, SizeF excludedFactor, Control requestingControl)
07.05.2017 17:16:12	RasterImport	   bei System.Windows.Forms.Control.ScaleChildControls(SizeF includedFactor, SizeF excludedFactor, Control requestingControl)
07.05.2017 17:16:12	RasterImport	   bei System.Windows.Forms.Control.Scale(SizeF includedFactor, SizeF excludedFactor, Control requestingControl)
07.05.2017 17:16:12	RasterImport	   bei System.Windows.Forms.Control.ScaleChildControls(SizeF includedFactor, SizeF excludedFactor, Control requestingControl)
07.05.2017 17:16:12	RasterImport	   bei System.Windows.Forms.Control.Scale(SizeF includedFactor, SizeF excludedFactor, Control requestingControl)
07.05.2017 17:16:12	RasterImport	   bei System.Windows.Forms.Control.ScaleChildControls(SizeF includedFactor, SizeF excludedFactor, Control requestingControl)
07.05.2017 17:16:12	RasterImport	   bei System.Windows.Forms.Control.Scale(SizeF includedFactor, SizeF excludedFactor, Control requestingControl)
07.05.2017 17:16:12	RasterImport	   bei System.Windows.Forms.ContainerControl.OnChildLayoutResuming(Control child, Boolean performLayout)
07.05.2017 17:16:12	RasterImport	   bei System.Windows.Forms.Control.OnLayoutResuming(Boolean performLayout)
07.05.2017 17:16:12	RasterImport	   bei System.Windows.Forms.Control.ResumeLayout(Boolean performLayout)
07.05.2017 17:16:12	RasterImport	   bei LaserGRBL.RasterConverter.RasterToLaserForm.InitializeComponent()
07.05.2017 17:16:12	RasterImport	   bei LaserGRBL.RasterConverter.RasterToLaserForm..ctor(GrblCore core, String filename)
07.05.2017 17:16:12	RasterImport	   bei LaserGRBL.RasterConverter.RasterToLaserForm.CreateAndShowDialog(GrblCore core, String filename, Form parent)
07.05.2017 17:16:12	RasterImport	   bei LaserGRBL.GrblCore.OpenFile(Form parent)
07.05.2017 17:16:19	OpenFile    	Open C:\Users\Public\Pictures\Sample Pictures\Koala.jpg
07.05.2017 17:16:19	RasterImport	System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
07.05.2017 17:16:19	RasterImport	   bei LaserGRBL.RasterConverter.RasterToLaserForm.PbConverted_Resize(Object sender, EventArgs e)
07.05.2017 17:16:19	RasterImport	   bei System.Windows.Forms.Control.OnResize(EventArgs e)
07.05.2017 17:16:19	RasterImport	   bei System.Windows.Forms.PictureBox.OnResize(EventArgs e)
07.05.2017 17:16:19	RasterImport	   bei System.Windows.Forms.Control.OnSizeChanged(EventArgs e)
07.05.2017 17:16:19	RasterImport	   bei System.Windows.Forms.Control.UpdateBounds(Int32 x, Int32 y, Int32 width, Int32 height, Int32 clientWidth, Int32 clientHeight)
07.05.2017 17:16:19	RasterImport	   bei System.Windows.Forms.Control.UpdateBounds(Int32 x, Int32 y, Int32 width, Int32 height)
07.05.2017 17:16:19	RasterImport	   bei System.Windows.Forms.Control.SetBoundsCore(Int32 x, Int32 y, Int32 width, Int32 height, BoundsSpecified specified)
07.05.2017 17:16:19	RasterImport	   bei System.Windows.Forms.Control.ScaleControl(SizeF factor, BoundsSpecified specified)
07.05.2017 17:16:19	RasterImport	   bei System.Windows.Forms.Control.ScaleControl(SizeF includedFactor, SizeF excludedFactor, Control requestingControl)
07.05.2017 17:16:19	RasterImport	   bei System.Windows.Forms.Control.Scale(SizeF includedFactor, SizeF excludedFactor, Control requestingControl)
07.05.2017 17:16:19	RasterImport	   bei System.Windows.Forms.Control.ScaleChildControls(SizeF includedFactor, SizeF excludedFactor, Control requestingControl)
07.05.2017 17:16:19	RasterImport	   bei System.Windows.Forms.Control.Scale(SizeF includedFactor, SizeF excludedFactor, Control requestingControl)
07.05.2017 17:16:19	RasterImport	   bei System.Windows.Forms.Control.ScaleChildControls(SizeF includedFactor, SizeF excludedFactor, Control requestingControl)
07.05.2017 17:16:19	RasterImport	   bei System.Windows.Forms.Control.Scale(SizeF includedFactor, SizeF excludedFactor, Control requestingControl)
07.05.2017 17:16:19	RasterImport	   bei System.Windows.Forms.Control.ScaleChildControls(SizeF includedFactor, SizeF excludedFactor, Control requestingControl)
07.05.2017 17:16:19	RasterImport	   bei System.Windows.Forms.Control.Scale(SizeF includedFactor, SizeF excludedFactor, Control requestingControl)
07.05.2017 17:16:19	RasterImport	   bei System.Windows.Forms.ContainerControl.OnChildLayoutResuming(Control child, Boolean performLayout)
07.05.2017 17:16:19	RasterImport	   bei System.Windows.Forms.Control.OnLayoutResuming(Boolean performLayout)
07.05.2017 17:16:19	RasterImport	   bei System.Windows.Forms.Control.ResumeLayout(Boolean performLayout)
07.05.2017 17:16:19	RasterImport	   bei LaserGRBL.RasterConverter.RasterToLaserForm.InitializeComponent()
07.05.2017 17:16:19	RasterImport	   bei LaserGRBL.RasterConverter.RasterToLaserForm..ctor(GrblCore core, String filename)
07.05.2017 17:16:19	RasterImport	   bei LaserGRBL.RasterConverter.RasterToLaserForm.CreateAndShowDialog(GrblCore core, String filename, Form parent)
07.05.2017 17:16:19	RasterImport	   bei LaserGRBL.GrblCore.OpenFile(Form parent)
07.05.2017 17:16:44	OpenFile    	Open C:\Users\Public\Pictures\Sample Pictures\Lighthouse.jpg
07.05.2017 17:16:44	RasterImport	System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
07.05.2017 17:16:44	RasterImport	   bei LaserGRBL.RasterConverter.RasterToLaserForm.PbConverted_Resize(Object sender, EventArgs e)
07.05.2017 17:16:44	RasterImport	   bei System.Windows.Forms.Control.OnResize(EventArgs e)
07.05.2017 17:16:44	RasterImport	   bei System.Windows.Forms.PictureBox.OnResize(EventArgs e)
07.05.2017 17:16:44	RasterImport	   bei System.Windows.Forms.Control.OnSizeChanged(EventArgs e)
07.05.2017 17:16:44	RasterImport	   bei System.Windows.Forms.Control.UpdateBounds(Int32 x, Int32 y, Int32 width, Int32 height, Int32 clientWidth, Int32 clientHeight)
07.05.2017 17:16:44	RasterImport	   bei System.Windows.Forms.Control.UpdateBounds(Int32 x, Int32 y, Int32 width, Int32 height)
07.05.2017 17:16:44	RasterImport	   bei System.Windows.Forms.Control.SetBoundsCore(Int32 x, Int32 y, Int32 width, Int32 height, BoundsSpecified specified)
07.05.2017 17:16:44	RasterImport	   bei System.Windows.Forms.Control.ScaleControl(SizeF factor, BoundsSpecified specified)
07.05.2017 17:16:44	RasterImport	   bei System.Windows.Forms.Control.ScaleControl(SizeF includedFactor, SizeF excludedFactor, Control requestingControl)
07.05.2017 17:16:44	RasterImport	   bei System.Windows.Forms.Control.Scale(SizeF includedFactor, SizeF excludedFactor, Control requestingControl)
07.05.2017 17:16:44	RasterImport	   bei System.Windows.Forms.Control.ScaleChildControls(SizeF includedFactor, SizeF excludedFactor, Control requestingControl)
07.05.2017 17:16:44	RasterImport	   bei System.Windows.Forms.Control.Scale(SizeF includedFactor, SizeF excludedFactor, Control requestingControl)
07.05.2017 17:16:44	RasterImport	   bei System.Windows.Forms.Control.ScaleChildControls(SizeF includedFactor, SizeF excludedFactor, Control requestingControl)
07.05.2017 17:16:44	RasterImport	   bei System.Windows.Forms.Control.Scale(SizeF includedFactor, SizeF excludedFactor, Control requestingControl)
07.05.2017 17:16:44	RasterImport	   bei System.Windows.Forms.Control.ScaleChildControls(SizeF includedFactor, SizeF excludedFactor, Control requestingControl)
07.05.2017 17:16:44	RasterImport	   bei System.Windows.Forms.Control.Scale(SizeF includedFactor, SizeF excludedFactor, Control requestingControl)
07.05.2017 17:16:44	RasterImport	   bei System.Windows.Forms.ContainerControl.OnChildLayoutResuming(Control child, Boolean performLayout)
07.05.2017 17:16:44	RasterImport	   bei System.Windows.Forms.Control.OnLayoutResuming(Boolean performLayout)
07.05.2017 17:16:44	RasterImport	   bei System.Windows.Forms.Control.ResumeLayout(Boolean performLayout)
07.05.2017 17:16:44	RasterImport	   bei LaserGRBL.RasterConverter.RasterToLaserForm.InitializeComponent()
07.05.2017 17:16:44	RasterImport	   bei LaserGRBL.RasterConverter.RasterToLaserForm..ctor(GrblCore core, String filename)
07.05.2017 17:16:44	RasterImport	   bei LaserGRBL.RasterConverter.RasterToLaserForm.CreateAndShowDialog(GrblCore core, String filename, Form parent)
07.05.2017 17:16:44	RasterImport	   bei LaserGRBL.GrblCore.OpenFile(Form parent)
07.05.2017 17:16:55	Program     	------------ PROGRAM STOP ------------

08.05.2017 18:08:44	Program     	------------ PROGRAM START ------------
08.05.2017 18:08:46	SetStatus   	Machine status [Disconnected]

**Comment by arkypita** [comment]
This was a bug, I create a new LaserGRBL version with a fix.
Would you like to try and tell me if now works?

**Comment by austriandummy** [comment]
shure i would :) where i can found it?

**Comment by arkypita** [comment]
https://github.com/arkypita/LaserGRBL/releases

**Comment by austriandummy** [comment]
i´ve got it
thanks ark, it works ;)
just waiting for my laser driver, but if my cnc runs i´ll show you some succsess with my projekt;)

**Comment by arkypita** [comment]
Thank you too, you contribute solving a bug
