### ISSUE TITLE
Converting the laser to a plotter

### ISSUE THREAD

**Issue by slanwar** [arkypita/LaserGRBL#340]
I converted my Openbuild Acro from laser to a plotter but with this software I don't see the option to lift the pen -on this case would be Z. The reason I converted (can switch back) was because the CNC is located in a school and of course I have 2 smoke detectors right above and even I have a fan blowing makes me nervous.

**Comment by beamzer** [comment]
I use it to drive my EleksDraw plotter, the M3 and M5 commands work to trigger the servo which lifts and lowers the pen. When the pen is lowered, the tip rests on the drawing surface by the gravity of the pen holding mechanism. That way it automatically follows irregularities. 
[EleksDraw Pen Holder](http://eleksmakeross.oss-ap-southeast-1.aliyuncs.com/wiki/EleksDraw/New/09.gif)

**Comment by beamzer** [comment]
I wouldn't advice EleksCam, it's terrible software, keeps throwing unhandled exception errors and
you need to run it as administrator.  LaserGrbl is much better and works with the EleksDraw.

**Comment by JoshuRuiz** [comment]
I converted my laser to a plotter and i use now laserGBRL with pictures. ONLY with the vector option (not fill). For that only you will need to edit with Notepad++ (for example) the instances in the gcode generated previously, of course the rotation angle must be in concordance to limits of power and depends the firmware you installed. 0-255 or 0-1000
change this:
M3 to M3\nG4\P0.2
M5 to M5\nG4\P0.2

**Comment by slanwar** [comment]
You have nice pictures you plotted on your instagram any chance I can get a copy?

**Comment by JoshuRuiz** [comment]
The pictures are on thematic [zentangle](https://www.google.com/search?q=zentangle&client=firefox-b-ab&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiI8MTRiZnbAhWC8RQKHYNZDuQQ_AUICigB&biw=1920&bih=933)
