### ISSUE TITLE
Bugged version v2.8.44

### ISSUE THREAD

**Issue by arkypita** [arkypita/LaserGRBL#342]
I have released a new version called v2.8.44 (immediatly removed) that has an issue with translation.
This is because I have compiled it with Visual Studio 2017 that seem to have a problem with localization.

https://developercommunity.visualstudio.com/content/problem/63772/winforms-resx-localization-does-not-work-in-vs-201.html

Also this version does not do any update so user with 2.8.44 are strongly invited to manually update to latest stable version: https://github.com/arkypita/LaserGRBL/releases/latest

**Comment by Arhimed-Ru** [comment]
when will this problem be solved?
or need the old compiler?

**Comment by arkypita** [comment]
For what I see if I compile LaserGRBL at home, where I have VS2017 freshly installed, I have an Issue with the translation (only english is working) but if I compile the same code with VS2017 at my office PC the issue with the translation disappear.

This is the version installed at office:

![image](https://user-images.githubusercontent.com/8782035/39297974-3c5e58a8-4945-11e8-9997-3fe0c9514dbc.png)

**Comment by arkypita** [comment]
later I will check the version I have at home

**Comment by Arhimed-Ru** [comment]
I have VS2017 freshly installed, I have an Issue with the translation (only english is working)
![image 1](https://user-images.githubusercontent.com/38332702/39303273-2d42aa5e-495e-11e8-899f-8d6f0c0f1df8.jpg)

**Comment by Arhimed-Ru** [comment]
I do not understand these compilations very well. 
but...
I think that the  probably the cause of the problem is not in the visual studio
I think that the new version of the framework (4.7) does not support your old localization language.
You need to update the localization files or use the old compilation framework (3.5 ... or older 4.7)
