### ISSUE TITLE
G1 missing

### ISSUE THREAD

**Issue by stanrob** [arkypita/LaserGRBL#347]
Hi, I'm using the v2.8.45 version (the lastes I guess) and I have the same issue as the #73 talk. 
I use this software on a 3D printer and the fact is that G1 and G0 modal fonction are not understand by my printer. It result that the laser fire only when the line show a G1 at the begining.  
Do you have any idea how I can fix this?

**Comment by arkypita** [comment]
I am sorry but LaserGRBL "raster import" is designed to produce GCode that is compatible with hardware that use grbl as controller, following its convention that are quite standards: if you don't have a working G0/G1 implementation on your 3D printer controller this is a problem of your controller, not of LaserGRBL.

Unluckily it is not so simple to write a gcode generator that can be compatible and optimized with wide types of controller, so I have to made a choice and mine was grbl.
