### ISSUE TITLE
Feature Suggestion - Custom Header/Footer

### ISSUE THREAD

**Issue by bdring** [arkypita/LaserGRBL#348]
Many CAM program have post processors that allow you to customize the gcode. I think it would be great to have at least custom headers and footer that are appended to the gcode.

I like to make custom laser machines and they could benefit from this.

https://youtu.be/EXcOcuE1Dxk

https://youtu.be/pktMoOVnKbw

**Comment by arkypita** [comment]
added to dev roadmap

**Comment by arkypita** [comment]
Added, You can test this version: https://github.com/arkypita/LaserGRBL/releases/tag/v3.0.19
