### ISSUE TITLE
$30 (max laser PWM) value

### ISSUE THREAD

**Issue by jorgemarmo** [arkypita/LaserGRBL#349]
Hi,
Wich vallue works better for $30 ? 
I've seen a lot of "$30=255" which seems logical to me since arduino nano PWM are 8bits...
but a I've seen a huge amount of "$30=1000" in laser mode.

regards,

**Comment by arkypita** [comment]
my suggestion is to use $30=255
higher values are useless cause max pwm resolution is 8bit
lower value are usefull if you don't need to use all the quality and you like to "compress" the image (in raster mode LaserGRBL join together all the segment that produce the same PWM value, so you can have less segment)

**Comment by jorgemarmo** [comment]
that makes sense, thank you!
