### ISSUE TITLE
LaserGRBL Skips last but one command.

### ISSUE THREAD

**Issue by StuartB4** [arkypita/LaserGRBL#350]
Not sure if this is an issue or something that could be easily fixed.

I add $SLP command to the very end of a gcode file so that the stepper motors are 
switched off at the end of the job. 
It works fine and the motors can easily be moved by hand as they are no longer powered up.

Usually the last line of the gcdoe is always G0 X0 Y0, and at the end of the job the laser goes back to the home position.

However, when I add the $SLP command after G0 X0 Y0 the G0 X0 Y0 is ignored and the laser stops exactly at the end of the last line it burned, then it goes to sleep.
So it does'nt run the G0 X0 Y0 command but skips to the $SLP command.

![untitled1](https://user-images.githubusercontent.com/16980026/39667324-402ebf0a-50ab-11e8-97d3-6e0ab8a7edeb.jpg)

Any ideas why would be greatly appreciated.

**Comment by arkypita** [comment]
I think $SLP act as an immediate command at arduino side, so it is not queued into grbl move buffer but executed immediately

**Comment by StuartB4** [comment]
Ok, but why does the laser not go to the home position when the burning has finished, it just stops at the end of the last line it burns.

**Comment by arkypita** [comment]
try sending this command manually, enqueuing them as fast as you can so the command is not completely executed when you type the last one $SLP

F50
G1 X10 Y10
G0 X0 Y0
$SLP

![image](https://user-images.githubusercontent.com/8782035/39695203-166bcb96-51ea-11e8-953d-bdb90c6a509a.png)

As you can see grbl return an error (you cannot send $SLP while moving). This means that grbl manage the SLP command at the same time it receive, and not when the previous command is received. So, you cannot use $SLP in a queue of command but only perform it manually when the job ended

I don't know why in a file streaming operation it act like this (without sending an error but stopping motors in a wrong pos) however this look like an issue of grbl, not LaserGRBL so this is not the right place where ask

**Comment by arkypita** [comment]
already tried putting a G4 delay between G0X0Y0 and $SLP ?
