### ISSUE TITLE
Laser GRBL has stopped working - Windows is checking for solution to the problem

### ISSUE THREAD

**Issue by ihab2010** [arkypita/LaserGRBL#351]
Hello,
It is my first time to Laser GRBL.
I like your software too much, I have seen it last week with one of my students.
Since then, it did not work.
I change the Arduino Uno card, I changed USB cable, I have changed USB port.
I have uninstalled Laser Grbl 2.8.45 and installed 2.8.30 instead.
It did not solve the problem.
What else could it be?
Best regards.
Ihab  

![image](https://user-images.githubusercontent.com/39032287/39675986-5e41b054-516b-11e8-971d-a0dc57d4749e.png)

**Comment by arkypita** [comment]
do you have .net framework 3.5 installed?
https://www.microsoft.com/it-it/download/details.aspx?id=21

**Comment by ihab2010** [comment]
Thank you arkypita for your prompt reply.
Yes, you right.
Once I installed .net framework 3.5 
 Laser Grbl open.
But unfortunately when I connect status became connected for few seconds and disconnected.
What could be the problem now?
Waiting for your prompt reply.
I am very excited to start using it on my project.
Thanks again.

**Comment by arkypita** [comment]
too generic

is grbl installed on your arduino? what version?
is correct USB driver installed to see arduino com port?

**Comment by ihab2010** [comment]
Thank you arkypita for your prompt reply.
Yes,  you right.
My Arduino was having an old version of Grbl.
I thought it will work.
now I uploaded a new verion

![image](https://user-images.githubusercontent.com/39032287/39836719-fc56c7c0-53dc-11e8-9066-07cd7894fd10.png)

now it works.
Many thanks for your understanding an cooperation.
Ihab
