### ISSUE TITLE
Custom Laser On button not working when using PWM.

### ISSUE THREAD

**Issue by StuartB4** [arkypita/LaserGRBL#355]
Since I started using PWM my custom button to switch the laser on does not work.
I'd like to have it working for focussing the laser.
Without PWM it worked every time just using M3 to switch it on and another custom button with M5 to switch it off.

I have a Framing custom button that works fine using the M4 and M5 command as below.

F600
M4 S100
G0 X[left] Y[bottom]
G1 X[right]
G1 Y[top]
G1 X[left]
G1 Y[bottom]
G0 X0 Y0
M5

I've tried the "Connected, Always, and Idle " options in the custom button drop down menu but nothing makes any difference.
This is my custom Laser on button.

M4 S255 or M3 S255
Neither options work. Am I missing something?

Thanks.

**Comment by StuartB4** [comment]
Worked it out now.
Just added G1 at the top of the list.

G1
M3 S255

**Comment by StuartB4** [comment]
Can I use the G1 in the custom button text somehow?

**Comment by Arhimed-Ru** [comment]
probably you are on laser mode
that the laser worked without movement - you need to turn off the laser mode

**Comment by vaicekas** [comment]
I use this:
Laser ON
G1 M3 S1 F1 
Laser OFF
G0 M5

**Comment by Arhimed-Ru** [comment]
vaicekas - there is not...
Look how you need to:

"Laser ON (laser mode=OFF)":
$32=0
M3 S1

"Laser OFF (laser mode=ON)":
$32=1
M5

**Comment by StuartB4** [comment]
Tried Arhimed-Ru's version and it works fine.
Thankyou very much.
