### ISSUE TITLE
 Burning problem

### ISSUE THREAD

**Issue by wilu9500** [arkypita/LaserGRBL#358]
Hi, I have a blue laser 5,5w PWM laser like in the picture below.

![32564409_1824823714230298_6268441035492294656_n](https://user-images.githubusercontent.com/35997091/40103596-476b300a-58ee-11e8-9bae-ddbf0470f213.jpg)

![32779089_1824823537563649_4632624486506561536_n](https://user-images.githubusercontent.com/35997091/40103608-5699e81e-58ee-11e8-95d5-89a7e7d0042a.jpg)

Engraves the image using the LaserGRBL program in the vectorization option. At a speed of 200 MM and a laser power of 70%. At different times, the laser stops firing as in the picture below.

![32644690_1824823250897011_2733652765854138368_n](https://user-images.githubusercontent.com/35997091/40103933-3bd2fc90-58ef-11e8-9aad-5a8c34598a15.jpg)

In this case, it happened after 1 hour but sometimes it happens after 10 minutes. So it does not always depend on the overheating of the laser because earlier my depopulation worked 12 hours and there was no such problem. I used the LaserGrbl 2.8.45 progam entry and checked on version 2.8.40 and the problem continues.

I am asking for advice what this wine can be

Thanks in advance for your help

**Comment by arkypita** [comment]
Do you think this is a problem of LaserGRBL? Why?

**Comment by wilu9500** [comment]
I thought the problem lies in the software. It turned out that one of the contacts from the laser plate loosened and it came to a turn and this was the cause of the wrong laser work. I was in a hurry. Thanks for replying and closing the topic.
