### ISSUE TITLE
Request: Optionally add extra commands to the end of the generated GCode.

### ISSUE THREAD

**Issue by StuartB4** [arkypita/LaserGRBL#359]
HI.
Just wondered if it would be possible to have an option of adding extra commands automatically to the end of the generated gcode just before / during generation.

I would like to add a delay and the sleep command to the end of every job.
I do it manually at the minute by saving the code file generated from the image, 
and then edit the code to add this just after the G0 X0 Y0:

G4 P10
$SLP

It works fine but I have to do it for every job, it would be nice and a bit easier if  there was an option to add the commands during the gcode generation.

Thanks for all the work you constantly put in to this great program.

**Comment by arkypita** [comment]
already in development roadmap #64

**Comment by StuartB4** [comment]
Ok thanks. Sorry I did'nt see it.
