### ISSUE TITLE
[Enhancement]Pause before filling when engraving images.

### ISSUE THREAD

**Issue by Tha14** [arkypita/LaserGRBL#363]
Hello,
Been using this wonderful .net app for quite some time now and I would like to know if it would not be a hassle to add an option which will pause the job before starting the filling of the engraved image. I would be helpful for us laser diode users in order to change the focus(no z axis) of the beam to fill a bigger area.  If there is a way to do this already I would be thankful to know about it. Thanks!

**Comment by arkypita** [comment]
It is a good suggestion, never think about it. Not so difficult but it should be inserted into generated gcode and "recognized" by the software to propose a "focus than press continue".
