### ISSUE TITLE
How to setup quality of line to line options more than 20 lines / mm....

### ISSUE THREAD

**Issue by emilvv** [arkypita/LaserGRBL#365]
Hello,

I am trying to import BMP image of PCB ( printed circuit board ) to 'engrave' the image on UV sensitive photoresist ...

UV laser diode produce tracks about 0.03 / 0.04 mm wide on my PCB UV printer ..

When I try to specify quality of line to line options more than 20 lines / mm.... it is not possible ..
( 20 is max possible choice ..)

Is there any way to use bigger parameter of quality - about 30 lines / mm - 

I have last LaserGRBL and GRBL 1.1f ..

Thank you in advance,

Emil

**Comment by arkypita** [comment]
#30
