### ISSUE TITLE
Pilot a pen instead of the laser

### ISSUE THREAD

**Issue by giampaolosacchetto** [arkypita/LaserGRBL#371]
Hello. I recently built a small laser engraver with arduino one, grbl firmware and Laser grbl v software. 1.1. Everything works well. Now I want to replace the laser module with a servo that commands a pen. The servo used is MG996R (duty cycle 20ms 50hz 5V) connected to pin 11. Firmware grbl servo (https://github.com/robottini/grbl-servo) modified in the parameters:

define RC_SERVO_SHORT 15 // Tick timer for pulse duration of 0.6 ms (9 for 0.6 ms)
define RC_SERVO_LONG 32 // Timer tick for pulse duration 2.5 ms (39 for 2.5 ms)

with the value of 9 and 39 respectively, as indicated in gitHub to move the servo by 180 °. I tried to send images with laser grbl; step motors do their job but the servant does not move.
If someone helps me thank you. 
Hello

**Comment by brakthehun** [comment]
LaserGRBL supports Firmware V1.1
Your servo firmware is built on V0.9

**Comment by giampaolosacchetto** [comment]
Thanks for the clarification. I try to reformulate my need:
I would like my engraver to draw with a pen a bitmap sent from the pc in g-code (with inkscape)
I tried various sw (gcode sender - CNCjs etc) moving the servo on the z axis of arduino but the servo has non coherent movements.
I have seen several plotter projects on the internet doing this but they do not explain the sw and firmware they need.
if you have any indication to give me thanks.
Hi Paul

**Comment by brakthehun** [comment]
Do you have any links to their projects or videos??

**Comment by StuartB4** [comment]
@giampaolosacchetto.

You might find what you are looking for here:
https://www.instructables.com/howto/arduino+pen+plotter
There are loads of different projects using different methods.

**Comment by giampaolosacchetto** [comment]
Thanks for your help.
Hello
