### ISSUE TITLE
How to stop over burning at the end of lines.

### ISSUE THREAD

**Issue by StuartB4** [arkypita/LaserGRBL#373]
Every time a burn an image with quite a dark background I get too much burning at the end of the lines.
The laser switches of at the end of a line and comes back on for the start of the next one, but for some reason I get overburning down both left and right edges of the image. 
If I'm using card the laser almost burns straight through it.
The rest of the image away from the edges is fine.
I've tried lowering the number of lines but then the picture is not good enough.
Tried turning the laser power down but then it does not burn the rest of the image dark enough.
Tried changing the burning speed but still get the same result.

These 2 images were set at 5 Lines.
The more lines I set it to for better quality the darker the overburning gets.

![img_3020](https://user-images.githubusercontent.com/16980026/40757250-85a13eb8-647f-11e8-815b-8d6f3686f918.JPG)

![img_3021](https://user-images.githubusercontent.com/16980026/40757252-85cb4686-647f-11e8-869d-aa9613fc7bcf.JPG)

**Comment by arkypita** [comment]
This is due to the deceleration of the laser. Using M4 (laser power corrected by speed) can help fixing this problem

**Comment by arkypita** [comment]
https://github.com/gnea/grbl/wiki/Grbl-v1.1-Laser-Mode

https://github.com/gnea/grbl/issues/34

**Comment by arkypita** [comment]
Another solution is to add a very light margin to the image  (not white, as white will be optimized/skipped by lasergrbl). An "acceleration border" feature should be already in dev roadmap

**Comment by StuartB4** [comment]
Ok, I will have a look at that.
Thankyou.
