### ISSUE TITLE
Add Vector and Raster in same job

### ISSUE THREAD

**Issue by jameshudson09** [arkypita/LaserGRBL#374]
There are times when I would like to raster an image with the laser at a low power then crank it up and cut it out. This is done through colors in the epilog laser software. For example a grey scale image with a black box around it can be changed to blue scale image keeping the black box. Then in the epilog software change the black box to vector cut and the blue to raster engrave. I am not sure how many levels can be done at once. The most I have done is 3. Thanks for all the work. I prefer your software over the epilog solution because of the more control and ease of use.

**Comment by mikemorana** [comment]
I imagine the File>Append File option could do this. First 'File>Load Image' the grayscale image then File>Append File the same file and choose vectorize or Append File another file intended for vector and increase the laser power..
LaserGRBL will then combine the two files, running the first file first. I suggest a queue option though.

**Comment by aftersight** [comment]
The append option works for this, but I would really love to see the option as a tick box to both vector and raster in the same procedure.
