### ISSUE TITLE
ENHANCEMENT, can you add hotkeys for rapid,spindle,speed, overides

### ISSUE THREAD

**Issue by sinfocomp** [arkypita/LaserGRBL#375]
would be nice if we could have hotkeys for G0 G1 S overides, this would make it easyer for a joystick controller interaction such as with JOYTOKEYS.

Thanks

**Comment by arkypita** [comment]
Added to roadmap

**Comment by arkypita** [comment]
https://github.com/arkypita/LaserGRBL/releases/tag/v2.8.48
