### ISSUE TITLE
No so much an issue, just wondered why Laser moves all the way to the right when theres nothing there to burn.

### ISSUE THREAD

**Issue by StuartB4** [arkypita/LaserGRBL#376]
Hi Arkypita.
I just wondered, why does the laser move all the way over to the right edge to increase by 1 line but it does not do it when it moves to the left ? It just stops on the left at the begining of the next line of the image, increases by one line and carries on burning.

https://www.youtube.com/watch?v=HxTlYBP4Rsc&feature=youtu.be

Settings are these.

![untitled](https://user-images.githubusercontent.com/16980026/40980730-1067e470-68d1-11e8-8a56-39605e178d61.jpg)

**Comment by arkypita** [comment]
Maybe your image does not have a "pure white" background, some dirty pixels on the right.
Try setting a "white clip" of 5 and see

**Comment by StuartB4** [comment]
Yes that was it. 
White clip set to 3 was enough to stop it for that particular image.
I will have to remember that for future use.
Thanks again.
