### ISSUE TITLE
ENHANCEMENT

### ISSUE THREAD

**Issue by sinfocomp** [arkypita/LaserGRBL#387]
It would help a lot if it where possible to:
1.- click a segment on the preview and be able to "Run from here"
2.- loaded gcode visible and editable
2b.- highlight current position on loaded code at preview image
Best regards
Ed

**Comment by arkypita** [comment]
Hi @sinfocomp  and thanks for your hint
1. It is not possible to do. I mean: not impossible at all but very difficult especially in the actual version of the code.
2. ok, i add this feature in dev roadmap
3. already present in dev roadmap

Roadmap: https://github.com/arkypita/LaserGRBL/issues/64
