### ISSUE TITLE
Vectorize issue.

### ISSUE THREAD

**Issue by burakerenn** [arkypita/LaserGRBL#388]
I tried to use vectorize mode to cut something. But it fails every time. Other tools works great but vectorize not. In the attached picture I have tried to cut a circle.

![whatsapp image 2018-06-27 at 21 07 43](https://user-images.githubusercontent.com/36729108/41991481-372c3aa0-7a4e-11e8-8095-b6888e241470.jpeg)

**Comment by StuartB4** [comment]
Do you still have the gcode for the circle?
if so can you post it here?
