### ISSUE TITLE
Sighting mode

### ISSUE THREAD

**Issue by tihant** [arkypita/LaserGRBL#390]
Whether it is possible to realize such function that on pressing a special button the laser was switched on in a sighting mode. This is necessary in order to correctly set the workpiece.
In this mode, a signal must be sent at 11 pin, at which the laser does not burn the workpiece.

**Comment by arkypita** [comment]
https://lasergrbl.com/usage/custom-buttons/

**Comment by tihant** [comment]
Thank you very much, I will try
