### ISSUE TITLE
Z-Axis Control

### ISSUE THREAD

**Issue by DUKEMURCIA** [arkypita/LaserGRBL#392]
Hola:
Sería posible añadir los controles para el eje Z, al igual que están para los ejes X e Y?
Gracias

**Comment by arkypita** [comment]
If you need to control Z axis for focusing, you can add a custom button.
If you need more control on Z (i.e. for cutting thick materials or deep map engraving) lasergrbl is not designed for it and add this feature is not in roadmap for now.

Note: english language is preferred here.
