### ISSUE TITLE
Presets

### ISSUE THREAD

**Issue by DUKEMURCIA** [arkypita/LaserGRBL#393]
Hola:
Sería posible añadir una opción para guardar las configuraciones de velocidad y potencia del laser?
Sería muy práctico para poder elegir esas configuraciones guardadas según el material que vayamos a utilizar.
Gracias

**Comment by arkypita** [comment]
I have plans to rewrite a lot of code for a new major version of LaserGRBL. One of the feature of the new version will be the ability of save and pick-up laser configurations.
Not a lot of time for now for working on this version :-(
