### ISSUE TITLE
More space for buttons

### ISSUE THREAD

**Issue by DUKEMURCIA** [arkypita/LaserGRBL#394]
Hola:
Quizás es que yo necesito más opciones preconfiguradas y por eso necesito más espacio para los botones personalizados.
Se podría añadir más espacio para botones, o un menú desplegable para macros?

Por cierto, este es sin duda el mejor programa para laser que he probado, sencillo y preciso, y con las mejoras que se van añadiendo poco a poco se va haciendo mucho más potente y útil.
Muchísimas gracias por un trabajo tan bien hecho.

**Comment by arkypita** [comment]
I think i can add some code to span buttons on multiple lines if there is no space to draw them in a single line. Added to #64
