### ISSUE TITLE
Laser not turn on

### ISSUE THREAD

**Issue by sankajalakshan** [arkypita/LaserGRBL#395]
i made the coreXY cnc machine and added a 2500mw 3p laser which has only 3 pins (vcc gnd pwm). and i connect vcc gnd to external power source (6A) and connect pwm to Z+ / D11 pin on the cnc shield. and im using the GRBL 1.1 (latset version) and i did not modified it.  however, when i passing the code through the lasergrbl laser did not turn one. when i press the weak light button the laser will turn on as a low light. but the burning is not working. i have no idea what happen. please help me to to solve this..
![1](https://user-images.githubusercontent.com/39721281/42458830-2ae96d44-83b8-11e8-8585-508ed3884b3d.jpg)
![2](https://user-images.githubusercontent.com/39721281/42458832-2c6a1c72-83b8-11e8-91a2-bf5bb08edd84.jpg)
![3](https://user-images.githubusercontent.com/39721281/42458835-2e046308-83b8-11e8-8687-8e00cf17e5d0.jpg)

**Comment by StuartB4** [comment]
You say " im using the GRBL 1.1 (latset version) and i did not modified it."
Did you enable laser mode $32 in GRBL settings? Enable it by changing the 0 to 1
Did you set $30 to 255 and $31 to 0 ?
![untitled5](https://user-images.githubusercontent.com/16980026/42471539-f41ca4fe-83b5-11e8-9d7e-c085e86e2a7d.jpg)

**Comment by sankajalakshan** [comment]
i have changed those settings. but i did not do any changes in config file or cpu_map file.

**Comment by StuartB4** [comment]
You might have a faulty laser. When the laser diode breaks it ends up looking just like an LED light.
So you would get the dim light but not it's not lasing. 
You could also have a faulty Arduino, do you have another one you can try?
It could also be bad solder joints on the CNC shield.
What is the power source for the Arduino, is it just from the usb (as mine is) or a seperate supply?

**Comment by sankajalakshan** [comment]
12V 6A power supply is used and week light is working. but laser not starting to burn.

**Comment by sankajalakshan** [comment]
Yes. Its the same power source

**Comment by arkypita** [comment]
> You might have a faulty laser

To be sure your laser is working you can detach it from the arduino side, and try to power it up giving necessary GND/VCC and put TTL at VCC to switch laser on. It should power up at maximum power.

If not, laser is death/faulty

Be care to your eyes

**Comment by arkypita** [comment]
> power it up giving necessary GND/VCC and put TTL at VCC

or leave it as connected and just move TTL (yellow cable) from Z+ to 5V like this

![cnc-shield01](https://user-images.githubusercontent.com/8782035/42513739-fa48bfaa-8457-11e8-8d39-60bb7112c922.jpg)

**Comment by StuartB4** [comment]
You can also try the yellow lead on the Z- because it is electrically connected to Z+.
If Z+ had a faulty connection then Z- should still work.

**Comment by kyroncfel** [comment]
Hi, did you ground the laser driver board to the arduino so that both share a common ground.

**Comment by StuartB4** [comment]
It should already be grounded, he said he's using the same power supply to power the laser and the Arduino.

**Comment by 1estrider** [comment]
When you are importing the image to what you have set the laser power?
You also could create a button for the laser on and off. Set the on to full power. You might have a faulty laser if that doesn't start burning.

**Comment by sankajalakshan** [comment]
sorry for the late replying. I think I had a faulty laser. so I ordered another new one and its working well. thank you all for your kind support.

**Comment by sankajalakshan** [comment]
my new laser is working. but I need to know how to engrave a photo with reducing the qulity

**Comment by StuartB4** [comment]
What do you mean by reducing the quality.
Do you want a lower quality engraving.
If so you can just change the amount of lines here:
![untitled](https://user-images.githubusercontent.com/16980026/43579016-98d98b7a-9648-11e8-92f1-15c9eba085f7.jpg)
