### ISSUE TITLE
LaserGrbl doesn't run

### ISSUE THREAD

**Issue by istruttoresp** [arkypita/LaserGRBL#398]
I built a cnc laser from old DVD looking some examples on web.
i was testing the the software and it was running at the beginning but then crashed.
i tryed to reinstall,  upgrade or dowgrade version, read allover the web looking some feature i was missing but...no resoult!
i read about java 8 but laserGrbl  works well before crush...now i can't start it again.

![immagine](https://user-images.githubusercontent.com/16006004/42762594-068bc8ee-8911-11e8-8cdb-3c87f6e149ee.png)

![immagine](https://user-images.githubusercontent.com/16006004/42762631-139355c0-8911-11e8-8515-95c514b6f79f.png)

**Comment by istruttoresp** [comment]
this is situation programs

![immagine](https://user-images.githubusercontent.com/16006004/42769497-8ebb820c-8922-11e8-8f16-579b89202e38.png)

**Comment by istruttoresp** [comment]
![immagine](https://user-images.githubusercontent.com/16006004/42769518-a0bca0a8-8922-11e8-86f6-9e76109225a6.png)

**Comment by istruttoresp** [comment]
i can't install 3.5... winzoz is big shit...

**Comment by istruttoresp** [comment]
sorry but... the tar.gz is for linux right? any instruction for installation?

**Comment by arkypita** [comment]
Why did you talk of tar.gz? LaserGRBL installer is .exe

**Comment by appolinari** [comment]
Hi! 
Can not run LaserGrbl on WinXP.
When starting, it gives an error message:
![image](https://user-images.githubusercontent.com/45756940/49728310-0b908e00-fc7b-11e8-85ff-c031bb39efc1.png)
My Win:
![image](https://user-images.githubusercontent.com/45756940/49728358-2bc04d00-fc7b-11e8-81ac-c87e26456223.png)

**Comment by StuartB4** [comment]
Looks like you may have to update Microsoft's .Net files.
Have a look here:
https://dotnet.microsoft.com/download/dotnet-framework-runtime

**Comment by appolinari** [comment]
Hello!
I deleted and re-installed NETFramework several times. Used also the recovery utility. But it did not work. I think the fact is that laserGrbl cannot work with NETFramework version 4.0. 
I just can not install on WinXP NETframework newer than 4.0.
Does anyone use a laserGrbl with WinXP?

**Comment by arkypita** [comment]
LaserGRBL use framework 3.5

![image](https://user-images.githubusercontent.com/8782035/49739617-992ba800-fc92-11e8-9b2b-c849db3fb322.png)

Work on XP

![image](https://user-images.githubusercontent.com/8782035/49740589-d98c2580-fc94-11e8-856b-7f5d746c5e99.png)

**Comment by appolinari** [comment]
HI!
Thank You! 
With N.fw 3.5 it works!

**Comment by MARVINU** [comment]
I´m using windows 10 64x. I ran many times the software LaserGRBL but, some time ago I´ve tried to run, the first screen appear but after the program did not run. What can be wrong with?
