### ISSUE TITLE
allow to delete some vectorized shapes with mouse

### ISSUE THREAD

**Issue by owai1980** [arkypita/LaserGRBL#399]
It would be nice if we could select and delete some vectorized shapes. This would allow us to print the drawing on wood, and after we could use the same input file to keep only the cut shape. (and repeat this shape several times to cut the wood, with a stronger power)

this will require to detect on witch shape the user clicks... not always easy with strange shapes :-)

i hope you understand what i mean, sorry for my english...

**Comment by StuartB4** [comment]
Nice idea.
Don't apologise for your english, it's better than some of the english speaking people I know, and I'm english. :)

**Comment by StuartB4** [comment]
A way of doing it without any program changes would be to make 2 identical drawings.
One for the first burn and one with only the vectors you want to go over to cut out.
Just load the second one in after burning the first one.

**Comment by owai1980** [comment]
thanks :)
yes, this is how i do it now... and it works, but i have to be careful about the sizes / scale. it's ok. but... if you need ideas for the future... maybe it's a good one :-)

btw, thank you a lot for this software, very nice piece of code!! and open-source!

**Comment by arkypita** [comment]
With the actual drawing code it is not possible, once preview is drawn, to recognize the source file by clicking on picture.
