### ISSUE TITLE
Whats the best way to set the home position?

### ISSUE THREAD

**Issue by midibase** [arkypita/LaserGRBL#40]
Hello,
I would like to set the home position, but who do I that?

My solution is now:
I add a button with "G92X0Y0" to set the home position. The lasermaschine set it right, but
the graphicUI do not set it- This mean the cross in the graphic stand still on the last position.
Homing button doesn't work (($H setting disabled)

So is there any solution to tell the programm-->please set the cross also an the zerro position?
bg fritz (from Austria)

**Comment by arkypita** [comment]
There is a closed issue about this.
https://github.com/arkypita/LaserGRBL/issues?q=is%3Aissue+is%3Aclosed

**Comment by midibase** [comment]
Thanks. It helped

lg

 

Von: arkypita [mailto:notifications@github.com] 
Gesendet: Freitag, 19. Mai 2017 12:31
An: arkypita/LaserGRBL <LaserGRBL@noreply.github.com>
Cc: midibase <midibase@gmx.at>; Author <author@noreply.github.com>
Betreff: Re: [arkypita/LaserGRBL] Whats the best way to set the home position? (#40)

 

There is a closed issue about this.
https://github.com/arkypita/LaserGRBL/issues?q=is%3Aissue+is%3Aclosed

**Comment by arkypita** [comment]
[Version v2.8.12](https://github.com/arkypita/LaserGRBL/releases/tag/v2.8.12) can now show working position if different from machine position.
