### ISSUE TITLE
Button for turning the laser on.

### ISSUE THREAD

**Issue by 1estrider** [arkypita/LaserGRBL#406]
I was wondering if there would be possible to have a button that turns the laser on manually with 1/4 of the power (or something like that) so I can position my work and also adjust my laser beam?

**Comment by StuartB4** [comment]
You can make a custom button.

I use GRBL 1.1 which has $32 set to 1 to enable laser mode.
This can be set from within LaserGRBL.
Click the Grbl menu (top left) and select "Grbl configuration"
look down the list for $32, move across and change the value from 0 to 1.
Then click the "Write" button at the bottom. That will save the setting in GRBL.

LaserGRBL 2.8.50 lets you use 1 button to do 2 things.
Just right click on an empty space on the bar with the buttons on at the bottom
and click "Add Custom Button"

![untitled3](https://user-images.githubusercontent.com/16980026/43431637-b9af189e-9466-11e8-8403-ea6639806bb1.jpg)
 
This is mine to switch laser on and off with one button.

![untitled](https://user-images.githubusercontent.com/16980026/43431174-79400bb2-9464-11e8-8d75-b31da0260d3b.jpg)

GCode.
$32=0 switches it out of laser mode.
M4 switches laser on to allow you to focus.
S255 is the laser power set to maximum, a quarter power is approx 64.
But you can set it to anywhere between 0 lowest and 255 highest.

GCode 2.
$32=1 switches back to laser mode.
M5 switches laser off after you have finished manually moving/focussing.

**Comment by 1estrider** [comment]
Thank you so much! This helps so much!  I ended up setting on S20, 1/4 power was still burning the mark on the cardboard.
