### ISSUE TITLE
Adding $32 line to GRBL config

### ISSUE THREAD

**Issue by 1estrider** [arkypita/LaserGRBL#407]
I am experiencing laser burning in the end of the each line. My GRBL configure window however does not have $32 line. Is the a way to add that line? I have 2.8.51 LaserGRBL version.
Thank you!

**Comment by StuartB4** [comment]
You need to update GRBL to version 1.1

**Comment by 1estrider** [comment]
Okay, I am as green as they come! Where do you find 1.1 version? Went to their website and couldn't on their links.

**Comment by dungjk** [comment]
Here you are.
https://github.com/gnea/grbl
Click button "Clone or download" > "Download ZIP"

**Comment by 1estrider** [comment]
Awesome! It worked! I have now $32, as well many other goodies!
Thank you!
