### ISSUE TITLE
DXF or other vector file support

### ISSUE THREAD

**Issue by DimchikUA** [arkypita/LaserGRBL#408]
Hello, arkypita!
Can you add support for DXF files to this program.
It would be good to burn not only bitmap pictures, but also some exact drawings, importing from different CAD software into a DXF file.
I think there will be enough simple passage through the lines with optimization for the shortest path.

I understand that there is GRBL-Plotter. But it is more complicated. In order to sometimes just run the laser down the line, I would not want to install it and set it up.

It would be very helpful!

**Comment by arkypita** [comment]
already in #64
