### ISSUE TITLE
How do you change the origin for the project?

### ISSUE THREAD

**Issue by beardedheathen** [arkypita/LaserGRBL#410]
Sorry don't know where else to ask. As far as i can tell i've got the grbl stuff set up right. It homes correctly for the origin being in the top left but when i import gcode into LaserGRBL it has the origin in the bottom left and tries to go that way directly into the end stop.

**Comment by dfox1787** [comment]
I also want to know this

**Comment by arkypita** [comment]
Set grbl conf with $$ to invert motor direction. Google for "grbl configuration"

**Comment by dfox1787** [comment]
and allows me to set origin to the centre of a project? or top right?

**Comment by beardedheathen** [comment]
Oh i did figure out that you can hit the globe button to set to zero.
@dfoxy that helped fix my problems.

**Comment by dfox1787** [comment]
But that just zeros the x and y. 

Im wanting to know how to set work coordinates

**Comment by mayhem2408** [comment]
If your machine coordinates have 0,0 in the top left, this means botton left must be in the negative. You need to zero you work coordinates  to the zero you want. You need to jog to the bottom left and zero the Y axis to set the work coordinates 0,0 in the bottom left. If you want 0,0 to be somewhere else, just jog there and zero the work coordinates again.

**Comment by dfox1787** [comment]
i know how to zero the machine. I have cnc and when i create a job i can choose where the start point is. 

Id like to do the same in grbl. Set wcs to center for example.

thank you

**Comment by mayhem2408** [comment]
@dfox1787 Machine coordinates and work coordinates are two different things. I'm obviously not understanding what you are trying to do.

**Comment by dfox1787** [comment]
:)
