### ISSUE TITLE
Laser Power

### ISSUE THREAD

**Issue by dfox1787** [arkypita/LaserGRBL#412]
How do you adjust the power?

If im wanting to engrave i dont need full power but if i want to cut then how to i set full power?

**Comment by StuartB4** [comment]
If you are engraving a picture in greyscale then LaserGRBL sets the power levels when it generates the gcode. That is using Line To Line engraving.
If you want to cut then you use Vectorize.

In Vectorize the power is set to maximum 255 in the first few lines of code.
S255 in this example. 

G90
G0 X0 Y0
M5 S255
F1000
G0 X6.042 Y25.378
M4
G1 X5.6 Y24.778
.................
You can edit it to whatever power you want between 0 and 255 for the different power levels
and save it, then load it back in.

The F1000 is the speed the laser moves in mm's per minute.

So F100 will move slower than F1000.
