### ISSUE TITLE
Jogging Mode con Joystick

### ISSUE THREAD

**Issue by oliveritech** [arkypita/LaserGRBL#413]
Prima di tutto...complimenti per aver sviluppato e reso pubblico questa fantastica front end GRBL grazie.
E possibile implementare l'utilizzo di un Joystick per posizionare il laser anziché utilizzare la tastiera?

**Comment by arkypita** [comment]
Grazie.
Penso di si, ma in questo momento non riesco a valutare bene la fattibilità. Se è fattibile lo aggiungo in roadmap.

Ps. È preferibile usare l'inglese cosi anche altri capiscono

**Comment by oliveritech** [comment]
Yes I will from now on, thank you
