### ISSUE TITLE
Sound when finishing a lob

### ISSUE THREAD

**Issue by christos-xithalis** [arkypita/LaserGRBL#414]
ok, this is a very simple request: the program plays a sound, custom or predetermined, to let you know when it has finished a job.
Thank you!

**Comment by arkypita** [comment]
Already in dev roadmap

**Comment by gerdvogel** [comment]
one question: when will the desired function be available?
I have a lot of wooden discs to laser and I am still working on other projects in my workshop on the side and sometimes I forget the laser and I don't get finished with the laser in time, if there would be a sound I could interrupt my active activity and put a new disc on the lasers.

**Comment by gmmanonymus111** [comment]
My version now has a limited sound support, if you want, you can build that. I want to add the ability to change sounds and volume before opening a pull request, that's why it is delayed

**Comment by gerdvogel** [comment]
Thanks for the answer.
