### ISSUE TITLE
Laser burns project on free hold

### ISSUE THREAD

**Issue by dfox1787** [arkypita/LaserGRBL#415]
If i want to pause my project by pressing freehold. the laser stays on and just burns a hole in my project. 

Same happens if i just use the halt or stop button.

**Comment by arkypita** [comment]
This is a standard behaviour in grbl that is native for cnc machine where a stop cause only a motor stop with spindle remaining active.

This cannot be controlled by lasergrbl. The only way is to upgrade your hardware to grbl v1.1 with the new features called "laser mode"
