### ISSUE TITLE
0.9 connects but 1.1 throws: Connection Timeout!

### ISSUE THREAD

**Issue by TravisBarker** [arkypita/LaserGRBL#416]
When attempting to connect LaserGRBL while using GRBL 0.9 everything works flawlessly. After flashing the device with GRBL1.1 it says "Connecting" then "Disconnected"  and the log shows "Connection Timeout!" 

I am using the same (correct) COM port settings and once I revert to GRBL0.9 it resumes working again. 

are there changes to GRBL in 1.1 that would cause this issue?

**Comment by arkypita** [comment]
No.
Maybe different baud rate?

Others software like universal gcode sender works?
