### ISSUE TITLE
Few ideas, Rotary and center image, make tutorial on custom buttons gcode

### ISSUE THREAD

**Issue by rolx95** [arkypita/LaserGRBL#418]
Hello, I use LaserGRBL a lot and really like it, so I would like to help you impove it with some ideas.
- Coordinates input, sometimes I exactly know where I need my laser dot in coordinates but moving it with the panel is somehow time consuming, so I think maybe some X Y coordinates field in lower left corner would be great, I know I can offset the image but it would be more user friendly this way.

- Rotary support, I made a rotary jig for engraving in wood so I would like to help with setting up the rotary. It is not that hard. All you need to do is manually change the $100, $101 value for your axis. So the order of commands would be something like this (I think). Button in Import raster image for turning on rotary - which axis - X or Y ($100 or $101)- read current value and remember it somewhere in memoty or reset it after finishing job (I am not sure if you can reset just $100 or you have to refresh whole GRBL settings). Make standart changes to the image you need. After Next ( in Targer image) under the size and image of the I would put two fields- either Circumference (C ) or Diameter (D) value insert. Now comes the calculating part, After inserting values for C or D, you need to recalculate it into circumference always. Next you put the C in this formula: (200*microstepping)/circumference=x.
X is now the value for $100, $101 (steps per mm). Voila and you are now rotary engraving. 
(there is a catch, I personally use eleks maker A3 and the standart microstepping is 10us ($0). with the formula above if I have a dowel with C of 220mm, it should be (200*10)/220=9,09. But, if I put this value into the $100, it does not do the whole circle. It works with standart microstepping of 16 microseconds as presented in source diymachining. I do not know why. So the formula for Eleks maker or their Mana SE is (200*16)/220=14,54. Now it makes a whole circle. )

- DXF support, I know you are working on it, I am just another guy who would really appreciate it. 

- Vectorizing center of lines. Dont know how to say it. Think of a png file of a thunder. 
![obrazek](https://user-images.githubusercontent.com/42325077/44006455-0d857dfa-9e85-11e8-82e1-4d5a45740baa.png)
 I do want it vectorize, but I dont want to have the cloud vectorize inside of the black cloud and outside, instead, I want one center line. Imagine the laser dot to be as thick as the black cloud. 

That is for now all I can think of, I am possitive there were more things but these are the ones I can think of today. I will be posting more as I run into more ideas, oh and I need help with costum button.

Most of the time I want to engrave something into the center of a rectangle board or center of a circular board. What I do is, I find the center of the board with a ruler and make a cross with pencil, then I put it under the laser and after that, I manually send the laser to the center with the lower left buttons. After I reach the center and am sattisfied, I have to set zero coordinates, and calculate manually, divide width and height by 2 and with lower left buttons send the laser dot to lower left corner (true zero coordinates for the start of a job), then set zero.
Could someone help me desing a costum button ? I use the one that someone posted here a while ago, that is move to center of a image, G0 X[left+width/2] Y[bottom+height/2] . Would my be the same but instead of + there would be - ? I really dont get these costom buttons, maybe someone could make a tutorial on these, like Roudabout, this is really helpful, but I have absolutely no idea what is happening in this gcode 
G00 X[left] Y[top/2-bottom/2+bottom] F1000
M4 S1
F1000 
G02 Y[top/2-bottom/2+bottom] I[top/2-bottom/2]
M5
G00 X0 Y0 F1000
.
Thanks.
(here are the sources I used for figuring this out https://www.machsupport.com/forum/index.php?topic=16260.0,  http://www.diymachining.com/grbl-settings-101-a-how-to-guide/ )

**Comment by arkypita** [comment]
> Hello, I use LaserGRBL a lot and really like it, so I would like to help you impove it with some ideas.

Enjoy you like LaserGRBL

> Coordinates input

There is a textbox to send gcode commands manualy: just type G0 X120 Y200 to fast move @ 120,200

> Rotary support, I made a rotary jig for engraving in wood so I would like to help with setting up the rotary.

It is difficult for me to implement because I cannot test it without having a rotary jig

> DXF support, I know you are working on it, I am just another guy who would really appreciate it.

Already in roadmap #64 

Vectorizing center of lines. Dont know how to say it. 

Already in roadmap #64
