### ISSUE TITLE
Dark lines

### ISSUE THREAD

**Issue by kimbo001** [arkypita/LaserGRBL#421]
Hi

After some trails i am giving grey scale a try but i get dark lines on the borders. like the laser switch on with a higher power and regulate to a lower power, if i burn horizontal i get them and the horizontal borders, vertical on the vertical borders and diagonal i get them on al four borders

2.5mW laser on Mana SE clone laserGRBL software GRBL 1.1f

**Comment by StuartB4** [comment]
Have a look here:
https://github.com/arkypita/LaserGRBL/issues/373
and here:
https://github.com/gnea/grbl/issues/34

**Comment by kimbo001** [comment]
Thank you

How do i change the M3 to M4 it does not appear in the drop down

**Comment by StuartB4** [comment]
What version of GRBL do you have?

**Comment by StuartB4** [comment]
Do you have Laser mode enabled in GRBL configuration?
![untitled](https://user-images.githubusercontent.com/16980026/44308966-bf150000-a3b6-11e8-91ce-4b4a25e9f0a5.jpg)

**Comment by StuartB4** [comment]
Click the Write button on the bottom of the GRBL config window, where you changed it.

**Comment by kimbo001** [comment]
Thank you

**Comment by StuartB4** [comment]
Just a thought, do you have the 2 settings just above the Laser enable setting the same as mine. $30 and $31.
They should be $30 255 and $31 0
That sets the laser power for PWM mode. Min power = 0 and Max power =255.

**Comment by StuartB4** [comment]
Can't think why at the minute, do you have your laser focussed correctly.

**Comment by kimbo001** [comment]
I will double check it. For some reason my $32 is not saving, all my other settings save but not that one, i even exported it, opened with notepad, made the changes and re-upload again but still not saving

**Comment by kimbo001** [comment]
Apologies for asking , but i never done a hex file in Arduino IDE can you help me please

**Comment by StuartB4** [comment]
Sorry, I don't use the Hex file.
I upload the GRBL source code (Version 1.1f) from the zip file here:
https://github.com/gnea/grbl/releases

This tells you how to do it but it's a couple of years old now and mentions version 0.9j, but you should get the Version 1.1f zip.
https://github.com/grbl/grbl/wiki/Compiling-Grbl

Then change any settings using the Serial Monitor in the Arduino IDE and re-compile it and re-upload it to the Arduino.

**Comment by kimbo001** [comment]
Here is the vid of the app not saving https://youtu.be/i5VK8_LPmKA
Maybe you can see what i am doing wrong

**Comment by StuartB4** [comment]
Oh yeah. It saves it until you actually connect to the com port, thats strange.
You seem to be doing everything correctly.
I hope you dont mind but I just opend an Issue on the GRBL site to see if anyone else has any ideas about what is happening, I included the video link you supplied.
Now we just have to wait to see if anyone replies.

One option you could try is to remove the Com port and let Windows reinstall it.
I just tried it and once it's removed it reinstalls it again.
See here:
https://youtu.be/cccKdNG8oYQ

**Comment by kimbo001** [comment]
No Problem

I will do everything from start, uninstall the driver and then reinstall and see what it does

**Comment by kimbo001** [comment]
Nope still get the same result

**Comment by StuartB4** [comment]
Oh yeah. Haha, can't believe I did'nt think of that. Glad thats sorted out.

**Comment by arkypita** [comment]
> Here is the vid of the app not saving https://youtu.be/i5VK8_LPmKA
> Maybe you can see what i am doing wrong

Maybe you can have a look at the clear red message that say "read and write enabled only when connected and idle"?

![image](https://user-images.githubusercontent.com/8782035/44647725-2cd8b180-a9df-11e8-891a-f5b516b5bf5a.png)

**Comment by kimbo001** [comment]
Hi

Did you look at the whole Verdi?

 did connect it before i saved

when i reconnect after the shut down it did not save

**Comment by arkypita** [comment]
Sorry, i was superficial. Now i have seen the whole video.

> In settings there is a soft reset ticked by default, untick and now it saves

Sound strange to me: soft/hard reset configuration should not affect grbl configuration at all.

I have tried the same sequence and saving is working for me, with and without soft reset.

**Comment by kimbo001** [comment]
Yea i get sometime it saves some time it does not save, i checked the hardware nothing weird i even tried other firmware i still get the same. I am trying to eliminate anti virri software but time is not on my side. Very nice software BTW i really like it

**Comment by kimbo001** [comment]
Done this with a 500mw laser at F1000
![img_20180827_100938 2](https://user-images.githubusercontent.com/42435356/44648709-2ef03f80-a9e2-11e8-9239-7d966681887e.jpg)
