### ISSUE TITLE
Laser skipping lines

### ISSUE THREAD

**Issue by Dennisrsa** [arkypita/LaserGRBL#425]
What would be causing my laser to skip lines during the engraving process? It doesn't always occur in the same place. Thanks for any advice.
![laser](https://user-images.githubusercontent.com/38247268/44583361-45f61e00-a7a5-11e8-9294-3284daf594d6.png)

**Comment by owai1980** [comment]
try to run the program slower...

**Comment by owai1980** [comment]
or activate "microsteps" on your stepper motor (and ajust the setting in grbl config), this will make the whole process more fluid, even at high speed

**Comment by brakthehun** [comment]
Look like you're using a laser that has the rubber wheel that roll along the extrusion. Check for wobble or play in your machine.
