### ISSUE TITLE
Custom button - Framing

### ISSUE THREAD

**Issue by kimbo001** [arkypita/LaserGRBL#432]
Hi

I am not a GRBL coder can somebody help me i want to frame my work but it must have a 10mm offset

**Comment by StuartB4** [comment]
10 mil X and Y ??

If so this should do it.
Create a custom button by Right clicking on an empty part of the bar at the bottom of Lasergrbl window, where the little man and hand icon.

Copy and paste this as it is in to the GCode box:
F100
M4 S255
G0 X10 Y10
G0 X[left] Y[bottom]
G1 X[right]
G1 Y[top]
G1 X[left]
G1 Y[bottom]
G0 X0 Y0
M5


Add a Tooltip, that just pops up when you move the mouse over the button so you know what it does.
Click Save button.

The F100 is the Speed. Change this to suit you.
M4 is Laser On. The S255 is the Laser power, change that to suit yourself between 0 and 255.
The G0 X10 and Y10 are the Offset setting.
If you just want X10 offset then leave out the Y10 and the same if you just want the Y10 offset, leave out the X10.

![offset](https://user-images.githubusercontent.com/16980026/44950811-afcb9300-ae49-11e8-9830-ab168c40031c.jpg)

**Comment by kimbo001** [comment]
Thank you very much :)

**Comment by StuartB4** [comment]
Thats a better option than the one I posted.
You get a frame 10mm away from the image, my option only framed 10mm away the home position
but right up to the image.

**Comment by kimbo001** [comment]
Thank you :)

**Comment by StuartB4** [comment]
> continue jogging possibility ?
Please explain what you want to do.

**Comment by manisaranbala** [comment]
X Y Z AXIS CONTINUE MANUAL KEY PAD MOVE

**Comment by arkypita** [comment]
@manisaranbala 

Continuos jogging is not possible because grbl protocol does not support this. Because jog command are queued a user can easily queue up more motions than he want without realizing it and move well-past desired location.

P.s. please do not post "ad mentula canis" under other user thread. If you have a question or an issue, please open a new issue for your request.

**Comment by arkypita** [comment]
@kimbo001 

> I am not a GRBL coder

GCode is very simple. Google for some tutorial www.google.it/search?q=gcode for beginner
There is a lot of video on youtube too.

**Comment by manisaranbala** [comment]
https://github.com/gerritv/Grbl-Panel/tree/master/RepeatButton
