### ISSUE TITLE
Custom button - centre

### ISSUE THREAD

**Issue by mooseuk** [arkypita/LaserGRBL#433]
Hi,
What is the code to create a custom button to find the centre of an image.
I have a custom button to show the frame but to find the centre also, would be a great help.

Thanks

**Comment by vaicekas** [comment]
Center Image

G0 X[left+width/2] Y[bottom+height/2]
G1 M3 S1 F100

**Comment by mooseuk** [comment]
Thank you so much

On 5 Sep 2018, at 07:50, vaicekas <notifications@github.com<mailto:notifications@github.com>> wrote:


Center Image

G0 X[left+width/2] Y[bottom+height/2]
G1 M3 S1 F100

**Comment by StuartB4** [comment]
If you use the TwoStateButton option in the dropdown on the Custom button options and add this:
G0 X0 Y0
M5
It will switch the laser off and return home when you click the button a second time.

**Comment by vaicekas** [comment]
Great idea! ;)

**Comment by arkypita** [comment]
www.google.it/search?q=gcode for beginner
