### ISSUE TITLE
Reload same drawing

### ISSUE THREAD

**Issue by fantilator** [arkypita/LaserGRBL#435]
Is it possible to add a button or shortcut to reload the same drawing after a change of the code.
This would make it easier for trial and error and troubleshooting when your machine is not doing what you want.

Thanks

**Comment by gisep** [comment]
I think that "ctrl+O,enter" is as the same as the shortcut, no?

**Comment by vaicekas** [comment]
Reopen Last File - "ctrl+R"

**Comment by fantilator** [comment]
Thanks, I have overlooked it.
