### ISSUE TITLE
build need admin privilege, why?

### ISSUE THREAD

**Issue by frobgm** [arkypita/LaserGRBL#44]
Hello
I try to build yours progam with visual studio 2017 community, but VS talk need admin privilege.
What is the important that need admin privilege?

thanks!
Robert

**Comment by arkypita** [comment]
Note: not the build itself require admin privilege, but "build and run" require it. This is the same also on my computer.

LaserGRBL is able perform self-update unpacking new version inside its own program folder, and overwriting its own executable/dll files. To do that, it must run as administrator.

To force LaserGRBL run as administrator I put the flag "requestedExecutionLevel=requireAdministrator" in app.manifest. I would prefer that LaserGRBL do not need this escamotage, but so far I have not found a simpler way to perform self update.
