### ISSUE TITLE
any way to add z-axis

### ISSUE THREAD

**Issue by dhigdon45** [arkypita/LaserGRBL#449]
I was wondering if is a way to add a z-axis for those of us with cnc machines?

**Comment by arkypita** [comment]
What do you mean?

- You can already manage Z axis manually sending GCodes from box, adding custom button to jog Z etc...
- You can load any GCode (including GCode that move Z axis) and LaserGRBL can stream them

If you mean "preview 3D job" it is not possible. I am using 2D drawing primitives to render the preview, so 3D is not available. 

If you mean a better handling of Z on resume, look at this fresh new release: https://github.com/arkypita/LaserGRBL/releases/tag/v2.8.53
