### ISSUE TITLE
Laser Head move (full speed with no laser) to show working area before engraving

### ISSUE THREAD

**Issue by Killthgz** [arkypita/LaserGRBL#450]
As the topic, is it possible to do that? if so I think this will help to align material before engraving or cutting.
I ever see this function in youtube. LaserHead will move as square at the edge of engraving area. Thank you.

**Comment by StuartB4** [comment]
![untitled1](https://user-images.githubusercontent.com/16980026/46215264-dee40000-c334-11e8-96df-bc993952c5a5.jpg)

![untitled2](https://user-images.githubusercontent.com/16980026/46215276-e4d9e100-c334-11e8-94bf-589fd54d2fb3.jpg)

Changing the F setting will change the speed, up to the maximum your machine is set for in GRBL.

You can copy and paste this code:
F1000
G0 X[left] Y[bottom] 
G1 X[right]
G1 Y[top]
G1 X[left] 
G1 Y[bottom]

**Comment by Killthgz** [comment]
Wow!! perfect!!!
Thank you very much for your advice ^____^. @StuartB4
