### ISSUE TITLE
Does anyone know what firmware compatible with LaserGRBL on Arduino DUE board?

### ISSUE THREAD

**Issue by Killthgz** [arkypita/LaserGRBL#452]
First of all, I want to tell you that I am now planning to make high speed GALVO engraver by following step;

LaserGRBL (computer) <------> Arduino UNO <------> MY CONTROLLER  <------> GALVO Scanner and CO2 laser 60W.

MY CONTROLLER (nucleo stm32 200MHz) can read linear position from UNO by interrupt reading step pin and dir pin then convert to angular position for galvo.

The problem is that the UNO has low stepper frequency (about 20kHz). It's unable to achieve my desired speed. Thank you for any help.

For more information about galvo engraver:
https://www.youtube.com/watch?v=YhOleKUe6MM

**Comment by arkypita** [comment]
ask to grbl page https://github.com/gnea/grbl

**Comment by Killthgz** [comment]
Sorry about the mix up and thank you for your advice @arkypita
