### ISSUE TITLE
Laser M4 command

### ISSUE THREAD

**Issue by Obewon909** [arkypita/LaserGRBL#453]
LaserGRBL M4 command not available in software when computer connected to laser it is visible when the computer is NOT connected . I'm running LaserGRBL v2.9.0 .  If I need to access the firmware on this I need to know how ,

**Comment by arkypita** [comment]
M4 is available if you connect to grbl v1.1
M4 is not available if you connect to grbl 0.9 or older

when disconnected LaserGRBL remember last version.
