### ISSUE TITLE
Override settings

### ISSUE THREAD

**Issue by christos-xithalis** [arkypita/LaserGRBL#454]
I'm running grbl 1.1 on a 40W arduino based CO2 laser cutter, when i try to override the G1 settings to make the laser move faster it also affects the laser power, ie. if i put the G1 slider to x1.10 then although the S slider remains at x1.00 the power output is increased by 10%. Is this how it's supposed to be or am i doing something wrong?
Thank you!

**Comment by arkypita** [comment]
This is not related to LaserGRBL.
override are managed by grbl firmware on your board

**Comment by christos-xithalis** [comment]
Thanks for the reply!
