### ISSUE TITLE
PolyLineSegment class in Mono

### ISSUE THREAD

**Issue by tomreed81** [arkypita/LaserGRBL#460]
I am trying to update the Linux branch with the latest master branch changes. The last hurdle is the PolyLineSegment object in LaserGRBL/LaserGRBL/SvgConverter/GCodeFromSVG.cs

The compile error is : 
git/LaserGRBL/LaserGRBL/SvgConverter/GCodeFromSVG.cs(24,24): Error CS0246: The type or namespace name `PolyLineSegment' could not be found. Are you missing an assembly reference? (CS0246) (LaserGRBL)

Do you have a suggestion how to resolve this class? I can't find any solutions searching around.

**Comment by arkypita** [comment]
PolyLineSegment is part of PresentationCore.dll don't know if it is supported my mono.
However... did you get LaserGRBL working in mono? I had a lot of try some time ago but nothing... too much issue with the UI.

**Comment by tomreed81** [comment]
I got the Linux branch to compile and run as is. I saw the same window sizing issues in the other issue. I am going to have a go at fixing it. I am new to Mono and C# so it may take a while. :smile: 

The PolyLineSegment error happened after merging master->Linux branch. I'll see if I can find a replacement.

Thanks for responding :exclamation:

**Comment by arkypita** [comment]
if you check out latest version, i have removed PolyLineSegment from code
