### ISSUE TITLE
weak laser area preview

### ISSUE THREAD

**Issue by unkaMoMo** [arkypita/LaserGRBL#463]
Litefire has this great feature which turns on the weak laser beam and outlines the work area giving a chance to be certain where the burn will be on the workpiece.

**Comment by StuartB4** [comment]
This Custom Button draws a box around the image to be engraved with low laser power.
Use this after you have prepared your image for burning.

![custom](https://user-images.githubusercontent.com/16980026/47249130-ca60c800-d407-11e8-8804-bbaaabc75276.jpg)

![custom2](https://user-images.githubusercontent.com/16980026/47249133-d0ef3f80-d407-11e8-99b5-821f3b6e9e65.jpg)

This is the GCode, you can copy this and paste it in to the GCode box.

M4 
S5
F300
G0 X[left] Y[bottom] 
G1 X[right]
G1 Y[top]
G1 X[left] 
G1 Y[bottom] 
G0 X0 Y0 F4000
M5

Explaination of code.
M4 Switches Laser ON.
S5 is the power setting. This can usually be anything from 0 min power  to 255 max power.
F300 is the speed setting and can be changed to suit you.
The next 5 lines draw a box around the image engraving area.
The next line moves the laser to the Home position at a speed to suit you.
M5 switches the laser OFF.

**Comment by StuartB4** [comment]
Another useful button is a 2 State Button.

![custom3](https://user-images.githubusercontent.com/16980026/47249327-27f61400-d40a-11e8-98da-86cd371ad7e6.jpg)

GCode for box 1:
G0 X[left+width/2]
Y[bottom+height/2]
G1 M3 S1 F900

GCode for box 2:
G0 X0 Y0
M5

Tooltip text:
Click to find center of image. Click again to switch laser off and return home.
M5

**Comment by unkaMoMo** [comment]
That worked perfectly. Thanks for the quick reply. I think  I've found the software to use from now on.
