### ISSUE TITLE
LaserGRBL codename Rhyhorn

### ISSUE THREAD

**Issue by arkypita** [arkypita/LaserGRBL#465]
Hi all!

I have released a new version of LaserGRBL that include **centerline vectorization**.
This feature was requested by a lot of user and complete LaserGRBL with a "must have features" for all who need a simple way to engrave images.

This release was released as a pre-release so it is not automatically updated. 
To those who want to test it I recommend downloading the installer from: [here](https://github.com/arkypita/LaserGRBL/releases/download/v3.0.0/install.exe)

**Comment by StuartB4** [comment]
Ok. Yes I see your point, good idea.
Thankyou.

**Comment by aMirMOsavi** [comment]
Hi **MR**
The new **Centerline** feature does not work
It only shows the _progressBar_ but nothing happens
:(

**Comment by arkypita** [comment]
Hi @aMirMOsavi 
Can you try to reinstall LaserGRBL? In a first moment I have released a first version with a bug (now solved).

If nothing change:
LaserGRBL use an external executable (autotrace.exe) located in C:\Program Files (x86)\LaserGRBL\Autotrace for centerline tracing. Please check if is not blocked by antivirus. At last, try to run LaserGRBL with administrator privileges.

let me know

**Comment by aMirMOsavi** [comment]
**Thank you** for Your answer
The problem was **solved** - my installation _place_ was another drive.
I think it's **better** if it finds the **autocenter.exe** file from the application location
I mean, for example
`C:\Program Files (x86)\LaserGRBL\Autotrace\Autotrace.exe`
change to:
`.\Autotrace\Autotrace.exe`
