### ISSUE TITLE
Faster Laser-Engraving-Mode

### ISSUE THREAD

**Issue by Alibaba0815** [arkypita/LaserGRBL#469]
I have an Idee for an fast engraving mode.
Line-by-Line in differend ways is slow, but you got filled Forms.
The Vector-Modus is fast, but you got only the Outline.
The Combined Method bings the best results, but is also only slow.

But what is, when an outlined form would be written again and again.
Every single time the diameter shrinks, til the Form is filled.

I think that would significantly speed up the entire engraving process.
After each process, the path of the laser would be smaller and thus each passage faster than the previous one. Probably gray values can not be implemented, but for black and white graphics, letters and logos this would certainly be a good method.

Could something like this be realized?

**Comment by arkypita** [comment]
It's something I've already thought of in the past, but it's not easy to do (aka not impossible but require too high amount of work).

Vector graphic converted from raster does not use native type of my code, and it is translated directly to gcode, so I cannot deal with them. Doing that in gcode is difficult.
Moreover, even if I had the import into native types, there are no built in function for shrinking path.

There is a talk about shrinking path in .NET but no solution seem to work well: https://stackoverflow.com/questions/4552008/net-opposite-of-graphicspath-widen

Actually LaserGRBL does the trick by rasterizing black path and using Line2Line algorithm to generate filling.
