### ISSUE TITLE
M3 / M5 issues

### ISSUE THREAD

**Issue by Grizz5280** [arkypita/LaserGRBL#471]
The M3 and M5 commands aren't working when I type them into the generator by hand. I can load a file in and it works just fine, even in greyscale. 

I am using the command M3 S65 to try and turn the laser on low power so I can focus and home it. I have no idea what the issue could be with it. Any ideas?

**Comment by StuartB4** [comment]
Just tried and for some reason typing M3 S10 and pressing Enter does'nt work.
But if I do it the same and then press the little house/home button the laser comes on.
M5 and Enter switches it off.

**Comment by StuartB4** [comment]
Why not just use a Custom Button.
Just Right click on a blank part of the bar at the bottom of the main window and Add Custom Button.
![untitled2](https://user-images.githubusercontent.com/16980026/47521306-97e12000-d88a-11e8-9998-cb666cca9b6d.jpg)

This one switches laser on with first click and off with the second.

![untitled](https://user-images.githubusercontent.com/16980026/47521351-b0e9d100-d88a-11e8-88ed-787be7495f9f.jpg)

**Comment by arkypita** [comment]
> The M3 and M5 commands aren't working when I type them into the generator by hand. I can load a file in and it works just fine, even in greyscale.
> 
> I am using the command M3 S65 to try and turn the laser on low power so I can focus and home it. I have no idea what the issue could be with it. Any ideas?

This is by design with grbl laser mode enabled.
If laser doesn't move it is switched of regardless of M3, M4 S

https://github.com/gnea/grbl/wiki/Grbl-v1.1-Laser-Mode

By the way this has nothing to do with LaserGRBL itself because this behaviour is managed by grbl firmware.
