### ISSUE TITLE
 The program can not see USB ports

### ISSUE THREAD

**Issue by wilu9500** [arkypita/LaserGRBL#473]
![bez tytulu](https://user-images.githubusercontent.com/35997091/47576167-151c9b80-d944-11e8-9dac-521d1b65a6e7.png)

**Comment by StuartB4** [comment]
Go in to Device Manager in Windows and make sure your Com Ports are ok, and if you are using an Arduino make sure it's showing on one of them.

![untitled3](https://user-images.githubusercontent.com/16980026/47577409-bef92980-d93e-11e8-98b3-14a210d6e691.jpg)
