### ISSUE TITLE
framing

### ISSUE THREAD

**Issue by Oldshed** [arkypita/LaserGRBL#474]
I have entered the g-code to frame an image.  Where does the [left]  [right]  numbers come from?

**Comment by Oldshed** [comment]
sorry for being so dense, but where do the values for  left,  bottom,
right,  top,   come from?  When I enter those g-codes lasergrbl puts a
little slash circle at the left and nothing happens.  My image is loaded
and system at idle.  What am I missing?

**Comment by StuartB4** [comment]
Where are you entering them?

**Comment by arkypita** [comment]
left, bottom etc are available only if entered in custom buttons.
http://lasergrbl.com/usage/custom-buttons/
