### ISSUE TITLE
Improving the scarring of the laser lens

### ISSUE THREAD

**Issue by wilu9500** [arkypita/LaserGRBL#475]
Hello, I am expanding my machine. I have increased the machine's working area.

![20181027_123412](https://user-images.githubusercontent.com/35997091/47603358-40a69100-d9eb-11e8-8ccd-f81c6d6a7a3c.jpg)

I would like to know your opinion because I have a 5.5 Watt blue laser with a wavelength of 405 nm. In the set there was such a lens that focused the laser. For M9 thread.

![bez tytulu](https://user-images.githubusercontent.com/35997091/47603363-5451f780-d9eb-11e8-9990-6c57cc8865cc.png)

It seems to me that there are better lenses for lasers of this type. I would like to know if you have experience with improving the focus of a laser beam of this type.

**Comment by StuartB4** [comment]
You could always join the forum here:
[Laser Forum.](https://laserpointerforums.com)
They have loads of help and experience .

**Comment by Focus3** [comment]
Good day,

G2 lenses seem to be top choice. Just search for a G2 lens with the right wavelength (405 nm should be in the range).

Focus3.
