### ISSUE TITLE
How to have laser on by default (swap M3 and M4)

### ISSUE THREAD

**Issue by LordOdin** [arkypita/LaserGRBL#476]
I have a solenoid for drawing and it works perfectly only problem is I need it to be inverted.. Power on travel and no power when drawing because it uses gravity to draw

**Comment by arkypita** [comment]
An hardware solution like use a PNP instead of a NPN to drive solenoid?

**Comment by arkypita** [comment]
A firmware solution modfying your grbl 

// #define INVERT_SPINDLE_ENABLE_PIN // Default disabled. Uncomment to enable.

**Comment by LordOdin** [comment]
Thanks!
