### ISSUE TITLE
il laser non funziona 

### ISSUE THREAD

**Issue by apreaa** [arkypita/LaserGRBL#479]
salve ho problemi con il laser il quale non emette il raggio (solo quello per regolare la messa a fuoco)anche modificando i parametri dal programma il laser non va si muove a vuoto e non incide nulla

**Comment by apreaa** [comment]
ciao,genero tutto con grbl laser ho risolto il problema solo che ora se stoppo il progetto il laser continua a incidere mentre se e le misure di incisione non corrispondono con quelle che setto come posso fare

**Comment by arkypita** [comment]
devi configurare i passi/mm dei tuoi motori
$100, $101

https://github.com/gnea/grbl/wiki/Grbl-v1.1-Configuration
