### ISSUE TITLE
Cursor position wrong 3.0.1

### ISSUE THREAD

**Issue by RDS356** [arkypita/LaserGRBL#486]
In this version , the cursor follow from machine position.
In the lastset version the cursor followed the WORK POSITION.
Why did you change it ?
![lasergrbl](https://user-images.githubusercontent.com/25726497/48265644-279ed680-e414-11e8-9e89-ce2c8a636f15.png)

Version that I back.
![lasergrbl1](https://user-images.githubusercontent.com/25726497/48266337-34242e80-e416-11e8-8cec-a0b03989cf68.png)

**Comment by arkypita** [comment]
Actual LaserGRBL version has this behaviour:

- First Line: always show Machine Position X, Y and Z (Z is optional, shown only if relevant)
- Second Line: optionally show Work Position X, Y, and Z (if relevant). The whole line is optional, shown only if there is a working offset active.
- Third Line: optionally show feed speed and power (F and S) if reported by grbl status report.

I don't remember how it was in older version but your screenshot of 3.0.1 is coherent with designed behaviour.

**Comment by arkypita** [comment]
> Why did you change it ?

Because people that does not use working offset now does not see an useless line
