### ISSUE TITLE
Overrides not working correctly on v3

### ISSUE THREAD

**Issue by gflaser-au** [arkypita/LaserGRBL#488]
When I change the linear slider from default (1x) position to 2x in one drag and drop, I only see a single 0x91 character sent on the wire.

serial log:

?<Run|WPos:33.425,19.900,0.000|Bf:0,189|FS:100.000,750.000|Pn:RHS|Ov:100,100,100|A:SF>

?<Run|WPos:33.763,19.900,0.000|Bf:0,189|FS:100.000,750.000|Pn:RHS>
?<Run|WPos:34.094,19.900,0.000|Bf:0,189|FS:100.000,750.000|Pn:RHS>
?<Run|WPos:34.425,19.900,0.000|Bf:0,189|FS:100.000,750.000|Pn:RHS>
‘?<Run|WPos:34.763,19.900,0.000|Bf:0,189|FS:110.000,750.000|Pn:RHS|Ov:110,100,100|A:SF>

?<Run|WPos:35.119,19.900,0.000|Bf:0,189|FS:110.000,750.000|Pn:RHS>
?<Run|WPos:35.487,19.900,0.000|Bf:0,189|FS:110.000,750.000|Pn:RHS>

Note: first char on 5th line (') is actually 0x91 on the wire (confirmed with hex dump)

Also,
After setting slider to 2x, if I drap and drop just a small amount, or just click the slider control handle, another single 0x91 is sent for each click, and speed increases a small increment.

To slow the machine, I must drag to < 1x and each click slows the machine a small amount.

I am sure this was working properly in lasergrbl version 2.x but can't be 100% sure - I have significantly changed my machine / controller and can't easily go backwards to confirm for sure.
I'm sure if I drag and dropped to 2x, the machine speed increased to 2x.

**Comment by arkypita** [comment]
I have not changed override managment in LaserGRBL.
If you want to test with older LaserGRBL version you can find and download version history from here: https://github.com/arkypita/LaserGRBL/releases

**Comment by gflaser-au** [comment]
I was 0.5 steps ahead of you... I have another laptop now with 2.8.50 installed.
It behaves the same as v3 - so not a v3 issue.

What is the response from the controller that LaserGRBL is expecting so it will send multiple 0x91 characters to increase the speed to the slider setting?
My serial port logger shows only one 0x91 char being sent for a step change between 1x and 2x.

Also, the reset button does not work for me either.

I am using Grbl_Esp32 port -  I suspect something has been changed in the status report - I can fix that if I understand LaserGRBL requirements.

**Comment by arkypita** [comment]
previous message was updated

**Comment by gflaser-au** [comment]
I have done some more testing and serial port logging.
I'm sorry the hexdump is not formatted well here.

I tested 2.8.47, and it behaves the same (just a single speed increment to 110% for a single slider move to 200%)

I then tested the gnea/grbl 1.1 in arduino Nano and logged - it works. I see multiple 0x91 commands until target is reached.

The status report from my controller (GRBL_esp32) does not seem to be correctly parsed by lasergrbl, therefore only one 0x91 cmd is sent.

Please compare these two status reports that include Ov: reports.

1, (gnea/grbl 1.1 on Arduino Nano (works with LaserGRBL overrride processing)
----------------------------------------------------------------------------------------
[14/11/2018 23:59:06] Written data (COM4) 
    91 3f                                             ‘?               
[14/11/2018 23:59:07] Read data (COM4) 
    3c 52 75 6e 7c 4d 50 6f 73 3a 2d 31 30 35 35 2e   <Run|MPos:-1055. 
    32 35 30 2c 2d 31 30 36 34 2e 36 30 30 2c 30 2e   250,-1064.600,0. 
    30 30 30 7c 46 53 3a 31 31 30 2c 37 35 30 7c 4f   000|FS:110,750|O 
    76 3a 31 31 30 2c 31 30 30 2c 31 30 30 7c 41 3a   v:110,100,100|A: 
    53 46 3e 0d 0a                                    SF>..            
[14/11/2018 23:59:07] Written data (COM4) 
    91 3f                                             ‘?               
[14/11/2018 23:59:07] Read data (COM4) 
    3c 52 75 6e 7c 4d 50 6f 73 3a 2d 31 30 35 34 2e   <Run|MPos:-1054. 
    38 35 30 2c 2d 31 30 36 34 2e 36 30 30 2c 30 2e   850,-1064.600,0. 
    30 30 30 7c 46 53 3a 31 32 30 2c 37 35 30 7c 57   000|FS:120,750|W 
    43 4f 3a 2d 31 30 38 34 2e 35 30 30 2c 2d 31 30   CO:-1084.500,-10 
    38 34 2e 35 30 30 2c 30 2e 30 30 30 3e 0d 0a      84.500,0.000>..  
(continues to send 0x91 until Ov:200 target is reached - correct operation)


2, GRBL_esp32 (does not work with LaserGRBL v2.8.47, 2.8.50, v3.0)
-----------------------------------------------------------------
 [13/11/2018 21:48:24] Written data (COM3) 
    91 3f                                             ‘?               
[13/11/2018 21:48:24] Read data (COM3) 
    3c 52 75 6e 7c 57 50 6f 73 3a 33 34 2e 37 36 33   <Run|WPos:34.763 
    2c 31 39 2e 39 30 30 2c 30 2e 30 30 30 7c 42 66   ,19.900,0.000|Bf 
    3a 30 2c 31 38 39 7c 46 53 3a 31 31 30 2e 30 30   :0,189|FS:110.00 
    30 2c 37 35 30 2e 30 30 30 7c 50 6e 3a 52 48 53   0,750.000|Pn:RHS 
    7c 4f 76 3a 31 31 30 2c 31 30 30 2c 31 30 30 7c   |Ov:110,100,100| 
    41 3a 53 46 3e 0d 0a                              A:SF>..          
[13/11/2018 21:48:25] Written data (COM3) 
    3f                                                ?                
[13/11/2018 21:48:25] Read data (COM3) 
    3c 52 75 6e 7c 57 50 6f 73 3a 33 35 2e 31 31 39   <Run|WPos:35.119 
    2c 31 39 2e 39 30 30 2c 30 2e 30 30 30 7c 42 66   ,19.900,0.000|Bf 
    3a 30 2c 31 38 39 7c 46 53 3a 31 31 30 2e 30 30   :0,189|FS:110.00 
    30 2c 37 35 30 2e 30 30 30 7c 50 6e 3a 52 48 53   0,750.000|Pn:RHS 
    3e 0d 0a                                          >..              
[13/11/2018 21:48:25] Written data (COM3) 
    3f                                                ?                
[13/11/2018 21:48:25] Read data (COM3) 
    3c 52 75 6e 7c 57 50 6f 73 3a 33 35 2e 34 38 37   <Run|WPos:35.487 
    2c 31 39 2e 39 30 30 2c 30 2e 30 30 30 7c 42 66   ,19.900,0.000|Bf 
    3a 30 2c 31 38 39 7c 46 53 3a 31 31 30 2e 30 30   :0,189|FS:110.00 
    30 2c 37 35 30 2e 30 30 30 7c 50 6e 3a 52 48 53   0,750.000|Pn:RHS 
    3e 0d 0a                                          >.. 


NOTES: 
- esp32 status report includes Pn: status directly before Ov:
- esp32 status report looks correctly formatted according to https://github.com/gnea/grbl/wiki/Grbl-v1.1-Interface#real-time-status-reports
- esp32 FS: report is floating pt numbers, whereas Nano is integers, lasergrbl uses int.parse()
- code below is the report parser.... does not include Pn: - will it just be skipped? will is prevent Ov: being parsed?
https://github.com/arkypita/LaserGRBL/blob/cb41da4f1f281af8eb7a5fc1a53826692741cc8f/LaserGRBL/GrblCore.cs#L1312-L1328
- Why is this status report that includes Ov: report, which looks to be correct to grbl specification, not being parsed by LaserGRBL? I can't see how this will not work correctly.

**Comment by arkypita** [comment]
When I have some time i'll read your post. Just two hint for you:

1) If you start LaserGRBL with "comlog" argument (LaserGRBL.exe comlog) by commandline or by a shortcut, LaserGRBL will log each tx and each rx in file called "comlog.txt" located in C:\Users\<YourName>\AppData\Roaming\LaserGRBL

No needs to use an external logger

2) If you can open the session log of LaserGRBL by click "?" and "Open session log".
In session log will be recorded eventual parsing exception.

Can you open your session log and post it here?

**Comment by arkypita** [comment]
I guess parsing is failing because of this:

> esp32 FS: report is floating pt numbers, whereas Nano is integers, lasergrbl uses int.parse()

**Comment by arkypita** [comment]
Documentation show that FS report is integer

![image](https://user-images.githubusercontent.com/8782035/48492854-fca8ee00-e82a-11e8-8c8d-f2d916282e7e.png)

**Comment by arkypita** [comment]
Totally agree with 1, about to catch exception not completly agree because it could hide problems. I prefere exception are  not too much catched so they have bigger effects

**Comment by gflaser-au** [comment]
I changed the controller to report FS: as integer numbers and the overrides work correctly. 👍👍

Also, I now have machine position and f / s readout back at top right of lasergrbl visualiser - I did not notice they were also gone!

If you close this issue, but please look at improving parsing code for status report messages so it will not break easily. 👍👍

**Comment by arkypita** [comment]
float parsing of FS field will be available with the next version
