### ISSUE TITLE
Centerline

### ISSUE THREAD

**Issue by vale67** [arkypita/LaserGRBL#489]
How does centerline work? After selecting it, a celestial bar appears at the bottom, moving alternately from right to left ... I waited even 10 minutes but nothing happens ... the program seems blocked.

**Comment by vale67** [comment]
forgot...version 3.0

**Comment by myfordboy** [comment]
I have the same issue.
I want to cut and importing a file produces 2 lines so the laser makes to passes which is not needed. I believe centerline is for this purpose but have the same issue as vale67.

**Comment by arkypita** [comment]
see #490
