### ISSUE TITLE
problem mit laser on off

### ISSUE THREAD

**Issue by goblin84** [arkypita/LaserGRBL#49]
My problem is that my laser at M04 is concerned and off with M03 but import raster image would like laser out on M05 this option I can not change in the laser grbl.

Thank you

**Comment by arkypita** [comment]
The question is not clear, I tried translating it with "google translate" and it is even less understandable.
Please write your question in english

**Comment by arkypita** [comment]
If I understand well, your laser works in reverse: turned off with M3 and turned on with M5. Is that so?

**Comment by goblin84** [comment]
Yes almost M4 on  M3 off and M5 no function

My grbl is standart 1.1e

**Comment by arkypita** [comment]
If your laser is off on M3/M4 maybe it is a problem with your hardware, not with LaserGRBL. So why ask here?

Please note that with GRBL v1.1 and "Laser Mode" laser turn on only on G1,G2,G3 movements and automatically shut down if no movement in progress or in G0 fast movement.
