### ISSUE TITLE
centerline

### ISSUE THREAD

**Issue by myfordboy** [arkypita/LaserGRBL#495]

**Comment by myfordboy** [comment]
I want to cut and vectorizing a file produces 2 lines so the laser makes to passes which is not needed. I believe centerline is for this purpose but have the same issue as vale67.

**Comment by arkypita** [comment]
so if the issue is the same you can post there instead open a new issue report

**Comment by myfordboy** [comment]
I posted there as well this. I mistakenly put it here. You must forgive me, new user!
