### ISSUE TITLE
Laser does not turn off, problem solved

### ISSUE THREAD

**Issue by David7820** [arkypita/LaserGRBL#497]
Hello everyone, first I apologize because this is a google translation.
I decided to write this after solving my problem, even though I do not have enough knowledge about grbl and I am new to the cnc world ..., maybe someone will save the time I lost installing my laser (a lot) and run LaserGRBL. The problem I had is that the laser simply did not turn off at any time, in any way, with all the software installed correctly. If someone has this problem with a laser like mine (built-in pwm), I finally solved it by simply connecting a ground wire (0V from the laser power supply) directly to an Arduino Gnd pin. Before I had it connected to the general Gnd of my homemade machine (in this way, I do not understand it, but it does not work even though they were all connected, including Arduino).
Thank you for being able to use this software.
I hope to help.
![5a79637f56598191295677](https://user-images.githubusercontent.com/44709986/48735929-a7f9de80-ec41-11e8-8240-e58ac946e482.jpg)

**Comment by OldShark** [comment]
Hi David. U suggests something like this?

![circuit](https://user-images.githubusercontent.com/6947351/48854961-48631680-ed9a-11e8-9dec-61e12a7dcb88.jpg)

**Comment by David7820** [comment]
Hi, yes to the arduino directly, to the common gnd of the cnc it did not work for me. Although I used the power supply that comes with the laserThere is not much information about these lasers, I almost give it as impossible.

Enviado desde Yahoo Mail con Android 
 
  El mié., nov. 21, 2018 a 16:33, OldShark<notifications@github.com> escribió:   
Hi David. U suggests something like this?

**Comment by OldShark** [comment]
I think it's not impossible. I already detected the problem in mine. I'll put the image at night. I connected the ocilloscope to pin 11 (Z +). the pulses strike right with the GRBLLaser tracing the image. The voltage sent is okay for laser firing in dark areas. but this without connecting pin 9 in the laser driver. When connecting to the laser driver, the voltage on pin 11 drops by half. I'll do a test. I will unsolder the SW-LD62 cooler (LD driver). I think he's actually draining something. This being real, I'll use a source just for it. otherwise I will put a set-up on pin 11 to raise the voltage for sending to the TTL.

**Comment by OldShark** [comment]
Do you have a multimeter to be able to measure the voltage at pin 11 (Z +) connected to the LD and without connecting?

**Comment by OldShark** [comment]
And sorry my poor english. ahahahahaahaha

**Comment by David7820** [comment]
Sorry, not understand the question ¿LD?
, My english is worse
Enviado desde Yahoo Mail con Android 
 
  El mié., nov. 21, 2018 a 18:38, OldShark<notifications@github.com> escribió:   
And sorry my poor english. ahahahahaahaha

**Comment by OldShark** [comment]
Are you french?

**Comment by David7820** [comment]
From Spain, Canary Islands

Enviado desde Yahoo Mail con Android 
 
  El mié., nov. 21, 2018 a 18:52, OldShark<notifications@github.com> escribió:   
Are you french?

**Comment by OldShark** [comment]
Ok. Let´s go. Google translate:
¿Tiene un multímetro para poder medir el voltaje en el pin 11 (Z +) conectado al LD y sin conectar?

**Comment by OldShark** [comment]
soy brasileño.

**Comment by OldShark** [comment]
pero una duda que no entendí. ¿has conseguido solucionar el problema con ese láser y el cnc shield?

**Comment by David7820** [comment]
Si resolví el problema, no tengo cnc shield, drivers externos para los motores conectados directamente a arduino.El problema es que la fuente de alimentación de estos laser no tienen una toma de tierra.Esto es lo que midoConectado  0.046vTrabajando  hasta 3.2vSin conectar 0.01vNo se si es lo que me pidesPerdón se me fue en español

Enviado desde Yahoo Mail con Android 
 
  El mié., nov. 21, 2018 a 19:02, OldShark<notifications@github.com> escribió:   
pero una duda que no entendí. ¿has conseguido solucionar el problema con ese láser y el cnc shield?

**Comment by OldShark** [comment]
creo que es exactamente el problema. la noche llegando del trabajo voy a poner las imágenes de las mediciones que realicé

**Comment by OldShark** [comment]
algo está drenando la corriente en el perno 11

**Comment by David7820** [comment]
Please to meet you

Enviado desde Yahoo Mail con Android 
 
  El mié., nov. 21, 2018 a 19:17, OldShark<notifications@github.com> escribió:   
algo está drenando la corriente en el perno 11

**Comment by OldShark** [comment]
sorry . corrente = cadena

**Comment by OldShark** [comment]
and nice to meet U2

**Comment by OldShark** [comment]
Go home now. when i came home put some photos

**Comment by David7820** [comment]
Saludos 

Enviado desde Yahoo Mail con Android 
 
  El jue., nov. 22, 2018 a 12:27, OldShark<notifications@github.com> escribió:   
buenos días David. desconectar el refrigerador no ha cambiado en nada. la caída de la señal permanece. voy a intentar poner un regulador step-up. Vamos a ver. gran abrazo
