### ISSUE TITLE
3Drag problem

### ISSUE THREAD

**Issue by meccel** [arkypita/LaserGRBL#50]
Ciao, complimenti per il tuo programma.
Ho una [3Drag della futura Elettronica](http://3dprint.elettronicain.it/) versione 1.3 convertita a cnc laser 5w.
Vorrei usare il tuo programma perchè ho problemi con Inkscape e plugin Gcode.
purtroppo non riesco a connetterla in nessuna porta e nel campo Laser ON quando importi l'immagine dovrei inserire M106 ma il campo non lo permette.
c'é qualche possibilità per utilizzare il tuo programma con questa stampante?
Grazie Michele

**Comment by dungjk** [comment]
Currently, LaserGRBL is compatible to GRBL only.
Sorry!

**Comment by arkypita** [comment]
I confirm what @dungjk just say
