### ISSUE TITLE
The Emulator UI won't let me close the window

### ISSUE THREAD

**Issue by brakthehun** [arkypita/LaserGRBL#501]
The Emulator UI window doesn't let me close it. It also doesn't track movement along the path,, it only shows where it ended up after the command

V3.0.1
I went to settings and changed it to emulation. I connected to the emulator and a dialog box showing commands was opened. I played around,, then went back to serial connection and I can't close the emulator window.

**Comment by arkypita** [comment]
> The Emulator UI window doesn't let me close it. It also doesn't track movement along the path,, it only shows where it ended up after the command

Yes: emulator only return "ok" and move to next position after an amount of time (computed by segment lenght and actual speed) but does not interpolate positions over time.

> I went to settings and changed it to emulation. I connected to the emulator and a dialog box showing commands was opened. I played around,, then went back to serial connection and I can't close the emulator window.

do not worry about this, the window will not be there at the next start
