### ISSUE TITLE
System.ArgumentException: Offset and length were out of bounds

### ISSUE THREAD

**Issue by jranavaya** [arkypita/LaserGRBL#505]
Hi,

Since yesterday I have been getting this problem where the program just gives a crash. I am not sure if this is a windows issue or specifically LaserGRBL. I'm guessing Windows because I installed a few drivers for my controller board I received, Laseraxe. Don't ask me why but it was the only one available locally in an emergency.  

First I had a problem where it would give me an error when trying to import a raster file such as a JPEG and now this. 

I will try tonight to uninstall everything to do with my laser board and also the LaserGRBL software itself and then I'll try again.

I have attached the file containing the error information.

Thank you! 

[laser grbl error.txt](https://github.com/arkypita/LaserGRBL/files/2611680/laser.grbl.error.txt)

**Comment by arkypita** [comment]
fixed in v3.0.4 let me know
