### ISSUE TITLE
"Filename" error

### ISSUE THREAD

**Issue by LucAn212** [arkypita/LaserGRBL#506]
This error is repeated in earlier versions. (I checked from v.2.9.2)
The "Filename" field does not show the correct file name.Shows the name of the previous file.. The correct name appears only after processing.
This is confusing.
![screenhunter_19 nov 23 22 53](https://user-images.githubusercontent.com/45270009/48961575-04c50400-ef76-11e8-8e24-db1edbb66522.jpg)
![screenhunter_20 nov 23 22 54](https://user-images.githubusercontent.com/45270009/48961577-0b537b80-ef76-11e8-8d54-b340d923aed2.jpg)

**Comment by arkypita** [comment]
True, and it is correct. One can cancel raster import an until the raster import procedure is completed the old file is not unloades.
