### ISSUE TITLE
ngc file format

### ISSUE THREAD

**Issue by ALDEEN19** [arkypita/LaserGRBL#507]

**Comment by ALDEEN19** [comment]
I think adding *.ngc  file format would make it more versatile.
I also couldn't find buttons for moving Z axis machine manual control.
Thanks a lot.

**Comment by StuartB4** [comment]
Go to
https://github.com/arkypita/LaserGRBL/issues/306

Scroll down a fair way and look for a post by 1estrider.
He has a custom button for manual movement, Z up and down.

If you are not sure how to make a custom button let me know here and I will explain.

**Comment by ALDEEN19** [comment]
Sure I already did created custom buttons for the Z axis movements
right just after I wrote my comment, so thanks for your prompt reply.
I am looking forward to have the ngc file format included among the
other available gcode formats.
Thank you again, I really appreciate your pleasant effort.

On 25/11/2018, StuartB4 <notifications@github.com> wrote:
> Go to
> https://github.com/arkypita/LaserGRBL/issues/306
>
> Scroll down a fair way and look for a post by 1estrider.
> He has a custom button for manual movement, Z up and down.
>
> If you are not sure how to make a custom button let me know here and I will
> explain.
>
>
>
>
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/arkypita/LaserGRBL/issues/507#issuecomment-441445388


-- 
Jamal Aldeen

**Comment by StuartB4** [comment]
Ok no problem, glad you got it sorted.

**Comment by arkypita** [comment]
.ngc is only an extension for a text file containing gcode?

**Comment by ALDEEN19** [comment]
ngc file extension is normally generated by "gcode tools" embedded in
Inkscape and it is usually a gcode file just like .nc extension.
In fact I have tried using this particular ngc extension in your nice
LaserGRBL application by choosing any svg file and then I change its
svg extension manually by typing ngc instead of svg and then Enter,
and it works always perfect just like any other gcode file.
Cheers!

On 26/11/2018, arkypita <notifications@github.com> wrote:
> .ngc is only an extension for a text file containing gcode?
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/arkypita/LaserGRBL/issues/507#issuecomment-441566949


-- 
Jamal Aldeen

**Comment by arkypita** [comment]
added in v3.0.4 let me know

**Comment by ALDEEN19** [comment]
Yes ! .. ngc file format now is viewable and nicely working.
Thank you very much.

On 02/12/2018, arkypita <notifications@github.com> wrote:
> added in v3.0.4 let me know
>
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/arkypita/LaserGRBL/issues/507#issuecomment-443460959


-- 
Jamal Aldeen
