### ISSUE TITLE
Movement wait after M03, for white paper cut

### ISSUE THREAD

**Issue by Luborson** [arkypita/LaserGRBL#508]
Hello,
quick question, can you insert a changeable waiting time after M03 (0-100ms appox.) in GCode generator ( Target Image screen)
this is usefull for cutting white paper, because burned (black) paper is possible cut much faster. similar function used in J Tech Photonic Laser Tool  plugin for Inkscape.
They it call "Power-On Delay"

Thanks, Lubor

**Comment by arkypita** [comment]
already in #64
