### ISSUE TITLE
Problem of mismatch between fill and stroke lines

### ISSUE THREAD

**Issue by Phenixoid** [arkypita/LaserGRBL#510]
Hello!
I want to immediately apologize for my bad English - Google Translate.
My machine consists of a bunch of Win7x64, LaserGRBL v3.0.3, GRBL v1.1f, mechanics based on Anet A8. When burning, I encountered the problem of mismatch between fill and stroke lines.

I open the PNG file. I set the following parameters:
```
Resize			Smooth (HQ Bicubic)
Brightness		100
Contrast		100
White Clip		11
B&W			On, 50
Conversion Tool		Vectorise!
Vectorise! Option
Smoothing		On, 10.0
Filling			Horizontal
Filling Quality		12 lines/mm
Speed			65 mm/min
Laser Options		M4/M5 S 0-255
Size			150x27 mm
```
The image is part of the phrase. Everything looks good in the preview window. Burnout lasted more than 4 hours. At the output, I got the offset of the stroke lines relative to the fill. Moreover, on the "correct" positions is filling. Stroke lines have a negative offset; the closer to the zero coordinates, the more offset, by the end of the phrase being burned off, the offset is reduced. At the end of the burn, the head returns to zero positions without shifting.
What could it be?

**Comment by arkypita** [comment]
can you upload a picture?

**Comment by Phenixoid** [comment]
Of course. Here are the files. 
![123](https://user-images.githubusercontent.com/729909/49068937-14c03a80-f239-11e8-9441-08d0014c9a92.png)

[123.nc.txt](https://github.com/arkypita/LaserGRBL/files/2618980/123.nc.txt)

**Comment by Phenixoid** [comment]
I can not attach the photo of the result obtained at the moment. I think by the evening I can provide.

**Comment by Phenixoid** [comment]
Photo
![img_20181127_205127_hdr](https://user-images.githubusercontent.com/729909/49106708-f25c0a80-f294-11e8-832f-677d4040b50a.jpg)
![img_20181127_205146_hdr](https://user-images.githubusercontent.com/729909/49106729-030c8080-f295-11e8-8658-754dfda30b4b.jpg)
![img_20181127_205205_hdr](https://user-images.githubusercontent.com/729909/49106748-0d2e7f00-f295-11e8-9995-ede54486bd6e.jpg)

**Comment by Phenixoid** [comment]
Greetings. I carefully watched the machine and tried to reproduce the problem. It turned out that the flexible cable channel along the X axis, with a considerable distance from the origin of coordinates, began to spring and push the carriage of the X axis closer to zero. I also found out that when burning filling lines, the engines are always in a state of motion. At the beginning of the burn-out of the stroke line, the head rises to the desired position and at this moment the engine stops and “releases”. The farther the carriage along the X axis, the more it will spring the cable channel back at the moment of stopping.
I conclude that I have a badly tuned GRBL. Your program has nothing to do with it. Sorry I thought for your software. The topic can be closed.
