### ISSUE TITLE
Disable sessionlog

### ISSUE THREAD

**Issue by mucek4** [arkypita/LaserGRBL#511]
Is there any option to disable writing in sessionlog.txt file? It's writing on a system disk and after "printing" one raster image it grows to 50+GB, consuming all disk space on my computer.

**Comment by arkypita** [comment]
Hi
SessionLog is recording manual user activity and program exceptions.
Since user activity is limited (opening file, click here and there etc) the session log should not increase so much, unless program is not doing exception while executing "printing".

Instead of disabling the log it would be more useful to understand what cause so much data recording. Could you copy-paste a piece of your file?

**Comment by mucek4** [comment]
Ok. I will. I just deleted file and it's empty now. I'll paste it when it gets "big" again.

**Comment by mucek4** [comment]
Ok. Here is the section of log: 
Log contains roughly 5200 lines a second. I found out that program starts to write this insane log file if I unplug my laser when I'm still connected. 

`28.11.2018 22:02:53	SendImmediate	System.IO.IOException: The device does not recognize the command.
28.11.2018 22:02:53	SendImmediate	
28.11.2018 22:02:53	SendImmediate	   at System.IO.Ports.InternalResources.WinIOError(Int32 errorCode, String str)
28.11.2018 22:02:53	SendImmediate	   at System.IO.Ports.SerialStream.BeginWriteCore(Byte[] array, Int32 offset, Int32 numBytes, AsyncCallback userCallback, Object stateObject)
28.11.2018 22:02:53	SendImmediate	   at System.IO.Ports.SerialStream.Write(Byte[] array, Int32 offset, Int32 count, Int32 timeout)
28.11.2018 22:02:53	SendImmediate	   at System.IO.Ports.SerialPort.Write(Byte[] buffer, Int32 offset, Int32 count)
28.11.2018 22:02:53	SendImmediate	   at LaserGRBL.ComWrapper.UsbSerial.Write(Byte b)
28.11.2018 22:02:53	SendImmediate	   at LaserGRBL.GrblCore.SendImmediate(Byte b, Boolean mute)
28.11.2018 22:02:53	CloseCom    	System.IO.IOException: The device does not recognize the command.
28.11.2018 22:02:53	CloseCom    	
28.11.2018 22:02:53	CloseCom    	   at System.IO.Ports.InternalResources.WinIOError(Int32 errorCode, String str)
28.11.2018 22:02:53	CloseCom    	   at System.IO.Ports.SerialStream.DiscardOutBuffer()
28.11.2018 22:02:53	CloseCom    	   at LaserGRBL.ComWrapper.UsbSerial.Close(Boolean auto)
28.11.2018 22:02:53	CloseCom    	   at LaserGRBL.GrblCore.CloseCom(Boolean user)
28.11.2018 22:02:53	CloseCom    	Close COM5 [CORE]
28.11.2018 22:02:53	CloseCom    	System.IO.IOException: The device does not recognize the command.
28.11.2018 22:02:53	CloseCom    	
28.11.2018 22:02:53	CloseCom    	   at System.IO.Ports.InternalResources.WinIOError(Int32 errorCode, String str)
28.11.2018 22:02:53	CloseCom    	   at System.IO.Ports.SerialStream.DiscardOutBuffer()
28.11.2018 22:02:53	CloseCom    	   at LaserGRBL.ComWrapper.UsbSerial.Close(Boolean auto)
28.11.2018 22:02:53	CloseCom    	   at LaserGRBL.GrblCore.CloseCom(Boolean user)
28.11.2018 22:02:53	CloseCom    	Close COM5 [CORE]
28.11.2018 22:02:53	CloseCom    	System.IO.IOException: The device does not recognize the command.
28.11.2018 22:02:53	CloseCom    	
28.11.2018 22:02:53	CloseCom    	   at System.IO.Ports.InternalResources.WinIOError(Int32 errorCode, String str)
28.11.2018 22:02:53	CloseCom    	   at System.IO.Ports.SerialStream.DiscardOutBuffer()
28.11.2018 22:02:53	CloseCom    	   at LaserGRBL.ComWrapper.UsbSerial.Close(Boolean auto)
28.11.2018 22:02:53	CloseCom    	   at LaserGRBL.GrblCore.CloseCom(Boolean user)
28.11.2018 22:02:53	CloseCom    	Close COM5 [CORE]
28.11.2018 22:02:53	CloseCom    	System.IO.IOException: The device does not recognize the command.
`

**Comment by arkypita** [comment]
The impression that I have is that the communication thread tries to close the serial port but can not (due to a failed support of the DiscardOutBuffer() in your hardware) and then the serial port remains open and then the thread try again, in continuous, to close it.

I'll fix in next release, making fail safe call to DiscardOutBuffer

**Comment by arkypita** [comment]
fixed in v3.0.4 let me know
