### ISSUE TITLE
32bit system problem

### ISSUE THREAD

**Issue by kefeur** [arkypita/LaserGRBL#514]
![image](https://user-images.githubusercontent.com/25538576/49170380-479f2700-f33c-11e8-820a-c094ce75de7a.png)
Hello!
The problem is a newer version of the 64bit system for generating centerline.
At my request it would work 32bit.
Thanks.

**Comment by kefeur** [comment]
Error message:% 1 is incompatible with 32-bit or 64-bit versions of Windows. My machine has win7 32 bits.

**Comment by arkypita** [comment]
This is a know issue. Unlucky the external program (autotrace.exe) i use to compute centerline is only available as precompiled exe for 64bit OS. I am looking for a solution but for now you should accept this limit

**Comment by kefeur** [comment]
OK . Thank you forissues.

**Comment by kefeur** [comment]
![image](https://user-images.githubusercontent.com/25538576/49175833-bf278300-f349-11e8-8711-afd98a680e8f.png)
Can it work?

**Comment by kefeur** [comment]
Martin Weber
martweb@gmx.net

**Comment by kefeur** [comment]
http://www.inkscapeforum.com/viewtopic.php?t=11898

**Comment by arkypita** [comment]
@kefeur I have tested the zip. Seem to work in a XP 32bit virtual machine.

The worst thing is that the executable is not autonomous, but it depends on all the libraries that are distributed with the zip. I would not like to fill my installation folder with all this files. I am looking if I can compile a stand alone autonomous version.

Meanwhile can you try to decompress the zip in your LaserGRBL installation folder, under autotrace subfolder, and replace actual autotrace.exe with the new exe and dll from zip? Let me know.

**Comment by kefeur** [comment]
It does not work well. He writes "the value can not be null (zero).
![image](https://user-images.githubusercontent.com/25538576/49240778-56521080-f406-11e8-90fc-22b3c412c633.png)

**Comment by kefeur** [comment]
Other autotrace for windows : 
![image](https://user-images.githubusercontent.com/25538576/49241092-26efd380-f407-11e8-8e1d-035c4cfdb3c6.png)
What is it ?

**Comment by kefeur** [comment]
https://github.com/PancakeBot/PancakePainter
https://github.com/autotrace/autotrace
