### ISSUE TITLE
Homing fails when using wireless connection

### ISSUE THREAD

**Issue by JyriT** [arkypita/LaserGRBL#517]
Working with 2 axis 3dpBurner and all works smoothly when LaserGRBL is connected via USB.
But, if connection is done through wifi, either telnet or LaserWebESP protocol Homing homes only X-axis. 
Y-axis just twitch. If I depress Y axis Limit switch by hand, Y axis backs up nicely as it should, so no "ghost swithing", If I unplug ESP and change to USB - All works nicely. 
Any tips where to search solution? 
Getting wireless to work would be awesome, burning plastic in living room doesn't sound good idea.. 

$H
M5G92X0Y420Z0F5000ok
$$
$0=10 (Step pulse time)
$1=255 (Step idle delay)
$2=0 (Step pulse invert)
$3=0 (Step direction invert)
$4=0 (Invert step enable pin)
$5=0 (Invert limit pins)
$6=0 (Invert probe pin)
$10=19 (Status report options)
$11=0.020 (Junction deviation)
$12=0.010 (Arc tolerance)
$13=0 (Report in inches)
$14=1 ()
$20=0 (Soft limits enable)
$21=0 (Hard limits enable)
$22=1 (Homing cycle enable)
$23=1 (Homing direction invert)
$24=200.000 (Homing locate feed rate)
$25=4000.000 (Homing search seek rate)
$26=0 (Homing switch debounce delay)
$27=0.000 (Homing switch pull-off distance)
$40=1 ()
$100=80.000 (X-axis travel resolution)
$101=80.000 (Y-axis travel resolution)
$102=0.001 (Z-axis travel resolution)
$110=12000.000 (X-axis maximum rate)
$111=12000.000 (Y-axis maximum rate)
$112=12000.000 (Z-axis maximum rate)
$120=1000.000 (X-axis acceleration)
$121=2000.000 (Y-axis acceleration)
$122=12000.000 (Z-axis acceleration)
$130=320.000 (X-axis maximum travel)
$131=420.000 (Y-axis maximum travel)
$132=10000.000 (Z-axis maximum travel)

**Comment by brakthehun** [comment]
Can you take a pic of your Y axis wiring?? Sounds like you're having a noise issue on your Y axis limit pin. to do a test,, set pull off distance ($27) to 20 or so. $27 should be higher than 0 anyways. 

if it homes X,, then pulls both X and Y back 20mm,, then it's most likely a noise problem.
