### ISSUE TITLE
New Feature: Possibility of measurement scale.

### ISSUE THREAD

**Issue by StuartB4** [arkypita/LaserGRBL#518]
Would it be possible to add a measurement scale along the bottom edge 
and down the left side edge of the image window.

At the minute it shows the size of the image, but nothing in between
The image below was 2 seperate elements.
The text loaded first and then the picture added using Append File.

Selecting the correct placement settings in Target Image Offset settings for the second image
would be easier if you could see a scale along the bottom and down the left side.
A line with Incremental marks of 1, 2 or 5 mm's would be enough.

![untitled4](https://user-images.githubusercontent.com/16980026/49386619-e00c2180-f717-11e8-95dc-f2bde1666ad8.jpg)

**Comment by arkypita** [comment]
Like it!

**Comment by arkypita** [comment]
I have done some test; it i difficult to arrange scale to not disturb the whole graphics, according to image quadrant and alignment. I have not found a nice look and feel that satisfies me

**Comment by StuartB4** [comment]
Ok. Thanks for considering it.

**Comment by arkypita** [comment]
![image](https://user-images.githubusercontent.com/8782035/52556971-631fb700-2dee-11e9-8871-49e965042ecc.png)

Horizontal scale is ok. The major issue is on vertical axis.
If I want to put numbers on it, i should enlarge the space, or put them rotated.

**Comment by StuartB4** [comment]
Oh yes I see. Would it be the same issue putting them down the right hand side?

**Comment by arkypita** [comment]
I achieved a good result with the rotation of the text. For me it is satisfactory in all quadrants.
You will see it in the next version.

![image](https://user-images.githubusercontent.com/8782035/52569878-7775ab00-2e12-11e9-9b42-70f81ba4698f.png)

![image](https://user-images.githubusercontent.com/8782035/52570002-be63a080-2e12-11e9-92a9-e4d4dab8079d.png)

![image](https://user-images.githubusercontent.com/8782035/52570045-d0ddda00-2e12-11e9-99e8-c78844f8be70.png)

**Comment by StuartB4** [comment]
Wow. That's excellent.
Looks really good, can't wait for the next version.
Thankyou.

**Comment by arkypita** [comment]
done

**Comment by StuartB4** [comment]
Thats great. 
Just tried it loading 1 image and Appending 3 others.
Got them all exactly where I wanted and the sizes I wanted.
Thanks very much for that, makes it a lot easier to position images.

Looks a bit untidy but it is only a test image.
![untitled6](https://user-images.githubusercontent.com/16980026/53524050-58e00700-3ad6-11e9-8539-b895be3bda77.jpg)
