### ISSUE TITLE
Questions about Telnet Feature

### ISSUE THREAD

**Issue by luc-github** [arkypita/LaserGRBL#523]
Hi I am working on GRBL_ESP32 project (https://github.com/bdring/Grbl_Esp32) and we are trying to make it work flawlessly with your great lasergrbl.
We are able to make the settings : `Telnet / Synchronous / Slow ` working so far so good

We would like to see if we can use also buffered, but we meet 2 issues, I looked in your code but I am not familiar with it :
 1 - randomly in telnet buffered mode, after few seconds, lasergrbl seems stop sending GCODE but continue to send the status query,
looks like laser grbl does not get the right amount of ack or something like this, 
Any way to check this ?
Also may I know what trigger the buffer to be full using telnet and buffered mode?

2 - Randomly again in telnet buffered mode, it seems the ESP32 wifi RX buffer is overflowed - and so board is no more responding and also freeze lasergrbl - so the only way to stop is to kill lasergrbl task May I know what is the max size of the sending buffer ?

3 - I see there is a log file for telnet in code `socketlog.txt` but I cannot find it - is a flag necessary to enable it ? or where is supposed to be generated ?

Thanks in advance

**Comment by arkypita** [comment]
Hi luc
I would like to give you all the support I can, for your project.

For what you describe at point 1 (stop sending GCODE but continue to send the status query) seem that lasergrbl "think" the buffer is full. 

> Any way to check this ? Also may I know what trigger the buffer to be full using telnet and buffered mode?

Buffer has nothing to concern with telnet. Grbl has a serial buffer that allow to send more than a single gcode line per time, allowing the grbl firmware to "predict" next movements and optimize acceleration/deceleration, allowing to have the very next instruction without hiccup etc.
This buffer has a fixed size and LaserGRBL implement the character counting protocol as [described here](https://github.com/gnea/grbl/wiki/Grbl-v1.1-Interface#streaming-protocol-character-counting-recommended-with-reservation).

One thing to know is that LaserGRBL use a buffer size of 127 char (not 128 as ) due to [compatibility with older grbl v0.9 that has a buffer of 127](https://github.com/gnea/grbl/issues/302).

LaserGRBL show the usage of this buffer in the lower-left progressbar near the line count info. Because it shows only a progressbar without showing numbers, it is not so usefully for debugging purpose.

If you activate buffer report with $10=2 grbl start sending debugging info about buffer inside status report.

https://github.com/gnea/grbl/wiki/Grbl-v1.1-Configuration#10---status-report-mask
https://github.com/gnea/grbl/wiki/Grbl-v1.1-Interface#real-time-status-reports

Also note that if LaserGRBL receive a status report that contain info about buffer, and that info contains a number of free space char higher then 127, LaserGRBL can enlarge itself buffer to this size. This was requested by [Grbl-LPC fork that has a 10240 buffer](https://github.com/arkypita/LaserGRBL/issues/379).

**Comment by arkypita** [comment]
> 3 - I see there is a log file for telnet in code socketlog.txt but I cannot find it - is a flag necessary to enable it ? or where is supposed to be generated ?

Run LaserGRBL from command prompt or by a shortcut. If you start LaserGRBL with "comlog" argument "C:\Program Files (x86)\LaserGRBL\LaserGRBL.exe comlog" the program will record a file called "netlog.txt" located in "C:\Users\YourName\AppData\Roaming\LaserGRBL". In comlog file you can find all the data transmitted/received from LaserGRBL.

**Comment by arkypita** [comment]
> LaserGRBL show the usage of this buffer in the lower-left progressbar near the line count info. Because it shows only a progressbar without showing numbers, it is not so usefully for debugging purpose.

I am going to add a tooltip with numeric info on the progress bar, so you can compare the buffer status reported by LaserGRBL character count with values reported by grbl status report.

**Comment by luc-github** [comment]
Excellent, thank you so much for the explainations, really appreciate your support, this will help to figure out what is going on on buffered mode.

**Comment by arkypita** [comment]
https://github.com/arkypita/LaserGRBL/releases/download/v3.0.6/install.exe

**Comment by arkypita** [comment]
I add that when LaserGRBL recognizes that the machine is no longer performing any movement, it intercepts the situation with an "Issue detector" dialog (you will probably have already seen it). At the same time it records some diagnostic information in the sessionlog.txt file.

Logger.LogMessage("Issue detector", "{0} [{1},{2},{3}]", issue, FreeBuffer, GrblBuffer, GrblBlock);

FreeBuffer is the space in buffer from LaserGRBL knowledge/point of view
GrblBuffer/GrblBlock are taken from last status report if $10=2

**Comment by arkypita** [comment]
let me know

**Comment by luc-github** [comment]
The log file is excellent - seems the ESP32 core has some issue with lwip - I may need to send your program  with a minimal sketch to reproduce issue - is that ok ?

**Comment by luc-github** [comment]
Actually I think I will do a simple sender in python so they can check sender and adjust for their debug

**Comment by arkypita** [comment]
get a look to `stream.py`

https://github.com/gnea/grbl/tree/master/doc/script

**Comment by luc-github** [comment]
Thank you - actually I was able to have a lock of WiFi server with a simple ping pong exchange so I just kept super simple

**Comment by luc-github** [comment]
I will keep you updated - until then I think we can close issue 

Thanks a lot for your great help

**Comment by luc-github** [comment]
Hi @arkypita  we got some fixes from ESP32 core and my test program which just do fast ping/pong is no more crashing, unfortunaly we still got some overflow somewhere as ESP32 lockup after few sec with lasergrbl
I need your help to understand the sessionlog.txt
```
16/01/2019 16:43:29	VersionInfo 	Detected Grbl v1.1f
16/01/2019 16:43:29	SetStatus   	Machine status [Idle]
16/01/2019 16:43:35	OpenFile    	Open C:\Users\luc\Desktop\cinque.nc
16/01/2019 16:43:53	EnqueueProgram	Running program, 253416 lines
16/01/2019 16:43:53	SetStatus   	Machine status [Run]
16/01/2019 16:44:43	Issue detector	StopResponding [3,1172,15]
16/01/2019 16:44:45	SetStatus   	Machine status [Disconnected]
```

this is end of netlog.txt
```
00395233	05649	tx	X18.6S643\n
00395235	05650	rx	ok
00395237	05651	tx	X18.4S549\n
00395241	05652	rx	ok
00395256	05654	tx	X18S588\n
00396576	05655	tx	[0x3F]
00398571	05656	tx	[0x3F]
00400581	05657	tx	[0x3F]
00402576	05658	tx	[0x3F]
00404571	05659	tx	[0x3F]
00406571	05660	tx	[0x3F]
00408581	05661	tx	[0x3F]
00410576	05662	tx	[0x3F]
00412571	05663	tx	[0x3F]
00414582	05664	tx	[0x3F]
```
you mentionnerd previously :
> Logger.LogMessage("Issue detector", "{0} [{1},{2},{3}]", issue, FreeBuffer, GrblBuffer, GrblBlock);

is that normal Grbl buffer is 1172 ? should not be under 128 ?

**Comment by arkypita** [comment]
Hi

When it start LaserGRBL assume grbl buffer is 127 (variable BUFFER_SIZE)
At runtime, if LaserGRBL receive a status report with a value of 128 or 256 or 10240 it enlarge its'own knowledge of BUFFER_SIZE to those value, to take advantage of all the buffer size.

Status report can contain this info it tis format: `Bf:15,128. The first value is the number of available blocks in the planner buffer and the second is number of available bytes in the serial RX buffer.`

Status report: [link](https://github.com/gnea/grbl/wiki/Grbl-v1.1-Interface#real-time-status-reports)
How to enable buffer status in report: [link](https://github.com/gnea/grbl/wiki/Grbl-v1.1-Configuration#10---status-report-mask)


```
private static int BUFFER_SIZE = 127;

private void ParseBf(string p)
{
	string bf = p.Substring(3, p.Length - 3);
	string[] ab = bf.Split(",".ToCharArray());

	mGrblBlocks = int.Parse(ab[0]);
	mGrblBuffer = int.Parse(ab[1]);

	EnlargeBuffer(mGrblBuffer);
}

private void EnlargeBuffer(int mGrblBuffer)
{
	if (BUFFER_SIZE == 127) //act only to change default value at first event, do not re-act without a new connect
	{
		if (mGrblBuffer == 128) //Grbl v1.1 with enabled buffer report
			BUFFER_SIZE = 128;
		else if (mGrblBuffer == 256) //Grbl-Mega
            BUFFER_SIZE = 256;
		else if (mGrblBuffer == 10240) //Grbl-LPC
            BUFFER_SIZE = 10240;
	}
}
```

This was requested by user that use Grbl-Mega and Grbl-LPC port, that want to use all the buffer size.
However the value of FreeBuffer, GrblBuffer, GrblBlock in log comes from

`FreeBuffer`: `BUFFER_SIZE - mBuffer` where mBuffer is the number of char in buffer as known by LaserGRBL (incremented when a message is sent, decremented when ok-error is received).
`GrblBuffer`: last know value of bytes received from status report `mGrblBuffer = int.Parse(ab[1]);`
`GrblBlock`: last know value of block received from status report `mGrblBlocks = int.Parse(ab[0]);`

Only `FreeBuffer` is used into code do decide if there is space for send another message or not.
GrblBuffer and GrblBlock are for diagnostic purpose.

**Comment by arkypita** [comment]
search inside your netlog.txt for some status report sent by grbl with `Bf:` data on it

**Comment by luc-github** [comment]
Ok got it - yes I put telnet buffer to 1200 but actually it is not the real telnet buffer, it is the one I setup to store telnet reading from wifi server - this one is supposed to have 1436 buffer
I did a test setting report buffer to 128 and still crash 
```
16/01/2019 18:23:53	EnqueueProgram	Running program, 253416 lines
16/01/2019 18:23:54	SetStatus   	Machine status [Run]
16/01/2019 18:25:21	Issue detector	StopResponding [0,128,14]
16/01/2019 18:25:22	SetStatus   	Machine status [Disconnected]
```
```
06432144	15873	rx	ok
06432145	15874	rx	<Idle|WPos:144.800,1.400,0.000|Bf:14,128|FS:0.000,929.000|Pn:X|Ov:100,100,100|A:S>
06432548	15875	rx	ok
06432559	15876	tx	X144.2S847\n
06432563	15877	tx	X144S854\n
06432567	15878	rx	ok
06432578	15879	tx	X143.8S847\n
06433553	15880	tx	[0x3F]
06434318	15881	rx	ok
06434318	15882	tx	X143.6S800\n
06435549	15883	tx	[0x3F]
06437559	15884	tx	[0x3F]
06439554	15885	tx	[0x3F]
06441549	15886	tx	[0x3F]
06443559	15887	tx	[0x3F]
06445557	15888	tx	[0x3F]
06447552	15889	tx	[0x3F]
06449547	15890	tx	[0x3F]
06451557	15891	tx	[0x3F]
```
so I start to wondering if the issue is really in RX buffer 
is there a way to fully disable `[0x3F]` request or increase the timer to 10 seconds ? 

I set it to slow which from what read, is every 2s but  currently there is no availabletowrite fonction  yet in ESP32 telnet API so I wondering if it is a tx overflow instead of rx overflow

**Comment by luc-github** [comment]
I have writen a sender in python according the buffer calculation to control everything and log everything 
I will feedback later - thanks a lot for your help and your patience

**Comment by luc-github** [comment]
I can reproduce issue with the python script - so this will help me to narrow down the issue - thanks again for all the informations

**Comment by luc-github** [comment]
looks like a ressource allocation issue on ESP32  WiFi stack as now I am able to stream in buffered mode with my test FW
I continue to investigating for a fix but there is hope ^_^
I close issue then as I can simulate lasergrbl with my python sender for the debug

Thanks again for all the help and the tips, I close issue now
