### ISSUE TITLE
The contours of the picture when engraving

### ISSUE THREAD

**Issue by KameliAnna** [arkypita/LaserGRBL#524]
There is a black and white or grayscale picture (no difference). Black color is engraved on the power from settings. There is no contour at picture, but it seems to be engraved at maximum power. I used LineToLine with default settings. What could be wrong?
![image](https://user-images.githubusercontent.com/17216923/49870613-f5263600-fe24-11e8-886d-bc1a76d98c64.png)
![image](https://user-images.githubusercontent.com/17216923/49870684-2acb1f00-fe25-11e8-885e-3b20f2711399.png)

**Comment by StuartB4** [comment]
Did you load a grayscale image in to LaserGRBL to start with?

**Comment by StuartB4** [comment]
OK.
It would help if you could give us some info on your machine.
What type of Laser and laser driver board you have.
Also, what were the settings in here:

![untitled2](https://user-images.githubusercontent.com/16980026/49876540-82648d00-fe1b-11e8-820e-e8a4ab0f356e.jpg)

**Comment by KameliAnna** [comment]
cnc shield v2.0 with arduino nano, 15W blue laser, LaserGRBL v3.0.4.
I made 2 simple tests with gradient picture:
![default](https://user-images.githubusercontent.com/17216923/49923728-6fa69280-fec5-11e8-82f6-53390763966f.png)
First settings:
<img width="508" alt="test1_1" src="https://user-images.githubusercontent.com/17216923/49923766-8947da00-fec5-11e8-9a28-14a1a29de462.png">
<img width="599" alt="test1_2" src="https://user-images.githubusercontent.com/17216923/49923767-8947da00-fec5-11e8-8760-7230ce09f837.png">
Second:
<img width="589" alt="test2_1" src="https://user-images.githubusercontent.com/17216923/49923784-96fd5f80-fec5-11e8-989d-d8ad89bfe7d5.png">
Result:
![image](https://user-images.githubusercontent.com/17216923/49923799-a4b2e500-fec5-11e8-9f72-798eebde441f.png)
You can see black borders.

**Comment by arkypita** [comment]
Use M4

**Comment by arkypita** [comment]
https://github.com/gnea/grbl/wiki/Grbl-v1.1-Laser-Mode

**Comment by KameliAnna** [comment]
How can I change it? I have only M3 in combobox.

**Comment by arkypita** [comment]
https://github.com/gnea/grbl/wiki/Grbl-v1.1-Laser-Mode

**Comment by KameliAnna** [comment]
It helped! Thank you!
