### ISSUE TITLE
FR: LaserGRBL for MacOS

### ISSUE THREAD

**Issue by smoki3** [arkypita/LaserGRBL#533]
Hi,

is it possible to compile LaserGRBL for MacOS?

I think that would be nice.

Kind regards

**Comment by arkypita** [comment]
Does .net and visual studio for MacOS exist?

**Comment by fedekrum** [comment]
https://www.youtube.com/watch?v=ZsMk8hKEJ1o
Is that what you are looking for?

**Comment by tgrrr** [comment]
Hi, looks like a great project. Is there a reason this request was closed?

**Comment by ah1102** [comment]
Windows virus hole of fascist Dr. Gates
