### ISSUE TITLE
program crashed

### ISSUE THREAD

**Issue by sinfocomp** [arkypita/LaserGRBL#534]
Description:
  Stopped working

Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	lasergrbl.exe
  Problem Signature 02:	3.0.4.0
  Problem Signature 03:	5c02fffe
  Problem Signature 04:	System
  Problem Signature 05:	2.0.0.0
  Problem Signature 06:	4ca2ba90
  Problem Signature 07:	3c71
  Problem Signature 08:	bb
  Problem Signature 09:	System.ObjectDisposedException
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	2058

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

**Comment by arkypita** [comment]
Install .net framework 3.5 or higher
