### ISSUE TITLE
Cut 3mm wood

### ISSUE THREAD

**Issue by aldva** [arkypita/LaserGRBL#536]
Hello 
I'm new from GRBL forum and I would ask how are the settings for cut 3mm wood
I use art cam for CNC Laser route but i do not able to cut plywood-
how I can sure that the power of laser is 100%? there is the possibility to manage the power?

Thans
Alberto

**Comment by Scorotron** [comment]
Hi Alberto. What type of laser do you have? Hom much strong? I have 2500W and 3mm is too much for it. Only balsa or soft wood and use 2 or 3 times for maximum power with low speed.

**Comment by aldva** [comment]
Hi
I have a 15w 1000x1000 PWM TTL it should cut until 5mm.
I buy it for cut 3mm spruce wood for my rc model.
I use software laser grbl and t2laser but I make a draw with Autocad than
with Artcam I realize the G code.
I think to have some problem with software.

Alberto

Il 1 gen 2019 20:35, "Scorotron" <notifications@github.com> ha scritto:

Hi Alberto. What type of laser do you have? Hom much strong? I have 2500W
and 3mm is too much for it. Only balsa or soft wood and use 2 or 3 times
for maximum power with low speed.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/arkypita/LaserGRBL/issues/536#issuecomment-450752054>,
or mute the thread

**Comment by Scorotron** [comment]
It does not matter which soft you use for prepare data. In Laser GRBL set M3 or M4 to 255, then try to use 1000. $32 set to 1. Of course you have to manually focus to the smallest point (use S10 or S20 for focusing). 

Dont forget to use glasses all the time!!

**Comment by aldva** [comment]
Ok I try tu set it!
I have install laser grbl but the version Is 0.9 du you know how is
possible upgrade in 1.1?
Last questions where I try to use 1000?
I need to search a manual for understand better how to use the software

Tanks for your help!!!


Il giorno mar 1 gen 2019, 21:32 Scorotron <notifications@github.com> ha
scritto:

**Comment by StuartB4** [comment]
Hi Aldva.
To upgrade GRBL to version 1.1f.

This link will download the GRBL version 1.1f, the latest.
All you need is the .hex.
https://github.com/gnea/grbl/releases/download/v1.1f.20170801/grbl_v1.1f.20170801.hex

Then goto here and download the XLoader zip file.
http://xloader.russemotto.com

Extract XLoader to a folder somewhere. 
You can also put the GRBL .hex file in the same folder.

Next make sure you machine is connected to the correct Com port.
Run XLoader.
Then do this.
![untitled](https://user-images.githubusercontent.com/16980026/50576774-030e1c00-0e11-11e9-8f26-f41174eb623d.jpg)

**Comment by aldva** [comment]
Thanks a lot
I try immediately

Alberto

Il giorno mar 1 gen 2019, 23:05 Stuart <notifications@github.com> ha
scritto:

**Comment by arkypita** [comment]
There are 2 config value: $30 and $31 that correspond to the values of S to use to obtain maximum power and miminum power.

They will be scaled by grbl to produce a range of 255 different PWM power regulation, so I suggest to use the more intuitive values of $30=255 and $31=0

![image](https://user-images.githubusercontent.com/8782035/50590965-69d11b00-0e8d-11e9-947a-95d5818ac37b.png)

**Comment by aldva** [comment]
I try to do the update to 1.1f grbl firmware but now do not function the y
axis.
The problem is that I do not know how reset the system

Il giorno mer 2 gen 2019, 12:58 arkypita <notifications@github.com> ha
scritto:

**Comment by StuartB4** [comment]
Have you checked all the wiring/cables/connectors.
Updating to 1.1f does not normally cause axis movement problems.

You could also check in GRBL configurations settings on the Grbl menu in LaserGRBL to make sure $101 is set correctly in GRBL.

![untitled](https://user-images.githubusercontent.com/16980026/50651039-1092e580-0f7a-11e9-86ea-c13f98286878.jpg)

**Comment by Scorotron** [comment]
Of course. I checked cabels more times. Machine works perfectly in mill mode with spindle, in laser mode as well. Strong laser on S1 is only one problem. FW 1.1f was inside when it was new, I dont have to do upgrade. All axis works correctly, $101-103 I have to set to exact size. Now when I do rectangle 100x100mm in vector SW, save it as SVG and then burn by LaserGRBL
![grbl](https://user-images.githubusercontent.com/45948850/50651810-ce22d600-0f84-11e9-8de2-fdd0418f69bc.JPG)
, it has EXACTLY 100.0 x 100.0.

**Comment by aldva** [comment]
I try to update the firmware with xloader for upload file .hex but after
few second that it seams OK the window of x loader is fix do not possible
close.
Than I try to use t2laser and at the and there is a a window That say 1
error?!?!?
When I open laser grbl the version is 1.1f but the button for move the step
motor do not work... I try everything



Il 3 gen 2019 18:25, "Scorotron" <notifications@github.com> ha scritto:

Of course. I checked cabels more times. Machine works perfectly in mill
mode with spindle, in laser mode as well. Strong laser on S1 is only one
problem. FW 1.1f was inside when it was new, I dont have to do upgrade. All
axis works correctly, $101-103 I have to set to exact size. Now when I do
rectangle 100x100mm in vector SW, save it as SVG and then burn by LaserGRBL
[image: grbl]
<https://user-images.githubusercontent.com/45948850/50651810-ce22d600-0f84-11e9-8de2-fdd0418f69bc.JPG>
, it has EXACTLY 100.0 x 100.0.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/arkypita/LaserGRBL/issues/536#issuecomment-451215006>,
or mute the thread

**Comment by aldva** [comment]
Do you know how is possible program the eleksmask mana v5.2?


Il 3 gen 2019 18:25, "Scorotron" <notifications@github.com> ha scritto:

Of course. I checked cabels more times. Machine works perfectly in mill
mode with spindle, in laser mode as well. Strong laser on S1 is only one
problem. FW 1.1f was inside when it was new, I dont have to do upgrade. All
axis works correctly, $101-103 I have to set to exact size. Now when I do
rectangle 100x100mm in vector SW, save it as SVG and then burn by LaserGRBL
[image: grbl]
<https://user-images.githubusercontent.com/45948850/50651810-ce22d600-0f84-11e9-8de2-fdd0418f69bc.JPG>
, it has EXACTLY 100.0 x 100.0.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/arkypita/LaserGRBL/issues/536#issuecomment-451215006>,
or mute the thread

**Comment by StuartB4** [comment]
I've just realised, when using XLoader and the GRBL 1.1f  .hex file you need to do it again but with a lower baud rate if you have a Nano. 
For the Arduino Nano it should be 57600.
You change that in the XLoader Baud rate setting.

**Comment by StuartB4** [comment]
You could try unplugging the Nano from the board and upload GRBL with just the USB lead plugged in to it.
Or you can unplug the Nano and use the Arduino IDE program and use the eeprom_clear sketch to clear the eprom first and then try and upload GRBL again.
If you dont have the Arduino IDE you can get it here:
https://www.arduino.cc/en/Main/Software
Just click the Windows Installer, for Windows XP and up.
You can click "just download" after that.

After installing the IDE do this.
Make sure your Nano is plugged in to the usb port.

Goto tools menu and select your Arduino from the list.
![untitled1](https://user-images.githubusercontent.com/16980026/50665933-82832300-0faa-11e9-85f9-b5fcb99116a5.jpg)


Select eeprom_clear.
![untitled2](https://user-images.githubusercontent.com/16980026/50665461-ae9da480-0fa8-11e9-9b21-06d192855853.jpg)

Click the Verify tick.
![untitled3](https://user-images.githubusercontent.com/16980026/50665477-b8270c80-0fa8-11e9-9e29-7944d1415bb0.jpg)

Click the Upload arrow button.
![untitled4](https://user-images.githubusercontent.com/16980026/50665528-e1479d00-0fa8-11e9-9307-bb4aff211ba3.jpg)

Then you can try and upload GRBL again.

**Comment by ukadyp** [comment]
Hi

when cutting 3mm it will not always cut on the first pass i have the 2.5wat laser and i have to go over it like 19times for it to do it but dont forget as well speed slower the more burn u will get

**Comment by aldva** [comment]
Hello,

I think that the EleksMaker Mana is broken, maybe I do some mistake. 

I try to order another EleksMaker EleksMana SE XY 2 Axis and try again for last time.

 

Thanks

Alberto

 

 

 

Da: ukadyp [mailto:notifications@github.com] 
Inviato: domenica 20 gennaio 2019 00:21
A: arkypita/LaserGRBL
Cc: aldva; Author
Oggetto: Re: [arkypita/LaserGRBL] Cut 3mm wood (#536)

 

Hi

when cutting 3mm it will not always cut on the first pass i have the 2.5wat laser and i have to go over it like 19times for it to do it but dont forget as well speed slower the more burn u will get

**Comment by brakthehun** [comment]
When you upgrade from GRBL 0.9 to 1.1,, you have to put in all your settings too. do you have a picture of the machine?? can you send the $$ settings??
Full power from the laser can be generated with an M3 command.
15W diodes are difficult to focus. You only get a good cutting focus 30mm to 60mm away from the laser.
