### ISSUE TITLE
Laser works when 12V is connected, cant turn off the laser

### ISSUE THREAD

**Issue by mintautasb** [arkypita/LaserGRBL#539]
Hello, been searching for some familiar issue but didnt found one.
Was engraving without any problems this morning. My laptop was disconnected from charger. Laser was connected, but all engravings were finished. When I came back after 2 hours the laptop was out of power, was turned off. When I turned on the laptop and pressed the connect button in grbl app, the laser turned on and doesnt turn off. Both fans are working. All motors work, but laser do not turn off. 

Was wondering, how to do master reset or smth... Or maybe change some settings in configuration...  Laser is on when i turn it to electricity. It can be disconnected from pc, laser still lights when connected to 12V... 

Dont know what to do... 
GRBL v1.1
LaserGRBL v3.0.4
5500mw laser

**Comment by brakthehun** [comment]
Can you take a pic of the control board??
