### ISSUE TITLE
Axis Going wrong way.

### ISSUE THREAD

**Issue by StuartB4** [arkypita/LaserGRBL#54]
Hi Arkypita. 
I really like this program but have 2 issuses with it.
At the minute I don't have my laser set up for PWM which would allow it to adjust the laser power so it is just on and off for now. But I am just testing LaserGRBL before doing it.

The first issue is that after loading an image and prepairing it for burning, and making sure both axis are at 0,0,
I click on the Run button to start it and both X and Y axis try to go the wrong way. Then there is a delay and the burning starts as it should.
You can see it here and hear the clicking of the slipping clutch of the axis just as it starts and before it burns.
https://youtu.be/DDn2oZ8QnvU 
I use 4 other programs for burning and don't have the problem with any of them.
They are:
GrblController.
UniversalGcodeSender.
Candle.
GRBLPanel.

The second issue is that the on screen indicator that shows where the laser is (the blue + sign) goes out of the bottom of the image being burnt and takes quite a while to reappear.
As you can see here it dissapears after 4 seconds and does'nt reappear until it gets to 18 seconds.
https://youtu.be/P2CE2Hi8CAE

Any ideas why this is happening would be appreciated.
Thankyou.

**Comment by arkypita** [comment]
> I use 4 other programs for burning and don't have the problem with any of them.
> They are:
> GrblController.
> UniversalGcodeSender.
> Candle.
> GRBLPanel.

This sound very strange because if LaserGRBL is used to load and send the content of a file without adding any external command.

Confirm that the problem exist, and you have different behaviour from this programs and LaserGRBL, if you use a gcode file (not a raster import from grbl).

Maybe the other programs send some particular command to initialize grbl?
