### ISSUE TITLE
Very overburnt borders, M4 mode unusable, laser engraving not consistent 

### ISSUE THREAD

**Issue by edocastri** [arkypita/LaserGRBL#542]
Hi!

As you can see this is a very wide thread, it may be because I'm new in the GRBL world, but I've searched a lot in google and GH and didn't find anything exactly related, it also could help people with the same issues.

I've just bought a chinese cnc machine called "CNC 3018 Pro" in Aliexpress, It came with a board labeled as "Woodpecker 3.2A" with axis step drivers labeled as "Stepstick Rev 0.1" or something like that.

The laser unit is a blue laser 5500mW 450nm.

The issue is that I can't engrave consistent grayscale patterns, the borders overburn when using M3 (I think it has something to do with de-acceleration / laser power synchro), and when using M4 it doesnt work at all, also M3 doesnt engrave under 50%.

As you can see in this photo, the upper is M3 and the bottom is M4:
![image](https://user-images.githubusercontent.com/19616239/50577584-a22f1580-0e09-11e9-808e-332563f66c98.png)

![grayscale_test_m3](https://user-images.githubusercontent.com/19616239/50577610-26819880-0e0a-11e9-87ad-ebfae82d827f.jpg)

![grayscale_test_m4](https://user-images.githubusercontent.com/19616239/50577612-2bdee300-0e0a-11e9-86aa-9d1e111ba8ee.jpg)

I've created a Google Photos Album if you want to take a look at the hardware:
https://photos.app.goo.gl/ZrvgQdLZPuKAP3wPA

I've already tested speed and set max speed at 1500 mm/min
I'm using LaserGRBL v3.0.4, GRBL 1.1f, connected by USB, COM4 115200 Baud.
These are my settings:

`$0=10 (Step pulse time)
$1=25 (Step idle delay)
$2=0 (Step pulse invert)
$3=5 (Step direction invert)
$4=0 (Invert step enable pin)
$5=0 (Invert limit pins)
$6=0 (Invert probe pin)
$10=1 (Status report options)
$11=0.010 (Junction deviation)
$12=0.002 (Arc tolerance)
$13=0 (Report in inches)
$20=0 (Soft limits enable)
$21=0 (Hard limits enable)
$22=0 (Homing cycle enable)
$23=0 (Homing direction invert)
$24=25.000 (Homing locate feed rate)
$25=500.000 (Homing search seek rate)
$26=250 (Homing switch debounce delay)
$27=1.000 (Homing switch pull-off distance)
$30=255 (Maximum spindle speed)
$31=0 (Minimum spindle speed)
$32=1 (Laser-mode enable)
$100=800.000 (X-axis travel resolution)
$101=800.000 (Y-axis travel resolution)
$102=800.000 (Z-axis travel resolution)
$110=1600.000 (X-axis maximum rate)
$111=1600.000 (Y-axis maximum rate)
$112=600.000 (Z-axis maximum rate)
$120=10.000 (X-axis acceleration)
$121=10.000 (Y-axis acceleration)
$122=10.000 (Z-axis acceleration)
$130=200.000 (X-axis maximum travel)
$131=200.000 (Y-axis maximum travel)
$132=200.000 (Z-axis maximum travel)`

A weird thing is that the machine came with 2 power adapters, one for the machine and other for the laser module, but it also works with only the main cnc power connected. These tests where made using both adapter connected. I've made some test and doesnt seems to be any noticeable difference between using one or both power adapters.
Thanks, sorry for my bad english.

**Comment by einencool** [comment]
I think the big problem is the low acceleration of this machine ( $120-122) with only 10 mm/ss
With the M3 Command the Laser starts burning when the axis begins to move, thats why everything is overburnt.
With the M4 it seems to me, that the software regulates the Power down too much so it doesn‘t burn at the beginning.

Maybe you can test some other settings for the acceleration.

**Comment by edocastri** [comment]
Hi.

Thanks for the answer.
Indeed, days ago I started to try with other settings, and set x and y acceleration up ($120 and $121) to 1000 mm/sec2 and now it works like wonders.
M3 works so good that I haven't tested M4 yet.

Now the only think that bugs me is that when I open a SVG file from LaserGRBL the canvas size and everything inside gets bigger by a 2.835 scale. Is that normal?
Also, LaserGRBL don't detect solid shapes in SVG format, and get everything as lines, so when I try to burn something I have to save it as BMP for the filling, and SVG for the borders, and also scale down everything /2.835 so it fits correctly.

**Comment by arkypita** [comment]
> Now the only think that bugs me is that when I open a SVG file from LaserGRBL the canvas size and everything inside gets bigger by a 2.835 scale. Is that normal?

#451 

> Also, LaserGRBL don't detect solid shapes in SVG format, and get everything as lines, so when I try to burn something I have to save it as BMP for the filling, and SVG for the borders, and also scale down everything /2.835 so it fits correctly.

Fill your solid shape with lines. This is the racomanded way to fill vector images:

https://wiki.evilmadscientist.com/Creating_filled_regions
https://graphicdesign.stackexchange.com/questions/45577/create-hatching-in-inkscape
http://www.inkscapeforum.com/viewtopic.php?t=4783
https://wiki.evilmadscientist.com/Hatch_fill

**Comment by edocastri** [comment]
Thanks, indeed I'm using illustrator with mm as measure unit, I will try to check using 96 dpi or points.

Filling svg with lines doesn't work quite well because most complex shapes require using a clipping mask, and when importing svg file in laserGRBL it shows all the entire line range, not only the portion that's supposed to show because of the mask. There's a workaround rasterizing the lines and then letting AI recognize the clipped lines to turn them back to strokes, but for my workflow it turns out kinda "not very neat".

Thank you Arkypita.

**Comment by hamby** [comment]
I have the same maschine (3018 Pro) my acceleration settings are.
$120=50.000 (x accel, mm/sec^2)
$121=50.000 (y accel, mm/sec^2)
$122=50.000 (z accel, mm/sec^2)
