### ISSUE TITLE
Voltage on PWM for driving laser power

### ISSUE THREAD

**Issue by Scorotron** [arkypita/LaserGRBL#546]
Hi there. Again my problem with strong laser on S1. I found out that voltage between GND and PWM is 5.3V when laser is off. When I set S1, the voltage changes to 5.18 and laser starts burning. The more S1, the lower voltage. Minimum voltage (0.08) there is on Sxxxx, it depends on $30 parameter. If I set $30 = 255, the lowest voltage is on S255. When I set $30=1000, on S255= cca 3V, on S1000 0.08. But the more S, the stronger laser power (and the lower voltage on PWM pin). Its interesting, isnt it?

**Comment by amurbeer** [comment]
Little info. What electrical board, what firmware, where measure, etc.

**Comment by Scorotron** [comment]
![6b562bb2-cc8e-406c-bc5f-03f03aee32bf](https://user-images.githubusercontent.com/45948850/50813826-ea719a80-1317-11e9-8857-f576c370c36b.jpeg)
FW 1.1f. Measured between GND and PWM pins on laser.

**Comment by amurbeer** [comment]
it is right. The laser must be connected between + 12v and pwm. If the laser has 3 wires, then connect gnd, pwm, + 12v.

**Comment by Scorotron** [comment]
Of course it is. 

Odesláno z iPhone 8


8. 1. 2019 v 8:10, MF <notifications@github.com>:

**Comment by Scorotron** [comment]
Unfortunatelly seller didnt give me any info about laser :-( 2500 mW, 3 PIN

Odesláno z iPhone 8


8. 1. 2019 v 8:29, MF <notifications@github.com>:

**Comment by amurbeer** [comment]
send some photos of the laser. Connect the laser to + 12v and GND. PWM wire do not connect. What is the voltage between gnd and pwm (free wire) from a laser? Does the laser glow in this state?

**Comment by Scorotron** [comment]
Thanks a lot. There is 12,7V between GND and PWM, when PWM wire is NOT connected to the laser. When I set M3 S1, it is 6V. Then the more S, the less voltage. M3 S255 = 0V. Laser does NOT light.
![img_2543](https://user-images.githubusercontent.com/45948850/50851876-5850ad00-137e-11e9-9166-f3cc6f663cbe.JPEG)
![img_2544](https://user-images.githubusercontent.com/45948850/50851878-58e94380-137e-11e9-897f-9437b4511a92.JPEG)
![img_2546](https://user-images.githubusercontent.com/45948850/50851883-5981da00-137e-11e9-869c-97522acc3945.JPEG)
![img_2547](https://user-images.githubusercontent.com/45948850/50851885-5a1a7080-137e-11e9-8a07-693c4fc51f44.JPEG)

**Comment by StuartB4** [comment]
Looks like you need to invert the pwm signal.
Have you seen this?
https://github.com/gnea/grbl/issues/22

**Comment by Scorotron** [comment]
But.. when I invert signal, won’t be inverted power? S1-max, S255 min?

Odesláno z iPhone 8


9. 1. 2019 v 2:19, Stuart <notifications@github.com>:

**Comment by amurbeer** [comment]
> Looks like you need to invert the pwm signal.
> Have you seen this?
> [gnea/grbl#22](https://github.com/gnea/grbl/issues/22)

He has already assembled a converter on the laser board.


> But.. when I invert signal, won’t be inverted power? S1-max, S255 min? Odesláno z iPhone 8 9. 1. 2019 v 2:19, Stuart <notifications@github.com>:
> […](#)
> Looks like you need to invert the pwm signal. Have you seen this? [gnea/grbl#22](https://github.com/gnea/grbl/issues/22) — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

Set 1 kΩ resistance to the PWM and 12Volt pins.

**Comment by Scorotron** [comment]
you mean simply add resistance BETWEEN +12 and GND pins?

**Comment by amurbeer** [comment]
not! did I write it correctly. one end of resistance to + 12v, the second end of resistance to pwm. Connect all the wires from the laser to the control board as it was originally.

**Comment by Scorotron** [comment]
ok, its easy.. I will do it and then let you know :)

**Comment by amurbeer** [comment]
![af9270eb-eeb0-4ce6-bf12-946d4c37a200](https://user-images.githubusercontent.com/19662241/50974552-364e5a80-1537-11e9-9534-93f380021757.jpeg)

**Comment by Scorotron** [comment]
No effect, still the same..

Odesláno z iPhone 8


10. 1. 2019 v 15:24, MF <notifications@github.com>:

**Comment by einencool** [comment]
Can you please tell us the original Firmware the Board came with?
Was it the GRBL 1.1 or 0.9?
I have a Woodpecker 3.0.2 and it was with the GRBL 0.9 and maybe you have to switch to the Endstop Z Pin for the right PWM signal.
I don't really know, it's just a thought.

Greets
Chris

**Comment by Scorotron** [comment]
Hi, there was 1.1f when I bought it.

Odesláno z iPhone 8


13. 1. 2019 v 19:35, einencool <notifications@github.com>:

**Comment by einencool** [comment]
Ah ok, then the connected Pins should be the right ones.
Sorry, then I can't help you :-(

**Comment by Scorotron** [comment]
>     1. show how you connected the resistor. 2. If you close the leg from the pwm laser to the ground, does the laser glow? 3. Measure the resistance between the middle leg of the transistor and the pwm signal with a multimeter. (without power)

Hi there.

1) I connected exactly to the PINS. Be sure it was connected well.
2) There is 2.47 kOhm
3) Yes. When i connect PWM ang GND, laser glows.

Thanks..

Pavel K.

**Comment by amurbeer** [comment]
set the jumper between the transistor and the connector labeled pwm. (drawn in blue) Or connect the wire from the laser (pwm) to the middle leg of the transistor. Check in work. You most likely have a diode between the transistor and the laser.

**Comment by arkypita** [comment]
If can help: https://github.com/arkypita/LaserGRBL/wiki/Laser-Wiring
