### ISSUE TITLE
[bug] Laser mode dont work

### ISSUE THREAD

**Issue by Alissonverd** [arkypita/LaserGRBL#547]
I 'am trying to setup my build with laser and now I have one problem to control PWM on D11.

Whats happen?
After send $32=1, we dont able to send M3 > S255 more. D11 dont change the pwm state.

How I check it?
I clear the EEPROM from my UNO and send GRBL1.1f again..
I installed a led between GND and D11.
With default settings.. send M3 > S255  (full led light) > S127 (half led)
So, with default settings the D11 work fine..

Now I send $32=1
Send M3 > S255 (led dont work)

It's a bug?
How I solve it?
Laser mode broken?

I use the last version of grnl on github.

**Comment by arkypita** [comment]
With [laser mode](https://github.com/gnea/grbl/wiki/Grbl-v1.1-Laser-Mode) ON laser will fire up only when moving. It's not a bug, it's a safety feature.

BUT: Please learn to discriminate on what concerns grbl and what about lasergrbl and please: if you have question concerning GRBL post them on gnea/grbl github board, not here. 

LaserGRBL only send gcode command to grbl so any issue and question with laser, pwm, stepper & co should not be posted here.
