### ISSUE TITLE
Rc plane plan problem

### ISSUE THREAD

**Issue by murat55** [arkypita/LaserGRBL#549]
Rc plan to cut, machine is moving, laser is waiting for help[](url)

**Comment by StuartB4** [comment]
Thats a bit random, can you please explain a bit better.

**Comment by jsp-email** [comment]
Hi
Gibt es eine Funktion die zB die zu gravierende Fläche abfährt bevor er anfäng zu lasern

**Comment by murat55** [comment]
Şu dil olarak değiştir: Türkçe
radio control airplanes try to cut plans the machine is less moving and the small size drawings do not have trouble in large size drawing can also help to have trouble 10w laser nano control card

**Comment by murat55** [comment]
Laseraxe firmware
