### ISSUE TITLE
SVG File not interpreted correctly

### ISSUE THREAD

**Issue by mschaeck** [arkypita/LaserGRBL#550]
Hello,

wy is ist SVG shown diffentently than Inkscape?

[svgtest.zip](https://github.com/arkypita/LaserGRBL/files/2729788/svgtest.zip)

**Comment by StuartB4** [comment]
Did you select all 3 objects and click the Object menu and Group them before saving.

**Comment by mschaeck** [comment]
Also if I do it, it is not working.

**Comment by mschaeck** [comment]
It seems to be a problem because of the program I creade the svg file. I I use Inkscape everything works fine.

But in Inkscape if I create a text, I could open the file correct with LaserGRBL. What do I have to to if I want to use text in inkscape to laser it.
[texttest.zip](https://github.com/arkypita/LaserGRBL/files/2729991/texttest.zip)

**Comment by StuartB4** [comment]
Try the J Tech GCode generator extension.
Available here and where to put in in Inkscape and how to use it.
https://jtechphotonics.com/?page_id=1980


Select Object to path.

![text](https://user-images.githubusercontent.com/16980026/50730784-299fc000-114d-11e9-83bd-aac41a054307.jpg)

Select Extensions, Generate Gcode, J Tech Photonics Laser Tool.

![text2](https://user-images.githubusercontent.com/16980026/50730786-2dcbdd80-114d-11e9-8b2d-ccaeef7b39d9.jpg)

That will create a GCode file of your text that you can load in to LaserGRBL using the File menu.

**Comment by m3vuv** [comment]
seems the extension isnt there anymore on the website mentioned as far as i can see.seems a bum link.

**Comment by StuartB4** [comment]
Link works fine for me.
Click this link and then check your downloads folder.
http://www.jtechphotonics.com/Downloads/Inkscape/JTP_Laser_Tool_V2_2%20-%20inkscape%209_2%20version.zip

![Untitled100](https://user-images.githubusercontent.com/16980026/57866784-cf4bf580-77f7-11e9-8711-6241e8aa2a42.jpg)

**Comment by m3vuv** [comment]
sorry my mistake,your fault lol,i thought it was an extension just for txt,sorry.

**Comment by arkypita** [comment]
i suggest to transform all object, including text, to path

**Comment by brakthehun** [comment]
What program are you using to generate the original SVG??

**Comment by gisep** [comment]
I suggest the "Hershey Text" extension to laser text as one-line (and not 2 borders):
https://www.evilmadscientist.com/2011/hershey-text-an-inkscape-extension-for-engraving-fonts/

Same the process to transform to path before converting to G-code with "J Tech" extension
