### ISSUE TITLE
Default VisualStudio icon on all other Forms

### ISSUE THREAD

**Issue by mschaeck** [arkypita/LaserGRBL#551]
On all other forms if they are open the standard VisualStudio icons.

**Comment by StuartB4** [comment]
This is a bit vague, can you explain please.

**Comment by mschaeck** [comment]
For example in the Form "GrblConfig" the form icon would be better to be "LaserGrblForm.ico". So if the window is open, you can see the correct icon for that and now also if a other app is in front whats going on.

Is also would be useful to do change it also for all the other forms.

If would also be good to change the text of the form to a more useful string. Acual it only Grbl. The Menue in the main shows Grbl configuration.
