### ISSUE TITLE
fotos no se graban bien 

### ISSUE THREAD

**Issue by naitsirc05** [arkypita/LaserGRBL#555]
hola. no e podido grabar bien una foto ya que salen muy mal.
¿que estoy haciendo mal? 

![whatsapp image 2019-01-07 at 10 57 23 pm](https://user-images.githubusercontent.com/46426282/50809153-da35cd00-12cf-11e9-8b80-140841ce74db.jpeg)

esta una de las configuraciones que usé 
![captura](https://user-images.githubusercontent.com/46426282/50809162-efaaf700-12cf-11e9-820b-c5cae3d1abbb.PNG)

**Comment by StuartB4** [comment]
Intenta cambiar M3 a M4
![12cf-11e9-820b-c5cae3d1abbb](https://user-images.githubusercontent.com/16980026/50829484-92995a80-133c-11e9-8e96-6eb1e52415b7.jpg)

**Comment by naitsirc05** [comment]
no me aparece la opcion de M4  solo aparece M3

**Comment by StuartB4** [comment]
Qué versión de GRBL tienes?
![untitled2](https://user-images.githubusercontent.com/16980026/50836771-f0846d00-1351-11e9-9af3-e5a3a82c0c4e.jpg)

**Comment by naitsirc05** [comment]
![captura](https://user-images.githubusercontent.com/46426282/50837301-4a247180-1329-11e9-8150-5034465fba1a.PNG)

**Comment by StuartB4** [comment]
De acuerdo. Para obtener M4 en el cuadro desplegable debe actualizar GRBL a 1.1f
Luego, obtienes 3 ajustes adicionales para el modo láser en los ajustes de configuración.
$ 30
$ 31
$ 32
![untitled3](https://user-images.githubusercontent.com/16980026/50838476-faa86a80-1355-11e9-8da3-12fb12a98168.jpg)

**Comment by naitsirc05** [comment]
Cuando instalo el 1.1 la máquina pierde la velocidad que tiene con el actual.
Esa velocidad se puede aumentar?

**Comment by StuartB4** [comment]
Puede cambiar la velocidad en la configuración de la imagen de destino "Velocidad de grabado".
Pero solo puede ir tan alto como el ajuste en $ 110 y $ 111.
![untitled4](https://user-images.githubusercontent.com/16980026/50839919-4ad4fc00-1359-11e9-8c67-ad7fa4dfdba1.jpg)

![untitled5](https://user-images.githubusercontent.com/16980026/50839952-5c1e0880-1359-11e9-8be4-1209b999114d.jpg)
