### ISSUE TITLE
Connecting fails but machine turns on and is uncontrollable

### ISSUE THREAD

**Issue by Aztaro** [arkypita/LaserGRBL#559]
I have a 3018 woodpecker CNC and the CNC part works fine with it's native program but when trying to use Laser GRBL with a 2500mw laser, the Y axis motor turns on and the laser turns on full power when trying to connect but after a few seconds the program disconnects and the Y axis motor and laser keep running [almost set the table on fire]
I have 0 idea what to do since it won't finish connecting, session log only has

1/16/2019 1:45:03 AM	Program     	------- LaserGRBL v3.0.4 START -------
1/16/2019 1:45:05 AM	SetStatus   	Machine status [Disconnected]
1/16/2019 1:45:25 AM	SetStatus   	Machine status [Connecting]
1/16/2019 1:45:25 AM	OpenCom     	Open COM4 @ 115200 baud 
1/16/2019 1:45:25 AM	SendImmediate	Send Immediate Command [0x18]
1/16/2019 1:45:35 AM	OpenCom     	Connection timeout!

Tried every "Baud" setting and same results, even with Laser GRBL program that came on the disk has same problem

**Comment by arkypita** [comment]
Are you sure native program use grbl?
lasergrbl.com/faq

**Comment by Aztaro** [comment]
It came with Laser GRBL 2.9 on the disk

**Comment by arkypita** [comment]
did you have installed CH340 driver?
Right baud is 115200

**Comment by Aztaro** [comment]
Windows 10 had a driver set up but used the program to uninstall it and reinstall it

**Comment by arkypita** [comment]
There are many different software like LaserGRBL that can be used with grbl compatible hardware. You can find a list here: https://github.com/gnea/grbl/wiki/Using-Grbl

Does others software work or not? I suggest to test with Universal G-code Sender (UGS)

If not maybe you have received a broken board.

**Comment by Aztaro** [comment]
I'll test it right now
Also how could the board be broken if when using Candle and a spindle it works fine?

**Comment by arkypita** [comment]
So, with Candle it work. Right?
Should be a difference in how Candle and LaserGRBL manage connection initialization.

Try configure LaserGRBL like this:

![image](https://user-images.githubusercontent.com/8782035/51266893-b869d380-19bc-11e9-81ed-2d8529e22bc4.png)

**Comment by Aztaro** [comment]
That solved EVERYTHING
Thank you very much, I'm running a test as we speak and it both connected and is following the program so far

**Comment by arkypita** [comment]
This is a very safe configuration. You can configure streaming mode to buffered and threading to normal/fast

**Comment by arkypita** [comment]
I guess it should work too

**Comment by Aztaro** [comment]
If I could ask an off topic question real quick, is there a way to turn the laser on a "low power" mode so I can focus it without having to run it?

**Comment by arkypita** [comment]
Yes, with custom button.
Do a search in closed and opened issue "share your custom button here"

**Comment by Aztaro** [comment]
Thank you very much for your time, I hope you have a good 2019
