### ISSUE TITLE
S12000

### ISSUE THREAD

**Issue by CaffeineOverdrive** [arkypita/LaserGRBL#56]
The GRBL version I am using allows simultaneous 3 Axis CNC spindle control and laser control. The two issues I have are:
1. I cannot jog the Z axis for focussing the laser. 
2. The firmware S command range is 0 - 12000. The option to change the max S command tops out at 255.

**Comment by arkypita** [comment]
1) you can send any gcode command you want, via [custom button](http://lasergrbl.com/en/usage/custom-buttons/) or via [manual command](http://lasergrbl.com/en/usage/user-interface/)

2) it is true, I can open to large values in input, but it is really needed? I mean, arduino can only PWM 8 bit, so 255 different power values. Grayscale image are 8 bit, so only 255 different shades of gray. Having a S range of 12000 in firmware is really useless. Why you don't normalize to 0-255 like other people?

**Comment by arkypita** [comment]
In [latest version](https://github.com/arkypita/LaserGRBL/releases/latest) I have removed upper limit for S range.

**Comment by CaffeineOverdrive** [comment]
Thanks,
I've already used it. It works great thanks!
