### ISSUE TITLE
Laser is always on.

### ISSUE THREAD

**Issue by charliet1010** [arkypita/LaserGRBL#560]
I am brand new to all this and just got my first laser in yesterday, I believe I got everything correct in GRBL and have $32 enabled but I have no control of the laser or power, it may be a hardware issue but again I have no idea because im pretty new. Everything seems to work just fine other than as soon as I connect the wall power to the laser it is on and wont shut off till i disconnect it, its like TTL isnt doing anything.

**Comment by einencool** [comment]
Do you have the same power Unit for laser and the Controller Board?
If you have different units, be sure that they are both connected to ground. Otherwise the laser pwm signal is not on ground and the laser will fire up.

I had the same issue when I began two weeks ago.

**Comment by charliet1010** [comment]
So in my case it looks like the power supply for the Control Unit, the one that holds grbl and everything plugs into, does not have a ground on the plug. If that's what your referring to, and that's all it is, that would be amazing!

**Comment by mintautasb** [comment]
Same problem here. I will upload pictures of my laser set. There is only one power supply for whole machine. Laser lights on instantly when blue power button is on no matter if it is connected to pc. It seems the controller which is responsible for laser lightning doesnt work. I used 5A main power supply.
![img_20190123_113952](https://user-images.githubusercontent.com/46249673/51598802-f90aa500-1f06-11e9-8f0f-62f31f2ddc9a.jpg)
![img_20190123_113929](https://user-images.githubusercontent.com/46249673/51598803-f90aa500-1f06-11e9-9443-d529d3a9959b.jpg)
![img_20190123_113902](https://user-images.githubusercontent.com/46249673/51598805-f9a33b80-1f06-11e9-8c2e-3387f086ad03.jpg)
![img_20190123_113855](https://user-images.githubusercontent.com/46249673/51598807-f9a33b80-1f06-11e9-8b60-0a97433dd755.jpg)
![img_20190123_113835](https://user-images.githubusercontent.com/46249673/51598808-f9a33b80-1f06-11e9-8685-9d5d46e8b8f4.jpg)
![img_20190123_114101](https://user-images.githubusercontent.com/46249673/51598809-fa3bd200-1f06-11e9-95ef-7e6f6de11007.jpg)

**Comment by mintautasb** [comment]
One photo more:
![img_20190123_121055](https://user-images.githubusercontent.com/46249673/51599385-18ee9880-1f08-11e9-8393-3349fc676483.jpg)

**Comment by arkypita** [comment]
If can help: https://github.com/arkypita/LaserGRBL/wiki/Laser-Wiring

**Comment by mintautasb** [comment]
Tried to start laser again. Right after connecting it to loptop (power is on, laser lights, fans work full power) I see this. How can I know the reason of this alarm?
![screenshot_12](https://user-images.githubusercontent.com/46249673/51625948-1fe8cb80-1f47-11e9-8978-7d5d77417942.jpg)

**Comment by arkypita** [comment]
Google for "grbl alarm". It'free

**Comment by brakthehun** [comment]
The white "signal" pin should not be in the "fan" port.
