### ISSUE TITLE
Homing Button

### ISSUE THREAD

**Issue by tus17** [arkypita/LaserGRBL#561]
Hello,

i have a question about the home button. The homing button is available, i have enabled the $22 in the configuration. BUT, when i click on the button, nothing happens. Can you help me?
i use the latest version of lasergrbl.

![homing](https://user-images.githubusercontent.com/46784505/51325125-86b04580-1a6c-11e9-937a-bfe48a70f93e.JPG)

Kind regards,
Dimitri

**Comment by arkypita** [comment]
When you click homing button LaserGRBL send $H (homing command) to your hardware.

Once LaserGRBL has sent the command (you can see that is sent in command log) the task of carrying out the homing procedure depends exclusively on the control board and your hardware. Any malfunction in this sense has nothing to do with LaserGRBL.

Check correct wiring of limit switch and proper grbl configuration:
https://github.com/gnea/grbl/wiki/Set-up-the-Homing-Cycle
https://github.com/gnea/grbl/wiki/Wiring-Limit-Switches

**Comment by arkypita** [comment]
https://github.com/gnea/grbl/wiki/Frequently-Asked-Questions

**Comment by tus17** [comment]
Thank you very much. 
Maybe the problem is, that i have a 2 axes laser and the software is configured for 3 axes. Where can i find the config.h-file for changing this? 
In have nothing found in the install-directory.

sorry for so much asking.

Kind regards,
D.B.

**Comment by StuartB4** [comment]
it should be in here:
C:\Users\your user name\Documents\Arduino\libraries\grbl

**Comment by tus17** [comment]
sorry i can`t find it. 

I use a eleksmaker A3pro 2500mW Laser . With a eleksmaker Mana SE v3.2 Mainboard.

Maybe thats the reason why i cant find it?

**Comment by StuartB4** [comment]
Yeah.
Usually it's there if you uploaded GRBL to an Arduino board with something like the Arduino IDE program.
If it was already installed in the Mana SE board then I would'nt know how to access it, or whether you can edit it or not. Sorry.

You could probably erase what is already on the Arduino Nano that comes with the Mana SE board and upload GRBL to it, but I don't know if anyone has had success doing that.

**Comment by ukadyp** [comment]
Hi

i have the same laser i am trying to work this out as well but can not find much on how to do it with the laser we have. i just found out how to add trace frame in so it helped me see hwere it going to laser with out having the home part

**Comment by tus17** [comment]
@ukadyp ,

how did you add trace frame in ? it would help me too, to see where the laser is going to grave.

**Comment by StuartB4** [comment]
To see a frame around the image you have prepared for burning.
![untitled](https://user-images.githubusercontent.com/16980026/51472232-1ccac100-1d36-11e9-9b97-2c9bc451f36a.jpg)

Add this Code to the GCode box.

M4 
S2
F500
G0 X[left] Y[bottom] 
G1 X[right]
G1 Y[top]
G1 X[left] 
G1 Y[bottom] 
G0 X0 Y0 F4000
M5

Give the button a Tool tip, that will appear when you hovver the mouse over the button.
Select Idle.
Click Create.

Prepare your image, click Connect then click your new button.
The laser will go around the image on low power.

**Comment by tus17** [comment]
@StuartB4 
Thank you very much, that was all i wanted. :+1: 

Issue can be closed

**Comment by StuartB4** [comment]
You're welcome.
