### ISSUE TITLE
Export gcode

### ISSUE THREAD

**Issue by noel841106** [arkypita/LaserGRBL#563]
Hi, it is possible to export gcode?
I open grayscale picture, set all parameters, and got previev. But i want export all gcode to file instead click start button.
I have 3d printer, and want to put laser next to exteuder. On board i've got marlin, and all is set to accept gcode and engrave using laser. I already done test and working good. But this youre program is the best for me so i want engrave on two machine. I will gcoder put on sd card and connect to 3d printer.
Is this possible in any way?
Thank you.

**Comment by StuartB4** [comment]
Yes. Click File menu and Save Program.

**Comment by noel841106** [comment]
Wow, so easy! Why I dont find it by myself.
Iam sorry for that silly question and wasting youre time.
Thank you again.

**Comment by StuartB4** [comment]
No problem. We all go there. :)
