### ISSUE TITLE
The laser do not burn when conected to cnc shield.

### ISSUE THREAD

**Issue by LordPueblo** [arkypita/LaserGRBL#566]
Hello!
I have a problem with my laser I cannot figure out for long time.
I have a laser which works (burns) when I switch it on without any control.
When I connect the laser to CNC Shield and start process in LaserGRBL programm, the laser doesn't give enouph power to burn. I can see that it changer the light power but never burns.
I connected the laser even to PIN11 on arduino, but the signal was the same.
PLease let me know it anyone has problem like this or any suggestion!
Thanks in advance for attention!

**Comment by StuartB4** [comment]
What laser do you have ?
Is it a Protoneer shield and an Arduino UNO ?
What version of GRBL do you have ?
Does the same power supply run the motors and the laser, is it strong enough. High enough Amps to run both ?

**Comment by LordPueblo** [comment]
Ok, here is my configuration
Adruino UNO
CNC Shield 
Stepstick Drv8825 
Laser - picture in link https://drive.google.com/file/d/1AJz37kW6iLAP8S2Lhjc-jpe2TIwxlHgG/view?usp=sharing
Driver is GRBL master servo

Servo and Laser I connect to Z+ and Z- pins on the shield

**Comment by StuartB4** [comment]
So do you have 12 volts going in to the red connector, and the Z- or Z+ pin and a ground from the shield going to the white TTL connector. Does'nt really matter if it's Z+ or Z-, they are both connected to each other.
Then the laser and fan plugged in the other end white connectors?
What version is the shield and what version of GRBL are you using?

**Comment by LordPueblo** [comment]
Yes, I have an adapter which was included in suply. The laser burns when I switch it on, but stop burning if I connect it to the shield. 
Here is the link for the shild 
https://ru.aliexpress.com/item/A4988-Driver-CNC-Qunqi-Shield-Expansion-Board-for-Arduino-V3-Engraver/32639790781.html?spm=a2g0s.9042311.0.0.274233edl2F7u3
I cannot figure out what is the version. Here is the pic of it.

![shield](https://user-images.githubusercontent.com/12953984/51665954-f0c96d00-1fcd-11e9-87c2-846e3bd09dba.jpg)

GRBL library actualy for me is the question, as I downloaded it from unknown pleace. Now I have the files. Name of archive is grbl-servo-master (it is attached).
maybe I downloaded it from here  https://github.com/arnabdasbwn/grbl-coreXY-servo

[grbl-servo-master.zip](https://github.com/arkypita/LaserGRBL/files/2790862/grbl-servo-master.zip)

**Comment by StuartB4** [comment]
Looks like you have the connections correct.
It should tell you the version on the board between the motor driver sockets.

![516659541](https://user-images.githubusercontent.com/16980026/51679381-bd3f1080-1fd6-11e9-9e46-6ed0653ce193.jpg)

Do you use a servo on your machine ?
If not you might be better off using GRBL 1.1 from here.
https://github.com/gnea/grbl

You still connect TTL to Z- or Z+ and a Gnd pin on the shield.
On the latest 3.10 or above shield it goes to SpnEn pin and Gnd.

**Comment by einencool** [comment]
Like Stuart already mentioned.
You have to connect the red TTL wire to Endstop Z (+ or –)
And the black TTL wire to ground (many black connectors beside the Endstop Z.

I think you connected the red wire to Z+ and the black wire to Z-, but that is not correct

**Comment by LordPueblo** [comment]
@einencool
I made a connection red to Z- and black to GND.
And still I have laser with low light when I connect TTL to shield. Without shield it burns wood from 2 m )

**Comment by StuartB4** [comment]
![untitled2](https://user-images.githubusercontent.com/16980026/51754725-f51c8580-20b4-11e9-9a09-80308fa4ab40.jpg)

Like this.

![untitled3](https://user-images.githubusercontent.com/16980026/51754734-fe0d5700-20b4-11e9-91b9-e7b4218429f8.jpg)

**Comment by LordPueblo** [comment]
@StuartB4 
![img_20190126_140929](https://user-images.githubusercontent.com/12953984/51786562-f31afb00-2176-11e9-8305-31b24f4a1e33.jpg)

**Comment by LordPueblo** [comment]
Dear @arkypita
here is the file attached which I send to board
[foxy_0022.zip](https://github.com/arkypita/LaserGRBL/files/2798929/foxy_0022.zip)

**Comment by LordPueblo** [comment]
here is my connection to ttl
![img_20190126_144746](https://user-images.githubusercontent.com/12953984/51786724-75a4ba00-2179-11e9-9a6c-ca3d06b1aa06.jpg)
![img_20190126_144731](https://user-images.githubusercontent.com/12953984/51786725-76d5e700-2179-11e9-9f6c-16c0d46ef6a1.jpg)

**Comment by StuartB4** [comment]
What did you use to create the file you uploaded (foxy_0022.zip)
I've just loaded it in to LaserGRBL and it looks all wrong.
Just a few red lines to burn and grey path lines.

![foxy](https://user-images.githubusercontent.com/16980026/51788326-b0582380-2174-11e9-87cb-cc99d9e96d72.jpg)

**Comment by StuartB4** [comment]
Looking at the GCode for the file, I noticed a lot of G4 P1 commands. 
How did they get in there ?
I think you need to get rid of the Servo version of GRBL and upgrade to the latest Version 1.1 from the link I supplied earlier.
https://github.com/gnea/grbl

**Comment by arkypita** [comment]
You are running with 1/4 of power.

**Comment by einencool** [comment]
Can you mark the wires on the picture with the cnc shield for the ttl connection?
I can't see them.
But as mentioned it seems that you have installed the wrong grbl version to your arduino

**Comment by LordPueblo** [comment]
Hi guys!
I use my plotter now with servo motor (to draw with marker) and I'd like to use the laser same time.

@StuartB4 thanks for recomendation. It seems like I uploaded wrong file. I'll send another one.
I tried different libraries but only one is working fine with servo motor it is the one I use now.
I'll try to install the one you send to me and let you know the result.

@arkypita the comand M3 SXX is working for 90 - it is maximum degrees which servo motor can move to. I have send M3 S120 and even 255 and the result was same as with M3 S90. I connected Servo to Z+ and Laser to Z- .

**Comment by LordPueblo** [comment]
> Looking at the GCode for the file, I noticed a lot of G4 P1 commands.
> How did they get in there ?

I generate the G Code file by Inkscape with MI GRBL Z-AXIS Servo Controller extention


> I think you need to get rid of the Servo version of GRBL and upgrade to the latest Version 1.1 from the link I supplied earlier.
> https://github.com/gnea/grbl
