### ISSUE TITLE
Problems with vector trace

### ISSUE THREAD

**Issue by WandMaker** [arkypita/LaserGRBL#567]
Hi
Iv'e found the neatest result for burning larger text, is to do a filled vector trace of a jpg file.  This works well about half the time! the other half, I get an unintended jog, so that the outline does not match the fill.
I assumed this was slippage on the hardware so I slowed the speeds down, but when it happens, it is always in the same place on the graphic despite using different areas of the laser bed.

Anyone have any suggestions what I should try?
![img_20190122_135121](https://user-images.githubusercontent.com/46929020/51540680-f64c7900-1e4e-11e9-8bd2-4d87f44bb6b9.jpg)

**Comment by arkypita** [comment]
Read similar topic: https://github.com/arkypita/LaserGRBL/issues/557

**Comment by WandMaker** [comment]
The trace shows a gap between the infill and the outline on the topside of each element. The laser is copying this very accurately, leaving that gap.  Is there any way around this?

![img_20190122_144207](https://user-images.githubusercontent.com/46929020/51542948-598cda00-1e54-11e9-8cff-51bd0030677d.jpg)

**Comment by arkypita** [comment]
@maillemaker if you see the image @WandMaker post on its own first message you can see a picture that show that in different areas of the engraved image he is having different offset in different part of the work-area. The "H" letter is correctly filled while "e, s, t" are engraved differently. This look like very similar to your problems.

> The trace shows a gap between the infill and the outline on the topside of each element. The laser is copying this very accurately, leaving that gap. Is there any way around this?

About the gap shown in preview you must consider that the gap you could see actually could be very very small. I guess you are producing very small output like 2x3cm and you are now showing it very very zommed like this:

![image](https://user-images.githubusercontent.com/8782035/51598227-5863b780-1efd-11e9-8dc5-52ba5c06672f.png)

The gap you are seeing in preview are actually tenths of a millimeter, and have no effects on engraving result.

**Comment by WandMaker** [comment]
Thanks @maillemaker that is an inspired observation!
I've been having the scenario that test pieces are looking fine, whereas the actual piece is slipping. Obviously the laser doesn't know what it's burning, the programme is the same, so I've been scratching my head, pixies was the best I could come up with!
The test pieces are rougher wood, the work piece is sanded! 
By jove, I think you've cracked it!!

**Comment by maillemaker** [comment]
Hope it works out for you, Wandmaker!  I am not convinced yet that my "super-smear" problems are due to work/machine movement, but I am still testing.  So far, so good.

**Comment by WandMaker** [comment]
Sorted!
@maillemaker that's fixed it. A bit of blu-tack on the feet is my high-tech solution.

Another small problem I had, was the cables snagging on the bolt-heads and corners, now I'm sure with a 3D printer you could make nice covers, I just used heat-malleable plastic, not so pretty, but works fine!


![img_20190201_114818 small](https://user-images.githubusercontent.com/46929020/52121457-9789bb00-2617-11e9-8ffe-4361fa38c761.jpg)
![img_20190201_114915 small](https://user-images.githubusercontent.com/46929020/52121472-a1abb980-2617-11e9-83f0-325e98c5ca42.jpg)
