### ISSUE TITLE
Laser GRBL freezing up when receiving information from GR BL controller

### ISSUE THREAD

**Issue by jguettler** [arkypita/LaserGRBL#572]
When the GRBL controller bounces back the GRBL position, about 50% of the time the program will just freeze up. Most of the time I can solve this by stopping and starting again. but occasionally it requres resetting the GRBL (at which point i have to re-home the mill).
See the image below with the last lines i typically recieve back before it freezes up.
any help would be apreciatd! 
<img width="190" alt="problem" src="https://user-images.githubusercontent.com/47289260/52172841-c5176580-27cb-11e9-800b-18e26fdc76db.png">

**Comment by arkypita** [comment]
See lasergrbl.co/faq about serial communication problem
