### ISSUE TITLE
Laser doesn't burn (GRBL 1.1)

### ISSUE THREAD

**Issue by SocialWood** [arkypita/LaserGRBL#576]

**Comment by SocialWood** [comment]
Hi. New laser (5500mW), and in LaserGBRL everything seems to work properly, but the laser doesn't burn. I did read some reactions here, but I think my problem isn't described (?). The laser is on, but that's it.

**Comment by SocialWood** [comment]
![2019-02-08 22_02_15-window](https://user-images.githubusercontent.com/47462566/52505933-508a5f80-2bed-11e9-833a-bbdb89c9f5a7.png)

**Comment by StuartB4** [comment]
Change $32 to 1.
Make sure the laser is focussed correctly.

**Comment by SocialWood** [comment]
Thnx. Focus: how?

Met vriendelijke groet,
Erik Vreekamp

-kort, want mobiel verstuurd-

Op 8 feb. 2019 om 22:48 heeft Stuart <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Change $32 to 1.
Make sure the laser is focussed correctly.

**Comment by StuartB4** [comment]
If you don't have an adjustable lens on the laser the only other way is to raise or lower the laser until you get the smallest dot size possible.
You should have the laser on low power and use eye protection when doing it.

**Comment by SocialWood** [comment]
OK, I did adjust it to a small dot. But nothing happens, also not on a paper underground :-(

**Comment by StuartB4** [comment]
Can you show us your harwdare and how it is all connected ?

**Comment by oxivanisher** [comment]
I might well be the problem I describe in #568 
(Starting with GRBL 1.1, the laser is not turning on with G0 movements, only G1 and higher)

**Comment by fabbbio986** [comment]
Maybe a problem with the power supply?
Check if your power supply can give enough current to the laser driver.

**Comment by SocialWood** [comment]
![20190212_191826975_ios](https://user-images.githubusercontent.com/47462566/52665366-b5a2c580-2f0b-11e9-96a4-c85a633fd3d2.jpg)
![20190212_191842313_ios](https://user-images.githubusercontent.com/47462566/52665367-b63b5c00-2f0b-11e9-84c9-f9633ccfc39f.jpg)
![20190212_191847038_ios](https://user-images.githubusercontent.com/47462566/52665368-b63b5c00-2f0b-11e9-8a08-0ed1ac9956aa.jpg)
![20190212_191901234_ios](https://user-images.githubusercontent.com/47462566/52665369-b63b5c00-2f0b-11e9-8423-81d47005004f.jpg)
![20190212_191904472_ios](https://user-images.githubusercontent.com/47462566/52665373-b6d3f280-2f0b-11e9-8f58-21489a7b7398.jpg)
![20190212_191908587_ios](https://user-images.githubusercontent.com/47462566/52665374-b76c8900-2f0b-11e9-80cb-9499fd8555ed.jpg)
![20190212_191917094_ios](https://user-images.githubusercontent.com/47462566/52665375-b76c8900-2f0b-11e9-8080-b6dad2cd781f.jpg)

**Comment by StuartB4** [comment]
Thanks SocialWood.
Everything looks ok there.
Are you using the power supply that came with the machine ?

Is this the Low Power/High Power Switch for the Laser?
![untitled-1](https://user-images.githubusercontent.com/16980026/52673661-4df37700-2f19-11e9-819b-fbc42836ef29.jpg)

**Comment by SocialWood** [comment]
That's power on/off

**Comment by SocialWood** [comment]
Anyone who can help me? It doesn't work in any way :-(

**Comment by arkypita** [comment]
> Update: laser is complete down now. I tried to connect to 2-pin laser connection on the Arduino, and after that the laser was off. Demolished?

Laser diode should ALWAYS be powered by its own driver board. In the most ideal form the driver board it is a constant current source, linear, noiseless, and accurate, that delivers exactly the current to the laser diode that it needs to operate. Your driver board is the blue one with fan.

If you have attached the black-yellow cable from laser to anything else you have destroyed it by sure.
Sorry

**Comment by SocialWood** [comment]
I connected to the 2-pin laser-connection on the arduino. Is that bad?

But another question: my first problem was not having a powerful laser to engrave in wood and even on paper. How was that possible?

**Comment by einencool** [comment]
Hi, 
Was the Code generated by LaserGrbl? What was the „max. Power“ in your Settings for your Picture? In the config I can see, that the „max Spindle speed“ is set to 1000. 
To engrave wood or paper you need almost around 200-250 in your G-Code to engrave wood.

I hope you understand what I mean, but I don‘t know how to explain it :-)

**Comment by osmosis14** [comment]
Make sure that when you create the code that you change the 0 to 255 to something more like 0 to 900.

**Comment by Actionslats** [comment]
Hi All. I have the same setup and a similar problem, but my laser is only a 2.5w. It was working, then I updated LaserGrbl, and now it doesn't work. Any ideas?
