### ISSUE TITLE
Missing Configurations/cant enable laser mode

### ISSUE THREAD

**Issue by monk1974** [arkypita/LaserGRBL#579]
Hello everyone. Quick summary, got a diy laser weeks ago, default software wasn't good, changed control board, started using LaserGRBL <-loving it.

My problem is I have been using this forum to figure things out and I have realized that everyone's screenshots of their grbl configuration window doesn't look like mine.

I am missing some values and this has made certain things impossible to do. I did not delete anything, this is how its been since install. I think my laser is out of laser mode and cant change it.

![screenshotlaser](https://user-images.githubusercontent.com/47600162/52715501-98511400-2f6a-11e9-9513-abf6baa23834.JPG)

**Comment by arkypita** [comment]
Laser mode was added in grbl v1.1.
What grbl version is installed in your control board?

https://www.google.it/search?q=update+grbl+to+1.1

**Comment by monk1974** [comment]
My card says Woodpecker 3.0.2  GRB
Apparently it is a 0.9

Thanks for the reply

**Comment by Gabezoid** [comment]
How can I check the installed version?
I have problem with jogging command, but maybe I just need to update the board

**Comment by StuartB4** [comment]
![untitled8](https://user-images.githubusercontent.com/16980026/53683097-f7e24a00-3cf4-11e9-96de-02de005ac682.jpg)

**Comment by Gabezoid** [comment]
Oh damn me, it was easy! :) Thank you very much Stuart, I'll open a thread then for the jogging problem then, my board should be updated (i have 1.1z version)
Thank again!

**Comment by StuartB4** [comment]
I think 1.1z is a custom version, I would stick to official 1.1f from here:
https://github.com/gnea/grbl/releases

**Comment by Gabezoid** [comment]
Indeed the problem was the 1.1z! Thank you very much :)
