### ISSUE TITLE
Override interface

### ISSUE THREAD

**Issue by oliv690** [arkypita/LaserGRBL#581]
Hello,
I tried to use override interface but it doesn't appear, even if I have LAserGrbl V3.0.4 and Grbl 1.1g.

I checked config.he and I don't disable any information on override setting.

I don't know how this interface should appear.

I have K40 laser with Arduino. 

Could you help in on this?

Than you

**Comment by StuartB4** [comment]
![untitled](https://user-images.githubusercontent.com/16980026/52914387-771c5a80-32bf-11e9-8f52-2e7320d2930f.jpg)

**Comment by LazerGalva** [comment]
Hi, I have something similar, but I don't have a override interface even on the bottom. What I should do now :D ? Is it some ERROR, or i need some plugin or fix bug? Actually I need all those buttons as well, dose someone knows some Gcode for that?  Thank you!
![dontHave_override](https://user-images.githubusercontent.com/49975182/56719196-f0657d00-6748-11e9-9f53-e3c04c38562f.jpg)
ug.

**Comment by cherry1pita** [comment]
a little late to this conversation. just started using lasergrbl and wanted to ask what the linear and the rapid options were for .?
