### ISSUE TITLE
Laser engraves unevenly

### ISSUE THREAD

**Issue by StepanTsymbaliuk** [arkypita/LaserGRBL#582]
Hello!
Recently during the engraving with LaserGRBL I have some problems with the final result. The thing is that in the middle of the process the engraving letters are shifted. The programmed picture is dislocated randomly and some extra lines are engraved. Please see the attached pictures.
![viber image 2019-02-19 11 04 49](https://user-images.githubusercontent.com/47775799/53004756-7bb94e00-343a-11e9-8fa2-7107f84a3d6b.jpg)
![viber image 2019-02-19 11 04 51](https://user-images.githubusercontent.com/47775799/53004757-7bb94e00-343a-11e9-96b1-15a3debb5ecf.jpg)

**Comment by arkypita** [comment]
Not a software problem, check your hardware.
Belt, motor, vibration and slippage of engraver respect of the piece or vice versa...

https://github.com/arkypita/LaserGRBL/issues/557

**Comment by StepanTsymbaliuk** [comment]
Thank you for your quick response. I appreciate your help. Could you also advise what is the reason why some extra lines are engraved along with the main letters?
![viber image 2019-02-20 10 21 50](https://user-images.githubusercontent.com/47775799/53076888-7c64e980-34f9-11e9-979f-2c0c49371a51.jpg)
![viber image 2019-02-19 18 02 23](https://user-images.githubusercontent.com/47775799/53076889-7c64e980-34f9-11e9-8fb4-3f63d762edad.jpg)

**Comment by StuartB4** [comment]
Looks like the laser is not switching off when moving across a blank space.
Was the GCode generated with LaserGRBL of another application and loaded in to LaserGRBL.

**Comment by StepanTsymbaliuk** [comment]
No, I never use GCode or any other application generated with LaserGRBL. Will Gcode help me to solve this problem? Are there any other applications that can improve the engraving?

**Comment by StuartB4** [comment]
You could try a program called T2 Laser.
They have a free trial version, so you dont have to buy it to try it.
https://t2laser.wordpress.com

**Comment by SHristov92** [comment]
The misalignment looks like missed steps. Check the current settings of the motors and if there is some mechanical issue that could block the motion.

**Comment by StepanTsymbaliuk** [comment]
Hello!  Thanks for all the help, but the problem that the laser is not switching off when moving across a blank space is still present.  I was told this could be when the Adruino settings on a computer is TTL and on laser heads it' PWM and they can't work together.  It is possible?  How can I fix this? 
Thank you for your help in advance. 
![1](https://user-images.githubusercontent.com/47775799/65758837-6b7cf600-e122-11e9-9174-e4409514b8f1.jpg)
![2](https://user-images.githubusercontent.com/47775799/65758838-6b7cf600-e122-11e9-8417-c1309c14e68e.jpg)
![3](https://user-images.githubusercontent.com/47775799/65758840-6b7cf600-e122-11e9-80f8-0aadb53ea991.jpg)
![4](https://user-images.githubusercontent.com/47775799/65758841-6c158c80-e122-11e9-90cb-43b77b75a88e.jpg)

**Comment by arkypita** [comment]
> Hello! Thanks for all the help, but the problem that the laser is not switching off when moving across a blank space is still present. I was told this could be when the Adruino settings on a computer is TTL and on laser heads it' PWM and they can't work together. It is possible? How can I fix this?
Thank you for your help in advance.

TTL or PWM mean the same. They are two words that say that the laser is able to be switched on/off rapidly via 0-5V signal ([TTL](https://en.wikipedia.org/wiki/Transistor–transistor_logic)) so you can modulate its power by switching on/off very fast and varying duty cycle ([PWM](https://youtu.be/B_Ysdv1xRbA?t=10)).

Laser modules with this ability usually have 3 Wires (black/red for power + other color for TTL signal).

In the image you show seem that the laser does not turn off "randomly", not always.
What append if you run the same program twice? the laser does not turn off always in the same position, or not? In few words: can you confirm that this is a random effect or not?

Did you see any red error icon near sent GCode?

![image](https://user-images.githubusercontent.com/8782035/65760985-4c7c6500-e11e-11e9-96a6-44f27e6154b7.png)

**Comment by StepanTsymbaliuk** [comment]
@arkypita The laser makes a random error.  There are no constant errors.
 No.  unfortunately i didn't pay attention to the error icon (if it fails again i will definitely check)
 if you run the program for a second time (after an error) it is possible that everything will be fine or again it will make a mistake somewhere else.
![1](https://user-images.githubusercontent.com/47775799/65763491-37a6ce00-e12c-11e9-9c8a-aba46ab65e42.jpg)
![зображення_viber_2019-09-27_13-30-59](https://user-images.githubusercontent.com/47775799/65763492-37a6ce00-e12c-11e9-9375-3b67e456148e.jpg)
![зображення_viber_2019-09-27_13-31-00](https://user-images.githubusercontent.com/47775799/65763495-383f6480-e12c-11e9-8ab9-dfa62bffdc4c.jpg)

**Comment by arkypita** [comment]
> There are no constant errors.
> No. unfortunately i didn't pay attention to the error icon (if it fails again i will definitely check)
> if you run the program for a second time (after an error) it is possible that everything will be fine or again it will make a mistake somewhere else.

LaserGRBL always send the same commands.
Also your electronics do always the same stuff for the same commands.

So What?

When LaserGRBL send a command to your electronic sometime could happen that the command are received wrong.

This is like what append in the "[chinese whisper](https://en.wikipedia.org/wiki/Chinese_whispers)" game: You say "cat" but the other ear "rat".

If both words have a common sense in the phrase you don't have any chance to realize the mistake.
- I turned the corner and I saw a really big cat
- I turned the corner and I saw a really big rat

The hardware give no feedback of what receive, except for a simple "ok" / "error" message, that LaserGRBL report as green or red icon. 

So, if sometime you have a red icon near any message, this could be the issue.

**Comment by StepanTsymbaliuk** [comment]
@arkypita I understand what you're trying to say. But the thing is that I don't know how can I avoid this error happening again? By error I mean Laser is not switching off during the engraving and making these extra lines.

**Comment by arkypita** [comment]
> the thing is that I don't know how can I avoid this error happening again?

If the problem is what I assume, you can try the solution explained in lasergrbl.com/faq

**Comment by StepanTsymbaliuk** [comment]
@arkypita Thanks for the advice. I'll try to solve the problem. I'll keep you in touch.
