### ISSUE TITLE
LaserGRBL v3.0.7 unsteady connection

### ISSUE THREAD

**Issue by Jnb3d** [arkypita/LaserGRBL#583]
Hello everyone, I can not keep the connection to my machine in the LaserGRBL software, it connects but disconnects soon then.
Follow the image maybe you can help me what is happening?
![01_erro](https://user-images.githubusercontent.com/23400467/53040682-bf26b300-3460-11e9-9539-0b4239cb2e99.jpg)

LOGS
___________________________________________________________________________________
19/02/2019 16:00:28	Program     	------- LaserGRBL v3.0.7 START -------
19/02/2019 16:00:33	SetStatus   	Machine status [Disconnected]
19/02/2019 16:00:37	SetStatus   	Machine status [Connecting]
19/02/2019 16:00:37	OpenCom     	Open COM5 @ 115200 baud 
19/02/2019 16:00:37	SendImmediate	Send Immediate Command [0x18]
19/02/2019 16:00:47	OpenCom     	Connection timeout!
19/02/2019 16:00:47	CloseCom    	Close COM5 [CORE]
19/02/2019 16:00:47	SetStatus   	Machine status [Disconnected]
___________________________________________________________________________________

**Comment by arkypita** [comment]
LaserGRBL is compatible with Grbl firmware.
Your engraver use benbox firmware

http://lasergrbl.com/en/faq/

**Comment by Jnb3d** [comment]
Obrigado, é possível trocar firmware?

**Comment by Jnb3d** [comment]
Thanks, it is possible to exchange firmware?

**Comment by StuartB4** [comment]
Have a look here:
http://benboxlaser.us/index.php?topic=11.0
