### ISSUE TITLE
Absolute to Relative conversion

### ISSUE THREAD

**Issue by garthanstey** [arkypita/LaserGRBL#585]
I have a project which requires me to repeat an image various time in different locations. The actual location can vary until late in the creation process. For example; I have engraved an image and I now want to include hearts in that image at different aesthetic locations. I would now create a start location for each heart, followed by the Relative G91 code. As the hearts accumulate I can make the decision to stop adding more. (Heartache perhaps?)
The Holy Grail would be a text file that could hold colon/comma separated information such as- X100Y100Z10S255F1000: X200Y etc . This would also be a boon for looping progressive Z values for those wood chewers. If there is software out there that converts G90 to G91 I'll settle for that.

**Comment by arkypita** [comment]
To engrave the same image in different places it is sufficient to move somewhere and assign a new zero point. Setting a new zero is done with G92 X0 Y0
