### ISSUE TITLE
 Help to start the laser. , SW-LD73 v1.1, with DEVELOPOWER V2.0

### ISSUE THREAD

**Issue by josestrella** [arkypita/LaserGRBL#586]
Good afternoon, I bought this laser module and I have this arduino card. I am new in this world and I would like to know how can I put it to work?
![whatsapp image 2019-02-22 at 9 08 46 am 1](https://user-images.githubusercontent.com/47903712/53274421-93f4cb80-36cd-11e9-8f14-b1318dd71438.jpeg)
![whatsapp image 2019-02-22 at 9 08 46 am](https://user-images.githubusercontent.com/47903712/53274422-948d6200-36cd-11e9-803d-1f4876d63c29.jpeg)

**Comment by Cetarik** [comment]
First, let my say that i am not 100% sure but i can tell you that i have just made my device work with DEVELOPOWER v2.0 but different.
My board looks like this:
![obrazek](https://user-images.githubusercontent.com/56511971/66717607-253ebc80-eddb-11e9-9fd4-5afa09cb6f68.png)

As you can see they are quite the same.
I guess you need to desolder that thing in the laser slot, solder there 3pcs of 2,54mm pins.
Then you need to measure what is your pinout. Middle pin should be GND but for example my board has switched PWM and +12V as you can see in the picture.
For me now it works with my board.

![obrazek](https://user-images.githubusercontent.com/56511971/66717545-9df14900-edda-11e9-93a7-2f2677ee91aa.png)

**Comment by jeffolemes** [comment]
Oi amigos, sou novo no assunto e gostaria de uma ajuda se possível, tenho o mesmo módulo laser, um arduíno uno e CNC shield v3, o grbl está configurado para laser já confirmei tudo mas quando ligo na energia já saí queimando na potência máxima, não faz o processo de liga e desliga na gravação com os comandos M3, M4 e M5! Por favor

**Comment by leoheck** [comment]
Hi @josestrella I have the same board. I am looking for the schematics of this board. Do you have any idea how to find it? I would like to work around it to be able to use GRBL 1.1

**Comment by johnalleO** [comment]
I purchased one of these and am looking at https://madhacker.org/sw-ld73-laser-driver-modification/ where they talk about removing a resistor to stop full power on start up. Has anyone tried this and does it work? I want to make sure that if I do remove this that the power will get to 100% when I need it.

**Comment by StuartB4** [comment]
Not tried it myself, but you should know they remove a Diode the Resistor is next to it on the right. If you do remove it and end up putting it back on make sure you put it the right way round, take a photo before you start. Diodes are polarised so they will only allow current in one directiuon, so it has to be right.
