### ISSUE TITLE
Nodemcu and laserweb esp8266

### ISSUE THREAD

**Issue by JalenTk** [arkypita/LaserGRBL#593]
Is it possible to use laser web esp8266 on laser gel if I do a serial communication between Nodemcu Esp8266 and Arduino Uno attached with an CNC shield ?

**Comment by arkypita** [comment]
I think so

**Comment by pblacq** [comment]
Cant comment on LaserWeb, but LaserGrbl works well with ESP12 and Arduino.  Check the RX signal for the ESP12 is not being pulled (hi/low) by your ESP12 module's USB<->Serial converter.
