### ISSUE TITLE
Jogging issue / Doesn't move

### ISSUE THREAD

**Issue by Gabezoid** [arkypita/LaserGRBL#596]
Greetings everyone!
I'm testing laserGrlbl on my Bachin Maker, and looks great!
Just one thing, jogging control doesn't respond.

The machine is connected and as you can see on the image it recognise the command., but when I press it the jog doesn't move. What can I do?

Thanks everyone for your time :)

ps. It works correctly when I launch a job.

<img width="257" alt="schermata 2019-03-02 alle 23 05 01" src="https://user-images.githubusercontent.com/48155704/53688150-9e533d00-3d3f-11e9-9a30-c32eb6f092e1.png">

**Comment by StuartB4** [comment]
Although it works with my machine with and without the spaces, have you tried typing the commands with spaces in like this.
$J=G91 X10 Y20 F200

**Comment by Gabezoid** [comment]
Solved! I updated to 1.1f and it works!

**Comment by StuartB4** [comment]
Thats good to know. :)
