### ISSUE TITLE
Lazer software won't connect

### ISSUE THREAD

**Issue by haunna** [arkypita/LaserGRBL#598]
The laser GRBL software, while it says it's not connected still causes the Z axis to bottom out as soon as I click the connect icon.
I can't stop it and it will continue to run, trying to go lower even after it bottoms out. I have to unplug the machine.
I also have to unplug the USB or when the machine is re-plugged in it, starts to try and bottom out again.
So it would seem there is some connection, but an improper one.
Any Ideas. 
Everything is new, Router CNC GRBL works greats, Just this problem with the laser.
Ernie

**Comment by StuartB4** [comment]
Have you got Hard Reset [DTR+RTS] enabled in LaserGRBL settings.
If so try it with it disabled.

![untitled](https://user-images.githubusercontent.com/16980026/53775248-b36bcf80-3ee9-11e9-859c-1e9036a6e2e1.jpg)

**Comment by haunna** [comment]
Stuart,
I got the program to run whatever pic I choose doing as you suggested. I click 'on" the hard reset.
Everything loads and stays connected; But the laser doesn't come on.
I have control of the manual controls and it will run the file, just No Laser.

Ideas ??
Ernie

**Comment by StuartB4** [comment]
What connections do you have to the laser.
Can you upload pics of your setup, like the wiring connections for the laser / laser driver and the main control board.

**Comment by codechangerr** [comment]
did you turn on lazer mode with $32=1?
