### ISSUE TITLE
Laser burns in wrong way creating unwanted effect

### ISSUE THREAD

**Issue by Elvis999IT** [arkypita/LaserGRBL#600]
Hi
Since this morning before update to 3.0.9 everithing was perfect. I was at 3.0.4.
Then i begin to have a strange effect, i tried different file and also differen format, different material,
the image it show 4 line diagonal but i have the same effect with orizzontal.
I tried everithin, uninstall th 3.0.9, install again 3.0.4. checked power line, signal, everithing but no result.
![wave](https://user-images.githubusercontent.com/48330354/53979497-500eb700-410e-11e9-9fef-1fe039ed19c7.png)

**Comment by gisep** [comment]
are you talking about the "low density"?

**Comment by StuartB4** [comment]
Whats the actual problem? It’s hard to tell whats wrong because we have not seen how it was before.

**Comment by Elvis999IT** [comment]
hi, thanks for the quick answer.
As you can see the top part appear with orizzontal line, one more dark, than one less, again more dark...
It shoul be all the same color.
I also tried with a black square made with Paint, same effect.
It must be just a black block.
Is not the material because before update (or at least is the only difference) i made the same image and was perfect.

**Comment by Elvis999IT** [comment]
No one have an idea of what it can be?
i tried different PC, different LaserGRBL version, reflashed arduino...
I Still Have this problem.
Next it will be replace the arduino board...

**Comment by arkypita** [comment]
You can exclude LaserGRBL issue. IMHO your is an hardware problem.
Look like "elastic" pull-spring tension, or eccentric problem of your engine/gears that cause laser head accelerating-decelerating during engraving
