### ISSUE TITLE
working table starts to move in y immediately on start up.

### ISSUE THREAD

**Issue by tjensen03** [arkypita/LaserGRBL#603]
Hello,
I'm using the SainSmart 5.5W laser module (for the first time yesterday). When I start LaserGRBL, the table automatically starts to move in -y direction. The only way to stop it is to kill the power and unplug the USB cable.  I did manage to get it to connect and runit ok after a few tries yesterday, but tonight, no luck... On connection, it starts to move, and the status bar says "connecting". 
If I use Candle, (the CNC software that came with the machine) as a test of the system, there is no issue. Everything seems fine.
Any idea what's causing this?
My other issue is with the PWM mode... it isn't strong enough to burn. I have to use the "power" switch on the PCB to get any burn at all. From what I read, this might be the S32=1 (from 0) issue? 

Regards 
Tim

**Comment by tjensen03** [comment]
Hi. Thanks for the quick response.
The first thing I tried was to uncheck the resets. I am currently using an old laptop running XP. I will load the software onto a Win 7 laptop and try that today.

**Comment by tjensen03** [comment]
SOOOOO close!
OK, I have the laser pulsing and burning now. Things move in the correct directions. Still working on bland and white images, haven't moved on to grey scale yet. Last remaining question... how do I set the home position? 
Thanks!!!

**Comment by arkypita** [comment]
The button with a globe and pin set zero position, as its tooltip say.

**Comment by tjensen03** [comment]
Great. Thank you for your help an patience!

**Comment by StuartB4** [comment]
> but two options that might be useful... a low power "laser on" setting to allow focus, but not strong enough to engrave.

Laser on to focus.

![Untitled2](https://user-images.githubusercontent.com/16980026/54275649-14974100-4583-11e9-8d46-e93c75ce1427.jpg)

>  And a preview area command that would move the laser around the work area at low power so that the user can ensure the work piece is properly positioned.

Make another Custom button this time just leave the Type setting to read Button.

Add this code to the GCode box.
M4 
S2
F1700
G0 X[left] Y[bottom] 
G1 X[right]
G1 Y[top]
G1 X[left] 
G1 Y[bottom] 
G0 X0 Y0 F4000
M5

Then add a Tooltip again.
Select Connected again and click save.

**Comment by StuartB4** [comment]
Another button you might find useful is to find the center of the image you have prepared.

![Untitled3](https://user-images.githubusercontent.com/16980026/54276817-28907200-4586-11e9-89b9-8ddad3c32375.jpg)

**Comment by tjensen03** [comment]
Thank you Stuart!!! That is exactly what I needed!!!

**Comment by StuartB4** [comment]
Glad to help. :)

**Comment by tjensen03** [comment]
Hey Stuart, I tried running the focus command and it doesn't seem to work. Laser doesn't come on even with $32=100 and it throws an error on second click "Expected value is..."  The center and work area commands are fine.
Any thoughts?

**Comment by StuartB4** [comment]
What version of GRBL are you using? It should tell you here:

![Untitled](https://user-images.githubusercontent.com/16980026/54475616-309d1b80-47eb-11e9-9fd3-edc5d7500be6.jpg)

Make sure you typed $32=0 and $32=1 not S32=0 it should be the dollar sign not S.

![Untitled2](https://user-images.githubusercontent.com/16980026/54475646-95587600-47eb-11e9-83f5-029c52e8982c.jpg)

**Comment by tjensen03** [comment]
Yep... figured it out... S instead of $. Old glasses and older eyes don't mix well LOL!

Again, thanks for your help. This is exactly the setup I wanted!

**Comment by StuartB4** [comment]
Haha, same here, old eyes, easy mistake to make, glad you sorted it.
