### ISSUE TITLE
Line spacing and off measurements.

### ISSUE THREAD

**Issue by Mk5mod0** [arkypita/LaserGRBL#604]
Hello

I just got a laser burner and am using LaserGRBL with it and love it.
But after my first controller burned up (The controller that came with the machine) I replaced it with a new Arduino Nano. After flashing the Arduino with Arduino IDE I thought I was good to go. But when I go to burn something there are large spaces between the lines, the program messes up the picture completely, or the measurements are off. It also writes backwards. Please help.

![p1](https://user-images.githubusercontent.com/48631467/54480899-bb3e4480-4804-11e9-9256-089cebfbc551.jpeg)
![p2](https://user-images.githubusercontent.com/48631467/54480900-bb3e4480-4804-11e9-8110-c01c43d4d6ea.jpeg)
![p3](https://user-images.githubusercontent.com/48631467/54480901-bb3e4480-4804-11e9-9b88-bb20eb04f617.jpeg)

**Comment by arkypita** [comment]
https://github.com/arkypita/LaserGRBL/issues/607

**Comment by Mk5mod0** [comment]
Thank you for all of your help everything is up and running like new.
