### ISSUE TITLE
Moving with numeric keypad does not work since v3.0.10

### ISSUE THREAD

**Issue by mucek4** [arkypita/LaserGRBL#605]
In version v3.0.10 "jogging control" was changed. Since then moving around with numeric keyboard does not work any more. Button "5" go home still works, others yust execute:
```
G91
G0X0Y0F1000
G90
```

Command works, just relative move direction is "0"

**Comment by arkypita** [comment]
Jogging control was changed due to external code contribution.
I admit I didn't check the implications too carefully.

I'll give a check and fix asap, thanks for report.

**Comment by arkypita** [comment]
fixed
