### ISSUE TITLE
My Custom buttons Zup and Zdown don´t work in new version

### ISSUE THREAD

**Issue by David7820** [arkypita/LaserGRBL#606]
Hi, my customs buttons Z up and  Z down don't work after loading the new version.
step up: $J= G91 Z[jogstep] F[jogspeed]
step down: $J= G91 Z[0-jogstep] F[jogspeed]
However, the new jog "home" icon turn down the z axis when make homing.
I do not know if it's just my case or it's happened to more people.
Thanks.

**Comment by arkypita** [comment]
Yes, it's the same cause of #605
The new jog control loose the slider for jog step and broke some features.

I suggest to put fixed value instead of jogstep and speed in your variables until i have found a good way to put both features together

**Comment by David7820** [comment]
Ok, Thanks.
Você é grande.

**Comment by arkypita** [comment]
Whould you like to try? https://github.com/arkypita/LaserGRBL/releases/tag/v3.0.11

**Comment by David7820** [comment]
Thanks,  I'll try tomorow.

Enviado desde Yahoo Mail con Android 
 
  El mar., may. 7, 2019 a 9:42, arkypita<notifications@github.com> escribió:   
Whould you like to try? https://github.com/arkypita/LaserGRBL/releases/tag/v3.0.11

**Comment by arkypita** [comment]
fixed

**Comment by David7820** [comment]
Ok, works fine, like before.Thanks. 

Enviado desde Yahoo Mail con Android 
 
  El mié., may. 8, 2019 a 10:19, arkypita<notifications@github.com> escribió:   
fixed
