### ISSUE TITLE
Right slider by jogging control missing

### ISSUE THREAD

**Issue by ShKh001** [arkypita/LaserGRBL#608]
Hello, with the new update the right slider by jogging control is missing.
Thanks for your help.
![Missing slider](https://user-images.githubusercontent.com/48842794/54853728-f05d0200-4cf0-11e9-9ab9-915ebe9386d3.JPG)

**Comment by Stankovo** [comment]
I have the same problem! Help!Still, low speed at burning out except vector. How to fix?

**Comment by Stankovo** [comment]
Went back to 3.09 appeared as before right regulator.

**Comment by StuartB4** [comment]
Read Arkypitas reply comment here.
https://github.com/arkypita/LaserGRBL/issues/606

**Comment by Stankovo** [comment]
I suggest to add a button that you hold down the mouse, you can move in any direction like a joystick. Pulled to the right a little - moving slowly to the right. I pulled harder, moving harder. Pulled right up - will move in this direction. Joystick button. He pointed the mouse, pressed the left button and holding adjust the direction and speed of the laser head.

**Comment by arkypita** [comment]
> I suggest to add a button that you hold down the mouse, you can move in any direction like a joystick. Pulled to the right a little - moving slowly to the right. I pulled harder, moving harder. Pulled right up - will move in this direction. Joystick button. He pointed the mouse, pressed the left button and holding adjust the direction and speed of the laser head.

This is not possible with the actual jogging protocol supplied by grbl/gcode.
You cannot send "runtime" jogging but only "go there with this speed" commands

**Comment by arkypita** [comment]
fixed
