### ISSUE TITLE
In v3.0.4, the X axis is moved uniformly in the Laser Mode, in version 3.0.10 X-axis moves as if not seeing that the mills in Laser Mode

### ISSUE THREAD

**Issue by sbrv** [arkypita/LaserGRBL#610]
In v3.0.4, the X axis is moved uniformly in the Laser Mode, in version 3.0.10 X-axis moves as if not seeing that the mills in Laser Mode

**Comment by arkypita** [comment]
the request is not understandable

**Comment by StuartB4** [comment]
Do you mean it's not moving in millimeters ?
If so then it may be the steps per/mm setting in GRBL settings has changed in the 3.0.10.
See my first comment here: https://github.com/arkypita/LaserGRBL/issues/607

**Comment by sbrv** [comment]
I mean, in version 3.0.4, the X-axis with the laser moves all the time at a constant speed, and after upgrading to 3.0.10, the X-axis starts to move unevenly: accelerates and slows down, as if the "laser mode" parameter is 0. As a result, the picture quality has deteriorated dramatically.  02.04.2019, 13:11, "Stuart" <notifications@github.com>:Do you mean it's not moving in millimeters ?If so then it may be the steps per/mm setting in GRBL settings has changed in the 3.0.10.See my first comment here: #607—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
