### ISSUE TITLE
No movement/ power. 

### ISSUE THREAD

**Issue by Mooftah** [arkypita/LaserGRBL#611]
assembled Tsemy Direct DIY 3040, Led light on, and connectivity to GRBL 3.0.1. I cannot move the engraver manually, there is no laser on, no laser fans, and when i tell the program to run the project...it completes with zero movement from the machine.

**Comment by arkypita** [comment]
Did you connect DC 12V power supply?

**Comment by Mooftah** [comment]
Yes.. I even tried a different one. Still nothing.

**Comment by arkypita** [comment]
The problem is only with LaserGRBL or also with others gcode sender like UGS etc?

**Comment by Mooftah** [comment]
First off. thank  you so much for being so responsive. you should know im very new at this GRBL game so my trouble shooting skills are limited. i agree think its a power issue not a software issue. Not sure what UGS is?

**Comment by arkypita** [comment]
Isba software called "universal gcode sender"
