### ISSUE TITLE
Vectorize Filling Not Burning

### ISSUE THREAD

**Issue by designr47** [arkypita/LaserGRBL#616]
Hello guys,
I'm using this software and very happy with it. 
But today i found a little problem.
I can use vectorize with no problem but It's not burning with filling option on. 

Here is the first 20 lines of codes.

With filling (diagonal. I've tried horizontal too, same)
`G90
G0 X0 Y0
M4 S0
F3000
G0 X36 Y2.667 S0
G1 X36.333 S1
G0 X38.667 Y3 S0
G1 X38.333 S1
G0 X36.667 Y3 S0
G1 X36.333 S1
G0 X36.333 Y3.333 S0
G1 X38 S1
G0 X38.333 Y3.333 S0
G1 X39 S1
G0 X40 Y3.333 S0
G1 X40.333 S1
G0 X40 Y3.667 S0
G1 X39.333 S1
X39 S2
X38.667 S1`

without filling (none)
`G90
G0 X0 Y0
M5 S255
F2000
G0 X60.838 Y32.902
M4
G1 X60.926 Y32.9
G1 X61.238 Y33.086
G1 X61.55 Y33.272
G1 X62.124 Y33.504
G1 X62.698 Y33.736
G1 X62.663 Y33.77
G1 X62.629 Y33.804
G1 X62.034 Y33.666
G1 X61.44 Y33.527
G1 X60.947 Y33.309
G1 X60.453 Y33.091
G1 X60.602 Y32.997
G1 X60.75 Y32.903
G1 X60.838 Y32.902`

laser turns on and working with filling option too but its just not burning anything.

**Comment by StuartB4** [comment]
For some reason all the S commands in the first lines (With Filling) you posted are either 0, 1 or 2.
Thats the power setting of the laser, so it wont burn anything with it set so low.

**Comment by designr47** [comment]
I know right ? Why does this happen ? I don't change the last settings same turn on m4, turn off m5, min power 0, max power 255.

**Comment by StuartB4** [comment]
Thats really strange. have you tried it with all the different settings here:
![Untitled](https://user-images.githubusercontent.com/16980026/55823496-bca81780-5af9-11e9-9686-a7a80791d68d.jpg)

**Comment by designr47** [comment]
I've tried horizontal and diagonal, only didn't try with vertical.

**Comment by StuartB4** [comment]
Just had a look myself,  if I select With filling I only get 1 S command in the generated code and that is set to 255.

Like this.
First few lines:
G90
G0 X0 Y0
M5 S255
F1000
G0 X19.2 Y5.918
M4
G1 X18.85 Y5.934
G1 X18.45 Y5.971
G1 X18.05 Y6.009
G1 X16.859 Y6.206
G1 X15.668 Y6.403
G1 X14.759 Y6.764
G1 X13.85 Y7.126
G1 X13 Y7.528

**Comment by designr47** [comment]
Do you use unidirectional engraving ? I don't, is this relevant?

Tomorrow I'll try on another computer with clean lasergrbl. I'll update.

**Comment by StuartB4** [comment]
Unidirectional is unticked on mine.

**Comment by designr47** [comment]
Another pc, lastest release. Those are my settings. Do they wrong or something ?
![image](https://user-images.githubusercontent.com/9532207/55854614-eb5fd580-5b6d-11e9-961f-b2c86a1100bf.png)
![image](https://user-images.githubusercontent.com/9532207/55854656-03cff000-5b6e-11e9-9a40-04fb27918b58.png)

And here is the result gcode
![image](https://user-images.githubusercontent.com/9532207/55854695-206c2800-5b6e-11e9-9057-41051df0c90e.png)

**Comment by StuartB4** [comment]
You might just have your speed settings to high.
This is with the same settings as yours but with a speed of 800 for both.
![Untitled11](https://user-images.githubusercontent.com/16980026/55875030-ef9aeb80-5b8b-11e9-969b-7b1cf5306964.jpg)

![Untitled12](https://user-images.githubusercontent.com/16980026/55875059-fd507100-5b8b-11e9-8ec4-3181dd545632.jpg)

![Untitled8](https://user-images.githubusercontent.com/16980026/55875080-093c3300-5b8c-11e9-8ea3-5c493858d666.jpg)

End Result. Would be better if the amount of lines was increased, it's only set to 3.
Also, my machine is only capable of burning 40 x 40 mm's, until I get a bigger one.

![IMG_68952](https://user-images.githubusercontent.com/16980026/55875093-122d0480-5b8c-11e9-92a8-1ae7c7ac308b.jpg)

**Comment by designr47** [comment]
Can you show the start of the code ?

**Comment by arkypita** [comment]
The image scaling produce smooth/light borders (a sort of anti-aliasing) that filling algorithm try to follow modulating power at the edge to produce less jagged edges.

With very small size and low line/mm this can produce very "light" filling lines.
If you need to "pump up" the power you can operate setting 300 or 350 inside S-MAX

This ensure your edges will always be engraved at the max power.

**Comment by StuartB4** [comment]
This one is with 6 lines/mm at the same speed of 800. 
Ignore the white bit on it's nose, it was something on the card.

![IMG_68977](https://user-images.githubusercontent.com/16980026/55877307-a188e680-5b91-11e9-986f-b9c389e7d8bf.jpg)

**Comment by StuartB4** [comment]
This is start of code for the 6 lines/mm.

G90
G0 X5 Y0
M4 S0
F800
Y0.167
G0 X11.5 Y1 S0
G1 X12 Y0.5 S1
G0 X11.667 Y1 S0
G1 X11.5 Y1.167 S1
G0 X11.333 Y1.5 S0
G1 X11.667 Y1.167 S5
G0 X11.833 Y1.167 S0
G1 X11.667 Y1.333 S15
X11.5 Y1.5 S70
X11.333 Y1.667 S36
G0 X11.333 Y1.833 S0
G1 X11.5 Y1.667 S50

**Comment by StuartB4** [comment]
@arkypita.

> If you need to "pump up" the power you can operate setting 300 or 350 inside S-MAX

Would that make a difference if the Max setting in GRBL Config is 255. ?

**Comment by arkypita** [comment]
> @arkypita.
> 
> > If you need to "pump up" the power you can operate setting 300 inside S-MAX
> 
> Would that make a difference if the Max setting in GRBL Config is 255. ?

If you put 300 as S-MAX LaserGRBL will scale any grayscale value from zero for white to 300 for black. It warns you with a red box that values over config are probably wrong, but it allow you to use the value.

GRBL by its side use the max value of 255 also if you send 300 or 10000, so no problem!

**Comment by designr47** [comment]
It was my fault. The image was so small to and has thin lines to engrave.

> 
> The image scaling produce smooth/light borders (a sort of anti-aliasing) that filling algorithm try to follow modulating power at the edge to produce less jagged edges.
> 

These are the proper results.

![IMG_20190410_181344](https://user-images.githubusercontent.com/9532207/55891469-4836ac80-5bbd-11e9-9cfa-c7e969c9a94c.jpg)
![IMG_20190410_181400](https://user-images.githubusercontent.com/9532207/55891470-4836ac80-5bbd-11e9-93ce-fc0b709b1586.jpg)

You can close the thread

**Comment by StuartB4** [comment]
@arkypita.

Ok, thanks for explaining that.

@designr47.

Glad to see you sorted it out.

**Comment by arkypita** [comment]
Perfectly sharp! This is the LaserGRBL i know
