### ISSUE TITLE
M8/M9 commands (Target Image window)

### ISSUE THREAD

**Issue by kompot81** [arkypita/LaserGRBL#617]
I added a M8/M9 custom button to manually start the cooler before image burn and stop it when burning finished. Would you plan to add a cooler options (in "Target Image" window, or anyway) to automatically start/stop cooler using g-code commands?

**Comment by cristianodems** [comment]
Hi! Just edit your post-processor.

**Comment by arkypita** [comment]
yes, custom gcode header/footer is my priority but too busy now.
#64
