### ISSUE TITLE
Auto image centering

### ISSUE THREAD

**Issue by kompot81** [arkypita/LaserGRBL#618]
Please make an ability to set working area dimensions (in Settings menu), and checkbox (Target Image window) to automatically put the target image on the center of working area. 
I think X-Y axis maximum travel values also can be used as the working area dimensions)

Now i have to use next formulas to set offsets for various picture sizes: 
X0=((working area)-(image_width))/2
and so on for Y axis.
So offsets (for example) for 10x12mm image and 24x30mm area is x=7mm, y=9mm.

I hope it will be useful for many users.
Thanks!

**Comment by arkypita** [comment]
I think that your needs could be done via a custom button that use the image size (there are variables for that) and compute center and call G92 to zeroing to that place
