### ISSUE TITLE
Laser Cutting

### ISSUE THREAD

**Issue by jdressing** [arkypita/LaserGRBL#621]
Can LaserGRBL support outlining?   

In order to use a laser engraver to cut, I need it to cut the outline.   
For a cutter, I was using vector files and converting them to outline and telling the cutter to just cut out the outline.  I have tried other tools and they want to use a JPG and draw with the laser which takes forever - this is more for burning the image and won't work very well when trying to cut out a shape.  It also makes it take much longer... instead of cutting out an outline in seconds, it may take a half hour to draw the shape.

Can LaserGRBL do this?

Thanks!

**Comment by StuartB4** [comment]
It sure can.
https://www.youtube.com/watch?v=3aLjCtB2iMo
