### ISSUE TITLE
Can't Connect Anymore 

### ISSUE THREAD

**Issue by poppen03** [arkypita/LaserGRBL#622]
Newly arrived engraver. LaserGRBL connected and worked fine. Now it can't connect. It says "connecting" then "disconnected" 10 seconds later and a soft click can be heard. Screenshot attached.  I can't figure out what has changed. The laser itself seems to work though there is no control over intensity, just an on/off switch on the board. Any ideas?
![Capture](https://user-images.githubusercontent.com/4306782/56463107-cc89ec00-6382-11e9-8806-32df0a6c4115.JPG)

**Comment by StuartB4** [comment]
Are you sure the com port you are trying to connect to is the correct one.
Try changing it for a different one with the drop down box underneath the File menu.
Or check in Device Manager in Windows to see which one your laser machine/Arduino should be on.
Have you tried a different usb port or a different usb lead.
Did you have to install a driver when you first set up the machine, is so try re-installing it.

**Comment by poppen03** [comment]
Thanks for the suggestions. I've tried all of them and tried two different computers. Still no success.

**Comment by arkypita** [comment]
As can be seen in picture you post, your hardware use benbox firmware.

As clearly written in http://lasergrbl.com/faq LaserGRBL is only compatible with GRBL firmware. Please read

**Comment by StuartB4** [comment]
> Newly arrived engraver. LaserGRBL connected and worked fine. 

Thats strange, you say it worked and now it does not. But it should not work, are you sure it was LaserGRBL that worked.

**Comment by poppen03** [comment]
It connects to Benbox but still doesn't work right. I'm thinking that maybe I altered the firmware when playing around with Benbox. I'm going to try and re-flash the board with GRBL because I prefer to use LaserGRBL. I'll let you know how it goes.

**Comment by StuartB4** [comment]
Ok poppen03. Good luck with it.

**Comment by poppen03** [comment]
OK, that worked. Only problem now is I'm not getting burning power (only 4.5v) to the laser.

**Comment by poppen03** [comment]
Thanks for the suggestions.  I've tried all of them except replacing the USB lead (don't have one yet).  I have also tried running it on 2 different computers without success. 

On April 20, 2019 4:40:52 PM MST, Stuart <notifications@github.com> wrote:
>Are you sure the com port you are trying to connect to is the correct
>one.
>Try changing it for a different one with the drop down box underneath
>the File menu.
>Or check in Device Manager in Windows to see which one your laser
>machine/Arduino should be on.
>Have you tried a different usb port or a different usb lead.
>Did you have to install a driver when you first set up the machine, is
>so try re-installing it.
>
>
>
>
>
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/arkypita/LaserGRBL/issues/622#issuecomment-485198126

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
