### ISSUE TITLE
why instead of halftones the relief turns out

### ISSUE THREAD

**Issue by sbrv** [arkypita/LaserGRBL#623]
Why with the same settings of the hardware and software part of the images burned in halftones(grayscales), and the other part turns in one colour, but relief.

**Comment by StuartB4** [comment]
Can you show us an example or the image you were burning and the settings you used.

**Comment by sbrv** [comment]
24.04.2019, 17:37, "Stuart" <notifications@github.com>:Can you show us an example or the image you were burning and the settings you used.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
Image.zip (38241341)

**Comment by StuartB4** [comment]
Hi sbrv. 
There's no link to get the image.

**Comment by sbrv** [comment]
Hi.Here is the link :  https://yadi.sk/d/6zK7lXeuPhIH5A Thanks for helping !!  24.04.2019, 21:22, "Stuart" <notifications@github.com>:Hi sbrv.There's no link to get the image.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by StuartB4** [comment]
Thanks sbrv.
Do you have the settings you used in the "Import Raster Image" and "Target image" settings. ?

**Comment by sbrv** [comment]
26.04.2019, 13:19, "Stuart" <notifications@github.com>:Thanks sbrv.Do you have the settings you used in the "Import Raster Image" and "Target image" settings. ?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by sbrv** [comment]
![image](https://user-images.githubusercontent.com/1056218/57333836-a99f5c00-7126-11e9-9802-6f2cbdca9c69.png)
