### ISSUE TITLE
No Laser Control

### ISSUE THREAD

**Issue by poppen03** [arkypita/LaserGRBL#625]
I just got a Chinese 3w laser engraver kit.  I flashed the board with GRBL 1.1 and have control over the motors. The laser turns on at a low power and stays on. I have tried checking and unchecking the PWM box, changed the laser enable  mode in the configuration from 0 to 1, the spindle max to 255 and spindle min to 0 and tried sending individual M3, M4 and M5 commands. Nothing has any effect.

What else can I do to get the laser to respond to commands?

**Comment by StuartB4** [comment]
Is it a new machine or a used one.
Does the board look like this one with the Blue Arduino Nano plugged in.
![Control-Board](https://user-images.githubusercontent.com/16980026/56684548-e5b6d380-66c7-11e9-8971-3fe82c395be7.jpg)

Some older boards have a jumper underneath the Arduino Nano board that needs moving across to make it compatible with GRBL 1.1

Switch the machine off before removing the Nano to find out.
The newer versions no longer have the jumper.

**Comment by poppen03** [comment]
Yes, it looks exactly like your photo. I bought it new. What do you mean by "needs moving across"?

On April 24, 2019 11:36:55 AM MST, Stuart <notifications@github.com> wrote:
>Is it a new machine or a used one.
>Does the board look like this one with the Blue Arduino Nano plugged
>in.
>![Control-Board](https://user-images.githubusercontent.com/16980026/56684548-e5b6d380-66c7-11e9-8971-3fe82c395be7.jpg)
>
>Some older boards have a jumper underneath the Arduino Nano board that
>needs moving across to make it compatible with GRBL 1.1
>
>Switch the machine off before removing the Nano to find out.
>The newer versions no longer have the jumper.
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/arkypita/LaserGRBL/issues/625#issuecomment-486374869

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by StuartB4** [comment]
I'm just going by what I found on the net, which was this.

> 1. unplug your machine.
2. Remove the nano (piece you plug the usb into) from the motor board
3. Underneath, there should be a jumper and 3 pins. Move the jumper to short out the center and other pin (that was not under the jumper already)
4. confirm your firmware (0.9 or 1.1)

It just pulls off and you move it to the middle pin and the other unused pin.
But looking at the image of the board I posted it looks like that jumper is a voltage
selector, so I don't know how changing the jumper would help.

**Comment by poppen03** [comment]
Thanks, but there is no jumper at all. Are these (see photo) the contacts you are talking about? If so, which two need to be connected?

![Under-Nano](https://user-images.githubusercontent.com/4306782/56703578-653fa500-66be-11e9-885b-198eee7ae297.jpg)

**Comment by poppen03** [comment]
![Nano1](https://user-images.githubusercontent.com/4306782/56712634-03923180-66e4-11e9-9a23-3ad078e11542.jpg)
![Nano2](https://user-images.githubusercontent.com/4306782/56712635-03923180-66e4-11e9-9822-fa9c215d1d6a.jpg)

**Comment by StuartB4** [comment]
Does yours have a version number printed on it, it actually looks older than the one in the image I uploaded, it has through hole resistors and a stardard led compared to the surface mount resistors and led.
Without knowing what the holes are for I would'nt connect anything there.

**Comment by poppen03** [comment]
Agreed! This photo shows the only thing that might identify the board. I'll see if I can get it translated. I'm starting to think I should abandon this board and use an Uno with a CNC sheild.
![Board-CU](https://user-images.githubusercontent.com/4306782/56743760-13356880-672c-11e9-8b82-6c33f95e56b2.jpg)

**Comment by StuartB4** [comment]
You could have a look here first:
http://benboxlaser.us/index.php
There are people who swapped from the Benbox firmware system to GRBL on their machine.

**Comment by poppen03** [comment]
Thanks, I really appreciate your prompt replies and help. Unfortunately i didn't find any help. Might switching to Grbl 0.9 help?

**Comment by lloyd1941** [comment]
Gyday Poppy
that board is out of date. send for a newie?
