### ISSUE TITLE
Minimum print size

### ISSUE THREAD

**Issue by lodale** [arkypita/LaserGRBL#626]
Hi
I have tried to vectorize a raster file (png) to a printable vectorized file. In the target image

**Comment by lodale** [comment]
Hi again ( I accidently closed the comment). I am running Lasergrbl ver. 3.0.10 (just updated). I try to vectorize a raster fil, in the target image I could not put in the right L and W. The values I want are L= 5.2 mm and W=1.3 mm. When i put these values in the target image window they change to red. and do not show up in the "print window".  How could I adjust LaserGRBL to be able to print images at small sizes, the bigger ones work
![Target](https://user-images.githubusercontent.com/49991843/56752543-cc299080-6788-11e9-8ffb-97ada99b0369.png)

**Comment by lodale** [comment]
Oh very embarresd i put in values like cm and not mm,

**Comment by StuartB4** [comment]
Easy mistake to make. At least you realised.
