### ISSUE TITLE
Transfer config file

### ISSUE THREAD

**Issue by oliveritech** [arkypita/LaserGRBL#632]
Hello, is there a way to mouve the LaserGRBL configuration (setting, custom Button etc etc) from one PC to a new installation ?

Thank you

**Comment by Alibaba0815** [comment]
In order to transfer the personal settings, you only need to backup the folder "C: \ USER \ Admin \ AppData \ Roaming \ LaserGRBL" (WIN10) and then manually re-install it.

**Comment by oliveritech** [comment]
Thank you
