### ISSUE TITLE
Easy solution to invert PMW power settings

### ISSUE THREAD

**Issue by codiak6335** [arkypita/LaserGRBL#633]
I just got a Sansmart 5w Blue Laser which I've mounted to a ShapeOko 2 driven by an Arduino Uno/GShield and GRBL 1.1f.  

I've rebuild GRBL to separate the direction pin to D13 and currently wire my laser to this pin as I'm just doing cuts, no engraving, so on/off is just fine.

The issue I'm having is that the PMW settings of the laser driver are inverted:
     0 = full power
  255 = 0

While modifying GRBL or adding an inversion circuit would work, so too would having the gcode created with inverted values.

Has anyone solved this, if so how?

**Comment by e6910** [comment]
I went thru that same problem. Save yourself a lot of frustration and make a signal inverter circuit. You can make it with pennies, only requires a transistor and some resistors and connectors. Simple and effective.
