### ISSUE TITLE
Low power on laser 5500mw

### ISSUE THREAD

**Issue by spriggam** [arkypita/LaserGRBL#634]
Hi , i am a beginner
I ve a laser engraver buy on ebay , it 's a 5500mw laser with arduino Nano 
The grbl is 0,9 
my problem is that when I run a burner the laser is very weak even if I vary the values ​​S to 255 . i can´t cut paper
Could you help me  ?

**Comment by StuartB4** [comment]
Is it a new machine or used?
Have you tried it with different software?

**Comment by spriggam** [comment]
it s a new laser , i try Benbox before but it doesn t work at all

**Comment by StuartB4** [comment]
You may have a faulty laser or laser driver.

**Comment by spriggam** [comment]
i don t think it s a problem of laser i think it s a problem of command 
but i don t know how to do
do you know another software i could try ?

**Comment by StuartB4** [comment]
You could try T2 Laser. They have a free trial version so you don't have to pay to try it.
http://t2graphics.weebly.com
Also look on youtube for how to use it.
https://www.youtube.com/watch?v=lyxqht64JNQ

**Comment by osmosis14** [comment]
Its not the laser, change the power from 255 to something more like 900 or 1000

**Comment by spriggam** [comment]
i try to change the power to 900 , but it doesn t work
and i try T2 software and it s work 
thanks a lot

**Comment by Ersukon** [comment]
Take a look

![Leistung](https://user-images.githubusercontent.com/50264364/57178136-93ff0d80-6e6c-11e9-8e3e-3cf976052182.PNG)

**Comment by spriggam** [comment]
Thank you , you are right , it s work perfectly
