### ISSUE TITLE
jogging not working

### ISSUE THREAD

**Issue by majstoralc9** [arkypita/LaserGRBL#637]
Hello
I upgrated laser grbl program but now jogging not working.
I try everything.
Can anybody help me?
Best regards
![laser grbl](https://user-images.githubusercontent.com/50273014/57198003-35ba5380-6f6e-11e9-8028-fb3618075644.png)

**Comment by arkypita** [comment]
Where did you download?
Did you compile from source? If yes, please update to latest trunk version

**Comment by majstoralc9** [comment]
I download program from github.com. Before upgrade jogging works well, but after upgrade it's like in atached picture.

**Comment by arkypita** [comment]
For me, seem to work

![image](https://user-images.githubusercontent.com/8782035/57284057-bd0fe000-70b0-11e9-8023-ee2137e000d1.png)

**Comment by arkypita** [comment]
However I am going to release a new version to restore prev version of jog control

**Comment by majstoralc9** [comment]
Thanks for reply. In my case jogging working only with mouse conntrol on screen and not working with keyboard conntrol.
When i press for example key 6 - for x movement give me program code $9=G91x0y0
In your case is code diferent.
Sorry for my bad english.
Best regards

**Comment by arkypita** [comment]
Oh, ok. Yes, this was already reported.
Just wait for new version, I'm fixing it.

**Comment by arkypita** [comment]
Whould you like to try? https://github.com/arkypita/LaserGRBL/releases/tag/v3.0.11

**Comment by majstoralc9** [comment]
Its working. Thanks
