### ISSUE TITLE
Overscan option

### ISSUE THREAD

**Issue by magwe** [arkypita/LaserGRBL#638]
As some machines suffer from slow acceleration, the start and end of each line may be overemphasized.

Add an option to scan well past the edges of the image so that acceleration/decelleration during direction change occurs while the laser is turned off and traveling past the image.

#565 #542

**Comment by arkypita** [comment]
already in dev roadmap #64

**Comment by chrisferagotti** [comment]
@arkypita There's nothing listed as overscan in that list; is it worded as something else?
