### ISSUE TITLE
Image import - EXIF gives a wrong size after rotating the image 90°

### ISSUE THREAD

**Issue by tomturican** [arkypita/LaserGRBL#640]
When i import an image and rotate it 90°, the EXIF reading give me a wrong size. (tested with 2400 dpi jpg and png file). I use the 3.0.10 Version.
While importing my PNG Image, the dpi value from EXIF reading is one point to low. In my case 2399 dpi instead of 2400 dpi.
I will use LaserGRBL to exposing my PCB (with a 50mW UV Laser), exported from KiCad. First tests looks very good, but i need exact dimensions. (ok, the one point dpi with png ist not realy a problem :-) )

**Comment by arkypita** [comment]
For what I can see, it work

https://youtu.be/oGe95z92wJg

**Comment by arkypita** [comment]
If you rotate the image using LaserGRBL rotation button it work. Tested now with latest version (no code changes in this part).

If you use windows or an external program to rotate the image, he is probably the cause, maybe this deletes the exif data from file? Please check file property.

**Comment by arkypita** [comment]
Also tested with PNG. No difference between rotated/unrotated.
Only rounding error but it is an issue of png file format.

Look at this: https://forums.adobe.com/thread/2139680

**Comment by tomturican** [comment]
Hello & thanks for the answer,

pls look on my screeenshots. The rotating was done within lasergrbl. The autosize Funktion should only swap the  values (x/y). This file is also attached.

Greetings
tom

Gesendet von Mail für Windows 10

Von: arkypita
Gesendet: Dienstag, 7. Mai 2019 10:33
An: arkypita/LaserGRBL
Cc: tomturican; Author
Betreff: Re: [arkypita/LaserGRBL] Image import - EXIF gives a wrong size after rotating the image 90° (#640)

Also tested with PNG. No difference between rotated/unrotated.
Only rounding error but it is an issue of png file format.
Look at this: https://forums.adobe.com/thread/2139680

**Comment by arkypita** [comment]
Can't see any screen shot

**Comment by tomturican** [comment]
I have attached them on this mail….

Gesendet von Mail für Windows 10

Von: arkypita
Gesendet: Dienstag, 7. Mai 2019 18:17
An: arkypita/LaserGRBL
Cc: tomturican; Author
Betreff: Re: [arkypita/LaserGRBL] Image import - EXIF gives a wrong size after rotating the image 90° (#640)

Can't see any screen shot

**Comment by tomturican** [comment]
![s1](https://user-images.githubusercontent.com/50337031/57316062-3fba8e80-70f5-11e9-88b0-a542c81ac057.png)
![s2](https://user-images.githubusercontent.com/50337031/57316063-3fba8e80-70f5-11e9-8392-d0a57abf148f.png)
![layout](https://user-images.githubusercontent.com/50337031/57316064-3fba8e80-70f5-11e9-8fe9-08b816bee92f.jpg)

**Comment by tomturican** [comment]
the dpi value itself is ok. but the B & H values (width and hight) dont swap after rotating.

**Comment by arkypita** [comment]
Understand. Try check/uncheck autosize please

**Comment by arkypita** [comment]
I will test as soon as possible

**Comment by tomturican** [comment]
check/uncheck tested, but no change....

Thanks ;-)

**Comment by arkypita** [comment]
fixed

**Comment by tomturican** [comment]
Great, it works perfect!

Many thanks!

**Comment by arkypita** [comment]
You are welcome, thanks for bug report.
