### ISSUE TITLE
After update v3.0.10 custom button flash not correct.

### ISSUE THREAD

**Issue by hardybeets** [arkypita/LaserGRBL#641]
Custom  button flash on[m3 s3]  off [m5]   pushbutton.
After update v3.0.10 no flash when pressed. 
M3 behaves like M4[dynammic laser]
only flash when head is moving.
How do I correct this? plz help!

**Comment by arkypita** [comment]
Does not depends by LaserGRBL version.

**Comment by hardybeets** [comment]
Ok, but then how can I fix it? I already deleted and created new button and still the same response.
I don`t see anywhere, where i can disable dynamic iaser.

**Comment by StuartB4** [comment]
I use this and it works with all versions since the Two State Button was added.
![Untitled5](https://user-images.githubusercontent.com/16980026/57409406-1e829c80-71e0-11e9-83b2-c348854030f5.jpg)
