### ISSUE TITLE
continuous Jogging move only to one direction

### ISSUE THREAD

**Issue by oliveritech** [arkypita/LaserGRBL#643]
Hello, thank you for this new 3.0.13 release. If I enable continuous Jogging my machine is moving only towards the + space; if continuous Jogging is off everything works as is should. Is it only me with this issue?

**Comment by arkypita** [comment]
Hi @oliveritech continuous jogging was developed as a new feature, so it could have some youth problem :-)

Please exactly describe the problem, so I can work on it.

**Comment by StuartB4** [comment]
Working fine for me, all directions and Home, also stops as it should when it reaches the maximum number set in GRBL $130, $131, $132 settings.

**Comment by oliveritech** [comment]
Hi, basically if continuous Jogging is enable my machine move only forward and can't move back with the arrow keys.

**Comment by arkypita** [comment]
I use limit switches + homing, so when I power on I do homing and homing procedure will seek for switches and set zero point in the lower-left limit of my machine. Is not possible for me to go negative.

I think that @oliveritech does not use homing, so it have zero point in the position where the laser is when he turn on, so he need to use negative space.

**Comment by oliveritech** [comment]
I have my machine set exactly the same with the Homing in to the lower left and limit switches on X and Y Axes, no Z axes enabled. I flashed the GRBL 1.1f in to the Arduino and is working now !
Is it normal that with continuous Jogging enable the Home button in the middle of the arrows, now need to be kept clicked to go home and not just one click like before ?

**Comment by arkypita** [comment]
> I have my machine set exactly the same with the Homing in to the lower left and limit switches on X and Y Axes, no Z axes enabled. I flashed the GRBL 1.1f in to the Arduino and is working now !

Which version you had before?

> Is it normal that with continuous Jogging enable the Home button in the middle of the arrows, now need to be kept clicked to go home and not just one click like before ?

Yes, for homogeneity.

**Comment by oliveritech** [comment]
0.9
Ok thank you for your great work.

**Comment by mschaeck** [comment]
I use GRBL 1.1f and continuous Jogging is not woking (only in one direction)
G53Y390.0F1960 for one direktion works fine, in the other direction the command the software dens G53Y0.0F1960 is not working (is moving in the same direction).
Why is not G53Y-390.0F1960 sendet?

**Comment by oliveritech** [comment]
Hello mschaeck, LaserGrbl mouve only in the positive direction. Basically the way I understud and resolved is; after you sucessfully home your machine with limit swithces, this shold be X0Y0 and from there you could mouve your machine only in the + space and not in the - unlike pro machine that from homing mouve to the - space. This should help https://github.com/grbl/grbl/wiki/Frequently-Asked-Questions#why-is-grbl-in-all-negative-coordinates-after-homing-or-it-so-annoying-and-not-what-im-used-to
ciao

**Comment by mschaeck** [comment]
I understand, I am using the home function. I home the machine with limit switches. Why is in the right upper conrer still not X0Y0 after homing?

**Comment by oliveritech** [comment]
Because that is where in the GRBL Firmware the $23 set the homing cycle direction , but that is not the origin of you X0Y0

**Comment by oliveritech** [comment]
https://openbuilds.com/threads/confused-about-homing-machine-position-zeroing-etc.6848/

**Comment by mschaeck** [comment]
![laser](https://user-images.githubusercontent.com/46404844/58778769-1c8bdd80-85d4-11e9-972f-85388857fa41.JPG)
I guess the first problem is why after homing the machine with limit switches (wich works fine) the first line with the absolut position is not set to zero, see the image.

**Comment by mschaeck** [comment]
I have set $23 = 1
