### ISSUE TITLE
Perfect circles with EleksMaker A3 Pro?

### ISSUE THREAD

**Issue by maillemaker** [arkypita/LaserGRBL#645]
Is anyone with an Eleksmaker A3 pro able to burn a perfect vector circle?

Steve

**Comment by RonyZlin** [comment]
Yes, I do. I think the most important thing is the correct tension of the belts.

**Comment by maillemaker** [comment]
So how tight should they be?  I have tried so tight it stalls out the motors and everything in between.

Can I get a copy of your settings for your a3 pro to re-load into mine?

Steve

**Comment by maillemaker** [comment]
And, what are your laserGRBL settings?

**Comment by RonyZlin** [comment]
Settings:

[GRBL_Configuration_Rony_2.txt](https://github.com/arkypita/LaserGRBL/files/3188994/GRBL_Configuration_Rony_2.txt)

![Settings1](https://user-images.githubusercontent.com/705791/57886105-c32e5b00-782c-11e9-884d-2bb6aa44eb58.PNG)
![Settings2](https://user-images.githubusercontent.com/705791/57886110-c6294b80-782c-11e9-83a5-92ba4a6ae027.PNG)
![Settings3](https://user-images.githubusercontent.com/705791/57886115-c9243c00-782c-11e9-9c6e-d04144a67f89.PNG)

**Comment by RonyZlin** [comment]
Some videos:
[Belt tension](https://youtu.be/Dq7W-a9pWHg)
[video1](https://youtu.be/og6RIotnSc8)
[video2](https://youtu.be/dJ486orKkOc)

**Comment by RonyZlin** [comment]
I found it's not perfect, but the shift is so small that I don't mind (approx. 
0.1 mm). I didn't notice it at all in usual engraving.

![Circles](https://user-images.githubusercontent.com/705791/57887269-5ff1f800-782f-11e9-8ce5-1a987f4193ba.jpg)

**Comment by brakthehun** [comment]
How do you generate a circle?? Is it a picture?? Is it a G2 / G3 command??

**Comment by RonyZlin** [comment]
It was a black bitmap filled circle. In LaserGRBL: Conversion tool: Vectorize, Filling: none, Laser ON: M4

**Comment by StuartB4** [comment]
RonyZlin.

You can view and save the code of any image you have prepared by going to the File menu and select Save Program.

**Comment by brakthehun** [comment]
Try using this instead in the command line:
G92X0Y0
G0X10Y60
F500
M4S255
G2X10Y60 I50J0
M5

This will create a 100mm circle using the arc command (G2)

**Comment by maillemaker** [comment]
I have discovered my problem.  The problem was 2 broken leads on the bottom side of the left gantry motor.  Once I repaired the broken leads, the machine now works fine.

broken leads:
![alt text](https://i.imgur.com/GzbH83P.jpg)

Test after fixing:
![alt text](https://i.imgur.com/Atpcp0q.jpg)
