### ISSUE TITLE
Vectorized engraving on return travel

### ISSUE THREAD

**Issue by RmnJn** [arkypita/LaserGRBL#646]
Hello, I come back to you for a technical question about the use of the software.

I would like to know if it is possible to burn in vectorized mode with filling in goings and comings without return with laser off.
Indeed when I burn in vectorized mode, the engraving is done in the first way but the laser switch down for the return travel at the starting position of the upper line. 
Whereas when engraving in line-by-line mode, the laser burn in going and back way but does not outline.
I would like to know if there is a mix between the two methods.

Thank you in advance and thank you again for the great software you offer us, I use it almost every day.

RmnJn

**Comment by galactyus01** [comment]
Prova a vedere la funzione su grbl laser,,, vai su grbl/impostazioni/raster import
