### ISSUE TITLE
Laser GRBL on mac

### ISSUE THREAD

**Issue by nikolayku** [arkypita/LaserGRBL#649]
Hi to all. 
Is anybody try run LaserGRBL on mac. How to do this. 
Thanks you for all your help.

**Comment by StuartB4** [comment]
https://github.com/arkypita/LaserGRBL/issues/218

**Comment by metalman1004** [comment]
I've been using LaserGRBL on my mac. I run windows in Bootcamp and then run LaserGRBL from windows. It works pretty well. I just miss out on certain functions that work with Mac that don't work in windows.

**Comment by spiritburner** [comment]
@metalman1004 Ok, so you are running this from within bootcamp, did you ever try to run in an emulator instead? 
No way do I want windows on my root....just checking to see if there is another way round this apart from buying a laptop....Thanks
