### ISSUE TITLE
Problem with image size: jpg, gcode & inkscape

### ISSUE THREAD

**Issue by AdamMulica** [arkypita/LaserGRBL#651]
Hello, i have problem with my laser co2. I don't understand why program LaserGRBL change image size when i use gcode or svg. What i must change, what parameters in program LaserGRBL or in Arduino Atmega328p with grbl_v1.1f or Inkscape?

Thanks very much for all your time and help.

![inkscape](https://user-images.githubusercontent.com/28787684/57854329-4bd6d800-77e8-11e9-8a98-9a1e7102d1d8.jpg)

![lasergrbl-1](https://user-images.githubusercontent.com/28787684/57854330-4bd6d800-77e8-11e9-9a0a-0d8d8ab0be2a.jpg)

![lasergrbl-2](https://user-images.githubusercontent.com/28787684/57854331-4bd6d800-77e8-11e9-9943-86266bdbc46d.jpg)

**Comment by brakthehun** [comment]
You can choose your image size in the second window of image process. They're always in mm.

**Comment by AdamMulica** [comment]
I finded the solution :D
I musted changes parametrs 
$100 and $101 - standard 250,000 - now 10mm is 1cm
$110 and $111 - for faster travel of the x and y axes - standard 500,000
$120 and #121 - standard 10,000

huh :D

![lasergrbl-settings](https://user-images.githubusercontent.com/28787684/57918009-37e9af80-7896-11e9-9837-9acf5bf966ff.jpg)
