### ISSUE TITLE
How can I connect laser module to cnc sheild v3.0

### ISSUE THREAD

**Issue by Timmerhus08** [arkypita/LaserGRBL#653]
Hello every one,

 I am new and I need help to connect   **Laser-Modul 500mW 405nm blau-violett 5V 0.5W** 
 ( 2 wires Read and Black )to cnc sheild v3.0 with

 arduino uno. I have connected the Read wire from the laser to Z+ in cnc shield but nothing happend and then I used this circute in the picture and nothing happend also , if any one can take me to the right direction?.

![s-l1600](https://user-images.githubusercontent.com/50706494/57926675-2ca17e80-78ac-11e9-9612-8ca229d488a9.jpg)

Best Regards

**Comment by brakthehun** [comment]
Red wire needs to be connected to 5v pin. 
560 ohm line needs to be connected to Z+

**Comment by Timmerhus08** [comment]
Tanks for your answer,

I did it but nothing happend and when I connect the laser direct to the 5V Power supplay it is working.

**Comment by brakthehun** [comment]
You need 3 connections,, right?? Black to GND,, Red(Rot) to 5V,, and the 560 ohm line to Z+??

**Comment by brakthehun** [comment]
Can you take a pic of your setup??

**Comment by Timmerhus08** [comment]
Tank you so much, I made like what you said and worked but when I try to engrave a pic the lser seen very weak and when I connect the laser to external powersupplay 5v it is strong when I moved manuel and brun the cardboard.

**Comment by Timmerhus08** [comment]
I am tryied to Upload a pictures but i couldn't .

Realy Thanks.

**Comment by Timmerhus08** [comment]
I am tryied to Upload a pictures but i couldn't .

Realy Thanks.

**Comment by Timmerhus08** [comment]
![20190518_115006](https://user-images.githubusercontent.com/50706494/57968392-4903f080-796a-11e9-8bb1-617ce15672ee.jpg)
![Uploading 20190518_101609.jpg…]()
![Uploading 20190518_101452.jpg…]()

**Comment by Timmerhus08** [comment]
![20190518_101609](https://user-images.githubusercontent.com/50706494/57968868-9edb9700-7970-11e9-9092-8e61e91c5d86.jpg)
![20190518_101452](https://user-images.githubusercontent.com/50706494/57968869-a69b3b80-7970-11e9-93e6-c8ef3e54acb1.jpg)

**Comment by brakthehun** [comment]
It looks like your transistor is miswired:
My transistors - go like this from the front view (heat sink plate on the back):
signal (z+ / resistors)
drain (laser (-))
ground (ground)

**Comment by Timmerhus08** [comment]
thank you so much, you have right (miswired) I did same your opinion and worked perfectly but it is not burn.  When I connected the laser direct to the power supplay its burning but connected throw the circuit its weak.
Best Regards

**Comment by brakthehun** [comment]
I think this is solved.

**Comment by Timmerhus08** [comment]
Yes thanks but it is weak not burn.

**Comment by brakthehun** [comment]
What laser module is it?? It looks like a 100mw red,, which might not have enough power to burn.

**Comment by brakthehun** [comment]
I'm looking at the pics. It looks like it needs to be focused better.

**Comment by StuartB4** [comment]
He said it's a " Laser-Modul 500mW 405nm blau-violett 5V 0.5W"

**Comment by Timmerhus08** [comment]
please can you give me a link to buy it?.

Best regards

**Comment by Timmerhus08** [comment]
Thanks to you brakthehun my laser (Laser-Modul 500mW 405nm blau-violett 5V 0.5W").I tryied to focuse it but same result.
Best Regards

**Comment by brakthehun** [comment]
https://www.ebay.com/itm/405nm-500mw-12V-Blue-Laser-Module-for-DIY-Laser-Engraving-Machine-with-TTL/192396147963?hash=item2ccbb43cfb:g:~VQAAOSw0JFbZ~wF

I never know the quality or lifetime of these.

**Comment by Timmerhus08** [comment]
Thank you so much.
