### ISSUE TITLE
Recommended speed for Vectorized and Filled art on pine wood?

### ISSUE THREAD

**Issue by maillemaker** [arkypita/LaserGRBL#654]
Hi all,
I am doing some experimenting with different burn speeds now.  I first tried 500 border and 1000 fill with 8 lines per mm.  This worked pretty good but resulted in some "bleed" of scorching into the surrounding wood.
I now bumped up to 1000 border and 1500 fill and 6 lines per mm and am having another go.  This looks like it might be a little light.

Does anyone have any suggestions for laser engraving pine wood with vector and fill artwork?
Thanks,
Steve

**Comment by StuartB4** [comment]
Have a look on at adding Air Assist to your machine.
This is with and without it.

![with-and-without-air-assist](https://user-images.githubusercontent.com/16980026/59541795-d8b1a600-8efa-11e9-983c-eac20e3fbc1f.jpg)

**Comment by maillemaker** [comment]
That is amazing!  I had already taken the step of pointing a small fan at the work area.  This helped, but also pushed the remaining "shadow" all in one direction! :)

I'll go google air assist now but do you have any links?

Steve

**Comment by arkypita** [comment]
Also covering with masking tape helps giving clear result
