### ISSUE TITLE
New Board Wiring Help Needed

### ISSUE THREAD

**Issue by poppen03** [arkypita/LaserGRBL#659]
I bought a 2 axis Chinese laser engraver that arrived with a bad board. I purchased a new board and  was sent one for a 3 axis machine and no wiring diagram. It already has grbl 0.9.

Can anyone share the connections to use with this board? The x and y axis connections are clear, but which one should I use for the laser (there appear to be 3 2-pin options? Also, There are 2 places to plug in the 12v power supply. Which should I use?  I have a 3w laser that I would like to control with Lasergrbl. 

![Board](https://user-images.githubusercontent.com/4306782/58035890-9e610e80-7ade-11e9-9173-684ec21a51dd.jpg)
![Board3](https://user-images.githubusercontent.com/4306782/58036273-9190ea80-7adf-11e9-83f2-a17a8adacf59.jpg)
![Board2](https://user-images.githubusercontent.com/4306782/58036274-9190ea80-7adf-11e9-806f-2a9d7b33a63e.jpg)

**Comment by StuartB4** [comment]
This is the closest thing I can find, it has a relay on the board instead of the FET (the black thing with F540NS written on it on your board) But I think thats more to do with using the machine as a router and not a laser engraver. Most of it looks similar to your board though.

![Controller Board Wiring Drawing](https://user-images.githubusercontent.com/16980026/58059925-e3c91e80-7b66-11e9-8a89-3976c0e807ba.jpg)

**Comment by poppen03** [comment]
Thanks! This is close and definitely helps. I'm still puzzled by the (2) 2-pin connections next to the Nano though. I appreciate your help!

**Comment by StuartB4** [comment]
Yeah, it's hard to see what the pins are connected to.  I do know that if you have a pair of long nose pliers you can usually grab the little plastic socket around the pins and carefully slide it up off of the pins, that way you might see where the pins go. Maybe they connect to tracks underneath the board though.

**Comment by StuartB4** [comment]
The first one that says 12 - 36 must be an input, theres now way to set the voltage between 12 and 36 if it was an output. It may also be connected to the barrel connector on the left as an alternate input.
The second one could be either input or output, need a multimeter to check. May be an output for a fan.

**Comment by StuartB4** [comment]
Hi  poppen03.
Just wondered if you are having any luck with it.

**Comment by poppen03** [comment]
I should know tomorrow (I have a day off to try it out). In what I consider a minor miracle the seller sent me  this photo with connection notes. I'll post again after I try hooking it up. 
![3 axis board](https://user-images.githubusercontent.com/4306782/58265739-22143880-7d35-11e9-83e2-839ca968ba7e.png)

**Comment by StuartB4** [comment]
Ok.
Strange how he marked 2 x 12 volt fan connectors, even though one is clearly marked 12 - 36 volts on the board.
Apart from that it looks pretty straight forward.

**Comment by poppen03** [comment]
No joy. No laser control with expected connections (see photo). The motors work fine but no power goes to the laser. 
The board is flashed with grbl 0.9. I moved the jumper over as shown in the above diagram you sent. I did try connecting the laser (2 pin) to the center connections (the 12-36 and the 12 v) and the laser does work, though there is no control over it. 
![20190524_102732](https://user-images.githubusercontent.com/4306782/58346549-1fd2dc80-7e10-11e9-917f-4fb6c884a923.jpg)

**Comment by StuartB4** [comment]
Looking at the image you posted, it looks like your laser is wired differently to the socket it's plugged to.
Usually the red wire is + positive, you have it connected to the - negative. Is that the correct way for that laser.

**Comment by poppen03** [comment]
Yes! Great catch! Thank you!!!  The laser now comes on and off when the engraving begins and ends. The only thing is that it doesn't seem to be at full power. It's not burning anything as it goes through the program. Any thoughts?

**Comment by poppen03** [comment]
Is it better to upgrade to grbl v1.1?

**Comment by StuartB4** [comment]
Is the laser focussed correctly, smallest possible dot.
What colour material are you trying to burn, white is always a problem, but that also depends on the lasers wattage and the engraving speed.

Upgrading to GRBL 1.1 is a good idea as it includes extra settings for laser mode.
I would carefully remove the Arduino Nano from the main board to upgrade it, then you should'nt have any problems with interference from it. All you need is the USB lead.

There is another reason why it's not burning, it could be damaged after connecting the laser the wrong way in one socket. Unless it has reverse polarity voltage protection. Usually when laser diodes break they stop LASING but still emit light, more like an LED light.

**Comment by poppen03** [comment]
Thanks for those ideas.  The laser is focused and capable of lasing, I'm using a piece of brown cardboard. 
I have found that I can send M3 command directly (through Lasergrbl) and nothing happens, however, if I send M3 S1000 (from Lasergrbl) the laser comes on and starts burning. Still, when I run a file the gcode only sends M3, so it doesn't turn on. Is there somewhere I can set a default to M3 = M3 S1000 or a setting I'm missing?

**Comment by StuartB4** [comment]
What speed are you trying to engrave at.
![Untitled](https://user-images.githubusercontent.com/16980026/58367658-dcdd3b80-7ed9-11e9-98fb-2bcc93b42042.jpg)

**Comment by poppen03** [comment]
Good question. Where can I find the dialog box in your image? Here's a photo of the current v0.9 config. I will upgrade to v1.1 but I thought I would get it working first.
![Config Snap](https://user-images.githubusercontent.com/4306782/58371786-62a4bb00-7ec9-11e9-82c7-be2a38552062.JPG)

**Comment by poppen03** [comment]
OK, please disregard what I said. I went ahead and upgraded to 1.1f and it seems to be working. Here is the current 1.1f config. Do you suggest any changes?
![Config1 1 Snap](https://user-images.githubusercontent.com/4306782/58372616-195a6880-7ed5-11e9-933e-18d6948c1b49.JPG)

**Comment by poppen03** [comment]
I agree that speed may be an issue, since I'm still seeing gaps in burning where faster moves occur. Where is that setting?

**Comment by poppen03** [comment]
Here's a photo of my first "successful" burn. Notice the uneven lines. It looks like longer, faster moves don't burn as well.
![Burn1](https://user-images.githubusercontent.com/4306782/58372866-3a24bd00-7ed9-11e9-8611-d0eaff23c89e.jpg)

**Comment by StuartB4** [comment]
> Good question. Where can I find the dialog box in your image?

![Untitled2](https://user-images.githubusercontent.com/16980026/58373780-8ac50600-7f2b-11e9-98f8-a187a6a1595f.jpg)

Your GRBL settings look fine. Just 2 things though.

1. $30 only needs to be 255.

2. Is the maximum travel of your machine 200 mm. If so then thats fine.
It's only a problem if you use Continuous Jog setting in LaserGRBL settings and the maximum travel
of your machine is less than the setting in GRBL settings $130, $131 and $132.

Continuous jog allows you to hold the mouse button down on any of the jog or Home buttons
and it will continue to jog while the button is down.
As long as your $130, $131 and $132 are set correctly then it will stop jogging when it reaches the limit you set. Or when you release the mouse button.

**Comment by poppen03** [comment]
You have been a tremendous help! Thank you, I really appreciate it! It's been a challenge, but now that I have basic functionality I can play around with various settings and find what works best for my projects.

**Comment by StuartB4** [comment]
Happy to help if I can.
Good luck with it.
There's always someone here to help if needed.

**Comment by brakthehun** [comment]
Have you tried using an M4 command instead of an M3 command??

**Comment by poppen03** [comment]
Only M3 works for me.

**Comment by Testimonial** [comment]
> No joy. No laser control with expected connections (see photo). The motors work fine but no power goes to the laser.
> The board is flashed with grbl 0.9. I moved the jumper over as shown in the above diagram you sent. I did try connecting the laser (2 pin) to the center connections (the 12-36 and the 12 v) and the laser does work, though there is no control over it.
> ![20190524_102732](https://user-images.githubusercontent.com/4306782/58346549-1fd2dc80-7e10-11e9-917f-4fb6c884a923.jpg)

Hi, I can see your board is almost same as my just with a small difference and I'd like to figure it out. Can you please help me to identify tiny part located besides 2pin DC 12V laser output please?
![image](https://user-images.githubusercontent.com/51442396/66052653-424cd300-e531-11e9-84be-b88341748d42.png)

I've got only 3 free holes with label STP1. I know if you read laser on right there is ground, in the middle there is signal up to +5 and left one is stabil 12V.
The name of this part could help me to extend my board.
Thanks a lot.

**Comment by StuartB4** [comment]
Looks like a mosfet / transistor.

**Comment by usamaijazz** [comment]
Hi, 
Hope you are doing well
I also Bought the same board form ALiExpress China about 4 years ago as you have mentioned in your first post.

![image](https://user-images.githubusercontent.com/55308608/136250547-68629c50-e86e-4865-a840-658843259fab.png)



and just got the time to operate it.
Can you help me out to start working with this board.
If its possible for your then Please send the link for for software to use.
Also any guide video you might know.

ThankYou,

Waiting for your reply.
here is my email id 
usamaijaz1162@gmail.com
