### ISSUE TITLE
Errore durante la lavorazione LaserGRBL

### ISSUE THREAD

**Issue by DamianoNisoli** [arkypita/LaserGRBL#663]
Ho un problemino: Durante la lavorazione di una foto rotonda D=240 la X si sfasa completamente e mi esce questo errore : 

ok
ALARM:3
Grbl 1.1f ['$' for help]
[MSG:'$H'|'$X' to unlock]
[MSG:Caution: Unlocked]
ok

Qualcuno sa cosa puo' essere ?

**Comment by arkypita** [comment]
possono essere tante cose. qualche informazione in più?
qualche immagine?

hai già provato a leggere le [faq](http://lasergrbl.com/it/faq/)?
