### ISSUE TITLE
Feature Request: Change M3 & M5 to String Variable which can be set by user

### ISSUE THREAD

**Issue by Dnaudio** [arkypita/LaserGRBL#665]
I'm currently using your software to create gcode for a Duet WiFi and I have to do quite a bit of file modification before I run the gcode every time. With the ability to append starting and ending gcode as well as being able to set my own code in place of the M3 & M5 code  I would be able to run the code as saved. Thanks for creating something better than using inkscape.

**Comment by arkypita** [comment]
Your request is already in the roadmap #64 

Contrary to what one might think, this change is not as simple as replacing a string. There are various points in the code that are affected by such a seemingly simple change:

- interpretation of the gcode and preview
- calculation of timing
- state building and recovery operations after abort
- automatic optimization of the generated code (M3 / M5 are modal and can be optimized, other commands are not) and more.
