### ISSUE TITLE
Image shifted in +Y axis from origin in software

### ISSUE THREAD

**Issue by maillemaker** [arkypita/LaserGRBL#666]
I have noticed what may be a bug in the LaserGRBL software.

Here is my image:

![RV Cutting Board 2](https://user-images.githubusercontent.com/26260929/58426780-22794000-8063-11e9-80f2-1769346981a2.jpg)

I used Paint to move the entire image to the upper-left corner in Paint, and then modified the image boundary to closely fit the image.  The result is above.

When I import this into LaserGRBL, the image is shifted in the +Y direction, like so:

![bug](https://user-images.githubusercontent.com/26260929/58426833-4b99d080-8063-11e9-9d9e-fb5e13e69ff8.png)

Sometimes if I click in the graphics area in LaserGRBL the image will suddenly re-center correctly.  Other times, it stays as you see above.

**Comment by arkypita** [comment]
Upload a screenshot of this window

![image](https://user-images.githubusercontent.com/8782035/58427424-dc8e9d00-809f-11e9-8dfb-28ee90b570ec.png)

**Comment by maillemaker** [comment]
I have been unable to reproduce this error.
I am pretty sure I did not put an offset in the Offset fields, but cannot be sure now.
So, I will close this issue.
Steve
