### ISSUE TITLE
Can't connect to the Laser - Status: Check door

### ISSUE THREAD

**Issue by Amicid13** [arkypita/LaserGRBL#667]
Hello,

i got today a CNC3018 with Laser-Module. I installed everything and the CNC Part works well with the software of GRBL (Candle). If i try to use my laser it doesnt't work as it should.
If i only connect the bigger power supply to the board i can connect to the device and laser engrave without a problem. If i connecting the smaller cable which is used for controlling the laser (I think so) then LaserGRBL tells me to check the door and says status "door". Don't know how to fix this and what i can do. So i can't controll the machine and the laser.

How can i fix this? Would be nice if somebody could help me.
![InkedIMG_20190527_222741_LI](https://user-images.githubusercontent.com/51097099/58438457-4c684c00-80cf-11e9-9bfa-d7ed2fdb9d82.jpg)
![InkedIMG_20190527_222643_LI](https://user-images.githubusercontent.com/51097099/58438458-4c684c00-80cf-11e9-9ea8-330cba897287.jpg)
![Programmfehler](https://user-images.githubusercontent.com/51097099/58438459-4c684c00-80cf-11e9-8270-af3c53216f70.JPG)

**Comment by arkypita** [comment]
LaserGRBL has nothing to do with this issue.

Check door should is an hardware feature that only be available if you or your CNC manufacturer has enabled it in control board software. The default is disabled.
It is used to wire a safety switch - lock on pin A1 that act when you open/remove the cover, in CNC that has a cover panel.

https://github.com/grbl/grbl/wiki/Connecting-Grbl

> In Grbl v0.8 and later, there are pin-outs of the cycle start, feed hold, and reset runtime commands, so you can have physical control buttons on your machine. Just like the limit pins, these pins are held high with an internal pull-up resistor, so all you have to do is connect a normally-open switch to each pin and to ground. Again make sure you practice good wiring methods to minimize external electric noise on the input pins.

If left unconnected it sense as if the panel is opened.
If you want to disable feature you should re-compile and flash GRBL to your Arduino (the blue one on your board) with this feature off, or at least connect A1 to the ground.

https://github.com/grbl/grbl/issues/1267
