### ISSUE TITLE
my laser runs out of power after 90% of the job

### ISSUE THREAD

**Issue by johnbluesboy** [arkypita/LaserGRBL#668]

**Comment by StuartB4** [comment]
Is it always 90% no matter what size image you burn?
Is the laser cooled.

**Comment by johnbluesboy** [comment]
Hi yes it seems to be

John Richardson

**Comment by brakthehun** [comment]
What laser are you using??
Are you using a diode?? A tube??

**Comment by johnbluesboy** [comment]
Hi I am using a 2500w diode it seems to lose power after about a minute of use

John Richardson

**Comment by brakthehun** [comment]
Sounds like a faulty diode.
Does the power return after you let it sit??

**Comment by johnbluesboy** [comment]
Yes it does after about 30 minutes 

John Richardson

**Comment by brakthehun** [comment]
There is anther revision to the software being tested that adds a cool down for diodes. It works very well so far.

**Comment by johnbluesboy** [comment]
Hi where can I get the new software?

John Richardson

**Comment by StuartB4** [comment]
Here it is.
https://github.com/arkypita/LaserGRBL/releases/tag/v3.0.15

**Comment by StuartB4** [comment]
https://github.com/arkypita/LaserGRBL/tree/v3.0.15

**Comment by arkypita** [comment]
> Hi where can I get the new software? John Richardson

I had removed it from releases because it works only with grbl v1.1 and produce bad results (burns) with older 0.9-0.8 grbl version. I am working on a version that act better with older version. Just wait for new version.

**Comment by johnbluesboy** [comment]
Ok thanks I am using 1.1

John Richardson
