### ISSUE TITLE
SD-card version

### ISSUE THREAD

**Issue by RunnyBore604** [arkypita/LaserGRBL#67]
Hi,

sorry for that spam. I hope it will be interested. I created GRBL version that can work without a PC. It requires LCD 1602, SD card module and only one Arduino Nano (not two, like this do others).

https://github.com/RunnyBore604/standaloneGRBL

**Comment by arkypita** [comment]
You did a great job. Did you have done some videos of your project at work?

**Comment by RunnyBore604** [comment]
One happy user made a few videos about how that controller works: https://cloud.mail.ru/public/3Bjd/jKH9tAcAj

And one video from another person on YouTube: https://www.youtube.com/watch?v=FmmlrxPS5jo

Discussion on Russian forum: http://www.cnc-club.ru/forum/viewtopic.php?f=41&t=16194

**Comment by arkypita** [comment]
thanks for sharing
