### ISSUE TITLE
query function to adjust the laser power

### ISSUE THREAD

**Issue by serchel111** [arkypita/LaserGRBL#671]
Hello!
Thanks for the software.
The degree of gray on the material depends on many reasons. And the repeatability of engraving on another material is not expected. Even if you change the focus settings of the laser. In this regard, I would like to have a utility to adjust the laser power. I see it like this:

sets the estimated power level of the laser "min" at a certain speed and the number of lines per mm. Sets the step of changing the power and the number of test areas (below and above the specified laser power).
The same is set for laser power "max."
There is a choice test "min" or, and "max".
Sent with all coefficients to laser engraving. Engraved test areas of at least 5 * 5mm. (preferably with engraved laser power parameters, but not necessarily).
Visually estimated optimal threshold power of the laser "min", "max" for this material.
The result will save a lot of time.
four . For complete happiness, a pipette is requested to determine the calculated laser power in the areas of interest in the bitmap image.
5. Limiting the 255 steps of changing the laser power due to the hardware support of the machine? Then is it possible to limit the maximum laser power? For example, I have a laser power at which the material begins to darken (Pmin) = 70. the power at which the material starts to char, (Pmax) = 110. My range on the material is Pmax-Pmin = 40 steps. But for me the details are important, which are in the range, for example, 70-80. That is only 10 steps.
When processing a raster, I make a range of 70-210 and get 40 steps of the range that is important to me. But the laser power from (Pmax) = 110 - 210 burns my material into coal. Therefore, I would like Pmax in the range from 110 to 210 to be 110.c).

**Comment by serchel111** [comment]
Hello!
Thanks for the software.
The degree of gray on the material depends on many reasons. And the repeatability of engraving on another material is not expected. Even if you change the focus settings of the laser. In this regard, I would like to have a utility to adjust the laser power. I see it like this:

sets the estimated power level of the laser "min" at a certain speed and the number of lines per mm. Sets the step of changing the power and the number of test areas (below and above the specified laser power).
The same is set for laser power "max."
There is a choice test "min" or, and "max".
Sent with all coefficients to laser engraving. Engraved test areas of at least 5 * 5mm. (preferably with engraved laser power parameters, but not necessarily).
Visually estimated optimal threshold power of the laser "min", "max" for this material.
The result will save a lot of time.
four . For complete happiness, a pipette is requested to determine the calculated laser power in the areas of interest in the bitmap image.
5. Limiting the 255 steps of changing the laser power due to the hardware support of the machine? Then is it possible to limit the maximum laser power? For example, I have a laser power at which the material begins to darken (Pmin) = 70. the power at which the material starts to char, (Pmax) = 110. My range on the material is Pmax-Pmin = 40 steps. But for me the details are important, which are in the range, for example, 70-80. That is only 10 steps.
When processing a raster, I make a range of 70-210 and get 40 steps of the range that is important to me. But the laser power from (Pmax) = 110 - 210 burns my material into coal. Therefore, I would like Pmax in the range from 110 to 210 to be 110.c).

**Comment by arkypita** [comment]
A "non linear" color to power conversion is already in development roadmap #64
