### ISSUE TITLE
Red laser pointer option control using FAN FLOOD PIN 

### ISSUE THREAD

**Issue by AxelGUILLAUMET** [arkypita/LaserGRBL#672]
Dear friend.

Unfortunately I don't know a lot about C#, I will make a try but... I'm not sure about the results... Where I defend myself is with Delphi. I know, nobody is perfect...

I saw you added the Z option to control the height of the table of a laser engraver. This option is VERY USEFUL!

One thing you can ADD is using the FAN output (A3 on Arduino UNO), here we drive a mosfet and the red laser pointer, used to help getting a correct origin.

Into GRBLPanel, you can activate this with the button FLOOD. The command is M8 to enable and M9 to disable.

What you can do is putting an option to activate red laser pointer, (Like you have done with the Z option) and a new button appear into the main interface near the jogging to activate this laser.

Hope you will think this idea is good, I will try to it by myself and share the code (A first for me...) I just installed SharpDevelop 5.1.... And here is a good way for me to learn a little about C#.

Regards!

**Comment by arkypita** [comment]
maybe a [custom button](https://lasergrbl.com/usage/custom-buttons/) is what you need
