### ISSUE TITLE
Pre-Settings for Engraving Parameters. (Feature Request)

### ISSUE THREAD

**Issue by Cyano95** [arkypita/LaserGRBL#674]
It would be nice if there is an option to save the engraving Parameters for example like:
---Wood---
Engraving Speed: 1500
Laser ON: M3
Laser OFF: M5
S-MIN: 0
S-MAX: 80

---Paper---
Engraving Speed: 5000
Laser ON: M3
Laser OFF: M5
S-MIN: 0
S-MAX: 50

---Steel---
Engraving Speed: 100
Laser ON: M3
Laser OFF: M5
S-MIN: 0
S-MAX: 255

So you can store the perfect parameters for your materials as your own default values.
And when you load a new file into LaserGRBL to engrave or cut, you can easily chose one of your default values (maybe like a drop down menue) and load it into the parameter boxes.

This Feature would be realy nice, because it will be faster and easier to make new files ready for engraving.

**Comment by arkypita** [comment]
already in roadmap #64
