### ISSUE TITLE
ligar os fios do laser na cnc shield 

### ISSUE THREAD

**Issue by ricardo356** [arkypita/LaserGRBL#675]
ola amigos sou novo por aqui. comprei um modulo laser e gostaria de saber como liga-lo na placa cnc shield 3.0. Estou usando GRBL 1.1. O modulo laser possui 3 fios( vermelho +/preto GND/ amarelo PWN) estou usando uma fonte de 12v. Ligo o positivo da fonte no vermelho 12v, o negativo da fonte no preto GND e o amarelo no Z+. Seria isso mesmo?

**Comment by StuartB4** [comment]
Sim, está correto se você tiver a versão 0.9 do GRBL. Se você tiver a versão 1.1, conecte o amarelo ao SpnEn.

**Comment by gisep** [comment]
Mais oui mon ami
