### ISSUE TITLE
eje z  placa cnc shield laser GRBL

### ISSUE THREAD

**Issue by angelp355** [arkypita/LaserGRBL#676]
hola a todos soy nuevo por aquí  e estado leyendo sobre el eje z en  cnc laser para que en cada pasada  baje   para poder cortar por favor como se configura el grbl en laser grbl para el eje z.
Nose si sera para ese fin o para que sirve .

**Comment by sinfocomp** [comment]
usa tu generqador de codigo G para eso, Vectric tiene la funcion de cuantas pasadas y divide la profundidad de corte en el numero de pasadas q quieras

**Comment by arkypita** [comment]
With latest version you can specify a custom GCode between passes so you can sink the Z axis
![image](https://user-images.githubusercontent.com/8782035/72418750-baa37100-377b-11ea-8ebb-d0499c9445a8.png)
