### ISSUE TITLE
Feature request: TbStep on JogBar should not have fix values

### ISSUE THREAD

**Issue by midibase** [arkypita/LaserGRBL#683]
Hello arkypita,
first off all thank you for your great work. 
Since a few versions you changed the value(s) of  TbSpeed in the JogBar. 
Now your UserControl (StepBar) have the fixed values (decimal[] values = { 0.1M, 0.2M, 0.5M, 1, 2, 5, 10, 20, 50, 100, 200 };)

This does not work for my purpose :(  I need to set the value with an invcrement of 1. From 1 to 100. 
Reason is that I must move per hand to fix value (e.g. 57mm). 
This value is a radius from an center point in a circle, This shows me if the wood is in the right position.

Is it possible to change it to the further version?

Thanks for your understand.
Best whishes to Italy from Austria

**Comment by arkypita** [comment]
The old scrollbar made it very difficult to pick "significant" values (1,2,5, 10...) and also difficult to take precise values of any type (37, 23...) so i think that the new version could be more useful for most users. 

In your case just check if you don't have better option for match your needs.
You can send G-Code manually from gcode box ("type gcode here" box) or design a "custom button" that do the move ti fixed value or based on image size.

Lot of example here https://github.com/arkypita/LaserGRBL/issues/306
