### ISSUE TITLE
Problem with laser off power

### ISSUE THREAD

**Issue by piotrusp** [arkypita/LaserGRBL#685]
Hi,
Maybe someone will be able to help me with my laser problem. 
I bought a 5W laser with a control module "SW-LD73 V1.1"

https://eu.banggood.com/Wholesale-Warehouse-450nm-5W-Laser-Engraving-Module-Blue-Light-With-TTL-Modulation-wp-Eu-1337358.html?rmmds=search

![62498497_330598334298775_4552162680852447232_n](https://user-images.githubusercontent.com/51910871/59601874-a6c05f80-9105-11e9-88ad-dc470626ee87.jpg)

I connected this laser module with a 3-pin cable (+, -, PWM) to the shield "GRBL V2.5.02" controlled by Arduino nano V3 to which I've uploaded the firmware grbl 1.1f

![62372377_2537706503181554_1684339088041181184_n](https://user-images.githubusercontent.com/51910871/59602011-fa32ad80-9105-11e9-9385-eb9bb85da31f.jpg)

When I power ON the shield, the laser immediately starts with full power and burns big hole. If I do not quickly press the black button on the laser module, then the plywood under the laser begins to burn with fire.  The button on the module switches the laser power to weak, but when I want to engrave something, the laser does not change its power and nothing burns. It burning plywood when I push the button on the module but he do it with full power. 
When I want engrave this pattern:
.  .  .  .  .  .  (dots)
he burns something like that
________ (line)
do not stop firing when going from point to point.

Please help!

**Comment by StuartB4** [comment]
Have you enabled PWM mode in LaserGrbl settings.
Have you set $32 to 1 in GRBL Configuration settings.
Also set $30 to 255 and $31 to 0
They can all be done in LaserGRBL.

**Comment by piotrusp** [comment]
Today I made the following steps:
1.	Disconected the Arduino nano from the shield
2.	Plug in to my laptop
3.	Open Arduino platform and cleared EEPROM
4.	I’ve uploaded clear firmware “grbl_v1.1f.20170801.hex” by XLoader
5.	Open LaserGRBL 3.0.16
6.	Connected with my Nano
When connected to my nano, I have such GRBL settings:
![1](https://user-images.githubusercontent.com/51910871/59630266-35a09c80-9145-11e9-8dae-7b1cba2eb1d4.jpg)
![2](https://user-images.githubusercontent.com/51910871/59630304-4bae5d00-9145-11e9-97f1-8045b74679e7.jpg)
![3](https://user-images.githubusercontent.com/51910871/59630312-4fda7a80-9145-11e9-8aed-c8e691e8ce67.jpg)
![4](https://user-images.githubusercontent.com/51910871/59630317-536e0180-9145-11e9-9a4c-5f7c02c50574.jpg)
and configuration:
$0=10 (Step pulse time)
$1=25 (Step idle delay)
$2=0 (Step pulse invert)
$3=0 (Step direction invert)
$4=0 (Invert step enable pin)
$5=0 (Invert limit pins)
$6=0 (Invert probe pin)
$10=1 (Status report options)
$11=0.010 (Junction deviation)
$12=0.002 (Arc tolerance)
$13=0 (Report in inches)
$20=0 (Soft limits enable)
$21=0 (Hard limits enable)
$22=0 (Homing cycle enable)
$23=0 (Homing direction invert)
$24=25.000 (Homing locate feed rate)
$25=500.000 (Homing search seek rate)
$26=250 (Homing switch debounce delay)
$27=1.000 (Homing switch pull-off distance)
$30=1000 (Maximum spindle speed)
$31=0 (Minimum spindle speed)
$32=0 (Laser-mode enable)
$100=250.000 (X-axis travel resolution)
$101=250.000 (Y-axis travel resolution)
$102=250.000 (Z-axis travel resolution)
$110=500.000 (X-axis maximum rate)
$111=500.000 (Y-axis maximum rate)
$112=500.000 (Z-axis maximum rate)
$120=10.000 (X-axis acceleration)
$121=10.000 (Y-axis acceleration)
$122=10.000 (Z-axis acceleration)
$130=200.000 (X-axis maximum travel)
$131=200.000 (Y-axis maximum travel)
$132=200.000 (Z-axis maximum travel)

Then I changed parameters:
$30=1000 (Maximum spindle speed) to $30=255
$32=0 (Laser-mode enable) to $32=1
GRBL said “Config written successfuly!

Then I disconnected from GRBL and checked new settings through the Arduino platform, its OK. Then I unplug Nano from laptop and plug into my Arduino Nano shield.
Then I made following steps:
1.	plug again power cable and USB cable
2.	open LaserGRBL
3.	connect with nano
4.	open file and set M3 to M4
![pic1](https://user-images.githubusercontent.com/51910871/59630449-9fb94180-9145-11e9-8e8f-12441ecb4478.jpg)
5.	push button on nano shield and laser start on full power
6.	push button on laser module and laser switch to weak mode
7.	start engraving and stepper motor work well but laser don’t burns
8.	when again pushed button on laser module that burns with too much power
LaserGRBL send properly command but laser don’t burn properly
That I want to engrave:
![pic2](https://user-images.githubusercontent.com/51910871/59630429-94feac80-9145-11e9-8a81-f5af329e339a.jpg)
This is my result:
![20190617_210933](https://user-images.githubusercontent.com/51910871/59630474-afd12100-9145-11e9-8fd4-074151c95f45.jpg)

**Comment by StuartB4** [comment]
I noticed the Engraving speed in Target image settings is 500, have you tried a higher speed?

**Comment by piotrusp** [comment]
changed speed $110,$111,$112 from 500 to 3000
but it did not help anything
then I changed acceleration $113,$114,$115 from 10 to 100
it has increased the overall speed, the plywood does not ignite anymore but still does not stop burning from point to point

**Comment by StuartB4** [comment]
You could just be unlucky and bought a laser with faulty laser driver board.

**Comment by M0USS** [comment]
Hello,

for the PWM you have to activate

$ 32 = 0 (Laser-mode enable)
by
$ 32 = 1 (Laser-mode enable)

and use the M4 command

**Comment by piotrusp** [comment]
Ok, thank you for help.

**Comment by piotrusp** [comment]
Is it possible that it has been damaged the arduino control board but not the laser module?

**Comment by judocka** [comment]
I am having the same problem on my cnc. I am trying to fix it, but have no progress. Have you have any update? Could you fix it?

**Comment by piotrusp** [comment]
Hi,  I have some solutions. Working without grayscale but its enough for
me. Tomorow I sens you some photo.
Piotr

czw., 5 wrz 2019, 20:51 użytkownik judocka <notifications@github.com>
napisał:

**Comment by piotrusp** [comment]
Hi, Im sending some pictures with my shield and laser module. Im not using
PWM pin, only + and GND, and LaserGRBL software with this settings

$0 Step pulse time 3 microseconds Sets time length per step. Minimum 3usec.
$1 Step idle delay 255 milliseconds Sets a short hold delay when stopping
to let dynamics settle before disabling steppers. Value 255 keeps motors
enabled with no delay.
$2 Step pulse invert 0 mask Inverts the step signal. Set axis bit to invert
(00000ZYX).
$3 Step direction invert 0 mask Inverts the direction signal. Set axis bit
to invert (00000ZYX).
$4 Invert step enable pin 0 boolean Inverts the stepper driver enable pin
signal.
$5 Invert limit pins 0 boolean Inverts the all of the limit input pins.
$6 Invert probe pin 0 boolean Inverts the probe input pin signal.
$10 Status report options 1 mask Alters data included in status reports.
$11 Junction deviation 0,010 millimeters Sets how fast Grbl travels through
consecutive motions. Lower value slows it down.
$12 Arc tolerance 0,002 millimeters Sets the G2 and G3 arc tracing accuracy
based on radial error. Beware: A very small value may effect performance.
$13 Report in inches 0 boolean Enables inch units when returning any
position and rate value that is not a settings value.
$20 Soft limits enable 0 boolean Enables soft limits checks within machine
travel and sets alarm when exceeded. Requires homing.
$21 Hard limits enable 0 boolean Enables hard limits. Immediately halts
motion and throws an alarm when switch is triggered.
$22 Homing cycle enable 0 boolean Enables homing cycle. Requires limit
switches on all axes.
$23 Homing direction invert 0 mask Homing searches for a switch in the
positive direction. Set axis bit (00000ZYX) to search in negative direction.
$24 Homing locate feed rate 25,000 mm/min Feed rate to slowly engage limit
switch to determine its location accurately.
$25 Homing search seek rate 500,000 mm/min Seek rate to quickly find the
limit switch before the slower locating phase.
$26 Homing switch debounce delay 250 milliseconds Sets a short delay
between phases of homing cycle to let a switch debounce.
$27 Homing switch pull-off distance 1,000 millimeters Retract distance
after triggering switch to disengage it. Homing will fail if switch isn't
cleared.
$30 Maximum spindle speed 255 RPM Maximum spindle speed. Sets PWM to 100%
duty cycle.
$31 Minimum spindle speed 0 RPM Minimum spindle speed. Sets PWM to 0.4% or
lowest duty cycle.
$32 Laser-mode enable 1 boolean Enables laser mode. Consecutive G1/2/3
commands will not halt when spindle speed is changed.
$100 X-axis travel resolution 100,000 step/mm X-axis travel resolution in
steps per millimeter.
$101 Y-axis travel resolution 100,000 step/mm Y-axis travel resolution in
steps per millimeter.
$102 Z-axis travel resolution 100,000 step/mm Z-axis travel resolution in
steps per millimeter.
$110 X-axis maximum rate 3000,000 mm/min X-axis maximum rate. Used as G0
rapid rate.
$111 Y-axis maximum rate 3000,000 mm/min Y-axis maximum rate. Used as G0
rapid rate.
$112 Z-axis maximum rate 1,000 mm/min Z-axis maximum rate. Used as G0 rapid
rate.
$120 X-axis acceleration 1000,000 mm/sec^2 X-axis acceleration. Used for
motion planning to not exceed motor torque and lose steps.
$121 Y-axis acceleration 1000,000 mm/sec^2 Y-axis acceleration. Used for
motion planning to not exceed motor torque and lose steps.
$122 Z-axis acceleration 1,000 mm/sec^2 Z-axis acceleration. Used for
motion planning to not exceed motor torque and lose steps.
$130 X-axis maximum travel 1000,000 millimeters Maximum X-axis travel
distance from homing switch. Determines valid machine space for soft-limits
and homing search distances.
$131 Y-axis maximum travel 1000,000 millimeters Maximum Y-axis travel
distance from homing switch. Determines valid machine space for soft-limits
and homing search distances.
$132 Z-axis maximum travel 1000,000 millimeters Maximum Z-axis travel
distance from homing switch. Determines valid machine space for soft-limits
and homing search distances.

sob., 7 wrz 2019 o 23:13 Piotr Policht <piotr.policht.pp@gmail.com>
napisał(a):

**Comment by piotrusp** [comment]
![module](https://user-images.githubusercontent.com/51910871/66315564-553b1b00-e916-11e9-8e91-866fef2f7ebf.jpg)
![shield](https://user-images.githubusercontent.com/51910871/66315577-5bc99280-e916-11e9-801d-807c4f785881.jpg)
![picture](https://user-images.githubusercontent.com/51910871/66315590-5ff5b000-e916-11e9-9628-9f1d8b9533a6.jpg)

**Comment by jeffolemes** [comment]
Olá gostaria de uma informação! Alguém conseguiu resolver o problema dessa ligação? Parece q não aceita os comandos do grbl. Estou na mesma situação e já verifiquei vários tutoriais e sem resultado satisfatório.
