### ISSUE TITLE
Virus reported at LaserGRBL v3.0.16

### ISSUE THREAD

**Issue by morcaozola** [arkypita/LaserGRBL#686]
A HackTool:Win32/Keygen and a Trojan:Win32/Fuery.C!cl are detected by Windows Defender. Prior versions are Ok.

**Comment by arkypita** [comment]
Known issue of false positive from AV

http://lasergrbl.com/faq/
https://github.com/arkypita/LaserGRBL/issues/235
https://github.com/arkypita/LaserGRBL/issues/70

I'm sorry for that, but it's something I cannot deal with it.
