### ISSUE TITLE
Laser modulation offset

### ISSUE THREAD

**Issue by flodu33** [arkypita/LaserGRBL#689]
Hello every body

I use laser mode, and m4 command.
I know my laser can't work under 10% duty cycle
How can i set my grbl?
I mean, at minimum speed , my signal modulation should be with 10%duty cycle minimum

Thanks

![IMG_20190625_085702](https://user-images.githubusercontent.com/52193435/60076533-18149980-9728-11e9-89d9-93eacc867038.jpg)

**Comment by arkypita** [comment]
![image](https://user-images.githubusercontent.com/8782035/60079217-c2db8680-972d-11e9-85a7-5c9e6b30ba63.png)

**Comment by arkypita** [comment]
https://github.com/gnea/grbl/wiki/Grbl-v1.1-Configuration#30---max-spindle-speed-rpm

**Comment by arkypita** [comment]
I am not 100% sure of this, but if you set something different from zero to $31 in grbl you can scale laser power.

**Comment by arkypita** [comment]
https://github.com/gnea/grbl/issues/531
https://github.com/gnea/grbl/issues/401
https://github.com/gnea/grbl/issues/49

**Comment by arkypita** [comment]
Those are if you want to change this behaviour in grbl.

Alternative way is to change the S values generated by lasergrbl.

![image](https://user-images.githubusercontent.com/8782035/60080078-7ee98100-972f-11e9-8cdf-3be5886c2738.png)

Just set "S-Min" to a value > 0 and LaserGRBL will use this value for pure white.

**Comment by flodu33** [comment]
Thanks, i ll try tomorow
Have a good day

**Comment by Singman33** [comment]
> Those are if you want to change this behaviour in grbl.
> 
> Alternative way is to change the S values generated by lasergrbl.
> 
> ![image](https://user-images.githubusercontent.com/8782035/60080078-7ee98100-972f-11e9-8cdf-3be5886c2738.png)
> 
> Just set "S-Min" to a value > 0 and LaserGRBL will use this value for pure white.

Hi, how fo you get that windows to set parameters ? I never found it !

**Comment by Singman33** [comment]
Ok, forget that, you only get it when converting a picture to gcode. That software is missing a lot of things to be usefull, like drawing text or lines without the picture step. :/

**Comment by arkypita** [comment]
@Singman33 https://github.com/arkypita/LaserGRBL/issues/85

**Comment by AxelGUILLAUMET** [comment]
Dear friend.

Is the $31 parameter could help to solve this?

https://github.com/grbl/grbl/issues/1637
