### ISSUE TITLE
On-screen Machine and Work position coordinates

### ISSUE THREAD

**Issue by hk89** [arkypita/LaserGRBL#69]
Hi

Sometimes I find it difficult to detect if I am approaching the end of my axes or not. It would be easier to have the machine and work coordinates in hand to avoid tripping a limit switch.

Could it be a feature where these coordinates are being displayed live within the application; maybe at the bottom of the screen next to the overrides. 

Thanks

**Comment by arkypita** [comment]
I agree. It will be a new feature on the next release.

Diego

Inviato con AquaMail per Android
http://www.aqua-mail.com


In data 31 Luglio 2017 21:37:49 hk89 <notifications@github.com> ha scritto:

**Comment by arkypita** [comment]
added in v2.7.3

**Comment by arkypita** [comment]
[Version v2.8.12](https://github.com/arkypita/LaserGRBL/releases/tag/v2.8.12) can now show working position if different from machine position.
