### ISSUE TITLE
Transverse speed while laser is on 

### ISSUE THREAD

**Issue by Geierma** [arkypita/LaserGRBL#690]
My issue is when the laser is on and transverses a long line, the movement speeds up and the laser does not burn. Can anyone help?

**Comment by cleola12** [comment]
Using the M4 control, gives power to the laser according to the speed that moves and the one that you put.

**Comment by Geierma** [comment]
On long lines while the laser is on to burn a line it moves faster then
when the laser is off moving to another location. in turn moving so fast
the laser does not have the time to burn the line.

**Comment by arkypita** [comment]
Edit grbl conf and setup lower value for max speed

**Comment by arkypita** [comment]
Or use lower speed in LaserGRB raster import procedure when set parameter for loaded image.
