### ISSUE TITLE
Forgot how to do maths?

### ISSUE THREAD

**Issue by TimSmith44** [arkypita/LaserGRBL#691]
My LaserGRBL just updated and seems to have forgotten maths.

I have a custom button that with no file loaded works correctly but as soon as a file is loaded, the X and Y works as if there is an offset. (There is none in the file).

Apparently, the centre of a 200 mm square image is now at 175.

I have tried other files and same happens.

Co-ordinates are reading x=0 and y=0 at home position,

Also tried re-starting software, and re-starting laser but the moment a file is loaded my centre is nowhere near centre and running would burn way too high.

**Comment by StuartB4** [comment]
Working ok here, version 3.0.17
What are the custom button settings?  can you paste them here so I can give it a go.

**Comment by TimSmith44** [comment]
It's not the button Stuart. Been using it for months and with no file loaded it works just fine.
(I can't copy as it's on a different machine but its the normal 3 second centre found on here).
Files that worked fine before the update now act as if they have a built in offset.
The display shows the laser at x = 0 and y = 0 and this is correct physically, yet when asked to centre a 200mm image, (x+200/2) and (y+200/2) it will then centre at x = 175 and y about 176.5 and it shows these figures when the laser travels there for its 3 seconds on low power.

I have a load of files for bowl diameters and it's like the files are ALL wrong now. Very frustrating as its been working just fine since I changed to LaserGRBL a few weeks back

**Comment by TimSmith44** [comment]
Button is ...

G0 X[left+200/2] Y[bottom+200/2]
M4 S1
G4 P3
M5
G0 X0 Y0 F3000

**Comment by StuartB4** [comment]
Yeah that's strange. You are right about it not being the button, works fine for me.

**Comment by arkypita** [comment]
The only changes done between v3.0.16 and v3.0.17 is the support of czech language. I am quite sure that no other stuff are changed. If you want to be sure just download older version

**Comment by StuartB4** [comment]
Have you used any software other than LaserGRBL on that computer?
I used Universal Gcode Sender once and forgot to reset all the settings before using LaserGRBL again.
When I did use it the next time, it was still using USG's settings for x and y that were present before I closed the program. Had to go back to it and reset everything before LaserGRBL would work correctly.

**Comment by TimSmith44** [comment]
Thanks Guys,

No. That computer does nothing else and it is only since the update but I wonder if maybe Windows has updated or similar? Not sure on that.

I will try going back to v3.0.16. Do I need to remove and re-install?

**Comment by StuartB4** [comment]
Not sure if you need to uninstall first. Only ever gone forward. You could also try updating  windows .Net, dont know if it would make a difference but should’nt make it any worse.

**Comment by arkypita** [comment]
No need to uninstall. Just download and install older version.
v3.0.16 (June 14) https://github.com/arkypita/LaserGRBL/releases/tag/v3.0.16
v3.0.14 (may 13) https://github.com/arkypita/LaserGRBL/releases/tag/v3.0.14

Older version ask you to update (of course) just skip the request and use it, just to test the issue you describe.

**Comment by arkypita** [comment]
However I'm not sure the issue you're reporting is really a bug or just a misunderstanding on your part of how it should work so please share with us your downgrade test result, and if you can try to show us the effects of what you are describing with some screenshoot or video in real usage condition.

**Comment by TimSmith44** [comment]
OK I will go shoot some video now.

It's very simple. I have a 200 mm square canvas set up in Photoshop with a logo centred within it. I program the custom button with 200/2 to arrive at a 100mm centre so I can align the 200 mm diameter bowl precisely. Instead of travelling to X100 and Y100 it goes to X175 and Y176.5 (from memory). Even if I replace the maths with 100 instead of 200/2, the result is the same once a file has been loaded.

I will try and get video from both versions and see now I have some time

**Comment by TimSmith44** [comment]
OK - I am weirded out by this   lol

I have tried .14 .16 and .17 versions and I have videos but they are taking a while to upload

Images i created in Photoshop, that previously worked just fine, are now exhibiting an 'offset'' for want of a better description.

Images I simply imported form another source work correctly in all 3 versions.

I can easy re-do my images as it seems something has maybe corrupted them somehow?

**Comment by arkypita** [comment]
For your information "left" and "bottom" are computer to the real leftmost point of the engraving and to the lowest point of the engraving, computed after the conversion to gcode. They are equivalent to the values reported in correspondence with the dashed lines on the ruler.

Conversion to gcode depends of the setup you insert in "raster import", for example white clip, spot removal, brightness, contrast etc and final image size and offset. So double check your setting.

**Comment by TimSmith44** [comment]
Thanks. That's kind of my point. The dashed lines on the ruler are showing exactly correct.

These images are being imported as 1 bit dithering, Stucki, horizontal, and 8 lines per inch

**Comment by TimSmith44** [comment]
![UNADJUSTEDNONRAW_thumb_46d4](https://user-images.githubusercontent.com/50911063/60451607-575d5180-9c24-11e9-944e-e2fadb93da05.jpg)

![UNADJUSTEDNONRAW_thumb_46d8](https://user-images.githubusercontent.com/50911063/60451643-6e03a880-9c24-11e9-802f-30897ac97f8a.jpg)

![UNADJUSTEDNONRAW_thumb_46d6](https://user-images.githubusercontent.com/50911063/60451700-925f8500-9c24-11e9-92ce-84072c9fdcc3.jpg)

![UNADJUSTEDNONRAW_thumb_46d6](https://user-images.githubusercontent.com/50911063/60451747-adca9000-9c24-11e9-903e-ad771c4f6c41.jpg)

**Comment by TimSmith44** [comment]
I cannot post a video on here - can I email it?

**Comment by arkypita** [comment]
Upload somewere and post link here

**Comment by TimSmith44** [comment]
https://youtu.be/QEo6K5wREDI

**Comment by TimSmith44** [comment]
Any ideas from the video please?

**Comment by StuartB4** [comment]
Hi Tim. Can you upload that image you used in the video to here so I can try it on my machine?
Just click Attach files below and select the image, then when it's done click the Comment button.

**Comment by TimSmith44** [comment]
![Bowl8](https://user-images.githubusercontent.com/50911063/60760590-7f3b2380-a02f-11e9-9f47-f994d521606c.jpg)

**Comment by StuartB4** [comment]
Here's the result.
Original image loaded.


![Untitled2](https://user-images.githubusercontent.com/16980026/60761252-ce3b8580-a03c-11e9-9597-5ee294435c20.jpg)

Settings.

![Untitled3](https://user-images.githubusercontent.com/16980026/60761258-d5629380-a03c-11e9-8366-ad0dab395395.jpg)

Actual image size in X direction.

![Untitled4](https://user-images.githubusercontent.com/16980026/60761263-dd223800-a03c-11e9-9b61-289050c65bec.jpg)

Actual image size in Y direction.

![Untitled5](https://user-images.githubusercontent.com/16980026/60761264-e14e5580-a03c-11e9-8fbf-ea537d33d1a9.jpg)

Position of cross using my Custom Center Button is correct.

![Untitled6](https://user-images.githubusercontent.com/16980026/60761268-e57a7300-a03c-11e9-995c-6a168d85de6d.jpg)

Starts engraving at lowest point of the image, bottom right of the H character on the word "Hand" 

![Untitled7](https://user-images.githubusercontent.com/16980026/60761277-f1fecb80-a03c-11e9-8cf6-9fc2ac884d7e.jpg)

This is my Custom Center Button settings.
![Untitled8](https://user-images.githubusercontent.com/16980026/60761279-02af4180-a03d-11e9-8939-0d106364457c.jpg)

**Comment by StuartB4** [comment]
I made another Custom Center Button using the same settings as your's and my machine does exactly the same, goes right off the screen. Just change the button settings to this.

G0 X[left+width/2] Y[bottom+height/2]
M4 S1
G4 P3
M5
G0 X0 Y0 F3000

**Comment by TimSmith44** [comment]
Thanks Stuart

All good here now

I thought I was going mad when it happened at first.

**Comment by StuartB4** [comment]
No problem. We all get a little mad every now and then.
