### ISSUE TITLE
Enhancement support settings for cloned and rotary axis

### ISSUE THREAD

**Issue by sinfocomp** [arkypita/LaserGRBL#694]
Hello, im using GRBL-Mega5X with a large 1.5 by 3 meter machine, have a cloned Y axis with auto squaring feature, on the grbl settings i can change all parameters for my cloned axis however there is no text  label indicating the labels of the values, it would be nice to have the GUI reconize these extra settings

**Comment by arkypita** [comment]
Recognizing non standard parameters for a non standard fork can conflict with others parameters defined in others non standard fork that use same numbering for other feature config. I prefer to recognize and give text hint only for standard grbl settings.
