### ISSUE TITLE
Laser Grbl engraving area.

### ISSUE THREAD

**Issue by firewirehn** [arkypita/LaserGRBL#695]
Hello.I am using 65x50 laser engraving machine with Benbox.Instead of Benbox I instaled LaserGrbl and downloaded one firmware from net to start using instead BenBox.When I uodated firmware my engraving area is only 30x30cm and I can not move machine all along X and Y ahis.Can somebody tell me what to change and how to adjust that my machine traveling all around that I can put homing point on some of corners.

**Comment by firewirehn** [comment]
Anyone please

**Comment by StuartB4** [comment]
You may need to change the Steps/mm.
To find the correct Steps/mm for your motors look at the 8th post by me in the link below.
https://github.com/arkypita/LaserGRBL/issues/664
When you have the correct numbers follow the steps in the picture below
![Untitled](https://user-images.githubusercontent.com/16980026/60758650-776c8680-a011-11e9-8c8c-b0803c339010.jpg)

**Comment by firewirehn** [comment]
Thanks a lot.It helps.
