### ISSUE TITLE
Bachin D8-4050P

### ISSUE THREAD

**Issue by passipire** [arkypita/LaserGRBL#696]
bonjour
je voudrai utiliser lasergrbl sur ma Bachin D8-4050P mais quand je veut faire bouger les axe avec la commande de base $J=G91X10Y0F1000 sa ne marche pas alors que quand je rentre la commande G91X10Y0F1000 en manuel cella fonctionne bien 

comment désactiver les argument $J= de début ?

Cordialement

**Comment by StuartB4** [comment]
Juste essayé moi-même avec et sans $ J = et cela fonctionne bien.
