### ISSUE TITLE
Laser won't turn on

### ISSUE THREAD

**Issue by mrfordnite** [arkypita/LaserGRBL#697]
I have a 250mw laser, and have followed the tutorial on [instructables.](https://www.instructables.com/id/DIY-Arduino-Mini-Laser-Engraver/) I have everything connected, and my stepper motors are working great. However, my laser is not turning on. Any ideas? Note: I have laser mode enabled. It is also worth noting that the "L" indicator light on my arduino nano lights up on m4 command, and turns off on m3 command.  Here is a [video ](https://drive.google.com/file/d/1-pSiDk878avIIzoZE5EyglDwemtudYOw/view?usp=sharing)of my setup.

**Comment by StuartB4** [comment]
Looks like you have the fet transistor next to the laser connector the wrong way round.

**Comment by mrfordnite** [comment]
@StuartB4 omg yes i just didn't notice. Will turning it around fix it or will i need to replace the mosfet?

**Comment by StuartB4** [comment]
I would remove the laser, turn the fet round and put a multimeter on the laser connector pins to see if there is the correct voltage coming out when you send a laser on command.

**Comment by StuartB4** [comment]
Hi mrfordnite.
Did you have any luck with it?

**Comment by mrfordnite** [comment]
@Stuart
I do not have the tools to remove the solder. I order a solder pump and
will try tomorrow.

**Comment by StuartB4** [comment]
Oh ok. Good luck with it.

**Comment by StuartB4** [comment]
Hi. Just wondered if you got it working.

**Comment by mrfordnite** [comment]
Hi, @StuartB4, after many backorders and setbacks, I have finally removed and replaced the fet (this time with it facing the right way.) However I am still experiencing a couple of issues...

1. Although the laser now turns on, it is a very weak beam- and it doesn't change when I run an engraving

2. The laser turns off when it should turn on, and is on when it should be off. (M3 turns off, M5 turns on.)

Any suggestions?
