### ISSUE TITLE
LaserGRBL stopped to run with Win10

### ISSUE THREAD

**Issue by MARVINU** [arkypita/LaserGRBL#700]
The program is not running anymore with Win10. It run when I´ve started to test the laser engraver but feel days after the program did not start.

**Comment by gisep** [comment]
It runs on my Win10, I don't think that's the problem.

**Comment by MARVINU** [comment]
Any clue why is not running? Something I can do or check?

**Comment by arkypita** [comment]
1. try uninstall then reinstall?
2. If not work check if uninstall completly remove C:\Users\YourUser\AppData\Roaming\LaserGRBL. If not delete the folder and install again.

**Comment by MARVINU** [comment]
The version v3.0.10 is runing nomally.

**Comment by arkypita** [comment]
did you have an antivirus? maybe could block latest version because of a false positive

**Comment by MARVINU** [comment]
I´m going to try an let you know.
