### ISSUE TITLE
LaserGRBL Picture Output Size

### ISSUE THREAD

**Issue by firewirehn** [arkypita/LaserGRBL#702]
Hello.How to change output size of the picture to desired size.Always is automatically set WxH like aspect ratio.Does anybody know how to set this for example ,I want 100x100 and automatically calculates 100x80.Where to adjust these.

**Comment by arkypita** [comment]
LaserGRBL always scale the image proportionally to keep aspect ratio. If you want to stretch/distort it you can edit image outside LaserGRBL (i.e paint, photoshop) to desired size.

**Comment by firewirehn** [comment]
Thanks for quick reply.I have one more question How to switch laser before beggining just to know where is start.Need to create custom button for this or not.

Sent from Yahoo Mail on Android 
 
  On sre, jul 17, 2019 at 21:05, arkypita<notifications@github.com> wrote:   
LaserGRBL always scale the image proportionally to keep aspect ratio. If you want to stretch/distort it you can edit image outside LaserGRBL (i.e paint, photoshop) to desired size.

**Comment by StuartB4** [comment]
This custom button will move the laser at low power around the border of the image you have prepared, so you can position the workpiece where you want.
This is the code I use but you can change the S and F setting numbers to suit you.
S = Laser power level. F = Speed the laser moves around the image border.
You can copy and paste this in to the custom button GCode box.

M4 
S5
F800
G0 X[left] Y[bottom] 
G1 X[right]
G1 Y[top]
G1 X[left] 
G1 Y[bottom] 
G0 X0 Y0 F4000
M5

![Untitled8](https://user-images.githubusercontent.com/16980026/61408772-baafda80-a8d8-11e9-9a15-771f3633e5b6.jpg)

**Comment by StuartB4** [comment]
This button will find the center of the image you have prepared.
Click once to find center with laser on. Click again to return home and switch laser off.

![Untitled9](https://user-images.githubusercontent.com/16980026/61409248-b9cb7880-a8d9-11e9-8236-338e783b0ab6.jpg)



GCode box 1.

$32=0
G0 X[left+width/2]
Y[bottom+height/2]
G1 M4 S5 F900


GCode box 2.

$32=1
G0 X0 Y0
M5

**Comment by firewirehn** [comment]
Thank you very much it is very helpfull.Thats mean with this custom button i can trace image before burning

Sent from Yahoo Mail on Android 
 
  On sre, jul 17, 2019 at 22:21, Stuart<notifications@github.com> wrote:   
This custom button will move the laser at low power around the border of the image you have prepared, so you can position the workpiece where you want.
This is the code I use but you can change the S and F setting numbers to suit you.
S = Laser power level. F = Speed the laser moves around the image border.
You can copy and paste this in to the custom button GCode box.

M4
S5
F800
G0 X[left] Y[bottom]
G1 X[right]
G1 Y[top]
G1 X[left]
G1 Y[bottom]
G0 X0 Y0 F4000
M5

**Comment by firewirehn** [comment]
Hello.Is there custom button for example to switc on laser only to spot piece of wood to know exactly where laser is.

Sent from Yahoo Mail on Android 
 
  On sre, jul 17, 2019 at 21:05, arkypita<notifications@github.com> wrote:   
LaserGRBL always scale the image proportionally to keep aspect ratio. If you want to stretch/distort it you can edit image outside LaserGRBL (i.e paint, photoshop) to desired size.

**Comment by StuartB4** [comment]
Try this. Press and release left mouse button to flash laser on and off.
![Flash Laser](https://user-images.githubusercontent.com/16980026/61879401-dcb5e800-aeea-11e9-8f40-51ea26c8f9ad.jpg)

**Comment by firewirehn** [comment]
I tried but nothing happened

Sent from Yahoo Mail on Android 
 
  On čet, jul 25, 2019 at 15:45, Stuart<notifications@github.com> wrote:   
Try this. Press and release left mouse button to flash laser on and off.

**Comment by StuartB4** [comment]
Did you change the Button Type to Push Button at the top.
Were you connected at the time.

**Comment by firewirehn** [comment]
I did not touch anything actually I don't know how to change that.

Sent from Yahoo Mail on Android 
 
  On čet, jul 25, 2019 at 19:34, Stuart<notifications@github.com> wrote:   
Did you change the Button Type to Push Button at the top.
Were you connected at the time.

**Comment by StuartB4** [comment]
Its the drop down menu where it says ButtonType.

**Comment by firewirehn** [comment]
I do not have this Button Type..only hotkeys.Can you send me picture to see exactly where is it
Sent from Yahoo Mail on Android 
 
  On čet, jul 25, 2019 at 20:21, Stuart<notifications@github.com> wrote:   
Its the drop down menu where it says ButtonType.

**Comment by firewirehn** [comment]
For example on the site I founded Toogle Laser on off.There is first Gcode M3 S30 and Second is M5.On mine settings instead M3 I put M4.Shall I put M4 S30...or something eles.Or if you have some example how to set up low light laser 

Sent from Yahoo Mail on Android 
 
  On čet, jul 25, 2019 at 21:42, spasoje kisic<kisicspasoje@yahoo.com> wrote:   
I do not have this Button Type..only hotkeys.Can you send me picture to see exactly where is it
Sent from Yahoo Mail on Android 
 
  On čet, jul 25, 2019 at 20:21, Stuart<notifications@github.com> wrote:   
Its the drop down menu where it says ButtonType.

**Comment by StuartB4** [comment]
![Untitled11](https://user-images.githubusercontent.com/16980026/61913157-195a0180-af34-11e9-870d-7677d31aa742.jpg)

![Untitled12](https://user-images.githubusercontent.com/16980026/61913162-1e1eb580-af34-11e9-9516-f7b58fd4267b.jpg)

When you've finished click on the Create button.

**Comment by firewirehn** [comment]
Hello my friend.I saw your article about connecting laser to cnc board.I ordered 8 wat laser and i have to connect to the cnc board.I am confused about that because I do not know which cable to connect and where.I will send you two picture of laser and cnc board.From laser going two cables one black thick one and red+white connected to white two pin connector.Both of this cable are connected to one cable which end should be connected to power supoly for laser.If you can help me with instruction where and how to connect









Sent from Yahoo Mail on Android 
 
  On pet, jul 26, 2019 at 4:01, Stuart<notifications@github.com> wrote:   




When you've finished click on the Create button.

**Comment by StuartB4** [comment]
Do you have the pictures?

**Comment by firewirehn** [comment]
I sent you in attachment.Check message before..i will send again now in attachment




Sent from Yahoo Mail on Android 
 
  On sre, avg 28, 2019 at 0:54, Stuart<notifications@github.com> wrote:   
Do you have the pictures?

**Comment by StuartB4** [comment]
There are no images attached.
Just click "Attach files" at the bottom of the box you type your reply in and select the images.

**Comment by firewirehn** [comment]
Check now



Sent from Yahoo Mail on Android 
 
  On sre, avg 28, 2019 at 6:49, Stuart<notifications@github.com> wrote:   
There are no images attached.
Just click "Attach files" at the bottom of the box you type your reply in and select the images.

**Comment by StuartB4** [comment]
Where are you sending them too, all I get is this.
![Untitled1](https://user-images.githubusercontent.com/16980026/63843265-034dbf80-c97e-11e9-8b6d-5020f5e7a015.jpg)

**Comment by arkypita** [comment]
@firewirehn attachment does not work if you reply by mail
all you need to do is to go to https://github.com/arkypita/LaserGRBL/issues/702 and drag-drop images into texbox, or click "Attach files by dragging&dropping".
