### ISSUE TITLE
     Please include Batch operation

### ISSUE THREAD

**Issue by zahidhasanmim** [arkypita/LaserGRBL#704]
Hello arkypita.
It will be helpful if you add batch operation section where multiple design can be engraved and before engraving low power laser light will show the area where individual design will be engraved.

Sorry for posting it in issue section.
thank you

**Comment by arkypita** [comment]
It is ok to post in issue section.
Multiple designs can be enqueued using menu "file -> append file".

It is a basic feature to do that. More complex batch operation, low power show etc is too complex and out of time/budget for me to develop in spare time.
