### ISSUE TITLE
laser engraving starts in 45 degrees 

### ISSUE THREAD

**Issue by jmennl** [arkypita/LaserGRBL#707]
hello everyone i 've build up my own laserengraver but the jog buttons are of when i pres n he goes nw and when i pres nw he goes w every time he goes 45 degrees off .
i tried to alter this in grbl settings but i can't find the right code line to do this also i've tried to changed it in lasergrbl settings and even this doesn't work .

is there someone who can help me please i'm a noob with this and tried to do this ad my one.

**Comment by StuartB4** [comment]
What moves wrong? The little blue cross in LaserGRBL or your laser

**Comment by jmennl** [comment]
The laser goes the wrong way

**Comment by StuartB4** [comment]
Then you must have your motors connected wrong or the settings in grbl are wrong, not LaserGRBL settings.

**Comment by StuartB4** [comment]
Have a look at $3 in GRBL configuration here:
https://github.com/gnea/grbl/wiki/Grbl-v1.1-Configuration

**Comment by StuartB4** [comment]
If you are using 1 motor for the X axis and 2 for the Y axis you may have them connected wrong.
You may have the X and 1 of the Y motors connected to the 2 Y axis connectors, that would move the X and 1 of the Y motors when you just want to move the Y.
The other Y Axis motor would then be on it's own on a serepate Y axis connector.

**Comment by jmennl** [comment]
Thanks STUARTB4,

I' ve got now the grbl. 0.9i and not the 1.1 and now it works the wright way,
But my hard ware config is like that of the draw robot 2 motors and 1 belt.
But now i gota problem with the output voltage of the ttl output formy laser the power output is 12.3 volts and ttl output is 0.49 low 0.69 volt high this must be 0 or 5 volts for laser on and off.

**Comment by jmennl** [comment]
https://1drv.ms/u/s!Aj0D-HJpPw_dlWtdzFG7ymwwWGDe
https://1drv.ms/u/s!Aj0D-HJpPw_dlWoLwqpk_1H5Vlzb

This is my build with a 10w laser and a sainsmart v2 bord and grbl 0.9i 
But know i've got a smal problem with lasergrbl software it works al fine teh software and hardware only grbl 0.9i doesn't support laser  $30 /31/32  and when i use grbl 1.1 i 'LL  have the problem again with 45 degrees startup.

My question is how can i upgrade 0.9i to 1.1 latest version or howto ad the commando's

Regards jmennl

**Comment by arkypita** [comment]
https://github.com/arkypita/LaserGRBL/issues/711
