### ISSUE TITLE
Feature Suggestion: Multiple passes

### ISSUE THREAD

**Issue by bearded1der** [arkypita/LaserGRBL#71]
Recommend adding drop down box for option to run multiple passes on a single design for the sake of cutting, vs. single pass for engraving.

Currently when I want to cut and need multiple passes, have to continuously press start after every finish. very inconvenient when I just want to set the machine and let it run.

Thanks for all your hard work!

Jake

**Comment by arkypita** [comment]
Easy to do, I will add in future version

**Comment by arkypita** [comment]
added in v2.7.3
