### ISSUE TITLE
How to upgrade grbl 0.9i to latest version 1.1 

### ISSUE THREAD

**Issue by jmennl** [arkypita/LaserGRBL#711]
This is my new project and need some help with it. 

https://1drv.ms/u/s!Aj0D-HJpPw_dlWtdzFG7ymwwWGDe 

https://1drv.ms/u/s!Aj0D-HJpPw_dlWoLwqpk_1H5Vlzb 

https://1drv.ms/v/s!Aj0D-HJpPw_dlW4TsKTByH2iJmnP

his is my build with a 10w laser and a sainsmart v2 bord and grbl 0.9i grbl corexy 
But know i've got a smal problem with lasergrbl software it works al fine the software and hardware  
only grbl 0.9i doesn't support laser $30 /31/32 and when i use grbl 1.1 i 'LL have the problem again with 45 degrees startup.My question is how can i upgrade 0.9i to 1.1 latest version or how to ad the commands

Regards jmennl
--

**Comment by arkypita** [comment]
If you use a CoreXY machine you should configure and compile grbl 1.1 for CoreXY, that is not the default firmware configuration. Read or ask about it on grbl page, not here: https://github.com/gnea/grbl/issues?utf8=✓&q=is%3Aissue+corexy

**Comment by juansr87** [comment]
Excuse me can you pass me the hex 0.9i I can't find it anywhere please

**Comment by juansr87** [comment]
Excuse me can you pass me the hex 0.9i I can't find it anywhere please
