### ISSUE TITLE
I turned laser mode on and now commands from the command line don't work

### ISSUE THREAD

**Issue by mcfitzp27** [arkypita/LaserGRBL#712]
I'm using LaserGRBL v3.0.17, and prior to activating laser mode, I was using the command line to focus the laser and set the home location. Then I put $32=1 into the command line, and now other commands like M3 and M5 no longer work. The laser still works when I run a programmed image, but I can't turn it on and off manually, and the home button doesn't seem to work anymore either. I turned laser mode back off, but still nothing works. Any clue what's going on here?

**Comment by arkypita** [comment]
Just open the "grbl config" form, so LaserGRBL download the whole conf and know all it needs to show correct options
