### ISSUE TITLE
Optimize travel

### ISSUE THREAD

**Issue by Zoli0123** [arkypita/LaserGRBL#717]
Hello,

Could somebody help me in optimizing G0 strategy at vector image?
If i would like to engraving thicker lines it takes long time because jogging. How can I reduce the jogging or optimize the process?

thx :)
![1](https://user-images.githubusercontent.com/43841743/63332195-649ae080-c337-11e9-8e4f-4e8deba246c8.JPG)
![4](https://user-images.githubusercontent.com/43841743/63333805-54d0cb80-c33a-11e9-8e49-02a31458e2fc.JPG)

![3](https://user-images.githubusercontent.com/43841743/63332724-644f1500-c338-11e9-8936-8c2a2af83c24.JPG)

**Comment by Dpsspower** [comment]
It seems that you do raster image.
Try vectorize with fill.

Line by line raster only can go one direction (vertical, horizontal or diagonal) and all empty space between must be traveled.
No other way.

**Comment by Zoli0123** [comment]
Hello,  It's vector style.

**Comment by Dpsspower** [comment]
Ah okay. This is already filled vector.
The fill is done by raster line. So the Laser has to jump along every line.
I don't see any other way.
The software should fill each object with raster infill as a single object, then jump to the next object. But this is not how this software works. 3D slicer software works such way to save time.

**Comment by arkypita** [comment]
Yes, filling of vector path is done using raster line alghoritm.
I know it is not efficient, but the code to fill vector path with vector path too is not so simple to write.

I suggest to use inkscape to generate vector filled path and then pass them to LaserGRBL.
