### ISSUE TITLE
Default Resolution

### ISSUE THREAD

**Issue by scorpio58** [arkypita/LaserGRBL#72]
Hi Everyone,

does anyone know what the default resolution in Laser GRBL? Everything that I import into it ends up being huge, even though it's the correct size before importing (I'm talking about lettering).

**Comment by brakthehun** [comment]
Are you importing a picture of the text or Gcode paths??

**Comment by arkypita** [comment]
are you sure to have the right [setup of $100 and $101](https://github.com/gnea/grbl/wiki/Grbl-v1.1-Configuration#100-101-and-102--xyz-stepsmm)
