### ISSUE TITLE
Not importing image correctly

### ISSUE THREAD

**Issue by lschaerer** [arkypita/LaserGRBL#721]
Yesterday, engraver (laserGRBL) was working fine.  Today, when importing the same image I worked on yesterday, the image isn't even recognizable.  I haven't changed any settings.   Image yesterday: 
![hummer for oval 4x5 test](https://user-images.githubusercontent.com/54603537/63815146-1bc7c680-c8f9-11e9-8379-a2bd79223993.jpg)
 Image today:  
![grbl](https://user-images.githubusercontent.com/54603537/63815461-3d757d80-c8fa-11e9-8e27-b8e80f0271dd.jpg)

**Comment by arkypita** [comment]
> I haven't changed any settings

Are you sure? Check parameter in raster import dialog.
Brightness, contrast, White Clip, and also output size.
