### ISSUE TITLE
Importare gcode senza rielaborarlo

### ISSUE THREAD

**Issue by Paoloc66** [arkypita/LaserGRBL#724]
Salve, vorrei riuscire a stampare un file G-code tramite LaserGRBL senza che il programma lo rielabori.
E' possibile?
Io non ci sono riuscito. Sarebbe una funzionalità utile in quanto a volte mi inviano dei file già pronti e non devo rielaborarli.

**Comment by arkypita** [comment]
file-apri è in grado di aprire file di testo con estensioni .nc, .cnc, .tap, .gcode, .ngc e li carica senza rielaborarli.
