### ISSUE TITLE
Images are mirrored 

### ISSUE THREAD

**Issue by FoRcE721** [arkypita/LaserGRBL#725]
Hi,
   I have the Uttiny CNC Laser Engraving Machine Kit, 500mw-2500mw , I am having an issue with the images I am bringing in to burn, even the ones that came with the laser to test. 
    The images burn but the are mirrored from the original , I have not messed with any settings yet I wanted to ask first before I went to changing them. Any ideal on why this would be happening?
![1CF45F9A-19EB-4EB9-AAC6-66809A473B4B](https://user-images.githubusercontent.com/54781753/64083147-1941e400-cce0-11e9-9fa1-225e802f6ad7.jpeg)
![8422BCD8-91E9-4013-B43C-53CC33005A28](https://user-images.githubusercontent.com/54781753/64083148-1941e400-cce0-11e9-995c-56c14fc9bd88.jpeg)

**Comment by arkypita** [comment]
LaserGRBL use cartesian axes system. X growing right, Y growing far from user.
If your engraver does not move like this, you should configure it by inverting axes in grbl settings. Grbl settings can be configured using LaserGRBL but they are stored and managed by your engraver control board.

https://github.com/gnea/grbl/wiki/Grbl-v1.1-Configuration#grbl-settings

**Comment by FoRcE721** [comment]
Thank you for the quick response, however I am struggling to find the solution, I do apologize as I haven’t had this setup more than 24 hours yet so u am still learning, I have tried a couple and made it worse so I reverted back but still have the same issue

**Comment by FoRcE721** [comment]
Got it thanks for the help again
