### ISSUE TITLE
General Question About Start Location 

### ISSUE THREAD

**Issue by FoRcE721** [arkypita/LaserGRBL#726]
Ok so is there a way to see the precise point the process will start before the laser begins the burn process? Like a quick view of the area the work will be done, I have looked but can’t find a answer to this.  I know this isn’t considered an issue do we have a community page or forum for general questions that may not be considered issues?
  Thanks in advance

**Comment by arkypita** [comment]
https://github.com/arkypita/LaserGRBL/issues/474

> I know this isn’t considered an issue do we have a community page or forum for general questions that may not be considered issues?

I am not sure, but seems that github doesn't have a section for general request, help etc, so ok to post into issue
