### ISSUE TITLE
MAC OSX

### ISSUE THREAD

**Issue by spiritburner** [arkypita/LaserGRBL#728]
Hi there, on the basis there is no .dmg file I am assuming if there was the developer would have ported it to OSX by now. I am just wondering if anyone knows whether this runs under emulation software or under Codeweavers Crossover, would love to find out, I recently discovered the fact that my Laseraxe cncc MC board with Arduino nano will run in OSX if flashed with the right version of GRBL and its been running Lightburn perfectly.

Just would like to know if anyone tried, not interested in Bootcamp install in anyway thanks.

**Comment by arkypita** [comment]
Sorry but I am not able to create software for OSX
