### ISSUE TITLE
Step slider does not display

### ISSUE THREAD

**Issue by Stevehyman** [arkypita/LaserGRBL#731]
I have Lasergrbl on another computer, but when I load into this computer the STEP slider does not show on the screen I have tried several down loads and it never shows up. I am using win 8.1, what is going on?
THanks

**Comment by StuartB4** [comment]
Check Continuous is not enabled.
![Untitled6](https://user-images.githubusercontent.com/16980026/64746389-432ab000-d503-11e9-8671-f2aed2e9cf28.jpg)

**Comment by Stevehyman** [comment]
Thanks, I did that but it still does not show up, but thanks to your reply I think I know what it is, I am using another version of GRBL, that says it's for lasers I will load GRBL1.1 and see if that fixes it.

**Comment by Stevehyman** [comment]
Thank, I loaded GRBL1.1 and unchecked Continuos Jog and now every thing is working as it should. Thanks for the wake up.
