### ISSUE TITLE
Hungarian translate

### ISSUE THREAD

**Issue by ddogman** [arkypita/LaserGRBL#735]
I would like to make a Hungarian translation.
With Visual Studio 2017.
This is my first time using Github, I have used Microsoft Team Fundation Server so far, sorry if I make a mistake.

**Comment by ddogman** [comment]
Hungarian translate v1.0 source:
https://github.com/ddogman/LaserGRBL

**Comment by arkypita** [comment]
Thanks and sorry for late reply. I am very busy this times.
I have added your job in latest version.

Best regards, Diego
