### ISSUE TITLE
mnr pieter pretorius

### ISSUE THREAD

**Issue by pieter65** [arkypita/LaserGRBL#737]
good day can you please tell me if I can change the point of O on the GRBL program I have 3 images that I want to laser on one board. example 1 photo on the left site writing in the middle and foto on the right site can you please help I wish there was a course that I can follow to learn. the ones on YouTube is not useful

**Comment by StuartB4** [comment]
Do you mean like this? This was 3 seperate images loaded one after the other using Append File on the file menu.

![Gruffalo](https://user-images.githubusercontent.com/16980026/65455225-b3f49500-de3e-11e9-9e74-225c9e4c9f58.jpg)

**Comment by pieter65** [comment]
Thank you for your helpSent from my Huawei phone-------- Original Message --------Subject: Re: [arkypita/LaserGRBL] mnr pieter pretorius (#737)From: Stuart To: arkypita/LaserGRBL CC: pieter65 ,Author Do you mean like this? This was 3 seperate images loaded one after the other using Append File on the file menu.

**Comment by pieter65** [comment]
Baie dankie waardeerSent from my Huawei phone-------- Original Message --------Subject: Re: [arkypita/LaserGRBL] mnr pieter pretorius (#737)From: Stuart To: arkypita/LaserGRBL CC: pieter65 ,Author Do you mean like this? This was 3 seperate images loaded one after the other using Append File on the file menu.
