### ISSUE TITLE
grbl 

### ISSUE THREAD

**Issue by amirghaffari33** [arkypita/LaserGRBL#738]
Hi im Amir from Turkey and im trying to do a laser cutiing with a arduino uno and cnc shield  v3 but i cannot upload last ver of grbl on arduino . I encounter with several Message like as " sketch does not invalid library
Please help me .from now thank you for your kind reply.
Best regard
Amir

**Comment by brakthehun** [comment]
what version of Arduino are you using??
What version of GRBL are you using??
This might be better for the GRBL repository:
https://github.com/gnea/grbl/issues
