### ISSUE TITLE
Burning of nichrome wire

### ISSUE THREAD

**Issue by Charus-OV** [arkypita/LaserGRBL#743]
Hi friends. Sorry for my English. I use an interpreter.
Wanted to know. It is possible to add several functions to the program. To be able to burn heated nichrome wire. Here is an example of such a machine.
https://www.youtube.com/watch?v=Kxm4z5hYxJU
https://www.youtube.com/watch?v=jeFRz7EQfyo

**Comment by arkypita** [comment]
Nice machine.

LaserGRBL is for laser. I'll go crazy if I want to make it usable with pen plotter, nicrome pyrograph, wire polystyrene cutter etc. 

Code is public so anyone can fork LaserGRBL to create "PyroGRBL" or "WireGRBL" or "PlotterGRBL" doing the changes he need to the logic.

**Comment by Charus-OV** [comment]
OK.
