### ISSUE TITLE
Raspberry Pi/Protoneer CNC Hat

### ISSUE THREAD

**Issue by Mochanic** [arkypita/LaserGRBL#744]
Would really like to use your software on a Raspberry Pi running a Protoneer CNC hat found here: https://blog.protoneer.co.nz/raspberry-pi-cnc-board-hat/
Is this possible?

Also, can I export the gcode from your software so that I can run it with Octoprint and the "Better GRBL Support" plugin?  No streaming from a computer will be necessary, the GRBL will be placed onto the SD card on the Pi itself when using this plugin.
https://plugins.octoprint.org/plugins/bettergrblsupport/

**Comment by arkypita** [comment]
Sorry LaserGRBL is windows only.
I have done some test to get it working with mono but without success.
