### ISSUE TITLE
Photo burning problem

### ISSUE THREAD

**Issue by TheTchief** [arkypita/LaserGRBL#749]
Hello,

I want to print a photo on a funeral urn but the result is not good.

What settings do I need to use to burn grayscale?

Thank you !

**Comment by StuartB4** [comment]
Your laser needs to be able to adjust the power up and down (PWM/TTL mode).
If you Start LaserGRBL and click Connect, then go to the GRBL Menu top left, then click Grbl Configuration. You should have a popup like this:

![Untitled](https://user-images.githubusercontent.com/16980026/67148160-274dc300-f294-11e9-831c-f3cad1569ee4.png)


Check the 3 settings I have highlighted and see if they are the same. If they are not just click on the value box with the numbers in for each one and change the value to the one you see there.
Then click the Write button and Close.

If you don't have them $ settings you have an older version of GRBL. 

Also in Target Image Setting, if it shows M3 for Laser on change it to M4 in the drop down box.

![Untitled2](https://user-images.githubusercontent.com/16980026/67148218-f752ef80-f294-11e9-9a91-da2b372e15c8.jpg)

**Comment by StuartB4** [comment]
Did you have any luck with it?

**Comment by TheTchief** [comment]
Hello,

I am starting to understand your software better and to have results.

Given that there are many options, I would like to know where I could find a complete user guide (ideally in French) to make the most of its many possibilities?

Thanks for your help !

Denis Cloutier
Quebec, Canada
denis@top-focus.ca

De : Stuart <notifications@github.com>
Répondre à : arkypita/LaserGRBL <reply@reply.github.com>
Date : jeudi 24 octobre 2019 05:58
À : arkypita/LaserGRBL <LaserGRBL@noreply.github.com>
Cc : Denis Cloutier <denis@top-focus.ca>, Author <author@noreply.github.com>
Objet : Re: [arkypita/LaserGRBL] Photo burning problem (#749)


Did you have any luck with it?

**Comment by StuartB4** [comment]
You could join the LaserGRBL Facebook group for more help, also Youtube videos. I've not seen any complete user guides anywhere either French or any other language.
