### ISSUE TITLE
Russian Translated

### ISSUE THREAD

**Issue by Newcomere** [arkypita/LaserGRBL#755]
.resx files
https://github.com/Newcomere/Translated

**Comment by StuartB4** [comment]
Is this an update, LaserGRBL already has Russian Language.

**Comment by Newcomere** [comment]
But the translation is not complete

**Comment by StuartB4** [comment]
Oh ok, no problem. Nice of of you to do it. :)

**Comment by Newcomere** [comment]
How to compile these files to dll?

**Comment by arkypita** [comment]
I have added your translation in latest version
