### ISSUE TITLE
Configuration export nit work

### ISSUE THREAD

**Issue by gerdvogel** [arkypita/LaserGRBL#76]
Hi,
I have a small problem.
In order to update the firmware, I would like to save the configuration before and to load it back later.
But when exporting the configuration I get the following error message:

Error exporting config!

it is a bug or a user error?

regards
Gerd

**Comment by arkypita** [comment]
Configuration export was one of the first functions I implemented. It's possible that with time it's no longer aligned with the latest code changes. At this time I can only test it with an emulation.

**Comment by gerdvogel** [comment]
Hi,

i have testet with grbl 0.9j and 1.1f, with both I gad the sam error.

LaserGRBL 2.7.4

 

regards

Schönen Gruß

Gerd Vogel

 

Von: arkypita [mailto:notifications@github.com] 
Gesendet: Montag, 21. August 2017 09:59
An: arkypita/LaserGRBL
Cc: gerdvogel; State change
Betreff: Re: [arkypita/LaserGRBL] Configuration export nit work (#76)

 

Configuration export was one of the first functions I implemented. It's possible that with time it's no longer aligned with the latest code changes. At this time I can only test it with an emulation.

**Comment by arkypita** [comment]
Released a new version v2.7.5
Hope it is fixing

**Comment by gerdvogel** [comment]
Thanks for the quick help. the bug is fixed. It tested export and import immediately.

 

regards

Schönen Gruß

Gerd Vogel

 

Von: arkypita [mailto:notifications@github.com] 
Gesendet: Montag, 21. August 2017 11:32
An: arkypita/LaserGRBL
Cc: gerdvogel; State change
Betreff: Re: [arkypita/LaserGRBL] Configuration export nit work (#76)

 

Released a new version v2.7.5
Hope it is fixing
