### ISSUE TITLE
How to control grbl using uart connection between arduino uno and node mcu

### ISSUE THREAD

**Issue by asankakumara** [arkypita/LaserGRBL#762]
How to control grbl using UART connection between Arduino UNO and node MCU

**Comment by brakthehun** [comment]
Are you trying to host a web server?? An SD card stream?? Is this actually LaserGRBL related?? I know there is a discussion on the GRBL page about this.

**Comment by asankakumara** [comment]
How to create a mit app inventor android app for s
end G code over WiFi.
