### ISSUE TITLE
Found Mailware in Download

### ISSUE THREAD

**Issue by Pix4hawk** [arkypita/LaserGRBL#763]
my antivirus found Mailware  HEUR/APC !??
![image](https://user-images.githubusercontent.com/18186206/68243796-960c7980-0013-11ea-8ba5-63eb59539b14.png)

**Comment by StuartB4** [comment]
It's a false positive, unless you downloaded it from somewhere other than LaserGRBL website.
It has something to do with certificate signing I think.

**Comment by Pix4hawk** [comment]
Thanks for quick answer!
-------- Ursprüngliche Nachricht --------Von: Stuart <notifications@github.com> Datum: 05.11.19  22:12  (GMT+01:00) An: arkypita/LaserGRBL <LaserGRBL@noreply.github.com> Cc: Pix4hawk <quaxforum@arcor.de>, Author <author@noreply.github.com> Betreff: Re: [arkypita/LaserGRBL] Found Mailware in Download (#763) It's a false positive, unless you downloaded it from somewhere other than LaserGRBL website.
It has something to do with certificate signing I think.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/arkypita/LaserGRBL/issues/763?email_source=notifications\u0026email_token=AEKX7XRX24GEK3MZCS2H4MTQSHOS3A5CNFSM4JJINYC2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEDEKWWQ#issuecomment-550021978",
"url": "https://github.com/arkypita/LaserGRBL/issues/763?email_source=notifications\u0026email_token=AEKX7XRX24GEK3MZCS2H4MTQSHOS3A5CNFSM4JJINYC2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEDEKWWQ#issuecomment-550021978",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by StuartB4** [comment]
Here's a better explanation from the author of LaserGRBL.
https://github.com/arkypita/LaserGRBL/issues/70
