### ISSUE TITLE
Help with CNC 3018 Pro

### ISSUE THREAD

**Issue by jonvarsol** [arkypita/LaserGRBL#768]
Hello! I don{t know how to use CNC 3018 Pro, I tried with PC software and cannot engrave with laser. 
It goes only form left ot right and up and down but the below plate doesnt moves, so all I got is a line over and over... It supposed to be the name: Paul Smith and looks in the other picture what I got :( 

![WhatsApp Image 2019-11-06 at 21 26 45](https://user-images.githubusercontent.com/57471306/68357882-5a89b200-00dc-11ea-9c80-c96c46969c9f.jpeg)
![WhatsApp Image 2019-11-06 at 21 27 43](https://user-images.githubusercontent.com/57471306/68357883-5a89b200-00dc-11ea-922f-1f6faed07a23.jpeg)

**Comment by StuartB4** [comment]
Are you sure all your electrical connections are ok?
Does the Y axis motor turn at all, can you see the lead screw rotating?
Check the Y axis motor connection. 
Then when the machine is connected go to the Grbl menu in LaserGRBL and select Grbl Configuration.
Look down the list of settings and check the $100 and $101 settings.
They should be about the same.

**Comment by StuartB4** [comment]
This may sound daft but is it a new machine? if so, are there any bits of packing left underneath the bed that might be stopping the motor from moving.

**Comment by jonvarsol** [comment]
Thanks for your help! and I am so sorry for my late response, I was out of my house. 

- yes, Y axis is working, I can see the lead screw rotating, actually same as X and Z axis.
- it´s a new machine. I already checked everything and there´s nothing underneath the bed :(

Sorry to botter you, but it will be great if you can text me by whatsapp, so I will be ablle to send you some videos... +506 8707-5923

Thanks,

Jonathan
![1](https://user-images.githubusercontent.com/57471306/68726671-d75ad700-0587-11ea-9b58-d9d60aadfc9f.jpg)

**Comment by StuartB4** [comment]
I don't understand, if the Y axis motor and the lead screw is moving then the bed should be moving.
Did you fix the workpiece, to the bed, there is a chance that it moved when the bed moves.
Also I would change $32 to 1 to enable Laser mode.

**Comment by jonvarsol** [comment]
Yes, its really weird! well, I mean, I can see the lead screw rotating when I move with offline control or with the grbl software, but no when is working with laser.

I dont know what you mean with fix the workpiece :(

I changed $32 to 1 and nothing happened.

Here´s another screenshot of my last test (same history).

![2](https://user-images.githubusercontent.com/57471306/68815075-09c80b00-0640-11ea-84f4-b4d8f80f2ab8.jpg)

**Comment by jonvarsol** [comment]
by the way, thanks for your help!

**Comment by StuartB4** [comment]
What I mean is, did you fix the item you were engraving to the bed so it could'nt move about with the vibration of the machine.

Changing $32 to 1 gives you more control over the laser power thats all.

You could try changing the steps/mm in grbl configuration settings.
Try changing the Y axis $101 to 1600.

The model number of the machine (3018) refers to the actual engraving area.
X  = 300mm  Y = 180mm. 
The maximum travel for the X axis on yours is set to 200 ($130) from what I can see in the image you posted. So you should be able to set $130 (X) to a bit less than 300.
Also check $131 for the maximum travel of the Y axis and set $131 (Y) a bit less than 180.

**Comment by arkypita** [comment]
> Thanks for your help! and I am so sorry for my late response, I was out of my house.
> 
> * yes, Y axis is working, I can see the lead screw rotating, actually same as X and Z axis.
> * it´s a new machine. I already checked everything and there´s nothing underneath the bed :(
> 

Just to be sure: are you telling that if you control the movement with jog all it's fine, and if you send a program the Y does not move (or it move bad)?

Please do this test: set jog step to 20 (2cm), speed ~1000

![image](https://user-images.githubusercontent.com/8782035/68839694-80591d00-06c1-11ea-8e57-0883c866f4ac.png)

Then move the X axis left and right. Does it moves? It moves by 2cm exactly?
Then move the Y axis far and near. Does it moves? It moves by 2cm exactly?

> I dont know what you mean with fix the workpiece :(

Attach to the bed with a bolt/nuts or at least tape.

**Comment by StuartB4** [comment]
Forgot to mention $20. 
If you set the Max Travel on $130 and $131 also make sure $20 is set to 1.
It enables Soft Limits so the Laser or the Bed don't go too far.
If you do try to tell it to move more than it's set to it will just not move and will say "Travel exceeded" in the window on the left where the GCode scrolls up.

**Comment by jonvarsol** [comment]
StuartB4 and arkypita, thank you so much for your help.

I found the solution... Y and Z cables were changed. You may be laughing ;), It´s my firts machine and I had not experiense. I really appreciate your time.

**Comment by StuartB4** [comment]
I'm not gonna laugh...........much. : )
We all have to start somewhere, glad you sorted it, and glad to help if I can.
Good luck with it.

**Comment by locovaldes** [comment]
Hi i have a 3018 Pro , and the laser was working good  and now sometime burn and sometime nothing, or do like small draw no normal
![12](https://user-images.githubusercontent.com/73902303/98016531-194de000-1dcc-11eb-8aca-46dd51d2bd1e.jpg)

**Comment by locovaldes** [comment]
![123189056_401928250983547_3121162529269964463_n](https://user-images.githubusercontent.com/73902303/98016755-5d40e500-1dcc-11eb-9288-d14ae4023692.jpg)
![123452324_373113303930923_8990102190788775060_n](https://user-images.githubusercontent.com/73902303/98016758-5dd97b80-1dcc-11eb-933b-0e23813424e8.jpg)

**Comment by locovaldes** [comment]
first was and now i try to do the 800 speed test and see what i got
