### ISSUE TITLE
Connection Problem 

### ISSUE THREAD

**Issue by Kapelaan** [arkypita/LaserGRBL#769]
I just got my new 3018 Pro Max laser engraver. I have installed LaserGRBL v3.0.18 on my computer, but the program don’t want to connect to my cutter. Can you please help?

**Comment by StuartB4** [comment]
Have you tried other programs with any success?

Did it come with a disk with USB drivers on it.

Is it showing up in the Windows Device manager:
You may need to install the CH340 driver.

![Untitled](https://user-images.githubusercontent.com/16980026/68390157-97958900-015c-11ea-9d07-170b7930073d.jpg)

**Comment by Kapelaan** [comment]
I have also tried engraver-Master and Laser-Engraver, but with no success.

I got some of the driver with the machine on a USB-stick.

I have installed the CH340 driver. The Device Status at the Windows Device Manager is saying: "The device is working properly", but still no program wants to connect to the maschine

**Comment by Kapelaan** [comment]
I have also tried engraver-Master and Laser-Engraver, but with no success.

I got some of the driver with the machine on a USB-stick.

I have installed the CH340 driver. The Device Status at the Windows Device Manager is saying: "The device is working properly", but still no program wants to connect to the maschine

**Comment by StuartB4** [comment]
Have you tried different USB ports, or a different computer?
Is the Baud rate set to 115200.

**Comment by Kapelaan** [comment]
I have tried different USB ports as well as a different computer.

Yes, the Baud rate is set to 115200

**Comment by StuartB4** [comment]
Does the control main board have a makers name on it?

**Comment by StuartB4** [comment]
Does it have a hand controller so you can use it without connection to a computer.
I do know that usually you can't use it if both the hand controller and the pc are connected at the same time.

**Comment by Kapelaan** [comment]
Thank you so much!!! That's it! The hand controller was still connected to the machine. The moment that I have removed it, my program was connecting to the machine. Thank you!

**Comment by StuartB4** [comment]
Oh right, that's good to know. Glad you got it sorted.
