### ISSUE TITLE
Cancel Job function

### ISSUE THREAD

**Issue by 3ditguy** [arkypita/LaserGRBL#77]
I would be very helpful to have an abort button, this should cancel streaming, disable the laser and return the carriage to 0. Perhaps the function should only become available while streaming is paused?

**Comment by arkypita** [comment]
The correct procedure to obtain what you need is

1) pause the execution (red hand button)
2) grbl-reset (lightning button, this cancel enqueued job in LaserGRBL and also flush grbl internal buffer)
3) press the "blue home" inside the arrows box (not homing!)

One "abort button" that does all the three things could be usefull but too powerfull... better to have 3 elementary buttons.
