### ISSUE TITLE
CNC 3018 550mw laser losing intensity?

### ISSUE THREAD

**Issue by rich12355** [arkypita/LaserGRBL#770]
Hi everyone, I have been using the CNC 3018 with a 550mw laser, which has been working quite well. But the latest project was progressing well, but towards the end it seemed as though the intensity of the laser weakened and the last part of the project did not burn, even at 100% barely burns the wood. 

Does this sound like a failing laser module? Its only done around 8hrs work. Lens is clean. 

It's running 1.1 M3  any help would be great!

**Comment by brakthehun** [comment]
It does sound like a failing laser module. Can you take a pic of it?? Can you restart the program and see if it just no longer burns??
