### ISSUE TITLE
Settings for the cutting and engraving of different materials

### ISSUE THREAD

**Issue by Kapelaan** [arkypita/LaserGRBL#771]
Hi.

Where can I find information about the settings for my 3018 Pro Max laser engraver (15V laser) in connection with the cutting and engraving of different materials (like the cutting of 3 mm thick Masonite)?     

I'm using the LaserGRBL v3.0.18 program.

**Comment by StuartB4** [comment]
A good place for things related to the 3018 is on the Facebook user group page.
https://www.facebook.com/groups/SainSmart.GenmitsuCNC

**Comment by Kapelaan** [comment]
Thank you so much
