### ISSUE TITLE
feature request, start streaming job when signaled form controller

### ISSUE THREAD

**Issue by sinfocomp** [arkypita/LaserGRBL#776]
is it possible to start streaming a loaded file when the feed hold cycle start is toggled, i have a big machine and machine is far from cpu, it would be nice to be able to start the job from whithin the machine

**Comment by brakthehun** [comment]
You can create a .txt file and just type in M0 in a single line. call it pause.txt
Then when you make a file,, you can open pause.txt,, then File>append file and make your program.

**Comment by brakthehun** [comment]
Rumor is,, you'll be able to add a custom header to files soon BTW.

**Comment by arkypita** [comment]
Hi all
I have released a preliminary version of LaserGRBL that allow to specify custom GCode for header/footer and between passes. I need more testing as possible.

https://github.com/arkypita/LaserGRBL/releases/tag/v3.0.19

**Comment by brakthehun** [comment]
This is great BTW. I can now home the gantry to the top of the machine.


     On Saturday, November 23, 2019, 5:13:36 AM PST, arkypita <notifications@github.com> wrote:  
 
 
Hi all
I have released a preliminary version of LaserGRBL that allow to specify custom GCode for header/footer and between passes. I need more testing as possible.

https://github.com/arkypita/LaserGRBL/releases/tag/v3.0.19
