### ISSUE TITLE
horizontal lines are not straight

### ISSUE THREAD

**Issue by GildDart** [arkypita/LaserGRBL#779]
Hello,
I have an Alfawise C30 engraver since a few days. I am using LaserGRBL that is realy great.
Every thing seems OK except that the horizontal lines are not straight. It looks like light waves or ripples.
It looks like a software issue (configuration ?) Do you have any idea ?
Thanks in advance for your help.
Gildart

**Comment by arkypita** [comment]
Take a look here: https://github.com/arkypita/LaserGRBL/issues/30

**Comment by arkypita** [comment]
And here

![image](https://user-images.githubusercontent.com/8782035/69320697-ed306200-0c41-11ea-8fd1-4ed6ccf68340.png)

**Comment by GildDart** [comment]
Thank you for your reply. I test many things regarding these topics and it's finaly a problem with the bottom wheel  of X axe...
