### ISSUE TITLE
Beta test for custom header/footer

### ISSUE THREAD

**Issue by arkypita** [arkypita/LaserGRBL#783]
Hi all!
I need beta testing this version: https://github.com/arkypita/LaserGRBL/releases/tag/v3.0.19
Anyone is welcome to download and use and give feedback about:

- customize header/footer/cycle codes (same macros of custom button are available)
- realtime commands sent from custom button, and from header/footer/cycles too

Available realtime commands: https://github.com/gnea/grbl/wiki/Grbl-v1.1-Commands#grbl-v11-realtime-commands

Available macros:

macro | value
-- | --
left | Left margin of loaded image (X)
right | Right margin of loaded image (X)
top | Top margin of loaded image (Y)
bottom | Bottom margin of loaded image (Y)
width | Width of loaded image
height | Height of loaded image
jogstep | Actual value of jog step cursor
jogspeed | Actual value of jog speed cursor
WCO.X | Actual value of WCO X (Work Coordinate Offset) use .X .Y .Z
MPos.X | Actual Machine position. Support .X .Y .Z
WPos.X | Actual Work position. Support .X .Y .Z

**Comment by distebia** [comment]
potrei inserire nel codice personalizzato il comando pause a ogni linea come discusso su https://github.com/arkypita/LaserGRBL/issues/698?

**Comment by arkypita** [comment]
> potrei inserire nel codice personalizzato il comando pause a ogni linea come discusso su #698?

no, this feature is not intended to do that

**Comment by B1Gt0ne** [comment]
How do I enter a code?
I want to add M452 P3 R255 F200 S1 as a header

**Comment by arkypita** [comment]
Download [latest pre-release](https://github.com/arkypita/LaserGRBL/releases/download/v3.0.24/install.exe) 

open "grbl-settings" and edit this page

![image](https://user-images.githubusercontent.com/8782035/69479119-2d3a4500-0dfa-11ea-9ed8-31bd55867913.png)

**Comment by B1Gt0ne** [comment]
I have tried this but it makes no difference 




Get Outlook for Android







On Mon, Dec 2, 2019 at 8:53 PM +0000, "arkypita" <notifications@github.com> wrote:












Download latest pre-release


open "grbl-settings" and edit this page

**Comment by arkypita** [comment]
Difference is not in exported gcode.
Exported GCode does not include custom header/footer

**Comment by B1Gt0ne** [comment]
OK I see. Is this a possibility for a future release? 




Get Outlook for Android







On Mon, Dec 2, 2019 at 9:15 PM +0000, "arkypita" <notifications@github.com> wrote:












Difference is not in exported gcode.

Exported GCode does not include custom header/footer

**Comment by arkypita** [comment]
> OK I see. Is this a possibility for a future release?

I don't think that is correct to export header/footer into saved gcode.

Custom header/footer, and code between passes, is sent by LaserGRBL to the engrave at the act of start job (header), between each passes (passes), and after the last pass (footer).

If you put this code into export, when you reload the exported file in LaserGRBL you can't distinguish them from the rest of GCode, so they will be repeated twice (and worse, between each pass). 

Furthermore, the changes you make to the header / footer configuration would no longer apply to the files you exported (because they now have that information inside them).

For all these reasons I am convinced that it is not right to export these lines to the saved file.
