### ISSUE TITLE
Red safety glasses vs red Gcode tracing

### ISSUE THREAD

**Issue by brakthehun** [arkypita/LaserGRBL#79]
Sometimes I like to be safe and wear the red safety lasses. It makes seeing the red outlines of the Gcode paths difficult.

**Comment by arkypita** [comment]
I have a blue laser, so I have developed the UI to be readable by me. However I understand your (and other users) problems.

Maybe in a future version I could add some kind of color scheme or color customization.
Thanks for suggestion

**Comment by arkypita** [comment]
added in v2.8.0
