### ISSUE TITLE
Help Needed compiling Lasergrbl

### ISSUE THREAD

**Issue by sinfocomp** [arkypita/LaserGRBL#793]
Is there tutorial on how to compile?, i tried doenloading the open source compiler on the readme (since microsofts is not free) and sends me to a git hub page with diferent projects
cane some one please point me on the right direction ?
Thanks

**Comment by arkypita** [comment]
You can use visual studio community. It's free.
https://www.quora.com/What-version-of-Visual-Studio-is-free

**Comment by sinfocomp** [comment]
Downloading, Thanks,
will try to compile original code and then close this if sucsessfull
Again, Thanks

**Comment by arkypita** [comment]
you are welcome
