### ISSUE TITLE
Communicating with ESP32 running GRBL

### ISSUE THREAD

**Issue by brakthehun** [arkypita/LaserGRBL#795]
I've had several issues communicating with an ESP32 running GRBL using LaserGRBL.

It seems -
When bluetooth is active - LaserGRBL seems to take a "BT echo" as a response during Gcode streaming.
LaserGRBL Randomly disconnects while idle or streaming. UGS and Bcnc do not disconnect.
I no longer see a verbose mode.

**Comment by arkypita** [comment]
There is a command line that activate a logging of any tx/rx and communication event.

Get some log and we can try to understand

https://github.com/arkypita/LaserGRBL/search?q=is%3Aissue+comlog&type=Issues

In this

**Comment by brakthehun** [comment]
[sessionlog.txt](https://github.com/arkypita/LaserGRBL/files/3907806/sessionlog.txt)
![2019-11-30 19_53_28-LaserGRBL v3 0 19](https://user-images.githubusercontent.com/16564592/69909181-0193fd80-13ac-11ea-9cb6-d7c4ebb6b89c.png)
![2019-11-30 19_53_49-LaserGRBL v3 0 19](https://user-images.githubusercontent.com/16564592/69909182-05278480-13ac-11ea-8008-fdc3b4756940.png)
![2019-11-30 19_55_49-LaserGRBL v3 0 19](https://user-images.githubusercontent.com/16564592/69909184-0789de80-13ac-11ea-9770-ced48866e60b.png)
![2019-11-30 19_58_57-LaserGRBL v3 0 19](https://user-images.githubusercontent.com/16564592/69909185-0a84cf00-13ac-11ea-9462-d7b1cffbb0b3.png)

**Comment by arkypita** [comment]
comlog.txt is more interesting that sessionlog.txt
try get it using indication you can find in threads i link you: https://github.com/arkypita/LaserGRBL/search?q=is%3Aissue+comlog&type=Issues

UnexpectedDisconnect is generated when LaserGRBL is reading from COM port and the read fails, not because there is no data but because the COM port is not in a readable state (usually because it was closed by the OS).

I have no specific log on it, but if needed I can add more logging in the two points where this error is throw, and give you a test version.

What I can suggest is to try to set "Syncronous" in streaming mode, and "Quiet" in threading mode.

**Comment by arkypita** [comment]
latest pre-release allow to enable com logging via "?" menu option
https://github.com/arkypita/LaserGRBL/releases/tag/v3.0.24

**Comment by brakthehun** [comment]
[comlog.txt](https://github.com/arkypita/LaserGRBL/files/3920673/comlog.txt)
[ExtendedLog.txt](https://github.com/arkypita/LaserGRBL/files/3920674/ExtendedLog.txt)

**Comment by arkypita** [comment]
Unfortunately I can't detect useful information from the log to understand the problem you're highlighting.

> What I can suggest is to try to set "Syncronous" in streaming mode, and "Quiet" in threading mode.

No changes with this settings?
Have you ever had the chance to try a different PC?

**Comment by arkypita** [comment]
If you want you can follow this instruction to record a log using a third-part com logger:
https://github.com/arkypita/LaserGRBL/issues/715#issuecomment-563354745

I can try to find the difference that make UGS not sensible to this issue.

**Comment by arkypita** [comment]
Hi @brakthehun 
Did you fix this issue by yourself? Let me know

**Comment by brakthehun** [comment]
The ESP32 UNO package doesn't crash with your program,, but the standard ESP32 package does. You can close this down. There is still more to figure out.
