### ISSUE TITLE
Layers not overlapping

### ISSUE THREAD

**Issue by alvarobeiste** [arkypita/LaserGRBL#798]
Hello, I'm trying out my laser engraver for the first time and I'm having some trouble with multiple passes not being aligned. The first pass turns out great, but the second one starts in some random place not over the previous one. What could be the cause for this problem? Attached is a picture of the Twitter logo, perfect on the first layer but starting wrongly on the wing zone during the second layer.
![IMG_20191206_182136](https://user-images.githubusercontent.com/16530003/70347740-7a3e0280-1861-11ea-95ce-d1bcd5316a71.jpg)

**Comment by arkypita** [comment]
Try to set a lower acceleration and max speed in your grbl config, and tight your belt if loose
