### ISSUE TITLE
8mm offset on x axis after homing problem 

### ISSUE THREAD

**Issue by armature81** [arkypita/LaserGRBL#799]
Hi
I have problem on machine homing 
I download latest grbl v1.1h.20190825
When i make homing for the machine and start my work From zero i found there is x axis offset about 8mm
Look at the picture please for machine Coordinate after homing you can see this -8 on X axis 
So please any idea how to remove this offset?
![0C3FBAE6-0AF1-4CD8-A10A-C7118576D664](https://user-images.githubusercontent.com/25241556/70379862-81d5d800-1943-11ea-9edc-a2c2263c4df6.jpeg)
![Uploading B37912FB-72F0-48F2-A63F-F2C934640755.jpeg…]()

**Comment by StuartB4** [comment]
Have you checked $27 in GRBL config settings on the Grbl menu.

**Comment by armature81** [comment]
But $27 will be applied on all axis not only x
Also pull off working good 
But this 8mm shift once start engraving

**Comment by StuartB4** [comment]
Have you tried it with Hard Limits off. $21=0
