### ISSUE TITLE
cutting offtop

### ISSUE THREAD

**Issue by Rost3** [arkypita/LaserGRBL#8]
what program you use to cutting plywood/cardboard. i have dxf but cant create g code. i want to cutting box.

**Comment by arkypita** [comment]
LaserGRBL does not import dxf (not yet) and this is an offtopic question.
However when I had to make cuts, I made drawings with inkscape and I exported them with one of the many inkscape plugin that generate Gcode.

Sorry can not help you more, but I had the need to cut only a couple of times.
