### ISSUE TITLE
DXF IMPORT , FILL AND RESIZING

### ISSUE THREAD

**Issue by filiqqo** [arkypita/LaserGRBL#800]
Ciao, avevo chiesto tempo fa se era possibile implementare l'importazione dei DXF con la relativa funzione di resizin e riempimente ... volevo solo sapere se ci stai lavorando o se sei ancora in alto mare ... Grazie

**Comment by arkypita** [comment]
la seconda, non ho molto tempo da dedicare al progetto e faccio fatica anche solo a rispondere alle richieste di aiuto. è nella development roadmap per quando riuscirò a metterci la testa #64
