### ISSUE TITLE
svg import positions misaligned

### ISSUE THREAD

**Issue by Skyfulrucm** [arkypita/LaserGRBL#803]
Hi, i am facing a weird issue.
Sometimes when i fill with eggbot or creating a svg in Inkscape, the Lasergrbl Software is not importing right.

My example of today is attached. It misalign some items.

Do you have an idea what is wrong?
![svg](https://user-images.githubusercontent.com/58818284/70720656-7e03d600-1cf4-11ea-86ab-b82239d6610a.JPG)

Many thanks

Ludwig

**Comment by rsalvarez1** [comment]
I have the same problem, in my case a 4 ft x 8 ft area  is converted in a 106758 x - 208921 , if i create in the 8 x 11 inch  space, i have to move the step/mm to cut and adjust size by test

**Comment by arkypita** [comment]
Sorry for late reply. What version of Inkscape do you have?

**Comment by arkypita** [comment]
It was reported that there are issue with SVG format generated by inkscape 0.92 when SVG generated by inkscape 0.91 is always good

https://github.com/arkypita/LaserGRBL/issues/872
https://github.com/arkypita/LaserGRBL/issues/907

**Comment by Skyfulrucm** [comment]
Yes indeed, i am using version 0.92
Thanks for your reply, i will test it with version 0.91 - Hopefully i do not miss a feature :)

cheers Ludwig

**Comment by arkypita** [comment]
Unfortunately SVG support is still under development in LaserGRBL, I'm looking at if I can correct those small problems that have been reported to me. Thread about SVG continues here: https://github.com/arkypita/LaserGRBL/issues/451

**Comment by arkypita** [comment]
Do you still have the file that gave you problems? If I can zip it and pass it, I can test it.

**Comment by Skyfulrucm** [comment]
Hi, no acutal not.
I'd moved every single item a litte from its origin position and kill all groupings - Then it was working.
May this help you in finding out what happened.

cheers

Ludwig
