### ISSUE TITLE
problem with Y axis movement

### ISSUE THREAD

**Issue by tpres500** [arkypita/LaserGRBL#805]
Y axis will move same direction no matter which arrow you click in manual movement. Will go the same direction or wrong direction when G code is typed directly in. No on X axis, only Y.

**Comment by StuartB4** [comment]
You must have something wrong with your machine. It works fine when pressing the arrow keys or typing in commands. Y up arrow moves Y axis away from home and Y down arrow moves it towards home, same when typing G0 Y10 or G0 Y-10.  May be you need to invert the Y axis in GRBL configuration settings.
https://github.com/gnea/grbl/wiki/Grbl-v1.1-Configuration

**Comment by tpres500** [comment]
The jog works fine unless you have it in continuous mode. When you switch to continuous, the Y axis moves the same direction no matter which arrow you click. It always moves towards 0. And, it will not home the Y axis when in continuous mode. I have tried with 2 different computers and does the same thing with both.

**Comment by StuartB4** [comment]
It only works with grbl 1.1. and it needs to have $130, 131 and 132 in grbl configuration settings set to the actual size of the engraving area. Which version do you have ?

**Comment by tpres500** [comment]
I downloaded the latest stable version. It said "Include all changes of the last pre-release (3.0.19 to 3.0.23) plus some minor changes." I have the max area set in the config.

**Comment by StuartB4** [comment]
So you have version 1.1 of GRBL already.

**Comment by tpres500** [comment]
I don't know. I just downloaded what is at https://github.com/arkypita/LaserGRBL/releases/tag/v3.0.24

**Comment by StuartB4** [comment]
Start LaserGRBL and click Connect and it will tell you here:
![opo](https://user-images.githubusercontent.com/16980026/70873650-900c9f80-1fa6-11ea-8479-8cc2f06f08e9.jpg)

**Comment by arkypita** [comment]
Are you sure that it's not an electrical problem?

Y direction is outputed by arduino pin 6

![image](https://user-images.githubusercontent.com/8782035/70900062-4cdb1c80-1ff8-11ea-9c80-43241cf94f07.png)

This pin goes to motor driver pin "DIR" throug the pcb that connect arduino to the motor driver. The motor driver generate pulses to control the motor, in accord to direction/step

![image](https://user-images.githubusercontent.com/8782035/70900546-5add6d00-1ff9-11ea-945d-b39b4c056f75.png)

Maybe you can have:
- a death arduino pin
- a shortcut on the pcb path
- an interrupted pcb path
- a death motor driver

Did you have a multimeter? Have you already tested this part?

**Comment by arkypita** [comment]
If your board use arduino nano those are the connections:

![image](https://user-images.githubusercontent.com/8782035/70900999-39c94c00-1ffa-11ea-96b7-75b6a246db6c.png)

**Comment by tpres500** [comment]
I do have 1.1. I actually cut parts with the software last night so everything worked fine doing that. I did more experimenting today and the Y axis did not act up. I switched it back and forth from incremental to continuous and it worked as it should. However, I swear that it did not in previous testing. As I stated, it would go the same direction no matter which arrow you clicked. The position display showed it going the same direction as well. It wasn't like the software was telling it do one thing and the machine was doing something else. The machine was doing what the software was telling it to. Sorry for the bringing this up in the beginning but it did do as I said and for whatever reason it doesn't do it now. Thanks for the replies.

**Comment by StuartB4** [comment]
Ok, that's good. No problem. :+1:

**Comment by arkypita** [comment]
Ok, so it looks like it solved by itself? If it happens again you may make a short video that takes up the whole LaserGRBL screen while the system behaves this way.

I'm curious to see what commands generate LaserGRBL for jogging, and how grbl responds with positions and movements.

I want to understand if it is LaserGRBL that generates the wrong commands, or if it is grbl that executes them wrong.

**Comment by arkypita** [comment]
Please note that continuous jog need to know the exact size of table to produce the correct jog commands.

LaserGRBL can read this info only if you edit/show them from "grbl - > grbl configuration" menu. Maybe you have simply opened the window and LaserGRBL read that values from the machine for the first time? Engraver need to be in "idle" state for LaserGRBL to be able to read that values.

**Comment by tpres500** [comment]
I put in 4000 mm for each axis for max travel for soft limits even though the machine has a larger area than that. In testing I was making smaller items so I didn't care if it knew the full extents of the machine nor could I see a reason that it needed to know a long as I wasn't exceeding them during program execution. I will put in the actual max readings when I get a chance to jog it to those limits. Since I have just gotten the steps/mm adjusted so the parts are the proper size, I can now jog the machine from 0,0 to the max and know what the limits actually are.
