### ISSUE TITLE
i start

### ISSUE THREAD

**Issue by shivahegde** [arkypita/LaserGRBL#809]
I started photoengrave, but it not engraved Dark area. Hairs and beard area not engraved and skkin area came out black some where.How tofix this?
![IMG_20191216_231051](https://user-images.githubusercontent.com/46863953/70930011-454c5f80-205a-11ea-814c-0758fb203046.jpg)

**Comment by brakthehun** [comment]
Your laser is out of focus.
Try focusing it first.
