### ISSUE TITLE
Cutting stops and restarts between each curve segment

### ISSUE THREAD

**Issue by ahndrash** [arkypita/LaserGRBL#810]
Hi! I am fairly new to the software and laser cutting, and I have a problem with creating complex, organic contours. Perhaps someone knows a solution or can point me to a useful thread in the topic.

So the thing is, I tried cutting some picture frames with sine-curve shaped edges via dxf files. First I realized that functions are exported as straight line segments. These make the cutter vibrate and it cuts the contour unevenly, as it stops at each line intersection. It is the same with spline curves (some CAD software have the option "export splines as splines to dxf"). Then I tried approximating the sine curve with circular segments, but it still stops where the curves meet.

Is there a fix for this? Can this stopping between sections be turned off, or tuned so short that it becomes practically insignificant? Or is there a  way to join segments in a way that makes cutting continuous? Is there a general solution for splines and function driven curves? ...Many downloadable contours are also composed of line segments, and I cannot use them so far, as the cutting is slow and uneven. Any fix?

I attached a curve-approximated dxf.

Thank you for reading this, and I am awaiting any tips.

Thanks!

[Frame.zip](https://github.com/arkypita/LaserGRBL/files/3977921/Frame.zip)

**Comment by brakthehun** [comment]
How are you creating your G-Code??
