### ISSUE TITLE
Laser power suddenly dropped off

### ISSUE THREAD

**Issue by baselbaransi** [arkypita/LaserGRBL#814]
Hello all,
While i was using the laser to engrave a picture, the laser power suddenly dropped off and it doesn't burn the wood any more.
What is wired that in the configuration the value of the laser power didn't change.
And there is still a laser light but so weak it doesn't burn the wood.
What could possibly be the problem and how to fix it.

Please help.
Thanks in advance

**Comment by cowich** [comment]
Hallo baselbaransi,

i have the same problem, is there a solution?

**Comment by StuartB4** [comment]
When a laser diode burns out or stops lasing it usually ends up with a weak light, like an led light. 
Still showing a light but not burning.
Hard to say without knowing anything about your machine, laser, settings etc.

**Comment by baselbaransi** [comment]
Is there a way to fix it?

This is the laser

![IMG_20191125_201155](https://user-images.githubusercontent.com/57457668/71590213-44bec900-2b30-11ea-9252-9255a6347025.jpg)

**Comment by cowich** [comment]
Thanks for the answer StuartB4 - I have the  Ortur Laser Master 15 W Desktop Laser and have only been using it for 3 days - have lasered a lot and since today it has not burned anymore. the laser cannot have had its day after 3 days????

**Comment by StuartB4** [comment]
cowich, if you've only had it a few day you should contact the seller. Not much else you can do really If you've checked all the connections and everything. If it just stopped burning part way through a job then it probably is a broken laser, or a power supply fault.

**Comment by cowich** [comment]
I think so, thanks StuartB4

**Comment by baselbaransi** [comment]
Do you think that this problem is fixable at a technician?

**Comment by jnweiger** [comment]
I found this issue much later, while debugging exactly the same problem, LED presumably dead. Surprise, a replacement also did not work.

So just for the records: In our case, it was a quite profane connector issue. There is a small PCB at the left of the x-axis gantry, where one of the 4 wires goes to the end stop, and the other three continue to the LED head:

![image](https://user-images.githubusercontent.com/1108546/127756526-d1760477-e8fd-4862-af50-d4f141082eee.png)
