### ISSUE TITLE
Connect Arduino Laser Modules

### ISSUE THREAD

**Issue by fcgfilho** [arkypita/LaserGRBL#817]
How to connect these two laser modules with arduino uno through CNC Shield?

![MOD_15W](https://user-images.githubusercontent.com/33495382/71525861-7b87ab80-28b2-11ea-9366-2858f233dee5.jpeg)
![MOD_5W](https://user-images.githubusercontent.com/33495382/71525863-7dea0580-28b2-11ea-99d3-c74f8a8de475.jpeg)

**Comment by StuartB4** [comment]
Which CNC Shield?

**Comment by fcgfilho** [comment]
CNC Shield V3.

![cnc-shield-v3](https://user-images.githubusercontent.com/33495382/71547679-b73d7680-2981-11ea-9819-4ea7c5b26132.jpg)

**Comment by StuartB4** [comment]
Sorry for the delay. I can only find a board with the  2 pin connectors on each end.

But it looks like you only need to use 2 of the pins on the 3 pin connector on your board.

If you look at this picture you can see that the power for the laser goes to 12+ and - on the bottom right socket and leave the other pin disconnected. Switch the switch over to TTL.

Then connect the + on the socket above it to the Z- or Z+ on the cnc shield,  and connect the negative- from that socket to one of the ground pins in the black row of pins on the shield, all the black ones are ground. 

It does'nt matter which Z pin you use they are both connected together on the circuit underneath the board.

![eree](https://user-images.githubusercontent.com/16980026/71563356-0f5da100-2a86-11ea-9ec7-247e99fcb3b0.jpg)

**Comment by fcgfilho** [comment]
Obrigado
