### ISSUE TITLE
Connect NEJE Laser to another board

### ISSUE THREAD

**Issue by murdoc77** [arkypita/LaserGRBL#818]
Hi there!

I bought the [NEJE 20w laser ](https://de.aliexpress.com/item/4000044112876.html?spm=a2g0o.detail.1000014.29.ffd0f558ltplHT&gps-id=pcDetailBottomMoreOtherSeller&scm=1007.13338.128125.0&scm_id=1007.13338.128125.0&scm-url=1007.13338.128125.0&pvid=8e046c57-d03d-4822-bbf3-9a35296b3ef8) and would like to connect it to the [cronos maker V 3.0 board](https://de.aliexpress.com/item/32866461881.html?spm=a2g0s.imconversation.0.0.433d3e5f2NQUUu).
Can I connect it using only 3 pins leaving the temp pin empty?
thanx for any reply :)

**Comment by StuartB4** [comment]
I use mine like that, no green wire connected, works fine.
