### ISSUE TITLE
Feature request: Don't zero between multiple passes

### ISSUE THREAD

**Issue by Alexnator1989** [arkypita/LaserGRBL#819]
Dear friends,

if I import an SVG and use the multiple passes to cut it out, the laser always returns to the zero point between each pass. This wastes a lot of time on cuts with many passes (100).

It would be better if the Laser drove from the last point directly to the first point of the next run.

Cool software that I use almost every day. Thanks a lot!

**Comment by arkypita** [comment]
I agree!
