### ISSUE TITLE
Path optimization

### ISSUE THREAD

**Issue by SMG2383** [arkypita/LaserGRBL#82]
Excuse me, my English is poor，I prepared a picture
![aaa](https://user-images.githubusercontent.com/5711646/29654750-0f592f1a-88e1-11e7-86fb-95850cf6d104.jpg)
Can you increase this mode? This saves time and saves time of line scanning,
![23](https://user-images.githubusercontent.com/5711646/29656732-ec2f5e54-88e7-11e7-806a-94a9ca3f6869.jpg)

**Comment by arkypita** [comment]
Optimizing VECTOR engraving sequence is a really interesting feature. Of course, it can only be done for the gcode generated by LaserGRBL itself (vectorization of raster import) where we can have the original vector path (optimizing gcode is more complex and require rebuilding vector path). It is already in the development line, but it is a particularly complex function to develop ([but some alghorithm already exists](http://parano.github.io/GeneticAlgorithm-TSP/)).

With raster/picture/image engraving is hundred time more complex, I'm pretty sure no professional software implement that. Complex does not mean impossible, but you have to consider not only the time for develop a good alghoritm (that is my time) but also the computational time of your computer to analyze the image and compute the best path that exponentially grow with the complexity of the image.

A "follow non white" could be a good basepoint, but have to deal with "do not forget nothing" when take a direction that exclude following another direction and with "I have already done this pixel". It sound very complex and noone can finally ensure it will be faster than linear scanning.
