### ISSUE TITLE
Precision Issues + Back and Forward Path when converting to path in inkscape

### ISSUE THREAD

**Issue by Wallio007** [arkypita/LaserGRBL#822]
Hi,

First, thank you for this software :). I really enjoy using it. Maybe you can give me some informations about these issues : 

1 : Precision : when cutting a 10mm x 10mm square the cut come out at 9.5mm x 9.5mm. I'm assuming there is a value that consider the laser "diameter". Is there a way to modify this value like a tool diameter in cnc machine ?

2 : Using Inkscape I often use the tool : contour to path. When uploading the .svg file to LaserGRBL, the Gcode created run automatically twice the path, back and forward.

Thanks for your answer.

**Comment by arkypita** [comment]
1) no, it is not implemented in LaserGRBL

2) it is absolutly normal since "contour to path" produce intenal and external path, as you can see if you switch to path modify tool (F2).

![image](https://user-images.githubusercontent.com/8782035/73184301-82f1dd00-411c-11ea-9ff6-66f8191664c2.png)
