### ISSUE TITLE
crop button

### ISSUE THREAD

**Issue by bkrusen1** [arkypita/LaserGRBL#826]
can someone explain how to crop an image? I dont think the button works

**Comment by StuartB4** [comment]
It does work but you have to be really close to the outside edge of the image you are cropping.

![Untitled3](https://user-images.githubusercontent.com/16980026/71673139-d6684980-2d6f-11ea-8ac4-723ddf08b800.jpg)

![Untitled4](https://user-images.githubusercontent.com/16980026/71673147-d9fbd080-2d6f-11ea-9ff1-a39ee7cb0105.jpg)

**Comment by bkrusen1** [comment]
Ty
