### ISSUE TITLE
Add Chinese

### ISSUE THREAD

**Issue by SMG2383** [arkypita/LaserGRBL#83]
https://github.com/SMG2383/CHINESE

Please reply me after downloading, and I will delete this file

**Comment by arkypita** [comment]
downloaded, thank for your translation

**Comment by arkypita** [comment]
Can i know your name for greetings, credits and contribution?

**Comment by SMG2383** [comment]
Hello,Nice to meet you.  my name is Yang Haiqiang. I like your software very much. I also like all kinds of machines, but I can't program it. Thank you very much for your contribution. Thank you very much

**Comment by arkypita** [comment]
added in v2.8.0
