### ISSUE TITLE
Engraving on shinny surfaces

### ISSUE THREAD

**Issue by Travismorrey** [arkypita/LaserGRBL#832]
I would like to know if it is possible to engrave or cut on surfaces such as thin sheet aluminium.

**Comment by arkypita** [comment]
LaserGRBL is a generic software that can be used on a wide variety of hardware.
The ability to mark / cut different types of material depends on your laser, not by LaserGRBL.

As a reference, a 40-W laser can cut through paper, cardboard plywood, foam, and thin plastic, while a 300-W laser can cut through thin steel and thicker plastic. If you wish to cut through 2-mm or thicker steel sheets, you’ll need at least 500 W.

Small power laser (1-10W) cannot engrave or cut metals.
