### ISSUE TITLE
Feature: Remember window size and position.

### ISSUE THREAD

**Issue by StuartB4** [arkypita/LaserGRBL#84]
Just wondered if it would be possible to add a feature that allows LaserGRBL to remember window size and screen position. After resizing the main window and moving it to where I want and then restarting again, LaserGRBL always opens at full screen. 
Just a thought.

**Comment by arkypita** [comment]
yes, possible and easy
i am just doing it in a lot of program i have developed for work :-)

**Comment by StuartB4** [comment]
Ok. It would be nice to be able to have the main window a certain size and position, so I can keep an eye on the progress while doing other things on the pc.

**Comment by arkypita** [comment]
added in v2.8.0
