### ISSUE TITLE
LaserGRBL software cannot read text in SVG file when reading SVG file

### ISSUE THREAD

**Issue by lianzaozi** [arkypita/LaserGRBL#843]
LaserGRBL software cannot read text in SVG file when reading SVG file

LaserGRBL software
![1](https://user-images.githubusercontent.com/53146195/72338136-cdc42b80-36fe-11ea-806c-18aa292ad11a.jpg)

Inkscape software
![2](https://user-images.githubusercontent.com/53146195/72338173-e16f9200-36fe-11ea-82f3-334fac97dc4b.jpg)

**Comment by StuartB4** [comment]
Highlight all objects and click Group on the Object menu. Then click Object to path on the Path menu then save svg.

**Comment by arkypita** [comment]
> LaserGRBL software cannot read text in SVG file when reading SVG file

Yes, it cannot. Not so easy to implement since "text" is not saved as path in SVG but as text+font+size info, so it is difficult to import.

Just follow @StuartB4 hint to transform "object to path" and then save SVG that now contains path instead of text.

**Comment by jomo487** [comment]
This subject would be a great addition to FAQ
