### ISSUE TITLE
RUIDA

### ISSUE THREAD

**Issue by sanyats** [arkypita/LaserGRBL#845]
Привет. можно ли сделать управление логикой лазера как в RUIDA?
Hey. Is it possible to do laser logic control like in RUIDA?

при выжигании линиями, чтоб выходил на белое поле и там отключал лазер. выходит так, что при остановке в крайней точке - сильно прожигает края.

**Comment by arkypita** [comment]
I don't know RUIDA

GRBL use M4 mode to prevent dark edges on directional change. You need grbl v1.1 and laser mode enabled: https://github.com/gnea/grbl/wiki/Grbl-v1.1-Laser-Mode

**Comment by sanyats** [comment]
Спасибо. все хорошо
