### ISSUE TITLE
Problems with no PWM while burning photos

### ISSUE THREAD

**Issue by davidkstyler** [arkypita/LaserGRBL#847]
I am trying to burn photos with Laser GRBL and a SainSmart 5.5W Laser on a 3018Pro CNC.
I am producing code but the laser is only ON or OFF. I watch the code go by and those are the only "S" values that I see (S0,S255). How do I make LaserGRBL produce PWM code?
I am importing the color photo into InkScape, sizing it, making it B&W and then exporting a PNG file that I import into LaserGRBL. I am using Line to Line Tracing as the coding method.
Any suggestions would be appreciated!

**Comment by StuartB4** [comment]
Make sure you have $32 set to 1 and $30 set to 255 in Grbl Configurations settings.
You can just load you image in to LaserGRBL. Set the brightness and contrast select Line to Line and how many lines you want, more lines=higher quality but slower.
Also in Target Images settings select M4 from the dropdown menu in the Laser options section.
