### ISSUE TITLE
Add text editor

### ISSUE THREAD

**Issue by SMG2383** [arkypita/LaserGRBL#85]
can You  add text editing and pencil、Eraser、multiple picture merge?
![123](https://user-images.githubusercontent.com/5711646/29766231-a79960e2-8c10-11e7-9bf8-9210d32de8d5.jpg)

**Comment by arkypita** [comment]
Texting, multiple image merge etc, would also require managing placement and alignment  (accurate, not just approximate).

If I add the ability to enter text then why not lines, circles, rectangles, arrows, and shapes? Adding similar functionality would require to implement a real graphic editor into LaserGRBL, and it is not a feature I intend to add, for now.
