### ISSUE TITLE
Custom On/Off stopped working

### ISSUE THREAD

**Issue by wmadkins23** [arkypita/LaserGRBL#869]
I created the custom button Laser on/off
M3 S30            M5
Always on

Worked for a few days then stopped working. I did change $32 laser mode =1 
Did not make any other changes?  Anything else I need to look at. This is an important button to focus my laser (15w) before starting a project.

**Comment by StuartB4** [comment]
This is my button to switch laser on low power for focussing.
It also moves the laser away from home 50 mm's first.
Then returns home afterwards.
Just makes it easier for me to get to the focus ring.

Button type: TwoStateButton

Gcode box 1

$32=0
G0 X50 Y50
M4 S3

Gcode box 2

$32=1
M5
G0 X0 Y0

**Comment by wmadkins23** [comment]
I will try it thx

**Comment by wmadkins23** [comment]
It works. Thanks

**Comment by StuartB4** [comment]
Ok. Thanks for letting me know. :+1:
