### ISSUE TITLE
Positioning of imported SVG files

### ISSUE THREAD

**Issue by Shroomo** [arkypita/LaserGRBL#872]
Hi guys. I'm pretty new to this world, learning as I go. I've had no issues with Raster importing, the image always lines up with the bottom left corner at 0,0. However when I import an SVG from Inkscape, LaserGRBL positions it in seemingly random places. I have checked the file on Inkscape to make sure there are no 'invisible' things off the page anywhere. I'm working on a small scale and precision of the placement is crucial.

Thanks a lot. Kris

![grblscreenshot1](https://user-images.githubusercontent.com/60618929/73672389-abda1b00-46a4-11ea-9927-4396cfcb68e4.jpg)

(Second link to same image) https://drive.google.com/open?id=1cZNQxO0Y72RsT8-OoNWmkRdoBxiKSdzW

**Comment by arkypita** [comment]
link to the svg file?

**Comment by Shroomo** [comment]
Sorry, here
[Pent with vines.zip](https://github.com/arkypita/LaserGRBL/files/4149026/Pent.with.vines.zip)

**Comment by arkypita** [comment]
Loading your file does the same to me.

I simply create a new file (default A4 file with unit in mm), copied your artwork (selecting with mouse, ctrl-c) pasted to this new file (ctrl-v), aligned to page margin bottom-left and saved.

Now LaserGRBL load it correctly.
Also if I resize page to 7x74 it load correctly.

Try yourself and let me know.

Don't know why. Something in original file?

**Comment by Shroomo** [comment]
I followed those steps and it did load up in lasergrbl fine. I tried the same with a different design (same size) but it didn't work. It must mean it's a problem with my use of Inkscape rather than a Lasergrbl issue. I'll keep trying and maybe ask on an Inkscape forum!
Thanks a lot for your quick help. And thanks for a nice piece of software which makes it easy for noobs like me to get creating. Cheers, Kris

**Comment by arkypita** [comment]
I do not know. Unfortunately I didn't write the part of the code that imports the SVG (I used a third part code) and I don't have any knowledge of how SVG encoding works, to get my hands on that code.

The only things I know is that SVG has a lot of variations in its format.

**Comment by StuartB4** [comment]
This might help. Just been playing with Inkscape.

I started with an A4 size document, added a few shapes and some text and saved it as a .svg file.
When I load it in to LaserGRBL I get this, which is what usually happens with SVG files.

![ioioioioio1](https://user-images.githubusercontent.com/16980026/73703398-a225d700-46e7-11ea-8fb0-229de98057aa.jpg)

The I looked at the document properties in Inkscape and found this.

![ioioioioio13](https://user-images.githubusercontent.com/16980026/73703427-b8339780-46e7-11ea-84c2-df6778c53d13.jpg)

Clicking on the "+" sign I get this.

![ioioioioio14](https://user-images.githubusercontent.com/16980026/73703448-ca153a80-46e7-11ea-9da1-83331d815c57.jpg)

Clicking on it I get this.

![image](https://user-images.githubusercontent.com/16980026/73703492-fa5cd900-46e7-11ea-8710-c8087d4bb918.png)

After saving the file again and loading in to LaserGRBL I get this without the X and Y Offsets.

![ioioioioio17](https://user-images.githubusercontent.com/16980026/73703610-62132400-46e8-11ea-8a95-b3d36a835393.jpg)

You could start off with any size document and resize it this way so it makes the document just the size you want upto the edges of the objects in it. Then use the Margin adjusters to give an offset for X and Y if you need it.

![ioioioioio18](https://user-images.githubusercontent.com/16980026/73704310-82dc7900-46ea-11ea-8ffe-fbb43336a8cf.jpg)

Like this.
![ioioioioio19](https://user-images.githubusercontent.com/16980026/73704354-b0292700-46ea-11ea-85b3-d246cb42d7d2.jpg)

**Comment by Shroomo** [comment]
Hi StuartB4, Thanks for your help and suggestion. I tried following your steps but it didn't work for me. LaserGRBL still positions it at -290, 224. 
![grblscreenshot2](https://user-images.githubusercontent.com/60618929/73785648-98f04500-478f-11ea-8e9b-b047026dbf12.jpg)

For now I think I'll export the images as PNG and use LaserGRBL to produce a vector path or Raster it.
Thank you

**Comment by StuartB4** [comment]
Just tried it with your file and it works. 
I loaded the file. Clicked Document properties on the file menu.
Clicked the + sign and then the Resize page to drawing or selection button.
Select all the objects and group them with Group on the Object menu, then Object to path on the Path menu.
Then save as a .svg file and load in to LaserGRBL.

![kjkjhd](https://user-images.githubusercontent.com/16980026/73792719-c98aab80-479c-11ea-8367-b44ed3b89d2f.jpg)

**Comment by arkypita** [comment]
Hi @StuartB4 
I follow your procedure step by step and does not work for me too.
Inkscape 0.92.3 (2405546, 2018-03-11)

**Comment by arkypita** [comment]
Only copy and paste to a new document works for me.

**Comment by StuartB4** [comment]
Strange. 
I'm using version 0.91 but I would think it should work in different versions.

**Comment by StuartB4** [comment]
Just uploaded a video of how I do it.
https://youtu.be/nYyP6aLuMZY

**Comment by arkypita** [comment]
https://youtu.be/AbWwn41vpVU

**Comment by StuartB4** [comment]
Wow, that is really weird. 
I wonder if it's anything to do with Windows 10, I use 7 Pro,  or the version of inkscape.

**Comment by StuartB4** [comment]
I just installed inkscape 0.92  and it's doing the same as it is for you. Not working.
Tried with 0.91 again and it works.
Need to find the difference in the 2 inkscape versions.

**Comment by Shroomo** [comment]
After watching a few Inkscape tutorials and reading comments, it seems there are a few issues/bugs with Inkscape .92. So I've installed .91 and now positioning is working fine.
Thank you StuartB4 for your investigations. Hopefully the Inkscape devs will get this sorted soon.
Thanks guys :)

**Comment by StuartB4** [comment]
Thats good. Glad you got it sorted. :+1:
