### ISSUE TITLE
Zero WCO not zero when resetting

### ISSUE THREAD

**Issue by cristianodems** [arkypita/LaserGRBL#876]
I started to realize that when resetting Zero not zero when, it always stays at X: 40.353 Y: -6.647 Z: 0.024
When I start work without a problem, but when I reset or stop during work, I lose the start position and the job.
![ScreenShot1031](https://user-images.githubusercontent.com/21195918/74387164-91a3e980-4dd6-11ea-821b-0d0758084033.jpg)

**Comment by arkypita** [comment]
WCO it is maintained by the hardware, so if you send a reset it is lost.

**Comment by cristianodems** [comment]
![ScreenShot1036](https://user-images.githubusercontent.com/21195918/74605106-74576f80-50a3-11ea-83f4-c5d6da6d9c50.jpg)

Conseguimos!!!
O G10 L20 P1 X0 Y0 Z0 muda o Wco para Wco X0 Y0 Z0.
basta run code after homing, hard reset arduino, run G10 L20 P1 X0 Y0 Z0 muda o Wco para Wco X0 Y0 Z0, restart LaserGrbl.
Muito obrigado!!!

**Comment by cristianodems** [comment]
Solution working
