### ISSUE TITLE
Ritaglio immagine con rapporto

### ISSUE THREAD

**Issue by distebia** [arkypita/LaserGRBL#884]
Salve, ultimamente lavoro pezzi di vetro anneriti con dello spray, importo l'immagine e inverto i colori.
fin qua tutto ok, solo che ho pezzi di vetro di misure diverse, tipo 95x155 oppure 96x160 ecc.. Il procedimento richiede l'annerimento della superficie, l'inversione dei colori e l'incisione. E' possibile importare l'immagine e ritagliare la foto con un rettangolo proporzionato alle dimensioni del vetro? esempio, misuro il vetro e ricavo 95x155, creo un rettangolo proporzionato a 95x155, lo trascino sulla foto e ritaglio? Grazie

**Comment by arkypita** [comment]
No, non è possibile.
Devi preparare le jpg delle giuste misure con un programma esterno (con paint, photoshop o altro sw).
