### ISSUE TITLE
Hobbiest Using a 3dprinter (powertoggle "M106 S0-255,M107")

### ISSUE THREAD

**Issue by sasaa86** [arkypita/LaserGRBL#888]
First of all I really like the software and love the neat and simple yet powerfull features.
I would like to request for the hobbiests like me.
A option to turn the laser on with the "M106 S0-255" command and off with the "M107" command.

I'm using a Cr-10 s4 with the laser connected to a extra fan header that is supposed to be the part cooling fan.
I have tried editing a .cn file to reflect my needs but it was a pain in the butt. (output was nice though)

the software that i used before did not support grayscaling and are To simple to be affective.

greets sasaa

**Comment by arkypita** [comment]
this was asked lot of time and the feature is already in development roadmap #64
