### ISSUE TITLE
Feature Suggestion: Image centering

### ISSUE THREAD

**Issue by bearded1der** [arkypita/LaserGRBL#90]
I have another feature suggestion for you. I spend a lot of time trying to center images, but since width/height inputs only take whole numbers, it can take quite a bit of time adjusting the size and offset (and often still need to adjust the GRBL machine offset to compensate) to get a perfectly centered image.

I'd suggest a checkbox option in image setup to select from either offsetting corner of image (as is current) to aligning center of image (whatever the size) to the specified coordinate. Anything that needs to be centered on an object will require significantly less work to get it aligned.

Again, thanks for all your hard work!
Jake

**Comment by arkypita** [comment]
I think about
