### ISSUE TITLE
vg-l7 and laserGRBL

### ISSUE THREAD

**Issue by domcrat** [arkypita/LaserGRBL#901]
Good afternoon. The problem lies in the incorrect operation of the engraver in the laserGRBl program. When engraving a photo, I can 't choose M4, I only always have M3. The command $32=1, it accepts if it is registered. But M4 does not appear. maybe you know what's going on . I attach a photo of the module. SWLD 59 V3.5 processor. It connects via a 3 pin wire, but there is a free 2 pin hole on the Board . maybe you know what it is for and you need to connect it ? I must say that the laser power is currently regulated.
![IMG_20200229_112542](https://user-images.githubusercontent.com/60337554/75853815-e4822700-5dff-11ea-99c4-4c435eb76add.jpg)
![Uploading IMG_20200229_112255.jpg…]()

**Comment by arkypita** [comment]
What version of grbl do you have? it should tell you here when you start LaserGRBL and click connect.
![opo](https://user-images.githubusercontent.com/16980026/70243394-682d6880-176a-11ea-8204-5ebfa2407e77.jpg)

**Comment by domcrat** [comment]
My version 1.1f is $30=255, when I turn on the program, I always have $32=0, I constantly change it to $32=1, the program writes OK, but M4 does not appear in the list that I did not do.

**Comment by domcrat** [comment]
check the box for PWM support. What is the probability that this is due to the 2 pin connector? can this be? the instructions about this do not say anything, maybe you know based on this processor

**Comment by arkypita** [comment]
To see M4 you need GRBL version >= 1.1 with laser mode enabled ($32=1)
No other information is known by LaserGRBL about your hardware.

> when I turn on the program, I always have $32=0

I have a vague recollection that someone has already reported a similar problem, but I can't find the post. If I remember correctly he had solved by rewriting the GRBL firmware on his controller board.

Just to be sure, do this test and let me know.

1) connect lasergrbl to the board and you put in idle state
![image](https://user-images.githubusercontent.com/8782035/75886425-7aca4300-5e28-11ea-8757-f706e5d2ece7.png)

2) Open the grbl configuration window, be sure that it show "34 config readed succesfully" when it open.
![image](https://user-images.githubusercontent.com/8782035/75886562-b6fda380-5e28-11ea-9c7d-15a881fee037.png)

- Tell me the value of $32.
- If the value is zero, set it to 1 and push "Write" button.
- Push "Refresh" button and check if is correctly set to 1 or not.
- If is correctly set to 1 please close the grbl config window, disconnect, and close LaserGRBL.
- Re-open LaserGRBL and connect (idle)
- Open grbl configuration (34 config readed succesfully) and check if the $32 is 1 again or not.

Let me know.

**Comment by domcrat** [comment]
Good day arkypita. I tried to change the version on your recommendation. 1.1f to 1.1h
![IMG_20200304_220720](https://user-images.githubusercontent.com/60337554/75949719-2c648500-5eb8-11ea-8dc3-ca38e40ca64b.jpg)
![IMG_20200304_220733](https://user-images.githubusercontent.com/60337554/75949724-2ec6df00-5eb8-11ea-807b-1624c8b6cb23.jpg)
![IMG_20200304_220745](https://user-images.githubusercontent.com/60337554/75949741-38504700-5eb8-11ea-96c2-b79ed5fb61fd.jpg)


. as a result, after driving in 32=1, and manipulations that you recommended, the setting was saved and M4 appeared. Thank you for your help.
![Uploading IMG_20200304_220901.jpg…]()

**Comment by arkypita** [comment]
You are welcome
