### ISSUE TITLE
I need hex 0.9i for laser

### ISSUE THREAD

**Issue by juansr87** [arkypita/LaserGRBL#902]
Someone who can pass me the grbl 0.9i I can't find it anywhere help

**Comment by arkypita** [comment]
Is available on the old grbl site https://github.com/grbl/grbl
Scroll down the page, section Archive, right click, save-as.

**Comment by arkypita** [comment]
NB: 0.9i is an old version. I suggest version 1.1h for better laser support.
You can flash it directly from LaserGRBL UI, or download from here: https://github.com/gnea/grbl/releases

**Comment by juansr87** [comment]
Thank you 👍
