### ISSUE TITLE
Cannot conect using New cpu

### ISSUE THREAD

**Issue by sinfocomp** [arkypita/LaserGRBL#906]
I have uograded motherboard, installed win 10 all drivers OK however I cannot conect, port is detecte but closes after a few seconds, tried installing win se en and have same problem

**Comment by arkypita** [comment]
Try change hard/soft reset setting, some serial port need to be reset on connect

![image](https://user-images.githubusercontent.com/8782035/76263647-ad789f00-625f-11ea-82e6-6937751bfe8a.png)

**Comment by arkypita** [comment]
if not work try change ultrafast to slow or normal

**Comment by sinfocomp** [comment]
Worked on slow, thanks
