### ISSUE TITLE
SVG files does not appear to be imported/created correctly

### ISSUE THREAD

**Issue by Ziggy2013** [arkypita/LaserGRBL#907]
SVG file does not appear to import correctly.

The file is for a solder paste stencil. The svg file displays properly in Inkscape but does not display properly in LaserGRBL.  A few of the solder pads are not in the correct place and appear to be mirrored around an arbitary XY axis. 

SVG file attached - renamed to *.txt as svg files are not accepted

[PC_wifi_19_brd_mod.txt](https://github.com/arkypita/LaserGRBL/files/4309814/PC_wifi_19_brd_mod.txt)

**Comment by Ziggy2013** [comment]
LaserGRBL Version is 3.1.2

**Comment by arkypita** [comment]
See if this can help you: https://github.com/arkypita/LaserGRBL/issues/872

**Comment by gmmanonymus111** [comment]
I've played around with Inkscape (v0.92.4) and it seems rotating an object makes its position messed up.
Before rotating:
![inkscape_bug](https://user-images.githubusercontent.com/9658243/76432525-64d1fa80-63b3-11ea-95e7-c2f20728b49c.png)
After rotating:
![inkscape_bug2](https://user-images.githubusercontent.com/9658243/76432577-77e4ca80-63b3-11ea-83ac-58f0d3e77738.png)

With v0.91, it seems to be working correctly.

**Comment by Ziggy2013** [comment]
Thanks gmmanonymus111 for following up.
Resizing an object also causes Inkscape v0.92.4 svg files not to import correctly into LaserGRBL.
I have resorted to editing the svg file XML statements directly so the LaserGRBL import works.
At this point I haven't identified what Inkscape generated XML construct causes the LaserGRBL import issue.

**Comment by arkypita** [comment]
very nice color scheme

**Comment by Ziggy2013** [comment]
I believe the root cause of LaserGRBL not importing the Inkscape svg files correctly is that Inkscape v0.92.4 uses an XML syntax which combines both translation and rotation.

if the XML syntax is separated into a translation and a rotation step (eg like this)

 transform="translate(22.387291,-39.921669) rotate(-270.000000)"

LaserGRBL imports correctly.

However in Inkscape v0.92.4 the translation and rotation are combined (eg like this)

     transform="rotate(90, 31.15448, -8.767189)"
  
LaserGRBL does not appear to handle this syntax correctly.

By directly editing the Inkscape v0.92.4 svg to separate the translate and rotate steps LaserGRBL will import correctly.

Happy for anyone else to confirm I'm right or prove me wrong. For example, I suspect that Inkscape 0.91 does not use the combined XML construct but I haven't checked

**Comment by Ziggy2013** [comment]
I have since realised that an example like

transform="rotate(90, 31.15448, -8.767189)"

is not combined rotation and translation. It is specifying rotation about a point. A good reference is here

http://tutorials.jenkov.com/svg/svg-transformation.html#translate

But the issue still is that LaserGRBL does not appear to import this XML syntax correctly.

**Comment by arkypita** [comment]
Thanks @Ziggy2013 for your analysis about rotation
I will try to see if I can correct this issue.

**Comment by arkypita** [comment]
I close, let's continue this topic in the general issue on SVG support #451
