### ISSUE TITLE
Software wont open

### ISSUE THREAD

**Issue by mommameg970** [arkypita/LaserGRBL#914]
I am new to this and i had my laser working just fine last night.
I was changing some settings and something in the global configuration got changed and i got a pop up saying if i quit it will close if i hit continue it will attempt to continue, well i hit quit and the program shit down and i have not been able to get it to start back up.  Is there a way to completely reset the laser or anything?
I have troubleshot with Microsoft and installed and uninstalled as many times as i can and i jeep having the same problem except it wont even open at all after i reinstall.
Any ideas, i am in need of major help.
Thank you

**Comment by arkypita** [comment]
did you have any message talking about LaserGRBL in windows event log? (press start menu and type event, then open event viewer

![image](https://user-images.githubusercontent.com/8782035/76649684-78bb5f00-6561-11ea-8320-4af4d87a84af.png)

I had something similar just today, solved simply rebooting windows and apply last windows update. I thin i had an update in progress that broke .net framework, something microsoft related

**Comment by arkypita** [comment]
I had messages like this in my event log

![image](https://user-images.githubusercontent.com/8782035/76650041-1b73dd80-6562-11ea-8e68-2c4a7c18a1a3.png)

**Comment by arkypita** [comment]
If you need to remove LaserGRBL you can delete the folder: 
- C:\Users\Your User Name\AppData\Roaming\LaserGRBL
- C:\Program Files (x86)\LaserGRBL

**Comment by mommameg970** [comment]
![image](https://user-images.githubusercontent.com/62154774/76654565-3f6ef900-6539-11ea-95fa-f174ac24f340.png)

**Comment by mommameg970** [comment]
![image](https://user-images.githubusercontent.com/62154774/76654680-8f4dc000-6539-11ea-811b-1beb5450422e.png)

**Comment by mommameg970** [comment]
i deleted it have not reinstalled or anything
I did look at the event log as i showed you above, but i have no idea what to do now... like i said it said something about the global configuration and then wont open at all...

**Comment by mommameg970** [comment]
Ok, so i got it to open in LaserWeb but i am getting a warning saying Gcode is out of machine bounds, can lead to running work hault... i assume this is why i cannot get it to open in LASERGRBL, anyone have ANY idea how to fix this?
