### ISSUE TITLE
Cannot connect to device. No such host is known.

### ISSUE THREAD

**Issue by Knight7171** [arkypita/LaserGRBL#928]
Hello everyone,

I purchased a Uttiny 6550 CNC laser engraver kit 10W on Amazon.
[https://www.amazon.com/gp/product/B0811TFNLD/ref=ppx_yo_dt_b_asin_title_o02_s00?ie=UTF8&psc=1](url)
I installed the CH340 driver and Installed the LaserGRBL software and updated it to v3.1.2. I also tested it on cardboard to make sure that everything works. And it did for almost 2 hours and now it does not. It tells my laptop (Windows 10 Pro) not connected.

Any help would be greatly appreciated.

Thank You!

![20200321_103924](https://user-images.githubusercontent.com/62468055/77229663-87a7a000-6b65-11ea-90cf-ebbf70fdea05.jpg)
[sessionlog.txt](https://github.com/arkypita/LaserGRBL/files/4363167/sessionlog.txt)
![2-axis-offline-controller-board-GRBL-USB-port-cnc-engraving-machine-control-board-for-2017-3020 jpg_q50](https://user-images.githubusercontent.com/62468055/77229675-955d2580-6b65-11ea-89be-e60acc6274fc.jpg)

**Comment by gmmanonymus111** [comment]
From the first picture, I guess you accientally set it to Telnet connection instead of USB. To change it back, click `Grbl` -> `Settings` -> `Connection protocol`
![githelp](https://user-images.githubusercontent.com/9658243/77235391-7edeba80-6bb5-11ea-88c2-68abb23e90f2.png)

**Comment by Knight7171** [comment]
Thank You gmmanonymus111. I switched it back and no errors. I am not sure how it got changed but I am very happy that it is working again. And it was a easy fix. :) I have been trying to figure this out for 2 days. Once again Thank you!
