### ISSUE TITLE
Poistion Tracking wrong after zeroing

### ISSUE THREAD

**Issue by lnxbil** [arkypita/LaserGRBL#93]
Hi,

I use your example to zeroize the x and y position. After doing that, the position of the laser on the right window is not shown correctly.

Best,
Andreas

**Comment by arkypita** [comment]
https://github.com/arkypita/LaserGRBL/issues/36

**Comment by arkypita** [comment]
[Version v2.8.12](https://github.com/arkypita/LaserGRBL/releases/tag/v2.8.12) can now show working position if different from machine position.
