### ISSUE TITLE
Jog buttons in the console pane

### ISSUE THREAD

**Issue by GrahamJB** [arkypita/LaserGRBL#934]
Every time I use a jog button I see the GCode in the console pane prefixed by $3= such as:
![image](https://user-images.githubusercontent.com/6019928/77824661-3e72c580-70fc-11ea-8313-d78f845cb96c.png)

It seems just to be the console display, they all seem to work fine!

**Comment by gmmanonymus111** [comment]
It shows `$J` and not  `$3`
`$J` means the Jog command in GRBL's language.
`$3` would set your direction mask, which will result in a messed up jogging.

**Comment by GrahamJB** [comment]
Sorry,
I think I need new glasses or a bigger monitor!
