### ISSUE TITLE
Jumping around could be minimized

### ISSUE THREAD

**Issue by lnxbil** [arkypita/LaserGRBL#94]
Hi,

This is not a bug, only some optimization request:
I noticed some jumping and therefore increased runtime (e.g. the eyes):

![jumping_around](https://user-images.githubusercontent.com/727711/30252920-23e5eac0-967b-11e7-8d24-8fd727a5f6f8.png)

I try to prevent this manually by running smaller/more local jobs. Maybe there is some way to optimize this.

**Comment by arkypita** [comment]
Path optimization [was already discussed](https://github.com/arkypita/LaserGRBL/issues/82) and added to [development roadmap](https://github.com/arkypita/LaserGRBL/issues/64).

However it is a tedious discourse, establishing a better path is not as easy as it seems.
Also conflicts with needs of who use the [laser to cut materials](https://github.com/arkypita/LaserGRBL/issues/18).

**Comment by Glasairman** [comment]
This is an Inkscape/JTech extension generated gcode file. It takes forever, does 2mm here , 2mm there  and jumps around generally like a fruit fly on ecstasy. 
Any ideas ? 
![grafik](https://github.com/user-attachments/assets/afafd22c-51b8-4833-ab97-07e0e75881cf)
