### ISSUE TITLE
Problem to import any Files

### ISSUE THREAD

**Issue by Geilergott** [arkypita/LaserGRBL#940]
Hello,
I can no longer import files correctly with the LaserGrBl V3.1.2 software. The data is only displayed as a rectangle. see photo
![IMG_1815](https://user-images.githubusercontent.com/62891634/77921978-b8dc4a80-72a0-11ea-9fb6-ddafcb81cba4.jpg)
Is anyone able to help me?

**Comment by arkypita** [comment]
adjusts the brightness and contrast
