### ISSUE TITLE
Laser on and off issue

### ISSUE THREAD

**Issue by nickm324** [arkypita/LaserGRBL#949]
I cannot get LaserGrbl to run on or off my laser. Movements controls work fine and it works fine with other laser applications like LaserWeb without issue. Where do I need to start to resolve this issue. I am running Grbl 1.1g, have laser mode set.

When sending m4 nothing happens.

**Comment by StuartB4** [comment]
Do you have PWM mode enabled in LaserGRBL settings?
![tytyty](https://user-images.githubusercontent.com/16980026/78936957-7e945980-7aa7-11ea-97dc-3e56f44760b3.jpg)

**Comment by nickm324** [comment]
Yes, it is working now. Had to send M3 then M4 a couple of times for some reason then it started working even after I had already restarted my controller a few times. Not sure what it was.

**Comment by StuartB4** [comment]
Ok Nick, that's good. :+1:
