### ISSUE TITLE
Include a Z move when using multiple passes

### ISSUE THREAD

**Issue by Grover49** [arkypita/LaserGRBL#95]
I was wondering if it would be a simple process to add a Z modifier box by the  Perform multiple passes box.

**Comment by arkypita** [comment]
Not so difficult, but not n°1 priority for me now. I'll add to development roadmap but cannot say when and if i will implement it (currently I am rewriting the whole g-code generator to be more maintainable).

**Comment by Grover49** [comment]
I completely understand, I certainly appreciate what you are doing and want to sincerely thank you for what you have done with LaserGRBL.

**Comment by mschaeck** [comment]
This would be a good feature to laser bigger parts

**Comment by arkypita** [comment]
You can test this version: https://github.com/arkypita/LaserGRBL/releases/tag/v3.0.19
Maybe custom gcode between passes can be a solution for you.
