### ISSUE TITLE
Post processor for Fusion 360

### ISSUE THREAD

**Issue by Lazzzzzzer** [arkypita/LaserGRBL#950]
Does Laser GRBL support I and J commands for curves? I cant get it to work. Is there a post processor for Fusion 360 that doesn't use I and J commands?

**Comment by Lazzzzzzer** [comment]
Never mind i figured it out. I had the "Arc tolerance" set to 1. Adjusted it to 0.002 and now it works.

**Comment by arkypita** [comment]
good to know
