### ISSUE TITLE
Wrong position during vector laser cut

### ISSUE THREAD

**Issue by mdeel-online** [arkypita/LaserGRBL#955]
Hello, at first... sorry for my bad english

I have a new toy. A Totem Laser engraver and i have one Problem only at vector laser cut.
I hope you can see the problem and know what i mean.
The laser does not move to the right place during cutting. It just starts in the middle. I don't have the problem with normal operations.
![20200415_172736_resized](https://user-images.githubusercontent.com/63735771/79357578-8be69380-7f40-11ea-9e48-8987333d0cc4.jpg)
![20200415_172811_resized](https://user-images.githubusercontent.com/63735771/79357586-8db05700-7f40-11ea-9fb7-002d3d3f40ec.jpg)
![20200415_172820_resized](https://user-images.githubusercontent.com/63735771/79357604-9143de00-7f40-11ea-8f62-bd5516167da0.jpg)
![20200415_172828_resized](https://user-images.githubusercontent.com/63735771/79357627-96a12880-7f40-11ea-8c11-a2208e888728.jpg)
![20200415_172849_resized](https://user-images.githubusercontent.com/63735771/79357645-9acd4600-7f40-11ea-833f-6dd9cc80e4ce.jpg)
![20200415_172855_resized](https://user-images.githubusercontent.com/63735771/79357661-a02a9080-7f40-11ea-9f15-f656ed2ac166.jpg)
![20200415_172925_resized](https://user-images.githubusercontent.com/63735771/79357677-a4ef4480-7f40-11ea-806a-96ff6670a525.jpg)
![20200415_172931_resized](https://user-images.githubusercontent.com/63735771/79357696-aa4c8f00-7f40-11ea-8cef-e9840164d7b8.jpg)

**Comment by mdeel-online** [comment]
I have found the cause and here it is explained in detail. Please note that the first G0 code must remain on G0. Otherwise the switched-on laser moves to the starting point

https://github.com/arkypita/LaserGRBL/issues/53

Now the question is to activate the old commands in the Lasergrbl?

![Lösung](https://user-images.githubusercontent.com/63735771/79482367-0b439800-8011-11ea-9457-acd23230fcc9.JPG)
![93167761_1555068041337591_8749584612360978432_n](https://user-images.githubusercontent.com/63735771/79482435-20b8c200-8011-11ea-9d86-0976887dcbd2.jpg)

**Comment by filap** [comment]
It looks like I have the same problem ... but why only few people face this ... as everyone use the same LaserGRBL. and arduino load ?

**Comment by StuartB4** [comment]
@mdeel-online. 

I noticed in the images you posted of you GRBL configuration you don't have Laser mode enabled ($32). In grbl menu, grbl configurating change it to $32=1. 
You can read what it does here: https://github.com/gnea/grbl/wiki/Grbl-v1.1-Laser-Mode

Also $120 and 121 seem a bit high for Acceleration. If it's too fast it can lose steps.

**Comment by mdeel-online** [comment]
Perfect thank you thats the Problem. 120 and 121 works fine at value 2000 and 32 its on now. Great Help from you!!!

**Comment by arkypita** [comment]
that's what I tell you here #53
