### ISSUE TITLE
Wrong dimensions with Centerline Mode, if "Adaptive Quality" checked 

### ISSUE THREAD

**Issue by tomturican** [arkypita/LaserGRBL#958]
Hello, thank you for this super good program, which offers me a lot of help. I am very pleased that you are so busy working on it and doing it better and better. The new "Adaptive Quality" function is very interesting and helpful. But unfortunately a problem has arisen. I very often use the "Centerline" function to cut out smaller parts for model making. However, if the checkbox of the new "Adaptive Quality" function is activated, the wrong size images are imported in Centerline mode. I have 3 screenshots here to show what I mean. The image size determination using EXIF works and shows the correct values, but at the last step the error seems to occur.

![1](https://user-images.githubusercontent.com/50337031/79488326-d5ef7800-8019-11ea-9c43-3ce3fc56e5e9.png)
Adaptive Quality is unchecked. All is OK.

![2](https://user-images.githubusercontent.com/50337031/79488332-da1b9580-8019-11ea-8707-395dda87c653.png)
Now i check the Adaptive Quality and then switch to Centerline.

![3](https://user-images.githubusercontent.com/50337031/79488343-dd168600-8019-11ea-99a4-72ac84aabdda.png)
Now already in Centerline Mode. The new imported image got the wrong size.

**Comment by arkypita** [comment]
Thanks for the quick feedback, I verify and release a correction as soon as possible.

**Comment by arkypita** [comment]
Fixed in v3.3.0
