### ISSUE TITLE
Engraver creating a slanted image.

### ISSUE THREAD

**Issue by wladbg** [arkypita/LaserGRBL#970]
Hello! 
I have a problem with my 2.5w Chinese laser engraver: 
if I use Line to line horizontal tracking mode the engraver shifts each register creating a slanted image. 

![line to line tracing - horizontal](https://user-images.githubusercontent.com/64245458/80199648-40ac3f00-862a-11ea-8404-5c7adfabc488.jpg)

If I use Vectrorize mode, looks much better: 

![vectroize](https://user-images.githubusercontent.com/64245458/80199710-502b8800-862a-11ea-9403-bbd58b209e73.jpg)

In Line to line - diagonal, is a disaster: 

![line to line - diagonal](https://user-images.githubusercontent.com/64245458/80199751-5b7eb380-862a-11ea-9184-a6bc68d478eb.jpg)

LaserGRBL settings: 
10000 lines / mm, 
Speed: 1000 mm/min
s-min 0
S-max 500
Size: 43/10

I have the feeling that it is not working smoothly, or maybe something mechanical is wrong.

Video link: https://streamable.com/qoy9ga   

Do you have any idea what could be the problem?
Thank you!

**Comment by StuartB4** [comment]
Have you just built the machine, if so are you sure the stepper motor leads are in the correct sockets on the main board.

**Comment by StuartB4** [comment]
Can you post a picture / snapshot of your GRBL configuration settings.

**Comment by wladbg** [comment]
Yes, it's my build. 
The mainboard is MKS DLC v2. 
All motors are connected exactly as in the manual, X-Y-Y. 
I have not changed anything in the configuration settings: 
![screenshot](https://user-images.githubusercontent.com/64245458/80222389-6e57af00-864f-11ea-8f1d-f9c2ea1e2402.jpg)

**Comment by StuartB4** [comment]
Start LaserGRBL and click connect. Then goto Grbl menu and select the grbl configuration like you did to get the list of settings. 
Change $32 to 1
I would lower $120 and 121 to about 2000.
Don't forget to click the Write button after changing the values.

Check to make sure none of the belts are too loose and that the toothed pulley wheels on the motor shafts are all tight.

Also use this online stepper motor calibrator to get the correct steps/mm.
https://jscalc.io/calc/tHjfIiKMKjDF42Hg?fbclid=IwAR219p6S0qWzVAsY8aLC8nyQaXaMpfa-mSTNCIXA7TAMPa3VzrGoCDcimsI

This is how to use it, but where it says inches select MM's instead.
![tytyt](https://user-images.githubusercontent.com/16980026/80225250-b7edcd00-8642-11ea-9af5-c2c12d10717c.jpg)

**Comment by wladbg** [comment]
After making all these adjustments, surprisingly it started working properly!
Only diagonally /line to line/ does not work, but horizontally and vertically it is OK now!
Thanks a lot for all your help, StuartB4!
Cheers!
