### ISSUE TITLE
Laser on/off (low power) button/checkbox

### ISSUE THREAD

**Issue by frankvdh** [arkypita/LaserGRBL#974]
It would be convenient if there was a button or checkbox to turn the laser on/off at low power for positioning and setting the Home position.

Rationale: I almost always start by positioning the laser, usually close to the edge of what I'm working to minimise waste. To do that accurately, I need the laser to be on, but at very low power, so there's a visible dot that doesn't mark the surface. I turn the laser on with M3 S1 (which doesn't actually turn the laser on until a move command is executed).

**Comment by arkypita** [comment]
Custom button is the answer

**Comment by frankvdh** [comment]
Ahhh.... there's custom buttons! :)
