### ISSUE TITLE
Swapping a new laser module in

### ISSUE THREAD

**Issue by LJg81** [arkypita/LaserGRBL#981]
Hi all

I realise this isn’t a GRBL-specific issue, but I’m new to the scene and this is the only laser community I’m in to date.

Had my laser working before I trashed it by running it at full power for too long. Have just received a new laser module to replace it.

The wiring is slightly different. I was after any advice anyone had for replacing the old 7kW laser module for this new 15kW one. 

Coming out of my Arduino(ish) board I have 3 wires, Laser 3-Pin labelled  Red ‘+’, White ‘s+’, Black ‘-‘.

On my new laser module there is a circuit board with a spare 2-pin port: labelled 
‘TTL (Analog) +’ 
and ‘TTL (Analog) -‘

Should I connect:

Arduino ‘+’ -> ‘TTL Analog +’
Arduino ‘s+’ -> nowhere
Arduino ‘-‘ -> ‘TTL Analog -‘

Asking for advice before I blow up another laser. Appreciate this is not the ideal place for this but new to lasers and GitHub and the scene.

Thanks in advance for any advice.

**Comment by LJg81** [comment]
![IMG_9817](https://user-images.githubusercontent.com/63862725/80596099-b98e0b00-8a1d-11ea-88a2-8f479cb2ec0b.jpg)
![IMG_9818](https://user-images.githubusercontent.com/63862725/80596119-be52bf00-8a1d-11ea-99c9-dfcc94b037ec.jpg)
![IMG_9819](https://user-images.githubusercontent.com/63862725/80596122-c01c8280-8a1d-11ea-8894-b684ab10dada.jpg)

**Comment by StuartB4** [comment]
The white and yellow connector from the laser with the board attached should go to the S and the - pins on the main arduino'ish controller board.  The red wire on the arduino board 3 pin connector is 12 volt power, but if you have a seperate power supply for the laser it is not needed. Just the S for the TTL/PWM signal and a Ground or -

**Comment by StuartB4** [comment]
Just one thing, are the yellow and white leads marked on the laser board, so you know which is which.?

**Comment by LJg81** [comment]
This is incredibly helpful @StuartB4 thank you.

I do have a basic wiring diagram with the new laser which does label the yellow and white leads thankfully, yes:

Yellow = TTL +
White = TTL -

Will update when I have rewired these connectors - thank you!

**Comment by StuartB4** [comment]
Ok thanks.

**Comment by LJg81** [comment]
@StuartB4 - it’s working like a dream. Thank you so much.

**Comment by StuartB4** [comment]
That's great. :+1: 
Thanks for the update. Have fun.
