### ISSUE TITLE
Laser Grbl crashing immediately 

### ISSUE THREAD

**Issue by frankenkj** [arkypita/LaserGRBL#989]
I just installed Laser GRBL on a win7 laptop, and when launching the program after install it immediately crashes. I've uninstalled and tried previous versions, all on this machine do the same thing. I have Laser GRBL installed on a win10 machine without issues - are these releases windows specific ?
![laser error](https://user-images.githubusercontent.com/64806615/81005520-b32fd280-8e13-11ea-98b2-9a2757c670fb.jpg)

this is the error specifics:
Description:
  Stopped working

Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	lasergrbl.exe
  Problem Signature 02:	3.3.0.0
  Problem Signature 03:	5e98aa76
  Problem Signature 04:	mscorlib
  Problem Signature 05:	2.0.0.0
  Problem Signature 06:	4ca2b851
  Problem Signature 07:	f9d
  Problem Signature 08:	14e
  Problem Signature 09:	System.IO.FileNotFoundException
  OS Version:	6.1.7601.2.1.0.768.3
  Locale ID:	1033

**Comment by gmmanonymus111** [comment]
It should work on Win7, as well as on XP
Do you have the correct .net framework installed on your Win7 machine?

**Comment by arkypita** [comment]
.net framework is required to run LaserGRBL

Install Microsoft .net framework

**Comment by frankenkj** [comment]
Just installed latest .net update, and I'm still getting the same error. Tried uninstalling and reinstalling laser grbl as well.

**Comment by gmmanonymus111** [comment]
AFAIK, you need .Net 3.5 to run LaserGRBL. Newer versions of .Net are not backward-compatible with 3.5 (only from 4.5, but then XP support would be dropped)

**Comment by frankenkj** [comment]
> 
> 
> AFAIK, you need .Net 3.5 to run LaserGRBL. Newer versions of .Net are not backward-compatible with 3.5 (only from 4.5, but then XP support would be dropped)

Thank you !
I uninstalled the .net latest version, reinstalled 3.5, and Laser GRBL Seems to be happy !
